### ISSUE TITLE
v0.17.0 send returns false but data is written to client

### ISSUE THREAD

**Issue by marcj** [uNetworking/uWebSockets#1000]
We upgradated from v0.16 and found that the new version triggers `drain` more often.
In fact in development we had never the drain event because not enough data was written to the socket. 

We implement a way to deal with `send()` returning false in a way that we reschedule the send until the buffer is on a healthy level again. However, `send()` returns now false although it was actually sent to the client. This results in data being sent multiple times to the client, which causes a lot of other errors.

What happens is following:

```
sending message id=17
sending id=17 failed, wait
sending id=17 failed, wait
sending id=17 failed, wait
got drain event. bufferAmount= 0
sending id=17 failed, wait
sending id=17 succeeded after 4 failures.
```

The client meanwhile received 4 messages, all the same. Sometimes it needs 2 tries, sometimes 5.
Also that we get a drain event with bufferAmount=0 is a bit weird.

Is this related to cork? I ask because [send](https://github.com/uNetworking/uWebSockets/blob/02f1ceeba01758a9175f2bca58f9c81a49976676/src/WebSocket.h#L104]) has 2 branches that return false and this code is new between v0.16 and v0.17. Is there a way to disable cork? We downgrade back to v0.16 as v0.17 doesn't work for us this way.

//edit this ticket supposed to be in https://github.com/uNetworking/uWebSockets.js. We're using the node package.

**Comment by marcj** [comment]
After debugging more and going back to v0.16 we experience there the same issue. Seems we send now enough data to hit some limits. However, we're not able to work around that since the only indication we get from `send()` is `true`/`false`, where `false` usually indicates that sending was not successful and should happen again. But when we do that, the client receives the message multiple times. After going back to the `ws` package those issues disappeared.

**Comment by alexhultman** [comment]
You really should read the documentation before making assumptions.
