### ISSUE TITLE
getHeader always misses first array item

### ISSUE THREAD

**Issue by fguerzoni** [uNetworking/uWebSockets#1002]
Hi,
I noticed that the for loop in getHeader method inside HttpParser.h always misses the first array item, being effective starting from the second item of the array.
Could you please check?
Regards
F

**Comment by alexhultman** [comment]
The first one is URL and is skipped

**Comment by fguerzoni** [comment]
Thank you for pointing it out.
I'd better use req->getUrl() method instead of directly access the 'post' header.
regards
F
