### ISSUE TITLE
Ending websocket in opening handler causes end frame not sent somehow

### ISSUE THREAD

**Issue by Yuu6883** [uNetworking/uWebSockets#1003]
Calling ws->end(whatever_code, "some message") in .open handler causes the end frame not sent somehow. The client always gets code 1006. I kinda fixed this by calling the end method deferred in the event loop, but this should be considered a bug since you should able to end a websocket as soon as it opens.

**Comment by alexhultman** [comment]
I tested this right now and it works like it should. Check your input. Anyways, this is something that is tested many times before and known to work.

**Comment by matheust3** [comment]
The problem to comment a line of code

```
  /* Send websocket close frame, emit close event, send FIN if successful */
  void end(int code, std::string_view message = {}) {
                               .
                               .
                               .
 if (webSocketContextData->closeHandler) {
       //Comment this line
      //  webSocketContextData->closeHandler(this, code, message);
  }
                               .
                               .
                               .
}
```


Now the connection is closed but no event is emitted
