### ISSUE TITLE
make uWebsockets available as library

### ISSUE THREAD

**Issue by RDP1974** [uNetworking/uWebSockets#1004]
hello,
thanks for this great code,
however:
- can be made a wrapper with C extern to make it compiled as library or static object (.so linux is enough)?
- have done stress load tests or realcase scenario for scalability and reliability? Any results to look?
best regards
R.

**Comment by alexhultman** [comment]
You can find stress tests in benchmark folder. C is great and all, but this library is a C++ one, so you can't really easily expose it as a C library. Well maybe by using lots o macros but that is not a direction I want to take. You could try and wrap it yourself and see if it turns out any good.
