### ISSUE TITLE
Wildcard routing

### ISSUE THREAD

**Issue by DarkMatterMatt** [uNetworking/uWebSockets#1015]
Hi, is it intentional that wildcards match one or more characters on non-root paths? I expected (perhaps incorrectly) that they would match zero or more characters.

I tested the table below and **I have marked the route that I believe is incorrect with a `*`**. The left column is the WS route that I added, and the top row is the URL that I tested. A ✓ means it connected and a ✗ means it didn't.

|         | / | /test | /test/ | test/test |
|---------|---|-------|--------|-----------|
| /       | ✓ |   ✗   |    ✗   |     ✗     |
| /*      | ✓ |   ✓   |    ✓   |     ✓     |
| /test   | ✗ |   ✓   |    ✓   |     ✗     |
| /test/  | ✗ |   ✓   |    ✓   |     ✗     |
| /test/* | ✗ |   ✗   |   ✗*   |     ✓     |

It's worth noting that the `/*` route matched everything, including `/`, while the `/test/*` did not match `/test/`.

Thanks

**Comment by alexhultman-2fa** [comment]
Probably related to #1019. It doesn't consider /test/ as "test" + "" I think

**Comment by alexhultman-2fa** [comment]
The stopping condition is currently "not on first URL segment and this URL segment is zero long": https://github.com/uNetworking/uWebSockets/blob/4750c0a68f033bb4b05e18971e7683731cc73378/src/HttpRouter.h#L149

It should really be "if this URL segment is the last".

That's what causes both of these bugs

**Comment by alexhultman** [comment]
This is fixed on master and will be in next version. Thanks for reporting
