### ISSUE TITLE
Routing double slash

### ISSUE THREAD

**Issue by kinsi55** [uNetworking/uWebSockets#1019]
I spotted this at random, I'm unsure if its a bug per se but definitely its not working as expected.

I am using the Node wrapper for testing.

Having added a route with the pattern `/foo` I can access it just one would expect, and trying to access `/foo/bar` will error just like one would expect

However, If I have a double foward slash in my **request** path where the route path ends, so for example `/foo//bar/baz/qux` it will match my `/foo` handler, no matter what is appened behind it. `getUrl()` will then also return the entire request path.

**Comment by alexhultman-2fa** [comment]
Is double slash really a valid URL? I don't think so and I don't think this is a bug more of a quirk

**Comment by kinsi55** [comment]
I'm not sure if it is valid (if I had to guess I would say no), but I dont think that it should match on a non-wildcard route

**Comment by alexhultman** [comment]
This is fixed on master and will be in next version. Thanks for reporting
