### ISSUE TITLE
Please use $(MAKE) instead of 'make' in the Makefile

### ISSUE THREAD

**Issue by yurivict** [uNetworking/uWebSockets#1026]
https://github.com/uNetworking/uWebSockets/blob/master/Makefile#L30

make can have different names on different systems, and ```$(MAKE)``` is an alias for this.

**Comment by alexhultman-2fa** [comment]
Will this work on macOS by default?

**Comment by yurivict** [comment]
$(MAKE) will work on OSes because it is a make feature.

**Comment by alexhultman** [comment]
Fixed

**Comment by yurivict** [comment]
Thanks!
