### ISSUE TITLE
No install target in the project

### ISSUE THREAD

**Issue by yurivict** [uNetworking/uWebSockets#1027]
Please add an install target that installs the headers under ```include/uWebSockets```.

**Comment by alexhultman-2fa** [comment]
I saw something about a FreeBSD port. You maintain this for FreeBSD?

I have little insights in how FreeBSD does things

**Comment by yurivict** [comment]
> I saw something about a FreeBSD port. You maintain this for FreeBSD?

Yes.

> I have little insights in how FreeBSD does things

You just need to add a cmake's ```install``` target to install the headers into ```include/uWebSockets```.

**Comment by epsilon-0** [comment]
@yurivict @alexhultman 
Please look at #1042 
It tries to address this problem
Also companion to PR on usockets: https://github.com/uNetworking/uSockets/pull/100

Possible change as mentioned by @yurivict, current install locations are adhering to unix header standards by not capitalizing the words, should the install locations really be changed to `uWebSockets` and `uSockets`?

**Comment by yurivict** [comment]
It works fine. The only difference is that I installed it into ```include/uWebSocket``` and you now install it into ```include/usockets```.

Do you think that matching the project name and calling the directory ```include/uWebSocket``` would be better?

**Comment by epsilon-0** [comment]
@yurivict lol, i totally messed that up! It was a remnant from something I copied.  
Thanks a lot for mentioning it, I fixed it.  
Still not sure if `uwebsockets` or `uWebSockets` is the better one.  
Currently going without camelcase because header files almost always avoid it.  
Strange the the project has most header files with capital letters.

**Comment by epsilon-0** [comment]
I actually changed it to `uWebSockets`, it fits with the whole project.

**Comment by alexhultman** [comment]
Fixed on master
