### ISSUE TITLE
https connections fail: PR_END_OF_FILE_ERROR

### ISSUE THREAD

**Issue by yurivict** [uNetworking/uWebSockets#1028]
The example from README fails:
![image](https://user-images.githubusercontent.com/271906/78836451-f464cc00-79a6-11ea-85f6-3d4714386c3e.png)

certificates are valid, they work with other applications.

When changed to http the same example works ok.

**Comment by alexhultman-2fa** [comment]
Enable SSL as per #1029

**Comment by yurivict** [comment]
Thanks.
