### ISSUE TITLE
How to compile for SSL?

### ISSUE THREAD

**Issue by alexe100** [uNetworking/uWebSockets#1029]
Hi
My first time with uWebSockets. It seems great.
I have just tested the EchoServer using firefox websocket client extension and it works great but just for ws://localhost:9001. wss does not works.

During compilation:

cd uSockets && make
make[1]: Entering directory '/home/user1/uWebSockets/uSockets'
rm -f *.o
cc -DLIBUS_NO_SSL -std=c11 -Isrc -flto -O3 -c src/*.c src/eventing/*.c src/crypto/*.c
ar rvs uSockets.a *.o
ar: creating uSockets.a
a - context.o
a - epoll_kqueue.o
a - gcd.o
a - libuv.o
a - loop.o
a - openssl.o
a - socket.o
a - wolfssl.o
...

Does DLIBUS_NO_SSL  means no SSL for all examples?

How to compile with SSL?

Thanks a lot
Alex

**Comment by alexhultman-2fa** [comment]
WITH_OPENSSL=1 make

This enables SSL. There is also WITH_WOLFSSL.

**Comment by alexe100** [comment]
Now EchoServer does nothing. I put cert on ../misc
Is there a way to show debug messages or log or something?

When compilling with:

$make
Then:
$./EchoServer
Listening on port 9001


When compilling with:

$WITH_OPENSSL=1 make
Then:
$./EchoServer

$
