### ISSUE TITLE
How to pass or access PerSocketData in a get action?

### ISSUE THREAD

**Issue by alexe100** [uNetworking/uWebSockets#1030]
Can not figure out how to access PerSocketData structure when inside the scope of an HTML action.

For websockets, the structure is passed like    .ws<PerSocketData>("/*", {
What about .get?
}).get<PerSocketData>("/hello", [](auto *res, auto *req) {  
?

Thanks

**Comment by alexhultman-2fa** [comment]
You have to stop abusing this bug reporting tool. Do not open bug reports unless you want to report a bug.

**Comment by alexe100** [comment]
Got it! ;-)
