### ISSUE TITLE
Reconsider pub/sub interfaces for v19

### ISSUE THREAD

**Issue by zappys** [uNetworking/uWebSockets#1035]
Hello 

```js
socket.id = 1234;
socket.subscribe("TOPIC1");
socket.subscribe("TOPIC2");

//Any way to do this?
socket.getAllSubscribedTopics();  //returns ["TOPIC1", "TOPIC2"]
```

How can i get the subscribed topics for a given socket. At the moment i keep a state myself in memory with the socket id and the subscribed topics, but i think the underlying library already keeps this state but i don't see a way to access that state. 

Thanks!

**Comment by alexhultman** [comment]
It can make sense to add, we expect each one socket to hold a limited amount of subscriptions anyways, so returning a list can make sense.

**Comment by prashanth-dev-web** [comment]
Also may I ask if the library internally maintains all the sockets subscribed to a particular channel. If so it would be helpful to have a function to return this too. My scenario is to unsubscribe this particular channel from redis when there are no sockets subscribed for it.

**Comment by prashanth-dev-web** [comment]
It would even be enough to return the number of sockets if returning sockets is too much. I can think of it in two ways. One is when we call subscribe and unsubscribe function it shall return the number of sockets currently subscribed to that particular channel. If it may seem confusing because one can even think the return value as the number of channels that this particular socket is subscribed to currently.

I think its better to expose a separate function that takes in a channel and returns the number of sockets subscribed to it.

**Comment by alexhultman** [comment]
Yes it keeps a list of sockets per topic and also a list of topics per socket. What I am considering is how to best expose this to JS since you don't want to copy out a huge list

**Comment by alexhultman** [comment]
If you expose it as forEach you have the issue of iterator invalidation if the user does something like unsubscribe while looping.

If you allocate fill and return a list, that's lots of waste

**Comment by alexhultman** [comment]
If you instead make simple functions that cover the most common questions with a simple Boolean return that's awesome

Like bool hasSubscribers(topic), bool isSubscribed(topic), etc

**Comment by alexhultman** [comment]
> [...] How can i check if a topic already exists before the user subscribes to it? In my case it’s important if the user connects to a topic that has no other devices connected to it. [...]

bool hasSubscribers("topic")

> [...] I think its better to expose a separate function that takes in a channel and returns the number of sockets subscribed to it. [...]

Okay so make it return integer instead

> [...] get a list of all subscribed topics on close / when calling unsubscribeAll [...].

> [...] How can i get the subscribed topics for a given socket. [...]

Okay we can return a list here since we expect one socket to have limited amounts of subscriptions

**Comment by prashanth-dev-web** [comment]
> > [...] How can i check if a topic already exists before the user subscribes to it? In my case it’s important if the user connects to a topic that has no other devices connected to it. [...]
> 
> bool hasSubscribers("topic")
> 
> > [...] I think its better to expose a separate function that takes in a channel and returns the number of sockets subscribed to it. [...]
> 
> Okay so make it return integer instead
> 
> > [...] get a list of all subscribed topics on close / when calling unsubscribeAll [...].
> 
> > [...] How can i get the subscribed topics for a given socket. [...]
> 
> Okay we can return a list here since we expect one socket to have limited amounts of subscriptions

I think the second function to get integer would not be necessary if we have the first boolean function. All we need is to know if a particular channels has any subscribers or not. 

The third function makes sense. 

To summarise it would be great to have a hasSubscribers(channel): boolean and getChannels(socket): list<string>

**Comment by alexhultman-2fa** [comment]
Okay I've re-read this thread and it makes a lot of sense.

* Calling unsubscribe/subscribe could return the number of sockets subscribed to that topic after done; this way you can release Redis subscriptions when you reach 0 and re-subscribe to Redis when it gets 1.

**Comment by alexhultman-2fa** [comment]
It could be useful to have a new event: "subscription" where you get called every time a socket subscribes or unsubscribes to a topic:

.subscription(ws, topic, numSubscribers, change, () => {
// clean up or re-establish external Redis subscriptions, keep track, etc
})

**Comment by alexhultman** [comment]
Both subscribe and unsubscribe now return [numSubscribers, success]. This helps a bit, but what is really asked for in this thread is a new event for when Topics are created/removed from the TopicTree:

```
.topic = [](std::string_view topic, unsigned int numSubscribers) {
 // numSubscribers are either 0 or 1 since we only get this event when a Topic is created or removed
}
```

**Comment by alexhultman** [comment]
unsubscribeAll is pointless to expose as a function  - nobody is ever going to use it. It is really only used internally.

**Comment by bellostom** [comment]
@alexhultman Any news regarding my previous comment? Shall I open a separate issue?
