### ISSUE TITLE
Dedicated compression with pub/sub

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets#1036]
Not only should it support shared compressor but dedicated as well. The compression should follow the options set in the WS route, same as for ws.send.

**Comment by alexhultman-2fa** [comment]
There is now shared compression support for pub/sub - dedicated compression to do.

**Comment by alexhultman** [comment]
Currently there are two tracks; uncompressed and shared compressed.

This is given as one single string ready to be sent. For dedicated compression we need a third track; entirely uncompressed and unframed messages, given as separate strings:

std::vector<std::string_view> unframed. Then we use regular WebSocket::send calls inside of the cb.

We also need some kind of bool per message to determine if that message should be compressed or not.

**Comment by alexhultman** [comment]
Turns out this only needed a minimal change to work. There are some missing things like corking and checking maxBackpressure, but it works now.
