### ISSUE TITLE
std::min failing with interfering macro 

### ISSUE THREAD

**Issue by jonjow** [uNetworking/uWebSockets#1037]
In HttpParser on line 272 I get an error when using std::min.

I have modified as shown below:
`int maxCopyDistance = (int) (std::min)(MAX_FALLBACK_SIZE - fallback.length(), (size_t) length);`

https://stackoverflow.com/questions/5004858/why-is-stdmin-failing-when-windows-h-is-included

**Comment by alexhultman** [comment]
This project is by no means going to wrap every function call in parenthesis just because of Microsoft's continued lack of giving a fuck about standards. You should define NOMINMAX like the post says, this project does that itself.

**Comment by jonjow** [comment]
Sorry I defined it in the wrong place, that solution is working now.

I managed to build and test the HTTP example which worked fine however when I try the echo server example I get the following:

No instance of function template "uWS::TemplatedApp<SSL>::ws [with SSL=false]" matches the argument list

No instance of function template "uWS::TemplatedApp<SSL>::ws [with SSL=true]" matches the argument list	

![image](https://user-images.githubusercontent.com/9991364/80003642-3880c200-84b9-11ea-8272-fc24a242c30b.png)

Do you know what could cause this? App.h is included.

**Comment by jonjow** [comment]
Ignore that, it was using std:c++17 not latest.
