### ISSUE TITLE
UWS_HTTPRESPONSE_NO_WRITEMARK Should be defaulted to false

### ISSUE THREAD

**Issue by Phara0h** [uNetworking/uWebSockets#1039]
`UWS_HTTPRESPONSE_NO_WRITEMARK` Should be defaulted to false due to security reasons or simply removed (increased performance). You do not want to let your client know what version and server you are using. This gives them free information about your server to make it easier to target specific attacks geared towards it.

**Comment by alexhultman-2fa** [comment]
Should is a strong word and I tend to close all issues starting with "X should Y because <subjective opinion>"

**Comment by Phara0h** [comment]
> Should is a strong word and I tend to close all issues starting with "X should Y because <subjective opinion>"

Then how would you like it worded? Should I use the word "Needs?"
