### ISSUE TITLE
Is this library server-only now?

### ISSUE THREAD

**Issue by Caydenz** [uNetworking/uWebSockets#1045]
I used this library a few years ago for a project where I had to interact with a third party API. Looks like the project has been rewritten from scratch in the meantime and the Hub functionality is gone.

If client-use is still supported, are there any examples on it?

Thanks!

**Comment by alexhultman-2fa** [comment]
Yes it was server-only up to v0.10 and is again server-only from v0.15. Client support doesn't make a whole lot of sense, that's not where you'll see a noticeable difference
