### ISSUE TITLE
bytecode stream in file "uSockets.a" generated with LTO version 7.1 instead of the expected 8.1

### ISSUE THREAD

**Issue by MKSoftechnician** [uNetworking/uWebSockets#1051]
Hi,
I am getting following error while linking
lto1: fatal error: bytecode stream in file ‘/home/mahesh/CLionProjects/uWebSocketTest/external/lib/uSockets.a’ generated with LTO version 7.1 instead of the expected 8.1
I am using same gcc and g++ compiler to build both uWebSockets and its test project.
Kindly help me to solve it.

**Comment by alexhultman** [comment]
Not a bug report.
