### ISSUE TITLE
Expose native SSL context to allow more SSL configuration

### ISSUE THREAD

**Issue by not-implemented** [uNetworking/uWebSockets#1054]
Currently, the example in the readme says "There are tons of SSL options", but there are only 6 options implemented (key_file_name, cert_file_name, passphrase, dh_params_file_name, ca_file_name, ssl_prefer_low_memory_usage) :-)

I really like cool and simple interfaces like this, but for special cases you need full control over the underlying SSL implementation (e.g. OpenSSL).

SSL/TLS best practices change over time and should not be hardcoded into a library, I think (especially without a chance to override). Currently I don't see a possibility to change e.g. the set_cipher_list, SSL_OP_CIPHER_SERVER_PREFERENCE or setting a ECDH curve (without patching).

Maybe the easiest way is, to expose the `SSL_CTX*` pointer in any way, to allow setting custom options after init (I dont't think, it makes sense, to add all possible SSL options to the options struct).

**Comment by alexhultman** [comment]
Haha, you don't think 6 is plenty? :)

Sure we can add that, but probably as void *. It could also make sense to add ways to get the SSL of a session so that you can read things like selected cipher and so on.

**Comment by alexhultman** [comment]
It could make sense if us_socket_context_get_native_handle returns the FD for TCP and the SSL * for SSL sockets

**Comment by alexhultman** [comment]
I'm a little behind with the SSL thing, I have to fix a few things before I can look at that since I have other issues to fix and tests to write and so on.

But yes overall SSL needs a big overhaul and many added functions.

**Comment by not-implemented** [comment]
sounds good :-) thanks :-)

**Comment by jbenguira** [comment]
I would love to have something similar to SNICallback (https://stackoverflow.com/questions/29604697/i-cannot-use-snicallback)
The goal is to be able to do ssl termination for several websites and also to be able to generate certs and load them automatically at runtime :)

**Comment by alexhultman** [comment]
The App holds one HttpContext which holds one SSL_CTX. So adding App::getSSLContext() is a starter.

This will require us_socket_context_get_native_handle, returning void ptr (or nullptr in case of TCP).

**Comment by alexhultman** [comment]
@not-implemented This commit aac11b07fbdd3ca59aa4823cf45db5c41a218b57 adds App::getNativeHandle and AsyncSocket::getNativeHandle and sets up the foundation in uSockets.

However it does not implement it in openssl.c, so us_internal_ssl_socket_context_get_native_handle and us_internal_ssl_socket_get_native_handle is not implemented yet. You could do that and PR it, it should be simple but I don't want to right now because it has to be done for OpenSSL, BoringSSL and WolfSSL.

Then we probably want WebSocket and HttpResponse to expose the protected getNativeHandle from AsyncSocket, I forgot that.

**Comment by alexhultman** [comment]
Never mind I made the changes, it should work now. Have a spin

**Comment by not-implemented** [comment]
@alexhultman: Very cool, thanks, I'll try next week and give you feedback!

**Comment by not-implemented** [comment]
@alexhultman Seems to work fine for OpenSSL (I had to refactor to the new "upgrade" handler in v18 first, so it takes a little bit longer).

I currently use `App::getNativeHandle()` only - but `AsyncSocket::getNativeHandle()´ will also be very interesting when implementing more metrics.
