### ISSUE TITLE
Close/skip backpressure behavior switch

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets#1056]
It should be possible to enable the former close-on-backpressure behavior when pub/subbing

Probably add us_socket_deferred_close() as a way to close down the reading side thus causing error-close next iteration (?)

**Comment by alexhultman** [comment]
Sending and publishing should never immediately call close handler as that often leads to complex recursion/reentry bugs.

**Comment by alexhultman** [comment]
This makes a lot of sense to add. Some users would surely require an in-order stream where too much backpressure simply leads to a close rather than skip. Skipping is only valid for application protocols that do not deal with history where previous messages are important. Therefore this feature is important to add.

**Comment by alexhultman** [comment]
maxBackpressure = number
backpressureMitigation = CLOSE | SKIP

Shutting down the read side of the socket seems to work the same on BSD sockets and WinSock so using that feature sounds perfect here.

**Comment by psy0rz** [comment]
I'm currently testing my backpressure handling by adding a DROP-rule to the firewall. 

I noticed i can send several MB's before i get a back-pressure build up. Is this normal? Where is the data stored? Is that size configurable? I would have expected to only be able to send maybe a few KB's before i got backpressure.

Edwin

**Comment by alexhultman-2fa** [comment]
Yes that's normal, the data is stored in kernel space. You can configure pretty much everything in this regard.

**Comment by alexhultman** [comment]
This is added as option bool closeOnBackpressureLimit
