### ISSUE TITLE
Not recognizing websocket routes

### ISSUE THREAD

**Issue by rjo** [uNetworking/uWebSockets#1058]
My simple websocket test based on the example code is not working. The server simply disconnects without transmitting anything the same way it does if you don't have a route defined for regular HTTP methods without a catchall.

```
void APIServer::runSocket() {
      struct PerSocketData {
          int x;
      };
     uWS::App().ws<PerSocketData>("/echo", {
        /* Settings */
        .compression = uWS::SHARED_COMPRESSOR,
        .maxPayloadLength = 16 * 1024,
        .idleTimeout = 10,
        .maxBackpressure = 1 * 1024 * 1204,

        /* Handlers */
        .open = [](auto *ws, auto *req) {
            /* Here you can use req just like as for Http */
            spdlog::info("websocket open");

        },
        .message = [](auto *ws, std::string_view message, uWS::OpCode opCode) {
            spdlog::info("websocket message: {}",message);
            ws->send(message, opCode);
        },
        .drain = [](auto *ws) {
            /* Check getBufferedAmount here */
        },
        .ping = [](auto *ws) {

        },
        .pong = [](auto *ws) {

        },
        .close = [](auto *ws, int code, std::string_view message) {
            spdlog::info("websocket close");

        }
    }).listen(8001, [this](auto *listenSocket) {

        if (listenSocket) {
            this->socketListenSocket = listenSocket;
            spdlog::info("Listening on port 8001");
        } else {
            spdlog::error("unable to listen on port 8001");
        }
    }).run();
}
```

Facts:
Tested on v0.17.5 and HEAD
I'm trying to connect from a javascript socket.io client and curl.

I'm able to serve regular HTTP routes just fine and don't understand why my ws route is not being handled.

**Comment by rjo** [comment]
My bad. I naively thought uWebsocket would support a connection that began in polling mode. Limiting the transport to websocket functions as expected.

**Comment by alexhultman** [comment]
Socket.IO is a non standard proprietary protocol that's a 90's mix between http hacks and websockets and even formerly Adobe flash sockets.

This library communicates only with vanilla html5 websockets, you shouldn't have any client side JavaScript library

**Comment by rjo** [comment]
Yeah I worked all that out. Thanks Alex.
