### ISSUE TITLE
ws.end in .open handler doesn't send TCP FIN

### ISSUE THREAD

**Issue by Yuu6883** [uNetworking/uWebSockets#1063]
Last time I reported this issue I didn't add a code snipet, but now here's the code:
```cpp
#include <uwebsockets/App.h>
int main() {
    struct PerSocketData {};
    uWS::App().ws<PerSocketData>("/*", {
        .compression = uWS::SHARED_COMPRESSOR,
        .maxPayloadLength = 16 * 1024,
        .idleTimeout = 120,
        .maxBackpressure = 1 * 1024 * 1024,
        .open = [](auto* ws, auto* req) {
            // This doesn't work
            ws->end(1000, "Bye World");

            // This works
            // uWS::Loop::get()->defer([&] { ws->end(1000, "Bye World"); });
        },
        .message = [](auto* ws, std::string_view message, uWS::OpCode opCode) {
            ws->send(message, opCode);
        },
        .drain = [](auto* ws) {},
        .ping = [](auto* ws) {},
        .pong = [](auto* ws) {},
        .close = [](auto* ws, int code, std::string_view message) {
            printf("Socket closed (code: %i, message: %s)\n", code, message.data());
        }
    }).listen(9001, [](auto* token) {
        if (token) std::cout << "listening on port " << 9001 << std::endl;
    }).run();
}
```

Interacting in browser: 
![image](https://user-images.githubusercontent.com/38842891/83363934-126cfe00-a352-11ea-9429-eb67346a3271.png)

Expected behavior (using line below `// This works` instead of line below `// This doesn't work`): 
![image](https://user-images.githubusercontent.com/38842891/83363966-6c6dc380-a352-11ea-94e7-c2835e419cbb.png)

Platform: windows10
Browser: chrome

This issue should be fixed because the websocket should be able to close in the open callback. Or I can just wait for v0.18 websocket authorization planned here https://github.com/uNetworking/uWebSockets/issues/966 to finish, so I don't need to validate the connection in the open handler.

**Comment by alexhultman** [comment]
Could it be an issue with Chrome? It works for me in Firefox, but not in Chrome.

When you end in the open handler, µWS sends the upgrade and close message as one single TCP packet. This could potentially mess with Chrome.

When you defer the end, things are split into two separate TCP packets.

**Comment by Yuu6883** [comment]
I guess this is chrome's problem (also doesn't work in Egde) for not implenting rfc6455 correctly since the close frame is indeed sent and CloseEvent.wasClean is expected to be true in the browser.  Not sure where I should report this, but for browser capacity I'll use defer for now.

**Comment by alexhultman-2fa** [comment]
Chrome recently made changes to their WebSocket implementation from version 80 I think, maybe it works in 70-ish and if so, Chromium bug tracker would be it

**Comment by alexhultman** [comment]
I have reported this as a bug, let's see what they say

**Comment by hst-m** [comment]
link to chromium bug report https://bugs.chromium.org/p/chromium/issues/detail?id=1090210

**Comment by alexhultman** [comment]
Alright it's not a Chrome bug after all, we don't send TCP FIN in this case and that breaks the whole thing.

**Comment by alexhultman** [comment]
Fixed
