### ISSUE TITLE
Attach specific http methods to one handler.

### ISSUE THREAD

**Issue by BFamzz** [uNetworking/uWebSockets#1073]
Please this is a FAQ but I can't seem to find a way to label it. 

How can I attach specific methods (get and post) to one handler?

All the examples available use just one http method.

```
uWS::App() app(); // is this appropriate??

// I want both get and post methods here
app().get("/hello", [](auto *res, auto *req) {
		res->end("Hello World");
	});
```

Thanks.

**Comment by alexhultman** [comment]
There's no specific way, you just call get and post with the same handler.

**Comment by BFamzz** [comment]
@alexhultman you mean something like this:

uWS::App() app();

app().get("/handler"){

}

app().post("/handler"){

}
