### ISSUE TITLE
Docker exits with 137

### ISSUE THREAD

**Issue by BFamzz** [uNetworking/uWebSockets#1078]
I am running a simple example using docker containers but when the container is stopped, it exits with a 137.

Here is the code: 

```
#include <uWebSockets/App.h>

int main(int argc, char *argv[])
{
	uWS::App().get("/hello", [](auto *res, auto *req) {

        std::cout << "Request method is: " << req->getMethod() << "\n";

		res->end("Hello World"); 
	}).listen(8080, [](auto *listenSocket){
        if (listenSocket)
        {
            std::cout << "Listening for connections...\n";
        }
        
    }).run();

    std::cout << "Shoot! We failed to listen and the App fell through, exiting now\n!";

    return 0;
}
```

![image](https://user-images.githubusercontent.com/38426051/86544629-5e4a2e80-bf20-11ea-99d1-354976d78b75.png)

How can I resolve this?

**Comment by alexhultman** [comment]
Stop abusing this bug tracker. You've posted three bug reports which are not bug reports at all but 101 questions regarding stuff that's not even part of this library.
