### ISSUE TITLE
Maximum QPS

### ISSUE THREAD

**Issue by portsip** [uNetworking/uWebSockets#1083]
Hi all, I'm try to use uWebSockets to write a websocket server, currently my application only handle maximum about 500 QPS then the connection is failed, but the CPU usage is very low, does there have any settings allow me to improve it?

**Comment by alexhultman-2fa** [comment]
I don't know what QPS is and how it relates to this project or what the meaning of "connection is failed" is.

I also don't know how this would be a bug report

**Comment by poor1017** [comment]
Hi @portsip 

How to repeat it? I think 500 qps is not enough in many situations.

**Comment by uNetworkingAB** [comment]
Assuming QPS is queries per second (which makes no sense, this is not a DB) - 500 requests per second is obviously not right. Something is wrong on your test client, even the observation that there is low CPU usage tells this very clearly. Any modern laptop can do 300k req/sec
