### ISSUE TITLE
example broadcasting echo server

### ISSUE THREAD

**Issue by G2G2G2G** [uNetworking/uWebSockets#1093]
On line 25 the St17basic_string_viewIcSt11char_traitsIcEE comparing to the string, how does this ever trigger as true?

            if (message == "closedown") {

https://github.com/uNetworking/uWebSockets/blob/master/examples/BroadcastingEchoServer.cpp

**Comment by alexhultman-2fa** [comment]
What do you mean? It triggers when the message is closedown?

**Comment by G2G2G2G** [comment]
I've added these to verify but I haven't ever got the "triggered" to print  

```
    std::cout << message;
    if (message == "closedown") {
               std::cout << "triggered" << std::endl;
               us_listen_socket_close(0, listen_socket);
               ws->close();
            }
```

**Comment by alexhultman** [comment]
It just tested it and it works like it should. You're never writing newline so your stdout is never flushed.

**Comment by G2G2G2G** [comment]
I do have an endl there, that isn't the issue. You're comparing a string to a St17basic_string_viewIcSt11char_traitsIcEE which doesn't work. Unless it needs some magic compiler that you're using

![1](https://user-images.githubusercontent.com/50514477/92386503-82212080-f0d9-11ea-9c66-c766a47ab587.jpg)

**Comment by alexhultman-2fa** [comment]
If you're so sure about your case then why are you asking? It works and what you describe is not how C++ works
