### ISSUE TITLE
uWebSocket 0.14.8 deadlock when I use vector manage the ws by myself

### ISSUE THREAD

**Issue by LianZhenLiang** [uNetworking/uWebSockets#1095]
1. build uWebSocket 0.14.8 with -DUWS_THREADSAFE thread safe
2. the wsServer store the ws to vector when OnConnection is called, and remov from vector when OnDisconnect is called.
3. but another thread send message all the time, to protect the vector, I use the std::mutex. now, deadlock occurs.
4. I do not known how to deal it. if I build libUWS.so without UWS_THREADSAFE, what shall I do to make the thread safe.
5. please give me a favor. thanks.
![image](https://user-images.githubusercontent.com/35195358/92503715-40f15380-f234-11ea-95c8-b22e33e96de5.png)

[uws_server_test.txt](https://github.com/uNetworking/uWebSockets/files/5189492/uws_server_test.txt)
[uws_client_test.txt](https://github.com/uNetworking/uWebSockets/files/5189493/uws_client_test.txt)

**Comment by alexhultman** [comment]
Is m_mutex the same as nodeData->asyncMutex? That sounds very wrong. Your mutex you use to protect your vector should not be the same as the internal mutex of the library itself.

Other than this, I cannot debug, help with or run your app - that version is 3 years old and not developed anymore so even if there would be a bug I'm not going to fix it. We are at v18.13 now
