### ISSUE TITLE
SSL with and without server name

### ISSUE THREAD

**Issue by epsilon-0** [uNetworking/uWebSockets#1101]
I've been using `uWS::TemplateApp<false>` and it's been working awesomely.
So I decided to step it up to using SSL and its been *running* so far, but not getting any inputs or connections.

Basically, I've followed the example in the [HttpServer](https://github.com/uNetworking/uWebSockets/blob/master/examples/HttpServer.cpp) and my server runs but takes no input, from POST, while the non-ssl version takes the POST input.
I was wondering if I need to do something like in the [ServerName](https://github.com/uNetworking/uWebSockets/blob/master/examples/ServerName.cpp) example if I want to accept POST requests?

Just thought it would be better to document this in a small issue.

Thanks!
Aisha

**Comment by alexhultman** [comment]
There are companies running with SSL in production so I'm sure it works. You don't need to add a server name.

**Comment by epsilon-0** [comment]
True, I wasn't implying it doesn't work, just wanted to know if I was missing something obvious.

> You don't need to add a server name.

Thanks for telling this. Knowing this helps in debugging.
