### ISSUE TITLE
cmake --build . fails

### ISSUE THREAD

**Issue by charlescookey** [uNetworking/uWebSockets#1102]
This is the output error I get. What am I to change

<Scanning dependencies of target uWS
[  6%] Building CXX object CMakeFiles/uWS.dir/src/Extensions.cpp.obj
[ 13%] Building CXX object CMakeFiles/uWS.dir/src/Group.cpp.obj
In file included from D:\cppw\uWebSockets\src\WebSocketProtocol.h:5:0,
                 from D:\cppw\uWebSockets\src\WebSocket.h:4,
                 from D:\cppw\uWebSockets\src\Group.h:4,
                 from D:\cppw\uWebSockets\src\Group.cpp:1:
D:\cppw\uWebSockets\src\Networking.h:133:10: error: 'mutex' in namespace 'std' does not name a type
     std::mutex *asyncMutex;
          ^~~~~
In file included from D:\cppw\uWebSockets\src\WebSocketProtocol.h:5:0,
                 from D:\cppw\uWebSockets\src\WebSocket.h:4,
                 from D:\cppw\uWebSockets\src\Group.h:4,
                 from D:\cppw\uWebSockets\src\Group.cpp:1:
D:\cppw\uWebSockets\src\WebSocketProtocol.h: In static member function 'static size_t uWS::WebSocketProtocol<isServer>::formatMessage(char*, const char*, size_t, uWS::OpCode, size_t, bool)':
D:\cppw\uWebSockets\src\Networking.h:26:28: error: there are no arguments to 'htonll' that depend on a template parameter, so a declaration of 'htonll' must be available [-fpermissive]
 #define htobe64(x) htonll(x)
                            ^
D:\cppw\uWebSockets\src\WebSocketProtocol.h:280:39: note: in expansion of macro 'htobe64'
             *((uint64_t *) &dst[2]) = htobe64(reportedLength);
                                       ^~~~~~~
D:\cppw\uWebSockets\src\Networking.h:26:28: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
 #define htobe64(x) htonll(x)
                            ^
D:\cppw\uWebSockets\src\WebSocketProtocol.h:280:39: note: in expansion of macro 'htobe64'
             *((uint64_t *) &dst[2]) = htobe64(reportedLength);
                                       ^~~~~~~
D:\cppw\uWebSockets\src\WebSocketProtocol.h: In member function 'void uWS::WebSocketProtocol<isServer>::consume(char*, unsigned int, void*)':
D:\cppw\uWebSockets\src\Networking.h:27:28: error: there are no arguments to 'ntohll' that depend on a template parameter, so a declaration of 'ntohll' must be available [-fpermissive]
 #define be64toh(x) ntohll(x)
                            ^
D:\cppw\uWebSockets\src\WebSocketProtocol.h:347:74: note: in expansion of macro 'be64toh'
                 } else if (consumeMessage<LONG_MESSAGE_HEADER, uint64_t>(be64toh(*(uint64_t *) &src[2]), src, length, frame, user)) {
                                                                          ^~~~~~~
In file included from D:\cppw\uWebSockets\src\WebSocket.h:5:0,
                 from D:\cppw\uWebSockets\src\Group.h:4,
                 from D:\cppw\uWebSockets\src\Group.cpp:1:
D:\cppw\uWebSockets\src\Socket.h: In member function 'void uS::Socket::transfer(uS::NodeData*, void (*)(uv_poll_t*))':
D:\cppw\uWebSockets\src\Socket.h:28:19: error: 'struct uS::NodeData' has no member named 'asyncMutex'; did you mean 'async'?
         nodeData->asyncMutex->lock();
                   ^~~~~~~~~~
D:\cppw\uWebSockets\src\Socket.h:30:19: error: 'struct uS::NodeData' has no member named 'asyncMutex'; did you mean 'async'?
         nodeData->asyncMutex->unlock();
                   ^~~~~~~~~~
In file included from D:\cppw\uWebSockets\src\Networking.h:56:0,
                 from D:\cppw\uWebSockets\src\WebSocketProtocol.h:5,
                 from D:\cppw\uWebSockets\src\WebSocket.h:4,
                 from D:\cppw\uWebSockets\src\Group.h:4,
                 from D:\cppw\uWebSockets\src\Group.cpp:1:
D:\cppw\uWebSockets\src\Socket.h: In static member function 'static uv_poll_t* uS::Socket::init(uS::NodeData*, uv_os_sock_t, SSL*)':
D:\cppw\uWebSockets\src\Socket.h:47:31: error: 'SSL_MODE_RELEASE_BUFFERS' was not declared in this scope
             SSL_set_mode(ssl, SSL_MODE_RELEASE_BUFFERS);
                               ^
C:/PROGRA~2/GnuWin32/include/openssl/ssl.h:578:32: note: in definition of macro 'SSL_set_mode'
  SSL_ctrl((ssl),SSL_CTRL_MODE,(op),NULL)
                                ^~
In file included from D:\cppw\uWebSockets\src\WebSocket.h:5:0,
                 from D:\cppw\uWebSockets\src\Group.h:4,
                 from D:\cppw\uWebSockets\src\Group.cpp:1:
D:\cppw\uWebSockets\src\Socket.h: In static member function 'static void uS::Socket::io_cb(uv_poll_t*, int, int)':
D:\cppw\uWebSockets\src\Socket.h:272:38: error: 'EWOULDBLOCK' was not declared in this scope
                         if (errno != EWOULDBLOCK) {
                                      ^~~~~~~~~~~
D:\cppw\uWebSockets\src\Socket.h:291:75: error: 'EWOULDBLOCK' was not declared in this scope
             } else if (length <= 0 || (length == SOCKET_ERROR && errno != EWOULDBLOCK)) {
                                                                           ^~~~~~~~~~~
In file included from D:\cppw\uWebSockets\src\WebSocket.h:5:0,
                 from D:\cppw\uWebSockets\src\Group.h:4,
                 from D:\cppw\uWebSockets\src\Group.cpp:1:
D:\cppw\uWebSockets\src\Socket.h: In member function 'void uS::Socket::changePoll(uS::SocketData*)':
D:\cppw\uWebSockets\src\Socket.h:364:35: error: 'struct uS::NodeData' has no member named 'asyncMutex'; did you mean 'async'?
             socketData->nodeData->asyncMutex->lock();
                                   ^~~~~~~~~~
D:\cppw\uWebSockets\src\Socket.h:366:35: error: 'struct uS::NodeData' has no member named 'asyncMutex'; did you mean 'async'?
             socketData->nodeData->asyncMutex->unlock();
                                   ^~~~~~~~~~
D:\cppw\uWebSockets\src\Socket.h: In member function 'bool uS::Socket::write(uS::SocketData::Queue::Message*, bool&)':
D:\cppw\uWebSockets\src\Socket.h:403:34: error: 'EWOULDBLOCK' was not declared in this scope
                     if (errno != EWOULDBLOCK) {
                                  ^~~~~~~~~~~
In file included from D:\cppw\uWebSockets\src\Hub.h:5:0,
                 from D:\cppw\uWebSockets\src\Group.cpp:2:
D:\cppw\uWebSockets\src\Node.h: At global scope:
D:\cppw\uWebSockets\src\Node.h:19:10: error: 'mutex' in namespace 'std' does not name a type
     std::mutex asyncMutex;
          ^~~~~
D:\cppw\uWebSockets\src\Node.h: In member function 'uS::Socket uS::Node::connect(const char*, int, bool, uS::SocketData*)':
D:\cppw\uWebSockets\src\Node.h:44:80: error: there are no arguments to 'getaddrinfo' that depend on a template parameter, so a declaration of 'getaddrinfo' must be available [-fpermissive]
         if (getaddrinfo(hostname, std::to_string(port).c_str(), &hints, &result) != 0) {
                                                                                ^
D:\cppw\uWebSockets\src\Node.h:63:28: error: there are no arguments to 'freeaddrinfo' that depend on a template parameter, so a declaration of 'freeaddrinfo' must be available [-fpermissive]
         freeaddrinfo(result);
                            ^
In file included from D:\cppw\uWebSockets\src\Networking.h:56:0,
                 from D:\cppw\uWebSockets\src\WebSocketProtocol.h:5,
                 from D:\cppw\uWebSockets\src\WebSocket.h:4,
                 from D:\cppw\uWebSockets\src\Group.h:4,
                 from D:\cppw\uWebSockets\src\Group.cpp:1:
D:\cppw\uWebSockets\src\Node.h:70:43: error: 'SSL_MODE_RELEASE_BUFFERS' was not declared in this scope
             SSL_set_mode(socketData->ssl, SSL_MODE_RELEASE_BUFFERS);
                                           ^
C:/PROGRA~2/GnuWin32/include/openssl/ssl.h:578:32: note: in definition of macro 'SSL_set_mode'
  SSL_ctrl((ssl),SSL_CTRL_MODE,(op),NULL)
                                ^~
In file included from D:\cppw\uWebSockets\src\Hub.h:5:0,
                 from D:\cppw\uWebSockets\src\Group.cpp:2:
D:\cppw\uWebSockets\src\Node.h:71:63: error: there are no arguments to 'SSL_set_tlsext_host_name' that depend on a template parameter, so a declaration of 'SSL_set_tlsext_host_name' must be available [-fpermissive]
             SSL_set_tlsext_host_name(socketData->ssl, hostname);
                                                               ^
D:\cppw\uWebSockets\src\Node.h: In static member function 'static void uS::Node::accept_cb(uS::ListenData*)':
D:\cppw\uWebSockets\src\Node.h:104:55: error: 'EWOULDBLOCK' was not declared in this scope
             if (!TIMER && errno != EAGAIN && errno != EWOULDBLOCK) {
                                                       ^~~~~~~~~~~
In file included from D:\cppw\uWebSockets\src\Networking.h:56:0,
                 from D:\cppw\uWebSockets\src\WebSocketProtocol.h:5,
                 from D:\cppw\uWebSockets\src\WebSocket.h:4,
                 from D:\cppw\uWebSockets\src\Group.h:4,
                 from D:\cppw\uWebSockets\src\Group.cpp:1:
D:\cppw\uWebSockets\src\Node.h:140:31: error: 'SSL_MODE_RELEASE_BUFFERS' was not declared in this scope
             SSL_set_mode(ssl, SSL_MODE_RELEASE_BUFFERS);
                               ^
C:/PROGRA~2/GnuWin32/include/openssl/ssl.h:578:32: note: in definition of macro 'SSL_set_mode'
  SSL_ctrl((ssl),SSL_CTRL_MODE,(op),NULL)
                                ^~
In file included from D:\cppw\uWebSockets\src\Hub.h:5:0,
                 from D:\cppw\uWebSockets\src\Group.cpp:2:
D:\cppw\uWebSockets\src\Node.h: In member function 'bool uS::Node::listen(const char*, int, uS::TLS::Context, int, uS::NodeData*, void*)':
D:\cppw\uWebSockets\src\Node.h:169:76: error: there are no arguments to 'getaddrinfo' that depend on a template parameter, so a declaration of 'getaddrinfo' must be available [-fpermissive]
         if (getaddrinfo(host, std::to_string(port).c_str(), &hints, &result)) {
                                                                            ^
D:\cppw\uWebSockets\src\Node.h:192:32: error: there are no arguments to 'freeaddrinfo' that depend on a template parameter, so a declaration of 'freeaddrinfo' must be available [-fpermissive]
             freeaddrinfo(result);
                                ^
D:\cppw\uWebSockets\src\Node.h:210:32: error: there are no arguments to 'freeaddrinfo' that depend on a template parameter, so a declaration of 'freeaddrinfo' must be available [-fpermissive]
             freeaddrinfo(result);
                                ^
D:\cppw\uWebSockets\src\Node.h:230:28: error: there are no arguments to 'freeaddrinfo' that depend on a template parameter, so a declaration of 'freeaddrinfo' must be available [-fpermissive]
         freeaddrinfo(result);
                            ^
CMakeFiles\uWS.dir\build.make:96: recipe for target 'CMakeFiles/uWS.dir/src/Group.cpp.obj' failed
mingw32-make.exe[2]: *** [CMakeFiles/uWS.dir/src/Group.cpp.obj] Error 1
CMakeFiles\Makefile2:116: recipe for target 'CMakeFiles/uWS.dir/all' failed
mingw32-make.exe[1]: *** [CMakeFiles/uWS.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
mingw32-make.exe: *** [all] Error 2

**Comment by alexhultman** [comment]
That code is way, way deprecated and is not supported in any way. CMake was removed many years ago, and Mingw32 was never supported.

**Comment by charlescookey** [comment]
Thanks for the reply
