### ISSUE TITLE
No matching overload function found

### ISSUE THREAD

**Issue by xrnss** [uNetworking/uWebSockets#1104]
I am trying to build a C++ server that uses uWebsockets.
When trying to build, I get "uWS::TemplatedApp<false>::ws': no matching overloaded function found" (also I get it with true instead of false but that's SSL handling)

I also get  " 'initializing': cannot convert from 'initializer list' to 'uWS::TemplatedApp<false>::WebSocketBehavior &&' ".

If you need code snippets, tell me.

I am a uWebsockets noob, apologies if this has been answered somewhere else but I cannot see that. Perhaps it is a recent update that has caused the issue?

**Comment by alexhultman** [comment]
#872
