### ISSUE TITLE
[Feature request] move settings to connection level

### ISSUE THREAD

**Issue by streamich** [uNetworking/uWebSockets#1106]
Currently `compression` and `maxPayloadLength` settings are set once for the whole server. Would be great to allow setting them for each connection individually instead.

**Comment by alexhultman** [comment]
They are set once for every "route". You can have many routes per app, and many apps per process. This grouping is important to reduce memory usage per socket.

**Comment by streamich** [comment]
To clarify, currently there are no extra data stored per each socket about compression, for example, even if `DEDICATED_COMPRESSOR_xxxKB` is used that information is not stored on connection level?

I'm just thinking in my use case I cannot have many routes. Say, I have 1 million clients, and each client configures their connections to be either with compression or not.

1. I cannot pre-create 1 million routes on each server for all possible clients.
2. Even if I could pre-create those routes, I would like the compression setting to be dynamic, so the client can change it at any time and all new connections will use the new setting.

**Comment by streamich** [comment]
Or, I could have two routes:

1. One where all clients with disabled compression connect.
2. Two where all clients with compression-enabled connect.

**Comment by streamich** [comment]
Looks like `websockets/ws` allows to set both of those settings per connection.

**Comment by alexhultman** [comment]
It also looks like `websockets/ws` is a heck of a lot less efficient 😉, so if that's an option for you then uWS probably never was applicable to your use case to begin with.

It's never going to be a per-socket data structure in uWS, it goes against the entire hierarchical design. You don't wan't these settings per socket, it makes no sense. And this is not how the websocket protocol works - you cannot set these settings dynamically, they are set at connection time and cannot be changed.

So you still have to inform the server what your intentions are, and that can be easily done by having two routes, one for each setting.

In any case, this request of yours is never going to fit in with uWS design goals.
