### ISSUE TITLE
Ability to replace HTTP route handler (regression? from v16)

### ISSUE THREAD

**Issue by lostrepo** [uNetworking/uWebSockets#1109]
1. Linux kernel 5.7.X
2. uWebSockets.js 18.13.X
3. Node 12.18.X

**In v16ish of uWebSockets.js I can replace HTTP route handler with new one at any time**.
In v18ish it doesn't work anymore.
**Just wondering if that feature will return in the future**.
Using it to live reload cached in memory gzipped buffers of files when they changed/deleted/etc.

Test script (assumes that uWebSocket.js versions located in local ```node_modules``` folder)
*Sorry for messy code*
```javascript
/*
	Test ability to replace HTTP route handler function
	ExitCode: 0 - success, 1 - failure
 */

'use strict';
var
cl	=	console.log.bind(console),
uws	=	{
// don't forget to place v16 binaries into v16.uWebSockets.js folder or comment out that line
	v16ish: require('./node_modules/v16.uWebSockets.js/uws.js').App(),
	v18ish: require('./node_modules/uWebSockets.js/uws.js').App()
},
portStart			=	3000,
route				=	'/test',
portReplaceString		=	'@port@',
requestUrl			=	'http://localhost:'+ portReplaceString + route,
firstRouteHandlerResponse	=	'First route response',
replacedRouteHandlerResponse	=	'Replaced route response',
toTest				=	0,
exitCode			=	0;

for (var k in uws){
	var port	=	portStart + toTest++;

	uws[k]
	// setup first route
		.get(route, function(resp, req){
			return resp.end(firstRouteHandlerResponse);
		})
	// setup replaced route
		.get(route, function(resp, req){
			return resp.end(replacedRouteHandlerResponse);
		})
	// listen
		.listen(port, function(listenSocket){
			if (listenSocket){
				cl('Listening on port: '+ this);
			} else {
				cl('Failed to listen on port: '+ this);
				exitCode	=	1;
			}
		}.bind(port));

	// test that we get replaced route
	// listen should succeed before request attempt timeout
	// otherwise something wrong with listen
	require('http').get(requestUrl.replace(portReplaceString, port), function(resp){
		var data	=	[],
		version		=	this;

		resp.on('data', function(chunk){
			data.push(chunk);
		});

		resp.on('end', function(){
			if (data.join('') === replacedRouteHandlerResponse){
				cl('Route replace success for version '+ version);
			} else {
				cl('Route replace failure for version '+ version);
				exitCode	=	1;
			}

			if (--toTest == 0){
				process.exit(exitCode);
			}
		});
	}.bind(k));
}

setTimeout(function(){
	cl('Test timeout');
	process.exit(1);
}, 5000);
```

Running:
```sh
node route.replace.test.js && echo 'success' || echo 'failure'
```
Results in:
```
Listening on port: 3000
Listening on port: 3001
Route replace success for version v16ish
Route replace failure for version v18ish
failure
```

**Comment by hst-m** [comment]
@lostrepo how many files are you setting routes for like this? if you have hundreds or thousands of files that is a large number of functions created/re-created and watched for GC
> Object allocations, particularly function object allocations due to the heavy amount of internal data needed to implement them, can be taxing to performance. Allocated objects are not simply just sitting in memory but the garbage collector is constantly looking for unused objects so that they can be deallocated. The more memory you use in JavaScript the more CPU is being used to power the garbage collector and less CPU becomes available to run actual code

you could have a single function handling it:
```javascript
app.get('/public/:file',(res,req)=>{
   const file=req.getParameter(0)
   if(!files[file]) return res.writeStatus('404').end()
   if(files[file].redirect) return res.writeStatus('301').writeHeader('Location',files[file].redirect).end()
   if(files[file].etag==req.getHeader('if-none-match')) return res.writeHeader('304').end()
   res.end(files[file].content)
})

const files={}
require('fs').watch('directory',(event,file)=>{
   // update files[file] here 
})
```
the `req.getParameter(0)` takes a very small amount of time and the if statements are instant, but you are using a tiny amount of memory/no extra functions being created and destroyed. I think being able to update the http routes is a good idea/nice feature so it should be added if possible but I wonder if creating unique functions for every possible file and state of those files is good performance. Also reading that arrow functions are same [performance ](https://stackoverflow.com/a/44031830) as normal functions

**Comment by lostrepo** [comment]
@hst-m
1. A bit less than 500 'static' routes in test VM. Maybe I'll make 50k tests later.
2. Using v8 flags to deal with dumb GC and scheduled+manual calls to it in code.
3. As I wrote before I prefer to trade memory for better hot path performance.
4. Good, will research how they optimized arrow functions and probably test how it performs in my case.

I think 'me' gone off topic here already.

**Comment by alexhultman** [comment]
I don't care about this support for performance reasons, the idea I have is better integration with the SNI support. I have opened a new issue for that.
