### ISSUE TITLE
Wrong return value from inflate in PerMessageDeflate.h

### ISSUE THREAD

**Issue by raskath** [uNetworking/uWebSockets#1111]
Hi,

 if i send  binary  payload bigger than 16361 byte  per websocket and compression is activated the onMessage function received an  empty string_view with size 1.

I looked into the code from inflate in PerMessageDeflate.h. And i think your return value in line 232 is maybe incorrect.

If i change the return value from   
`          return {zlibContext->dynamicInflationBuffer.data(), zlibContext->dynamicInflationBuffer.length()};  
`
to 
`            return {{zlibContext->dynamicInflationBuffer.data(), zlibContext->dynamicInflationBuffer.length()},true};
` 
Everything works fine.

**Comment by alexhultman** [comment]
You're right, it hasn't been updated when std::string_view became std::pair<std::string_view, bool>. Really, it should use std::optional as that is less prone to error and more elegant ;) Great find!

**Comment by alexhultman** [comment]
This should be fixed now. You mind checking that it works properly?
