### ISSUE TITLE
How to access websocket connections in GET, POST,..etc routes.

### ISSUE THREAD

**Issue by BFamzz** [uNetworking/uWebSockets#1113]
Please this isn't a bug and can be labeled FAQ.

The uWebSockets manual strongly disapproves of using std::map to store websocket connections, that's why there's a userData structure available.

But assuming we have 3 websocket connections with unique ids (assigned via userData struct), how can we access the websocket connection outside of the websocket routes (i.e inside get, post...etc routes).

Thanks.

**Comment by alexhultman** [comment]
That's not up to me. You're supposed to make your own decisions. I don't know what's best in your case and it seems you've read the manual so do whatever you feel like

**Comment by BFamzz** [comment]
Hi @alexhultman Thanks for your response. I understand that use-cases differ per application but can you just do a small example showing how you would go about sending a websocket message to a user with an active websocket connection with a unique id (via userData) in a GET route.

Thanks.

**Comment by alexhultman** [comment]
Your question has nothing at all to do with this library.

If you cannot figure the pieces out then you need to go back to the basics first. You can't run before you know how to crawl and I don't crawl with people.
