### ISSUE TITLE
CLOSE-WAIT status  Impact on other user login

### ISSUE THREAD

**Issue by aFoxWithDream** [uNetworking/uWebSockets#1126]
hello, I'm sorry to bother you... When I close a large number of clients at the same time, there are a lot of CLOSE-WAIT states, must wait for the state to disappear, new users can connect,  is there any problem with the program?

tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                 ::ffff:119.139.199.126:20201              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                  ::ffff:192.168.80.125:54318              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                 ::ffff:119.139.199.126:46457              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                 ::ffff:119.139.199.126:33476              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                 ::ffff:119.139.199.126:18635              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                 ::ffff:119.139.199.126:10676              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                 ::ffff:119.139.199.126:47850              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                  ::ffff:192.168.80.125:54262              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                  ::ffff:192.168.80.125:54328              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                ::ffff:183.8.192.10:52514              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                 ::ffff:119.139.199.126:23886              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                  ::ffff:192.168.80.125:54332              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                ::ffff:183.8.192.10:52393              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                 ::ffff:119.139.199.126:12244              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                 ::ffff:119.139.199.126:22251              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                ::ffff:183.8.192.10:52553              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                 ::ffff:119.139.199.126:33154              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                 ::ffff:119.139.199.126:30131              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                  ::ffff:192.168.80.125:54340              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                ::ffff:183.8.192.10:52505              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                 ::ffff:119.139.199.126:31040              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                 ::ffff:119.139.199.126:47844              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                  ::ffff:192.168.80.125:54342              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                  ::ffff:192.168.80.125:48242              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                 ::ffff:119.139.199.126:24396              
tcp    CLOSE-WAIT 1150   0      ::ffff:172.16.10.211:1516                  ::ffff:192.168.80.201:35086              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                ::ffff:183.8.192.10:52580              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                ::ffff:183.8.192.10:52234              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                  ::ffff:192.168.80.125:54324              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                  ::ffff:192.168.80.125:54336              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                 ::ffff:119.139.199.126:17128              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                 ::ffff:119.139.199.126:43689              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                 ::ffff:119.139.199.126:35659              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                  ::ffff:192.168.80.125:54352              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                 ::ffff:119.139.199.126:12975              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                  ::ffff:192.168.80.125:54292              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                  ::ffff:192.168.80.125:54312              
tcp    CLOSE-WAIT 312    0      ::ffff:172.16.10.211:1516                 ::ffff:119.139.199.126:16655              
tcp    CLOSE-WAIT 220    0      ::ffff:172.16.10.211:1516                  ::ffff:192.168.80.125:54270

**Comment by aFoxWithDream** [comment]
sorry, it's my mistake.....

**Comment by alexhultman** [comment]
What did you fix?
