### ISSUE TITLE
C++ how to read request body

### ISSUE THREAD

**Issue by Riku32** [uNetworking/uWebSockets#1127]
There is no body parameter or documentation on how to read the body

**Comment by Riku32** [comment]
I have figured out it is with onData but the issue now is that while reading data the connection aborts due to taking too long. Also segfaults in the process since im doing stuff in the request.

**Comment by alexhultman-2fa** [comment]
There are several examples of how to read a body in the JS repo.

**Comment by Riku32** [comment]
I use C++

**Comment by alexhultman** [comment]
So fix your app? It's not a bug in the library.
