### ISSUE TITLE
Bad template deduction in some example files

### ISSUE THREAD

**Issue by Sunstradamus** [uNetworking/uWebSockets#1130]
`BroadcastingEchoServer`, `EchoServer`, and `EchoServerThreaded` fail to compile/deduce due to lacking the `.upgrade` handler on older versions of GCC.

EDIT: Seems to have been only partially fixed in PR #1116

**Comment by alexhultman** [comment]
You can set upgrade to nullptr, but having holes in the initialization is kind of the point with designated initializers (holes are default initialized) so a standards compliant C++20 compiler should handle this. I guess you have a too old compiler?

**Comment by Sunstradamus** [comment]
I agree, but for capital R reasons I'm using GCC 7.5.0 from Ubuntu Bionic.

**Comment by alexhultman** [comment]
Never heard "capital R reason" before but it made me giggle. Is that a "bullshit reason" such as company policy?

Anyways, the library itself is always compatible with C++17. Only the examples make use of C++20 for brevity.

**Comment by Sunstradamus** [comment]
Yup, that's exactly what it means but it sounds a lot nicer :). Good to know that the library will aim to be C++17 compatible, version upgrades have been smooth sailing so far.
