### ISSUE TITLE
Calling websocket->close() and websocket->write() from another thread

### ISSUE THREAD

**Issue by ludekvodicka** [uNetworking/uWebSockets#1153]
Sorry for bothering again. I have another crash on Win64 but I'm not sure if this is a bug or wrong library usage.

Should it be safe to call `websocket->close()` from another thread (or `websocket->write()`) ? 

Occasionally the application is crashing after calling `websocket->close()` from the main application thread (when simulating manual client disconnection in our tests). 

It's because `s->context` is `0xddddddddddd` during `TopicTree::unsubscribeAll()`

But I'm not sure if this is a bug or it's caused by calling it from the other thread because this code https://github.com/uNetworking/uSockets/blob/master/src/socket.c#L65 doesn't seem to thread-safe.

Is there any list of methods that are safe to call from another thread? 

And is there any "writeable" callback in the uWebsockets thread where is it possible to run these not thread-safe methods? I read about `us_timer_set` which should be probably utilized too (https://github.com/uNetworking/uWebSockets/blob/master/examples/UpgradeAsync.cpp)

Thank you

**Comment by ludekvodicka** [comment]
I just find that also calling `us_listen_socket_close ` from the main thread is occasionally crashing the app. 

![devenv_2020-12-23_15-50-29](https://user-images.githubusercontent.com/3900551/103009206-a5f85d00-4536-11eb-9636-6fe8cfc8f026.png)

![ApplicationFrameHost_2020-12-23_15-52-25](https://user-images.githubusercontent.com/3900551/103009299-e0fa9080-4536-11eb-8f03-fb527cbb7edb.png)

**Comment by hst-m** [comment]
Have you read user manual regarding threads? https://github.com/uNetworking/uWebSockets/blob/master/misc/READMORE.md

**Comment by ludekvodicka** [comment]
I read it several times but based on your reply I probably missed something. 

I know a whole uWS::App has to run in own thread. But I didn't find any example/mention in the docs how to invoke commands (finalize loop, send data,...) from other threads.

I'm aware that all these issues are caused probably by missing synchronization, but I didn't find any way how to invoke it from the uWS::App thread. This is the reason why I'm posting it here.

Should I use a timer for such cases? Or is there any "Writeable" callback where I can execute it?

Thanks for pointing me to any example/docs.

**Comment by ludekvodicka** [comment]
Seems I found the solution in `uWS::Loop::get()` and `uWS::Loop::defer()`, but I'm not sure if this is currently the recommended way, because there is no mention of this anywhere in the documentation or examples.

**Comment by alexhultman** [comment]
Loop defer is the only thread safe function.

**Comment by ludekvodicka** [comment]
Thanks for the confirmation and thanks for the great library. 

If I can suggest, it would be probably good to have any example or mention about defer in the documentation.

**Comment by jrch2k20** [comment]
Yeah, i would appreciate an example on how to use uWS::SSLApp::Publish from another thread.

**Comment by alexhultman** [comment]
If you search in Discussions you'll find 5 answers of this

**Comment by alexhultman** [comment]
Hehe np, maybe I should link to it from the readme. It's a new tab

**Comment by jrch2k20** [comment]
yeah i think would be nice, good stuff in there and yeah defer and publish working like a charm now ;)

Awesome work and tyvm for your time

**Comment by jacobsologub** [comment]
`uWS::Loop::defer()` doesn't seem to be firing...

I've got a separate thread firing at about 1 seconds interval(s).

```
uWS::Loop::get()->defer ([] () {
    auto x = 0; // not fired.
});
```

`Loop::deferQueues` just keeps building up.

I'm on 8410f7e
