### ISSUE TITLE
Remove getUserData

### ISSUE THREAD

**Issue by hellow554** [uNetworking/uWebSockets#1160]
Currently `getUserData` returns a `void*` which must be casted manually to my type. But I will pass the type in the `ws` function, so my question is, would it be possible to pass that type internaly to the Websocket class as well, so we can get a function signature like this: `T &getUserData()`?

Would make it a little bit safer to use.

**Comment by alexhultman** [comment]
Yes definitely. But that would have to break backwards compatibility since WebSocket needs one more template argument. This can be considered for next major release.

**Comment by alexhultman** [comment]
Why not just remove getUserData and make the WebSocket derive from USERDATA then?

Then you can do things like

struct PerSocketData {
 int something = 12;
};

ws->something++;

**Comment by alexhultman** [comment]
That would sync with the JavaScript wrapper as well, since they just do ws.something++; That removes differences between the two

**Comment by alexhultman** [comment]
getUserData remains but is now type safe. I did not find a good way to remove the function so it stays

**Comment by hellow554** [comment]
https://github.com/uNetworking/uWebSockets/blob/2d65df86c7988f5d9afa826cfbceda332f06f6a4/misc/main.cpp#L43
https://github.com/uNetworking/uWebSockets/blob/2d65df86c7988f5d9afa826cfbceda332f06f6a4/misc/main.cpp#L48
https://github.com/uNetworking/uWebSockets/blob/2d65df86c7988f5d9afa826cfbceda332f06f6a4/misc/main.cpp#L63
https://github.com/uNetworking/uWebSockets/blob/380b3a7134ee0b52fd0ed02bcef8ddecdf244576/src/App.h#L216

should get updated
