### ISSUE TITLE
WebSocket::getRemoteAddress() usage

### ISSUE THREAD

**Issue by aprole** [uNetworking/uWebSockets#1173]
Hello,
I am trying to get the remote address from a WebSocket with an IPv4 address, but for some reason the fourth byte is a random number. The first three integers are correct. Am I doing something wrong with the parsing or could this be an issue with getRemoteAddress()?

```
string_view address = ws->getRemoteAddress();
int size = (int)address.size();
string dest;
		
// IPv4
if (size == 4)
{
	char buff[16];
	snprintf(buff, sizeof(buff), "%u.%u.%u.%u", address[0], address[1], address[2], address[3]);
	dest = buff;
}

cout << dest;
```

**Comment by ddevienne** [comment]
According to https://en.cppreference.com/w/cpp/io/c/fprintf, a _naked_ `%u` expects an `unsigned int`, i.e. 4 bytes,
and that you need to use `%uhh` instead, for a 1-byte unsigned integer. Assuming `getRemoteAddress()` returns it in binary form that is. In general, you should shy away from unsafe C-style API IMHO, and stick to type-safe C++, either iostreams, or `fmt::format` (pre-C++20) and `std::format` if you can use C++20.

**Comment by aprole** [comment]
Thanks, good to know! I also just realized that my outdated branch was missing a new function, getRemoteAddressAsText(), which works just fine.
