### ISSUE TITLE
Loopdefer affects the performance of connection creation

### ISSUE THREAD

**Issue by aFoxWithDream** [uNetworking/uWebSockets#1176]
when i used a lot of defer to publish message, new connection cannot be ESTABLISHED,  i tried upgradeAsync and upgradeSync,  How should I solve the problem, can you make some suggestions?Thanks

**Comment by alexhultman** [comment]
Do you have a second thread with a loop that just calls publish all the time?

**Comment by aFoxWithDream** [comment]
Yes, I'm testing an application scenario like this

**Comment by alexhultman** [comment]
Then you're going to blow your server sky high. You can look at the Backpressure.js example of the JS repo.
