### ISSUE TITLE
Add option for redirecting head to get

### ISSUE THREAD

**Issue by hellow554** [uNetworking/uWebSockets#1190]
According to [wikipedia](https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Request_methods)

> The HEAD method asks for a response identical to that of a GET request, but without the response body. This is useful for retrieving meta-information written in response headers, without having to transport the entire content.

Currently they are two distinct listeners where I can each register a callback.

I would like to see that if no `head` callback is defined, but a `get` cb, that uwebsockets calls the `get` callback and throws away the body (:

Maybe this one can be used with an AppOption, e.g. `redirectHeadToGet` or similar if you don't like that to happen per default.

What do you think?

**Comment by alexhultman** [comment]
It's a good proposal but I think that falls out of scope.

You can easily wrap get and head functions into a convenience function taking bool isHead then making the appropriate decisions.

app.getOrHead with res, req, isHead

**Comment by hellow554** [comment]
> app.getOrHead

do you suggest a new method on the `TemplatedApp` class, or am I misreading it?

**Comment by alexhultman** [comment]
I could add getOrHead, but there is already head and get, so I don't see why I should provide _mixes_ of components. That is not going to scale, scope-wise. You have to do with what you have.
