### ISSUE TITLE
license

### ISSUE THREAD

**Issue by weqdev** [uNetworking/uWebSockets#1191]
Do I have to pay to use uWebSockets JS library for the enterprise website development?
Or can I just use it after simply cloning from github?

**Comment by alexhultman** [comment]
Source code and compiled binaries are licensed Apache License 2.0 (free to use). Everything else (logos, names, texts) is not licensed so you cannot put the logo on your product or something like that.

**Comment by weqdev** [comment]
What do you mean by "Everything else (logos, names, texts)"?

**Comment by alexhultman** [comment]
I mean you can read texts and look at logos but you can't redistribute modifications of those, or use my brand to sell or market products.

The source code itself you can do pretty much what you want with.

**Comment by weqdev** [comment]
What logo do you mean? uWebSocket has logo when I use it in the code?

**Comment by weqdev** [comment]
I'm going to develop the big chatting application.
Can't I use uWebsocket for it for free?

**Comment by alexhultman** [comment]
uWebSockets is free to use commercially, yes.
