### ISSUE TITLE
Implement shared compressor using libdeflate

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets#1211]
Benchmarks show that libdeflate is about 2.5x in performance to zlib when it comes to non-sliding-window-compressions (which are exactly what SHARED_COMPRESSOR is).

zlib-cloudflare did not show any significant gains for small message compressions over zlib in fact it was slower (which makes sense, SIMD).

So libdeflate is the perfect fit for SHARED_COMPRESSOR (if it turns out to have all the features we need!).

**Comment by alexhultman** [comment]
I have implemented this. The nice thing is that this can work seamlessly as a fast path to zlib. It boosts perfomance by insane amounts - from 120k messages/second to over 210k on my WSL2. This is insane and so simple. Will test with Autobahn!

**Comment by alexhultman** [comment]
I even get better compression ratios for JSON messages! WTF IS HAPPENING!?

**Comment by dvergeylen** [comment]
Probably [Huffman coding](https://www.ietf.org/rfc/rfc1951.txt) at its best and[ no checksum computation for the DEFLATE algorithm](https://github.com/ebiggers/libdeflate#deflate-vs-zlib-vs-gzip) 🙃

**Comment by alexhultman** [comment]
Zlib does DEFLATE just like libdeflate so there is no "cheating" involved. Zlib is written for 1980s computers and does streaming; libdeflate is Über-optimzed for non-streaming cases and is SIMD-optimized for modern computers. It passes Autobahn now, so closing

**Comment by alexhultman** [comment]
Well I am officially a moron. Too much coffee, way too little fact checking.

LIBDEFLATE WAS NEVER COMPRESSING - THEY SKIP COMPRESSING SMALL MESSAGES!

Zlib actually still wins when you start hitting cases where it actually does compress! *facepalm*.

At least there is a benchmark now!
