### ISSUE TITLE
Content-length header is being overriden

### ISSUE THREAD

**Issue by kolodziejczak-sz** [uNetworking/uWebSockets#1229]
Currently, the Content-Length header is being overriden with the `res.end(data) data.length`. This solution blocks the opportunity to properly respond to the http.HEAD request.

Here's code example:

```javascript
  res.writeHeader('Content-Length', '36');
  res.end();
```
Header response should not contain any body data and in the above example the Content-Length header is being overriden to 0.

https://github.com/uNetworking/uWebSockets/blob/be19c7f939f9f5e36f92578c433c7dc0b6a5f887/src/HttpResponse.h#L96

**Comment by alexhultman-2fa** [comment]
This requires a new function like res.endWithoutBody(length) or similar

**Comment by alexhultman** [comment]
Use new endWithoutBody in 20.9
