### ISSUE TITLE
'install' target breaks: cp: /usr/ports/www/uwebsockets/work/stage/usr/local/include/uWebSockets is not a directory

### ISSUE THREAD

**Issue by yurivict** [uNetworking/uWebSockets#1236]
Here: https://github.com/uNetworking/uWebSockets/blob/master/Makefile#L56

you need to add ```mkdir -p $(DESTDIR)$(prefix)/include/uWebSockets```

**Comment by alexhultman-2fa** [comment]
Oh you're right that was removed when I removed f2
