### ISSUE TITLE
Shorter socket-timeouts after WebSocket::end()

### ISSUE THREAD

**Issue by not-implemented** [uNetworking/uWebSockets#1245]
Currently after calling `WebSocket::end()`, the normal idleTimeout (default 120s) is active. For broken/hanging connections (reproducable with iptables DROP of WebSocket port after connecting), the socket is still active until this timeout.

Normally this is not a big issue ... but it is, when doing a graceful shutdown of the whole application. Such broken clients cause the event loop to hang until all the timeouts are reached.

One solution will be, to call `WebSocket::close()` instead of `end()` on shutdown, it works ... but it is not "graceful" anymore, of course ;-)

Another solution will be, to expose `WebSocket::timeout()` as public, but maybe you don't want this, because it will interfere with the internal timeout handling and will be very misunderstanding.

The third solution will be, to set a shorter timeout in `WebSocket::end()` ... for example to `webSocketContextData->idleTimeoutComponents.second` which you used for the auto-ping-timeouts. (`WebSocketContextData::calculateIdleTimeoutCompnents` needs to be adjusted, so `second` is also set if `sendPingsAutomatically` is off.)

Of course, I would prefer to have it configurable separately ... e.g. `pingTimeout` ... sometimes, too much "magic" is intransparent ;-)

What do you think? If you like, I can try a pull-request.

**Comment by alexhultman** [comment]
Third option is nice imo

**Comment by not-implemented** [comment]
Ok cool, I'll try to implement in the next days.

By the way - I don't know if you receive notifications on closed issues - did you see my comments in https://github.com/uNetworking/uSockets/pull/97 ? Unfortunately I broke the timeout implementation there.

**Comment by alexhultman-2fa** [comment]
I saw but no release has that yet
