### ISSUE TITLE
uWS for golang

### ISSUE THREAD

**Issue by xyndata** [uNetworking/uWebSockets#1254]
I like uWS very much, right now we are planning to use it for NodeJS. Are there any plans for golang?

Thank you very much

**Comment by alexhultman-2fa** [comment]
No, golang is not compatible as it is not really a low level language but rather a high level coroutine-only, GC-only runtime. You can't even do per-thread data in golang, so implementing the memory hierarchy in golang is impossible. There are no concept of threads in golang, everything is co-routines. And their C-FFI is really, really slow.

However, golang is fast on its own so the need for uWS is minimal there. gobwas/ws is incredibly fast (written in golang).

**Comment by alexhultman-2fa** [comment]
https://github.com/gobwas/ws

**Comment by xyndata** [comment]
Thank you Alex!
