### ISSUE TITLE
QUIC benchmarks

### ISSUE THREAD

**Issue by alexhultman-2fa** [uNetworking/uWebSockets#1257]
I have started benchmarking things - raw UDP, lsquic.

UDP message passing seems to be about 2x faster than TCP, so it does leave some margins for the QUIC implementation. I have compiled and am doing tests with lsquic - nothing definite to report yet but my plan is to have real numbers next month.

Like said the plan is do have QUIC perform the same as TCP/TLS - if that goal can be met then implementation in uSockets will begin.

**Comment by alexhultman** [comment]
Not sure I have all numbers correct but from all I can tell, QUIC is 2x the performance even compared with non-TLS TCP on my localhost. Again, not sure about if this is realiable or not but it definitely seems to kick ass in performance.

With a modified lsquic example I can do 333k msg/sec between two processes, while with uWS I can do 165k (over non-TLS) so even if I have something wrong, it still seems incredibly superior for short message sending.

lsquic also seems really well written and is easy to understand and work with! Getting QUIC support in uSockets will definitely be a high priority in the following summer months!

**Comment by alexhultman-2fa** [comment]
Better testing shows QUIC performs about (roughly) the same as TCP/TLS. It does not look to be significantly slower at least. Will continue with more 1-to-1 testing.

I first tested with multiple QUIC streams, but that shows very overestimated results as it essentially translates to packing multiple messages in the same UDP packet, which is not a reasonable case.

Testing instead with many separate QUIC connections, shows a lot more similar results to TCP/TLS.

**Comment by alexhultman-2fa** [comment]
Alright, I can already say with certainty that QUIC can perform the same as TCP/TLS. 103k vs. 102k is practically identical. With more tweaking QUIC might even go a little higher, but I do not expect it to go significantly higher than TCP/TLS. But that's fine - as long as we are not regressing in performance compared to the already high numbers with TCP7TLS. Both tests use BoringSSL, as BoringSSL is significantly faster than OpenSSL.

**Comment by ronag** [comment]
Might be relevant to test with network congestion and packet loss? I think quic might make more of a difference with that I’m mind.

**Comment by alexhultman-2fa** [comment]
The only real benefit of QUIC is that it does fewer round-trips per connection establishment (smacking both TCP and TLS into the same layer). The rest is nonsense marketing. Congestion algorithms for TCP are already evolving year-by-year.

The other "benefits" of QUIC are basically fixes for flaws of HTTP. Anyways; good news is that QUIC is not a downgrade at least.

**Comment by hst-m** [comment]
This is all referring to WebTransport built on top of QUIC which has 2 different message types, [Datagram](https://www.w3.org/TR/2021/WD-webtransport-20210504/#datagram-transport) for unreliable out-of-order size-limited messages and [Streams](https://www.w3.org/TR/2021/WD-webtransport-20210504/#bidirectional-streams-transport) for reliable in-order messages similar to Websocket, comparing these Websocket over TCP may have similar performance to Streams over UDP/QUIC but the Datagram messages will have network performance benefit, if that is what your app needs (unreliable out-of-order size-limited messages)

browser implementation:
```javascript
const wt = new WebTransport(url)

// Datagram read
for await (const data of wt.datagrams.readable) { /* datagram message */ }
// Datagram write
const datagramWriter = wt.datagrams.writable.getWriter()
datagramWriter.write(datagram)

// Stream read
const stream = await wt.createBidirectionalStream()
for await (const data of stream.readable.getReader()) { /* stream message */ }
// Stream write
const streamWriter = stream.writable.getWriter()
streamWriter.write(data)
```

**Comment by alexhultman-2fa** [comment]
Yes I know ;) I'm exaggerating a bit. My point is that QUIC is no silver bullet and it won't magically make everything a billion times better. It is still limited in pretty much the same ways.

**Comment by hst-m** [comment]
Looking at WebTransport protocol more and it is interesting because you have multiple options how to send messages, you can use a single Stream if you need messages in-order or you can use a different Stream for each message and still get reliability guarantee and no size limit unlike Datagram, I think this would give some performance benefit vs a single Websocket stream over TCP

**Comment by alexhultman-2fa** [comment]
The problem with TCP is not TCP. The problem with TCP is TLS. TLS run atop TCP so every "stream" becomes heavyweight. QUIC has TLS under the transport, not above. So "streams" become lightweight. TCP itself is pretty much flawless.

**Comment by alexhultman-2fa** [comment]
One big fat problem with QUIC is that is it really slow for internal traffic since it requires TLS for everything. Same with HTTP2. So TCP is still drastically faster for internal traffic. And what happens with proxies? Should proxies decrypt / encrypt everything? That is heavyweight as hell.

**Comment by ronag** [comment]
There is http2 without tls. Dunno about quic.

**Comment by alexhultman-2fa** [comment]
https://daniel.haxx.se/blog/2021/05/27/quic-is-rfc-9000/

QUIC is always encrypted
