### ISSUE TITLE
HTTP method is lowercased though it is case-sensitive

### ISSUE THREAD

**Issue by not-implemented** [uNetworking/uWebSockets#1261]
Currently the `req->getMethod()` returns a lowercased string (e.g. "get"). But the HTTP spec says, it is case-sensitive:

> The method token is case-sensitive because it might be used as a gateway to object-based systems with case-sensitive method names.

see https://datatracker.ietf.org/doc/html/rfc7231#section-4.1

So, IMHO the HTTP method name should not be lowercased.

**Comment by alexhultman** [comment]
I agree

**Comment by alexhultman** [comment]
This is definitely API-breaking, and in a bad way since people who compare with strings won't simply get compilation errors.

**Comment by uNetworkingAB** [comment]
I have a rewritten header parser that skips lowercasing the method (and is 35% faster) that I will swap to soon:

```
<GET> = </hello.htm HTTP/1.1>
<user-agent> = <Mozilla/4.0 (compatible; MSIE5.01; Windows NT)>
<host> = <www.tutorialspoint.com>
<accept-language> = <en-us>
<accept-encoding> = <gzip, deflate>
<connection> = <Keep-Alive>
```

**Comment by uNetworkingAB** [comment]
This bug makes no sense without a way to also register custom methods, not just the ones for http. So this is not really a bug report rather a feature request for app.custom(method string) which, needs to be case sensitive as a side note

**Comment by uNetworkingAB** [comment]
There is now a getCaseSensitiveMethod and the getMethod does an extra pass of lower casing to be backwards compatible
