### ISSUE TITLE
make install is failing on mac

### ISSUE THREAD

**Issue by j0t3x** [uNetworking/uWebSockets#1262]
https://github.com/uNetworking/uWebSockets/blob/c0ba2eb7b4f91611b202e877ea24f4476dec621c/Makefile#L57

```
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory

```
i think it should be `cp -r src/ "$(DESTDIR)$(prefix)/include/uWebSockets"`

**Comment by dalisoft** [comment]
I compiled few minutes ago, it works nice on x64 Intel macOS Big Sur 11.4.

Here steps i've tried:
```bash
git clone git@github.com:uNetworking/uWebSockets.git --recursive
cd uWebSockets
make
```

**Comment by j0t3x** [comment]
did you try the install step?

**Comment by dalisoft** [comment]
I did only 3 commands and it worked

**Comment by alexhultman-2fa** [comment]
installs fine for me

**Comment by alexhultman-2fa** [comment]
@j0t3x if you want to PR someting that works better do so, but I cannot see any problem with current ways
