### ISSUE TITLE
Inconsistent behavior with subscribe() and publish()

### ISSUE THREAD

**Issue by scottbradybuckii** [uNetworking/uWebSockets#1269]
When building a websocket server that conditionally subscribes certain sockets to topics, there seems to be inconsistent behavior when publishing to those topics. Sometimes the publisher receives the message and sometimes they don't. Based on my testing, the first socket to publish data to the topic works correctly (does not publish to themselves as well) and subsequent sockets do not (they publish both to themselves and to the rest of the topic).

I am currently using v19.2.0

Code example:

**Server**
```
const uWS = require('uWebSockets.js');
let index = 0;

uWS
  .App()
  .ws('/*', {
    open: (ws) => {
      index++;
      if (index == 1) ws.subscribe('b1');
      else ws.subscribe('b2');
    },
    message: (ws, message, isBinary) => {
      console.log(ws.getTopics());
      ws.publish('b1', 'b1');
      ws.publish('b2', 'b2');
    },
  })
  .listen(3000, (token) => {
    if (token) console.log('listening');
    else console.log('failed');
  });
```

**Client**
```
var W3CWebSocket = require('websocket').w3cwebsocket;

var client1 = new W3CWebSocket('ws://jb.scottbrady.dev/');
client1.onmessage = (e) => console.log("Client1 Received: '" + e.data + "'");

var client2 = new W3CWebSocket('ws://jb.scottbrady.dev/');
client2.onmessage = (e) => console.log("Client2 Received: '" + e.data + "'");

setTimeout(() => {
  console.log('-------------------\n### Client1 Sent ###');
  client1.send('');
}, 1000);
setTimeout(() => {
  console.log('-------------------\n### Client2 Sent ###');
  client2.send('');
}, 2000);
setTimeout(() => {
  console.log('-------------------\n### Client1 Sent ###');
  client1.send('');
}, 3000);
setTimeout(() => {
  console.log('-------------------\n### Client2 Sent ###');
  client2.send('');
}, 4000);
```

**Server Output**
```
listening
[ 'b1' ]
[ 'b2' ]
[ 'b1' ]
[ 'b2' ]
```

**Client Output**
```
-------------------
### Client1 Sent ###
Client2 Received: 'b2'
-------------------
### Client2 Sent ###
Client2 Received: 'b2'
Client1 Received: 'b1'
-------------------
### Client1 Sent ###
Client2 Received: 'b2'
-------------------
### Client2 Sent ###
Client1 Received: 'b1'
Client2 Received: 'b2'
```

**Comment by hst-m** [comment]
This section here needs update https://github.com/uNetworking/uWebSockets/blob/master/src/TopicTree.h#L94-L111

**Comment by alexhultman** [comment]
I will have a look at this. First step would be to extend the unit tests regarding pub/sub so that this failure is caught.

**Comment by alexhultman** [comment]
@hst-m using set_intersection is probably the way to go, but you don't need to allocate a new vector and fill it, then iterate it, you can just iterate directly with set_intersection. This is a fast path so you cannot have allocations there.

**Comment by alexhultman** [comment]
@scottbradybuckii repoen if not fixed in v19.3.0

**Comment by scottbradybuckii** [comment]
Sounds good, thanks for your quick work on this!

**Comment by alexhultman** [comment]
@hst-m Nice fix, it is released now make sure NPM downloads the latest
