### ISSUE TITLE
Error C2664

### ISSUE THREAD

**Issue by GalBaToRicS** [uNetworking/uWebSockets#1275]
![изображение_2021-06-26_143912](https://user-images.githubusercontent.com/73175148/123511814-46693e80-d68c-11eb-8649-8df07bcfd098.png)

**Comment by GalBaToRicS** [comment]
I add all necessary files and configure project.
Visual Studio Community 2019 (version 16.10)

**Comment by alexhultman** [comment]
I'm not familiar with these Sputnik letter and cannot infer what you are trying to report? We know the project does compile on Windows, so you'll have to solve your end.
