### ISSUE TITLE
No matching calls for uv_timer_init

### ISSUE THREAD

**Issue by JadeVand** [uNetworking/uWebSockets#1287]
I'm trying to add my own code to run alongside the main internal loop with libuv. 
I grabbed the loop with ```uWS::Loop::get()``` which I believe is the main loop and then I try to initialise a uv_timer with it by calling ```uv_timer_init(uWS::Loop::get(),&timer);```  where `timer` is `uv_timer_t` and I receive a compiler error `error: no matching function for call to 'uv_timer_init` 
How can I resolve this?

**Comment by alexhultman-2fa** [comment]
This is a generic C++ issue you can lookup on stackoverflow or in your compiler manual. Types do not match, there are examples to look at regarding this
