### ISSUE TITLE
casting us_timer_t to uv_timer_t

### ISSUE THREAD

**Issue by JadeVand** [uNetworking/uWebSockets#1288]
I'm initiating a timer with `us_create_timer` using `struct us_timer_t*` but is it okay to cast that `us_timer_t*` object to a `uv_timer_t*` object then set the data variable?
```
uv_timer_t* uvt = (uv_timer_t*)timer;
    uvt->data = this;
```
I tested and ran the code compiled and executed correctly but I'm just wondering if there is any potential downfalls to doing this or im overwriting something critical by casting and setting the data pointer.

**Comment by alexhultman** [comment]
#1287 you have already asked this question.

No, you can't just covert pointers of one type to another.

https://github.com/uNetworking/uWebSockets/blob/d94bf2cd43bed5e0de396a8412f156e15c141e98/examples/UpgradeAsync.cpp#L64

**Comment by JadeVand** [comment]
I looked at your code example in the broadcast server which used a lambda expression. I mainly just wanted to pass "this" into the expression. But I didn't know how to so I tried to rely on type conversion and use the data pointer

**Comment by alexhultman-2fa** [comment]
You can't do that. Check the example I posted

**Comment by JadeVand** [comment]
Thank you the example solved the issue.
