### ISSUE TITLE
WebSocket message handlers on the same thread?

### ISSUE THREAD

**Issue by maksimpiriyev** [uNetworking/uWebSockets#1295]
Is it possible to route all WebSocket message handlers on the same thread? (if multiple threads are running on the same machine)
Sometimes you may need to handle some operations concurrently such as shared buffer on the user data,Does uWebSockets handle this situation? or it needs an explicit mutex, etc to be used ?

**Comment by alexhultman** [comment]
How you handle events on different threads is up to you. You can lock, you can postpone, you can drop, whatever. Best would be to not need synchronization at all and keep things isolated to their own thread.
