### ISSUE TITLE
Using uWS in python as ws backend?

### ISSUE THREAD

**Issue by meiry** [uNetworking/uWebSockets#1296]
Hello 
is there any update on [this](https://pypi.org/project/uws/)  ?
if it is not supported , what will take to build support for this in python ? 
thanks

**Comment by alexhultman** [comment]
Hi the Python extension was discontinued. The C extension with callbacks was very fast, much faster than Node.js but Python developers have their own asgi interfaces which require futures which are implemented in script via asyncio and dramatically sinks performance to levels not worth pursuing. Also the Python community seemed very reluctant and unfriendly

**Comment by joeky888** [comment]
There is https://github.com/cirospaciari/socketify.py .
