### ISSUE TITLE
How to send data via a websocket using uWebsockets v0.14?

### ISSUE THREAD

**Issue by NikitaMishin** [uNetworking/uWebSockets#1304]
Have struggled to send data via WebSocket Group out of onUpdate , onConnection and other onSomething methods. Does it support it? If i just store the pointer to uWS::WebSocket<uWS::CLIENT> * will it work?

**Comment by NikitaMishin** [comment]
i thougt only of a broadcast but maybe it is overkill

**Comment by alexhultman** [comment]
I don't even remember how v0.14 works. You're on your own here

**Comment by NikitaMishin** [comment]
Ok, is this possible with the recent version?

**Comment by NikitaMishin** [comment]
actually solved the issue with PostCb, anyway thanks for the time
