### ISSUE TITLE
HttpRequest::getHeader cannot handle duplicate HTTP headers correctly

### ISSUE THREAD

**Issue by sky3141** [uNetworking/uWebSockets#1305]
Currently `req->getHeader()` can only get the HTTP header that appears for the first time. But the HTTP header can appear multiple times. 

> Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)]. It MUST be possible to combine the multiple header fields into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field-value to the first, each separated by a comma. The order in which header fields with the same field-name are received is therefore significant to the interpretation of the combined field value, and thus a proxy MUST NOT change the order of these field values when a message is forwarded.

see http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

When we use `req->getHeader("sec-websocket-protocol")` to parse a HTTP request like this:
```
...
Sec-WebSocket-Protocol: foo
Sec-WebSocket-Protocol: bar
```
Then we get `foo`, but expect `foo, bar`. 

> The |Sec-WebSocket-Protocol| header field MAY appear multiple times in an HTTP request (which is logically the same as a single |Sec-WebSocket-Protocol| header field that contains all values). However, the |Sec-WebSocket-Protocol| header field MUST NOT appear more than once in an HTTP response.

see https://datatracker.ietf.org/doc/html/rfc6455#section-11.3.4

**Comment by alexhultman** [comment]
I guess this is somewhat of a bug, but it also comes from design. If you want to look at all headers you can still loop over them and collect those with the same key.

**Comment by alexhultman** [comment]
Well it can be solved by introducing a new function getHeaders("sec-websocket-protocol") that seeks up all matches and returns something like a vector. But that can already be done on your end by just iterating over all headers and matching them yourself. So this is kind of not an issue.

**Comment by alexhultman** [comment]
Closing, since this can be solved already.
