### ISSUE TITLE
Message too big should return a 1009 code (is currently 1006)

### ISSUE THREAD

**Issue by hakoptak** [uNetworking/uWebSockets#1321]
Hi Alex,

First of all: thanks for creating and maintaining this wonderful project.

I've just started using uWebSockets (C++) in a side project and I've noticed the following:

When I send a message larger than the set limit (`maxPayloadLength`), the socket is currently forced to close and returns a `1006 (Abnormal Closure)`. But wouldn't it be neater to return a `1009 (Message too big)`?

**Comment by alexhultman** [comment]
The difference between 1006 and 1009 is that 1006 is reserved and cannot be sent. While 1009 can be sent as an actual message.

1006 can only be reported by the library itself, no peer can ever send it over the network. So when you get 1006 you know you can interpret the reason as coming from the library. If we would report 1009, that would conflict with what peers can actually send you.

**Comment by hakoptak** [comment]
Thanks for your quick reply.

The problem I am facing with 1006 is that I also get this message code when the connection abruptly closes (no wifi, for example). So I cannot distinguish 1006 as coming from the library or from the browser socket implementation. That's why it would be useful to have more specific codes, like 1009 for payloads that are too big. But this may be reported in the 1006 reason... (I should have checked that before creating this issue, sorry)

As of your last remark: that's a good point, I didn't think of that.

**Comment by alexhultman** [comment]
If the code is 1006 you can check if reason is ERR_TOO_BIG_MESSAGE

**Comment by hakoptak** [comment]
Thanks for pointing at the reason message and for your help. I misunderstood the close event protocol.

I'll close this thread since it turns out to be a non-issue.
