### ISSUE TITLE
trying to compile HttpServer.cpp but got this error

### ISSUE THREAD

**Issue by superdolt** [uNetworking/uWebSockets#1341]
how to compile the httpserver.cpp?

examples/HttpServer.cpp:28:5: warning: missing initializer for member 'optparse_long::argtype' [-Wmissing-field-initializers]
examples/HttpServer.cpp:69:32: error: no matching function for call to 'uWS::TemplatedApp<true>::TemplatedApp(us_socket_context_options_t&)'
   69 |         uWS::SSLApp(ssl_options).get("/*", [&asyncFileStreamer](auto *res, auto *req) {
      |                                ^

**Comment by alexhultman** [comment]
That example has been broken for a long time and does not compile

**Comment by superdolt** [comment]
is it difficult to fix? basically would hope for a working version.

**Comment by alexhultman** [comment]
https://github.com/uNetworking/uWebSockets/pull/1137
