### ISSUE TITLE
Re-ordering of sent messages

### ISSUE THREAD

**Issue by JWalker1995** [uNetworking/uWebSockets#1350]
I'm debugging an issue that I believe manifests as re-ordering messages. I'm still trying to make a small consistently reproducible example, but here's the human version:

1. Start cork.
2. Call WebSocket.send with large (750kb) binary string. This will call getSendBuffer and proceed down the fallback path that uses backpressure (asyncSocketData->buffer) as the buffer. NEEDS_DRAIN is returned, which calls AsyncSocket.write with zero length, which calls us_socket_write with part of the string.
3. End cork - Since we still have more data (500kb) to send, this calls AsyncSocket.write with zero length, which calls us_socket_write to write some more (I'm not sure if it's entirely written at this point).
4. Start cork.
5. Call WebSocket.send with some small messages (~50 messages, ~300 bytes each). This fills up the cork buffer.
6. Eventually, the cork buffer will be full and the next message will go down the fallback backpressure route in getSendBuffer. This appends it to asyncSocketData->buffer. NEEDS_DRAIN is returned, which calls write with zero length, which sends this message, however we've skipped the previous ~50 messages. Eventually they're sent, but obviously out of order.

**Comment by alexhultman** [comment]
So the last message to overflow cork buffer will get sent before those who did not overflow the cork buffer? One message gets sent out of order (the one that did not fit in cork buffer)

**Comment by JWalker1995** [comment]
Yes, plus many messages will be sent before the cork buffer drains, so more than one message is out of order.

**Comment by JWalker1995** [comment]
Here's a somewhat minimally reproducible example:

```
#include <string>

#include <uWebSockets/src/App.h>

class Conn {};
typedef uWS::WebSocket<false, true, Conn>::SendStatus SendStatus;

uWS::WebSocket<false, true, Conn> *conn = 0;
unsigned int nextIndex = 1;

int main(int argc, char **argv) {
    uWS::App app = uWS::App();

    struct us_timer_t *timer = us_create_timer((us_loop_t *) uWS::Loop::get(), 0, 0);
    us_timer_set(timer, [](struct us_timer_t *) {
        if (!conn) {return;}

        conn->cork([](){
            while (true) {
                if (nextIndex > 100) {
                    conn->close();
                    nextIndex = 1;
                    break;
                }

                unsigned int count = nextIndex == 1 ? 750000 : 300;

                std::string str(count, '-');
                std::string num = std::to_string(nextIndex++);
                std::copy(num.cbegin(), num.cend(), str.begin() + 1);
                str.back() = '\n';

                SendStatus res = conn->send(str);
                if (res == SendStatus::BACKPRESSURE) {
                    break;
                } else if (res == SendStatus::DROPPED) {
                    // Send again next time
                    nextIndex--;
                    break;
                }
            }
        });
    }, 16, 16);

    uWS::App::WebSocketBehavior<Conn> subConfig = {
        .compression = uWS::DISABLED,
        .maxPayloadLength = 16 * 1024 * 1024,
        .idleTimeout = 120,
        .maxBackpressure = 1024
    };

    subConfig.upgrade = [](uWS::HttpResponse<false> *res, uWS::HttpRequest *req, struct us_socket_context_t *socketCtx) {
        res->template upgrade<Conn>(
            Conn(),
            req->getHeader("sec-websocket-key"),
            req->getHeader("sec-websocket-protocol"),
            req->getHeader("sec-websocket-extensions"),
            socketCtx
        );
    };

    subConfig.open = [](uWS::WebSocket<false, true, Conn> *ws) {
        conn = ws;
    };

    subConfig.close = [](uWS::WebSocket<false, true, Conn> *ws, int /*code*/, std::string_view /*message*/) {
    };

    app
        .ws<Conn>("/sub", std::move(subConfig))
        .listen(9001, [](us_listen_socket_t *) {})
        .run();
}
```

Output:
-1--- (~750kb more)
-55--- (~300b more)
-56--- (~300b more)
-57--- (~300b more)
...
-100--- (~300b more)

**Comment by alexhultman** [comment]
Is the output that you list wrong or right? I get the output you list.

**Comment by alexhultman** [comment]
Can you repro before https://github.com/uNetworking/uWebSockets/releases/tag/v19.8.0 ?

**Comment by alexhultman** [comment]
Can you check this commit: https://github.com/uNetworking/uWebSockets/commit/7956546836904402ad18a00a1aa033c7a9c5c5ab

The issue is that once you cannot fit in cork buffer, it just makes a spot in the backpressure buffer completely disregarding how much is in the cork buffer. Then when uncorking happens, that corkbuffer content it put last in backpressure buffer, so essentially 1 or more messages can be sent in the wrong order.

This fix just copies any content in the corkbuffer to the backpressure buffer before it copies the message that did not fit. So it really is a fallback path once you send more than fits in the corkbuffer.

**Comment by JWalker1995** [comment]
Nice, that last commit works, thank you!

It's kind of surprising that a bug like this was able to manifest; are there tests that should have caught it?

**Comment by alexhultman** [comment]
Great, thanks for awesome digging & reporting. The bug was only there for 10 days but no tests found it (mainly Autobahn Testsuite is used for correctness). Oss-fuzz only tests for crashes but doesn't care for actual correctness. Smoke tests should be added, though.
