### ISSUE TITLE
Ability to handle an incoming connection from a socket descriptor (enabling multi-process)

### ISSUE THREAD

**Issue by Rush** [uNetworking/uWebSockets#1360]
Would it be possible to start handling a websocket connection in one process and pick up the connection in another child process where `uWebSockets` is used? If this was possible then it would be quite easy to implement Node.JS cluster-like multi-process solutions. Example flow:
- Master process (language/platform agnostic) starts a pool of processes with uWebSockets (C++ or Node.JS via uWebSockets.js)
- Master process starts handling connections
- A HTTP GET request comes in to master process
- Master process sends the file descriptor to one of the child processes
- Child process with uWebSockets responds with `HTTP/1.1 101 Switching Protocols` and owns the connection from now on

**Comment by alexhultman** [comment]
This is a "leaky abstraction" we used to allow before but don't want to support anymore. You can already run multiple processes listening on the same port, on Linux.
