### ISSUE TITLE
Add / remove HTTP routes dynamically (better SNI support)

### ISSUE THREAD

**Issue by ghost** [uNetworking/uWebSockets#1361]
Passing nullptr to app.get(url, .. can be a way to unregister that route.

**Comment by alexhultman** [comment]
This can only be done for HTTP routes, WS routes cannot be removed

**Comment by alexhultman** [comment]
It's not just about adding/removing routes - it also needs to be per SNI.

You should attach routes to SNI domains, not the app itself.


App.sni("www.example.com").get("/someurl").post("/url").sni("www.another.com").get("/helllo").listen(3000).run()

To be backwards compatible it should default to "all" if you don't specify with sni what domain it is for.

**Comment by uNetworkingAB** [comment]
There is now initial app.domain(server name).get(...).domain(another server name).get(...) support added.

**Comment by uNetworkingAB** [comment]
Technically this is possible now - you can add and remove Server names, which removes all URL routes. So it is possible to remove-all-then-add-some to achieve removal
