### ISSUE TITLE
Please add example how to set more OpenSSL options

### ISSUE THREAD

**Issue by sirzooro** [uNetworking/uWebSockets#1363]
I need to set few extra OpenSSL things (minimum TLS version, list of allowed ciphers, enable mTLS). I found `TemplatedApp::getNativeHandle` method, but there is no example how to use it. Please add new example how to use it to set additional OpenSSL options.

**Comment by alexhultman** [comment]
https://github.com/uNetworking/uWebSockets/blob/5d8983902690a0b93193d922d6239965bdca2f76/src/App.h#L108

You have the SSL_CTX so lookup what you want in the OpenSSL docs
