### ISSUE TITLE
Missing support for Unix-Domain sockets

### ISSUE THREAD

**Issue by sirzooro** [uNetworking/uWebSockets#1364]
uWebSockets library does not allow to start server on unix-domain socket (AF_UNIX). It also does not have option to use specified socket descriptor, what could be used as a workaround.

**Comment by alexhultman** [comment]
This is tracked already in uSockets repo

**Comment by Young-Flash** [comment]
I have add this support, it can been see [here](https://github.com/Young-Flash/uWebSockets). @sirzooro
