### ISSUE TITLE
Set IP for listen

### ISSUE THREAD

**Issue by johnroper100** [uNetworking/uWebSockets#1368]
Is there any way to set the IP of the listen command? Right now it just allows for a port selection, but that seems to work only on localhost. I'd like to set the IP to something other than localhost so that it can be accessed from the public IP.

**Comment by johnroper100** [comment]
@alexhultman maybe you might know?

**Comment by alexhultman** [comment]
You can pass hostname and port if you look further

**Comment by johnroper100** [comment]
I couldn't find an example of this.

**Comment by johnroper100** [comment]
@alexhultman like this? `.listen("192.168.0.1", 8000, [](auto *listenSocket) {`

**Comment by alexhultman** [comment]
You have to provide a bug report with all the info needed if you want this looked at. Pretty sure it works like should already.
