### ISSUE TITLE
Encountered "Error: Cork buffer must not be held across event loop iterations!"

### ISSUE THREAD

**Issue by kaishian** [uNetworking/uWebSockets#1369]
Hi there,

I am using below feature or function:
- c++-17
- received BINARY message from remote peer
- external event-loop (libuv): call Loop::get(uv_loop_t*)->integrate()

I didn't use following function:
- pub/sub
- cork
- forking

I tried these versions:
uWS v19.3.0: work well
uWS v20.5.0: failed
uWS v20.8.0: failed

call stack attached as below.
[uws_call_stack.txt](https://github.com/uNetworking/uWebSockets/files/7461787/uws_call_stack.txt)

Please provide suggestions on how to overcome this issue, thanks a lot.

**Comment by alexhultman** [comment]
The call stack does not tell me anything since this error can only be thrown at one specific point. You have to debug what causes this. Are you using cork? Are you using async upgrades? Are you using multithreading? Etc

**Comment by alexhultman** [comment]
Nobody else has reported this for 2 months, closing for now
