### ISSUE TITLE
Response with a status code of 204 No Content must not send a Content-Length header field per RFC 7230 section 3.3.2

### ISSUE THREAD

**Issue by davidmurdoch** [uNetworking/uWebSockets#1370]
> A server MUST NOT send a Content-Length header field in any response
> with a status code of 1xx (Informational) or 204 (No Content).  A
> server MUST NOT send a Content-Length header field in any 2xx
> (Successful) response to a CONNECT request

https://datatracker.ietf.org/doc/html/rfc7230#section-3.3.2 (see page 30)

I couldn't find a way to prevent uWebsockets from writing the Content-Length header on end.

**Minimal reproduction steps (uWebsockets.js#20.4.0, Node v14.17.4):**

Create server:
```javascript
// test.js
const {App} = require("uWebsockets.js");

App().any("/*", (response) => {
  response.writeStatus("204").end();
}).listen(8888, () => console.log("listening on port 8888"))
```

Start server:
```console 
$ node test.js
listening on port 8888
```

Make a request and examine headers:
```console
$ curl -v http://localhost:8888
*   Trying 127.0.0.1:8888...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8888 (#0)
> GET / HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 204
< uWebSockets: 20
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
```

**Expected Result:**

`Content-Length: 0` should be omitted.

**Comment by alexhultman** [comment]
This is the same issue as when respoding to HEAD method; the library lacks a way to end a response without a body. Something like endWithoutBody() is needed as alternative to end(). Whatever status code you write is irrelevant for the lib, it doesn't care.

**Comment by davidmurdoch** [comment]
Would exposing `internalEnd`'s `allowContentLength` param (via `end`?) be enough to accomplish this for the cases you know about?

I wouldn't mind having to control the behavior from user-land.

**Comment by alexhultman** [comment]
#1229

We need a new function endWithoutBody(size)

**Comment by alexhultman** [comment]
endWithoutBody(std::optional<size_t> reportedContentLength = std::nullopt)

end() "writes" an empty body with content length 0
endWithoutBody() just omits content length and writes no body.
endWithoutBody(36) adds content length 36 but does not actually expect to write any body.

**Comment by alexhultman** [comment]
A basic variant of endWithoutBody has been added and will be exposed in JS land next release
