### ISSUE TITLE
Cookie string from getHeader() returns more than cookie only

### ISSUE THREAD

**Issue by hakoptak** [uNetworking/uWebSockets#1371]
Hi Alex,

For my webapp to work properly I use session cookies to pass information onto the socket server. However, when I read a cookie with `req->getHeader("cookie")` I get the string

`a=MiIlDbvSVvjV; p=V_ilI3sqIe6WSw-BJKtrId`
`sec-websocket-key: KmmiZdLlSJQJB7M/WApO1Q==`
`sec-websocket-extensions: permessage-deflate; client_max_window_bits`

The total header reads something like

`key: host: localhost:3000`
`connection: Upgrade`
`pragma: no-cache`
`cache-control: no-cache`
`upgrade: websocket`
`origin: https://localhost`
`sec-websocket-version: 13`
`accept-encoding: gzip, deflate, br`
`accept-language: en-GB,en-US;q=0.9,en;q=0.8`
`cookie: a=MiIlDbvSVvjV; p=V_ilI3sqIe6WSw-BJKtrId`
`sec-websocket-key: KmmiZdLlSJQJB7M/WApO1Q==`
`sec-websocket-extensions: permessage-deflate; client_max_window_bits`

So it returns the header section from the key to the end. I've verified this with other keys. I am on version 19.9.0.

Is this fixed in a later version? And is this reproducible?

**Comment by hakoptak** [comment]
I can confirm that this also happens in the latest version 20.8.0

**Comment by ddevienne** [comment]
What's the type returned by `getHeader()`? Your symptoms suggest it returns a `std::string_view`-like object,
which is not null terminated, but properly sized, and the null terminator you assume is the end of your cookie is in fact the end of the full header itself. Just guessing :)

**Comment by hakoptak** [comment]
Oh boy, that must be it. I should have thought about that! Thanks for the help.
