### ISSUE TITLE
Cannot work with QT

### ISSUE THREAD

**Issue by lainswork** [uNetworking/uWebSockets#1374]
I run the server in a separate thread,  (uWS::APP* server) this->server->run() will return immediately
When I call (uWS::APP* server) this->server->run() in the main thread of QT,uWebSockets works normally, but QT's GUI is stuck

int listenPort = ui->serverListenPort->value();

    std::async(std::launch::async, [this, listenPort]() {
        
        emit signalServerStarted();

        this->server->listen(listenPort,
            [this, listenPort](us_listen_socket_t* socket) {
                if (socket) {
                    socketToken = socket;
                    emit signalTextLogOnGui(QString(_T("start listen:%1 ...")).arg(listenPort));
                }
                else {
                    emit signalTextLogOnGui(_T("listen erro..."));
                }
            });

            this->server->run();

            return 0;
        });

**Comment by alexhultman** [comment]
QT or not is irrelevant. Does it work with multiple threads? Yes, use Loop::defer.

How your particular app is going to implement this, I don't know or care and cannot possibly spend time on.
