### ISSUE TITLE
refresh request cause server crash when using the version 0.14.8

### ISSUE THREAD

**Issue by Bruce-2018** [uNetworking/uWebSockets#1382]
version 0.14.8. Using the sample(tests/main.cpp), Uncomment the following two lines
```
    serveEventSource();  
    serveHttp();
```
After  compiling, run  a.out. The browser frequently refreshes request "http://127.0.0.1:3000/",  Eventually the program crashes, prompt: Segmentation fault (core dumped). 
Can you give me some suggestions? How to make it no crash?

**Comment by e3dio** [comment]
My suggestion is update to v20, you are many years of development behind at v0.14.8
