### ISSUE TITLE
Route starting with a number gets lost if there's a parameter route at the same path

### ISSUE THREAD

**Issue by snowbldr** [uNetworking/uWebSockets#1387]
If you have a static route that starts with a number, and a route with a path parameter at the same route, the static route starting with a number is not reachable and the parameter route is called instead.

If the static route starts with a letter, or there is no parameter route at that path, it works as expected.

Here's a js example to reproduce this issue.

```javascript
let uws = require( 'uWebSockets.js' );

uws.App()
    // these work fine
    .get( '/foo', ( res ) => res.end('got static foo') )
    
    // gets called for GET /1ab
    .get( '/:id', ( res, req ) => res.end(`got param ${req.getParameter( 0 )}`) )
    
    // This handler can't be reached
    .get( '/1ab', ( res ) => res.end('got static 1ab') )
    
    .listen(9001, socket => console.log('listening on 9001'))

uws.App()
    // these work fine
    .get( '/foo', ( res ) => res.end('got static foo') )
    .get( '/1ab', ( res ) => res.end('got static 1ab') )
    
    .listen(9002, socket => console.log('listening on 9002'))

```

**Comment by alexhultman** [comment]
Sorting here assumes letters come after * and : but this is not true for letter and numbers: https://github.com/uNetworking/uWebSockets/blob/2017892a7d389ab319576e7372041da8c6a8e28d/src/HttpRouter.h#L85

**Comment by alexhultman** [comment]
Fixed thanks for good report
