### ISSUE TITLE
Route ordering

### ISSUE THREAD

**Issue by e3dio** [uNetworking/uWebSockets#1388]
Get `/` here responds with 1, if you switch the .get order you get 2 but it should respond 2 either way
```javascript
require('uWebSockets.js').App()
.get('/*',res=>res.end('1'))
.get('/',res=>res.end('2'))
.listen(8080,s=>{})
```
https://github.com/uNetworking/uWebSockets/blob/master/misc/READMORE.md#pattern-matching

**Comment by alexhultman** [comment]
Thanks, fixed
