### ISSUE TITLE
LICENSE and README.md are confusing

### ISSUE THREAD

**Issue by DemiMarie** [uNetworking/uWebSockets#1394]
The LICENSE specifies that this repository is under Apache 2.0, but README.md states that only some files (which seem to be just `src/`) are.  This excludes the top-level Makefile, as well as the examples, tests, and fuzz harness.

This is a serious problem because the examples are what people will likely base their code off of, and because distributions like to be able to run tests during the package build process.  Since the project claims to be “Permissively licensed,” I would expect the entire repository to be under Apache 2.0, except perhaps for logos.  This does not prevent reserving the name “uWebSockets” for the original code (you can do that with a trademark).

**Comment by alexhultman** [comment]
What are you trying to accomplish?
