### ISSUE TITLE
WebSocket demasking is not done if WebSocket-frame is split along multiple TCP frames

### ISSUE THREAD

**Issue by mirkootter** [uNetworking/uWebSockets#1407]
Unfortunately, I do not have a simple reproduce but the problem is obvious in the code (see my PullRequest #1406)

Background: Clients have to mask their payloads using a simple XOR operation, so the server has to unmask it using the same XOR operation. If a WebSocket-Frame is split into several TCP frames, this should not change anything - the payload has still to be demasked.

However, it seems like the code path for handling this continuation has a little bug. It *only* demasks the content if the mask if zero - but it should be exactly the opposite

**Comment by alexhultman** [comment]
https://github.com/uNetworking/uWebSockets/releases/tag/v20.10.0
