### ISSUE TITLE
Cork Exception on HTTP1.1 - POST method

### ISSUE THREAD

**Issue by mohsenomidi** [uNetworking/uWebSockets#1421]
Dear @alexhultman

I am using the library for HTTP/1.1 (no ssl) server to handle my client requests

For TPS load test, I just create the simple curl client to send post requests with 20 async threads to the server (around 100,000 requests) , but server crashes randomly and it is randomly throw the exception below: 

```
Error: Cork buffer must not be acquired without checking canCork!
terminate called without an active exception
```
is there any suggestion ?

**Comment by alexhultman** [comment]
You have a history of reporting really stupid things, so I'm closing this as invalid.
