### ISSUE TITLE
Remove all Safari hacks

### ISSUE THREAD

**Issue by ghost** [uNetworking/uWebSockets#1431]
Since Safari is the only browser which continuously takes a dump on the spec, we have several Safari hacks:

* User agent hack for permessage-deflate being completely broken before 15.4
* Hack for dealing with Safari-specific x-webkit-deflate-frame and its deviating behavior

All of this garbage should be removed (at some point in the future) and we should only implement the standard behavior.

**Comment by uNetworkingAB** [comment]
This is going to take years of waiting and has very little benefit; closing
