### ISSUE TITLE
Sending data to a WS client

### ISSUE THREAD

**Issue by azertyalex** [uNetworking/uWebSockets#1439]
In all examples the websocket is given as an `auto *`. I can not save this element into an array of clients.
I need a way to send data to  one specific client. How can I do this?

**Comment by azertyalex** [comment]
It's always the moment you ask you finally find a solution. The problem seems I'm not very well at templating.

When I use `uWS::WebSocket<false, true, PerSocketData>` as type, I can get all to work fine and use these objects later on. I didn't know I had to fill in the actual values rather than  `uWS::WebSocket<bool, bool, PerSocketData>`

**Comment by alexhultman** [comment]
The examples are a little misleading yes, in bigger apps you probably need to specify the whole thing everywhere or at least make a typedef.
