### ISSUE TITLE
Looking for a producer-consumer pattern or an example

### ISSUE THREAD

**Issue by pinebit** [uNetworking/uWebSockets#1458]
Hello!
I am looking for a usage pattern that allows me to send messages over a websocket pushed by a producer running on a separate thread.
The producer pushes the messages at arbitrary point in time and because I cannot mix the threads, I cannot call `ws->send/publish` from the producer's callback (which is running on the producer's thread).
The question is how otherwise to call `ws->send/publish` on an external event?
Worth to mention my protocol does not assume the client is sending a request and I am responding with a message. In my design, the client wants to simply connect using ws and the server would periodically push messages.
Thank you in advance for any hints or suggestions.

**Comment by e3dio** [comment]
So your real question is how to do inter-process communication, look up unix sockets IPC. This is not an issue, you should have opened in discussion for noobie help https://github.com/uNetworking/uWebSockets/discussions

**Comment by alexhultman** [comment]
https://github.com/uNetworking/uWebSockets/blob/master/misc/READMORE.md#threading
