### ISSUE TITLE
Actively send/receive messages

### ISSUE THREAD

**Issue by cjxx2016** [uNetworking/uWebSockets#1465]
As a long-connected network protocol, it only provides an interface for passively sending/receiving messages. I think it is a design failure. This also requires the work of actively sending/receiving messages to become very painful. Very inefficient. I hope to provide activesending/receiving Interface to deal messages.

**Comment by alexhultman** [comment]
> it only provides an interface for passively sending/receiving messages

No it doesn't

**Comment by cjxx2016** [comment]
> > it only provides an interface for passively sending/receiving messages
> 
> No it doesn't

Yes It is.

**Comment by cjxx2016** [comment]
> @Jacob-Burckhardt I think @cjxx2016 means to send messages from the server to connected sockets without waiting for the sockets to send something to the ws /message handler

That's right

**Comment by cjxx2016** [comment]
> How do you define active and passive?

Active sending means that the server can send a message when it wants to send a message to a client, instead of waiting for a message to be received before returning a message.

**Comment by alexhultman** [comment]
A few hints -

1. Don't argue about stuff you don't know anything about, and don't ask if you're going to reject the answer
2. Don't use language such as "you will have to". I really do not have to do anything here.
3. You don't control the agenda here, so stop pointing fingers like you have anything to control

You must be utterly unaware and have entirely ignored the examples if you believe you cannot send a message at free will any point in time. What would be the purpose of WebSockets if that was the case?

Also, I recognize your name from some other really off posts
