### ISSUE TITLE
Testing UWS server using the framework

### ISSUE THREAD

**Issue by HagaiVinik** [uNetworking/uWebSockets#1471]
Is there a convenient way to mock an HTTP request for testing purposes, using uWebSocket framework? by that - I mean to invoke the handler that I've been set to route to different endpoints/methods.
Thanks in advance! and sorry if this issue was discussed I couldn't find it :(

**Comment by uNetworkingAB** [comment]
You can mock it, sure. But nothing like a "null implementation" is provided. But it shouldn't be that hard to create your own mock of the request and response objects

**Comment by HagaiVinik** [comment]
> 

Another question if possible:
i want to get the body parameters of an http request when the callback is invoked, couldn't find any method to perform on req.
I saw the example with the OnData() method, though I couldn't set it right in my application, If I want to wait for `onData` with future & promise I'll have to let the handler run out of scope and then I get an `std::terminate` .
any suggestion on what should I do?

**Comment by HagaiVinik** [comment]
@uNetworkingAB

**Comment by uNetworkingAB** [comment]
Copy them into the lambda you attach to onData. The point here is we only keep what explicitly gets copied. You can do capture-by-copy very elegantly with modern c++

**Comment by HagaiVinik** [comment]
Can u please provide some kind of example? would really appreciate it :pray:

**Comment by HagaiVinik** [comment]
@uNetworkingAB 
seems like there's no way to escape the call of `std::terminate` if I'm not returning a response immediately, even if I pass through the capture req and res.
