### ISSUE TITLE
uWebSockets server thread never returns from uv_run()

### ISSUE THREAD

**Issue by z16166** [uNetworking/uWebSockets#1472]
hi,

here is my case:
1. run just 1 server thread to do uWS::SSLApp().run().
2. upon receiving ctrl+c signal,  the signal handler sends a GET request to web socket server thread to notify its shutdown.
3. web socket server thread responds to GET request and call us_listen_socket_close() to shutdown listening socket. I can see all client sockets are closed during this call(by debug print).
4. But uWS::SSLApp().run() never returns from uv_run(). with some debug, I find that there are 8 pending requests in uv__poll(), returned by pGetQueuedCompletionStatusEx():

```
static void uv__poll(uv_loop_t* loop, DWORD timeout) {
...
    success = pGetQueuedCompletionStatusEx(loop->iocp,
                                           overlappeds,
                                           ARRAY_SIZE(overlappeds),
                                           &count,
                                           timeout,
                                           FALSE);

  ...
    if (success) {
      for (i = 0; i < count; i++) {
        /* Package was dequeued, but see if it is not a empty package
         * meant only to wake us up.
         */
        if (overlappeds[i].lpOverlapped) {
          req = uv_overlapped_to_req(overlappeds[i].lpOverlapped);
          uv_insert_pending_req(loop, req);
        }
      }
```

The above "count" is 8. And loop->active_handles is also 8.
maybe we have to also abandon pending requests/active handles in us_listen_socket_close()?

If I call us_listen_socket_close() directly in ctrl+c signal handler, it probably crashes. It seems it's not thread-safe to do that.

thanks

**Comment by uNetworkingAB** [comment]
I don't know what you're doing but "falling through" the run call is something we do thousands of times per second in fuzz testing so that's definitely a core feature that works
