### ISSUE TITLE
Question regarding endianness

### ISSUE THREAD

**Issue by macadev** [uNetworking/uWebSockets#1479]
First of all, just want to say I love this project. I recently ran into a little hiccup (mostly stemming from my inexperience with C++ and low-level programming). I'm sending my uWebSockets server an int32 as follows:

```
// From JavaScript
const buffer = new ArrayBuffer(4);
const view = new DataView(buffer, 0);
view.setUint32(0, 1111);
// Data sent is in big-endian because we that's what the websocket protocol dictates (I think)
socket.send(buffer);
```

Then in the server I have this code to parse the message:

```
.message = [](auto *ws, std::string_view message, uWS::OpCode opCode) {
  uint32_t *number = (uint32_t*) &message[0];
  std::cout << *number << "\n"; // prints 1459879936
}
```

Upon running this the server wasn't printing the '1111' I expected to see. It turns out that my server's CPU is little-endian, which means I needed to transform the endianness of number:

```
// Go from big endian to whatever the server uses
uint32_t number = ntohl(*((uint32_t*) &message[0]));
```

So my very vague question is... is there a reason why uWebSockets doesn't do this for me? Isn't everything that arrives always big-endian and should be converted to the server's endianness?

This isn't a complaint, I just want to inform myself on this topic.

Thanks for your time!

**Comment by uNetworkingAB** [comment]
uWS is not Facebook - it doesn't look at or modify your data
