### ISSUE TITLE
Segfault when trying to execute HTTP PUT/POST request containting binary data

### ISSUE THREAD

**Issue by kiryasolod** [uNetworking/uWebSockets#1480]
Hi. I'm using postman to send a request which contains a PNG file. The content of the request is following: 

PUT /api/users/1/avatar HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjI2MzI4ODAsImlhdCI6MTY2MjAyODA4MCwiaXNfYWRtaW4iOnRydWUsImlzcyI6Im1vcmRvciIsInVzZXJfaWQiOjEsInVzZXJfbmFtZSI6Im1vcmRvciJ9.EmBSutLkKizXRwFmKxPeMTK9A5tYapgdDyUMbXXELmNZu0_H57lNdG_ZpZuJwsVQxH1mCZNzFBbqaBW69Iuj5un6hc88MgMtNCJamB49KCzhiPiHg7Mc6jDzQ_93R-1JPgNMvXRl-UyLoqyTUGLUUhnWjO6OMn6KQDlh9wzwvAr34sdcrlLuU9XTMOhvuSDfhsnCcy31Ol9cepvdL3jGv--yDWDtKx9jRI_qrztD0_LEo0T9e0__KT6NFzGqhK_lZ7dWfu4JrmBQynt_CX72oVt2HA5iFvdRj5u4kKnJuAdFiGhqXCiWQoFBRWf_DPm42GzP3U5GBX8ed2M-XfX9nQ
User-Agent: PostmanRuntime/7.29.2
Accept: */*
Postman-Token: 8c8be357-e74e-4fe9-a27b-050669e617ab
Host: localhost:8081
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 773777
Content-Type: image/png

PNG

IHDR
p ÂsBITÛáOà IDATx^ìÇFÅÝÝwwwYÜÝÂbÁK'Xpî°¸»-îîîÎ;Kñffº§×`î|ûÁLuÕ[§ª«{¦þ¾4kÖ¬Aä%B@! B@! B@! 	8ÅOÅM! B@! @ #<xÈ¼wB@! @(QpP¾mì^ïB@! Ô®³çÎJïÅi! B@! @&,i`Ø=qM! B@! B@! B@! B@! øJDPø@K5~B...

As a result I get this in request data structures:
req.currentParameters.second is nullptr
All headers in req object are also zeroes and nullptr
Binary buffer is valid and contains a PNG which I'm sending, so it's ok
Thus when I try to call req->getParameter(0) I get segfault because of the nullptr

**Comment by uNetworkingAB** [comment]
You can only access req object inside the request callback. You probably access it inside the onData callback where it is no longer alive

**Comment by kiryasolod** [comment]
Thank you. You were right, I was trying to get this data inside onData callback. Fixed my code and now it's working. It would be great to have some information about this details in docs or examples

**Comment by uNetworkingAB** [comment]
It's already written both in readmore and in some examples, but yes it is a common pitfall.
