### ISSUE TITLE
HTTP Requests with more than 4 GB is not supported

### ISSUE THREAD

**Issue by mirkootter** [uNetworking/uWebSockets#1485]
The Content-Length attribute is parsed as a `unsigned int`, which gives the wrong result for stream sizes larger than 4 GB.

In our company, we use µWebSockets to provide websocket and REST API endpoints. The REST API endpoints are used, for example, to upload binary blobs of data.

Unfortunately, those data blobs can become very large. We were able to fix the problem by changing some ```unsigned int``` to ```uint64_t``` in HTTPParser.h, but maybe other users may have this problem as well.

**Comment by uNetworkingAB** [comment]
Feel free to PR it as size_t

**Comment by uNetworkingAB** [comment]
Please add your changes to be merged if you want it fixed. Will close as this is a very unusual request.

**Comment by mirkootter** [comment]
In case anyone else stumbles across this: Looks like this is supported since v20.54.0
