### ISSUE TITLE
Handling of long headers

### ISSUE THREAD

**Issue by chyvonomys** [uNetworking/uWebSockets#1487]
I use long headers (e.g. `Authentication: Bearer <TOKEN>`) and noticed that uWS **randomly** drops connection.
For example: sending same 100 requests sequentially with curl to the same endpoint with large header will fail with `empty response from server` in half of attempts. And there is no pattern.

I briefly looked at HttpParser.h code and seems that this is because of `MAX_FALLBACK_SIZE` being 4KB. Headers that I send are 4KB+.  In some cases whole headers chunk come in one 'slice' and it doesn't use fallback, but in some cases it uses fallback and since header is longer than that 4KB it drops that request.

After increasing that size to 16KB I no longer see that problem. But this doesn't look like a good long term solution.

**Comment by e3dio** [comment]
> We use a 4kb max length for requests, meaning URLs must be less than 4kb. This is for security reasons.

Related question here https://github.com/uNetworking/uWebSockets.js/discussions/314

**Comment by uNetworkingAB** [comment]
There is no standardized limit to http headers but from an implementation perspective you don't want long ones. If 16kb works for you then that's fine, I guess.

**Comment by chyvonomys** [comment]
@uNetworkingAB yes that makes sense. But I wanted to emphasize that it was not doing it consistently. I took some time for me to figure out that it was because of headers.
