### ISSUE TITLE
Is it possible to remove a registered HTTP resource form uWS::SSLApp?

### ISSUE THREAD

**Issue by sajithshn** [uNetworking/uWebSockets#1489]
Is there a way to remove a registered handler of a specific resource path in uWS::SSLApp?

In my use case, I register handlers with the server to handle a given resource path on-demand. I also want to be able to remove such handlers from the server dynamically, so that the removed resource should not be accessible. 

Following is the code snippet I use to register my handlers

`_server->post(std::string(http_info._resource_path),
                                  [http_info, this](uWS::HttpResponse<true> *uws_response,
                                                    uWS::HttpRequest *uws_request){// My handler impl});`

**Comment by uNetworkingAB** [comment]
No but it's a feature I want. You can only add routes for now, but you can add them under a domain name (SNI) then remove the whole SNI domain name and add the routes you want again. So technically, yes for SNI it is possible but for regular non-SNI use it is not.

I want a simple way to remove routes in any case (both SNI and non-SNI).

**Comment by uNetworkingAB** [comment]
I added removable routes. You remove the route by passing nullptr as handler. So app.get("/*", nullptr) removes a prior app.get("/*", some lambda here);

**Comment by uNetworkingAB** [comment]
_server->post(std::string(http_info._resource_path), nullptr)
