### ISSUE TITLE
implementation leading to "multiple definition" error

### ISSUE THREAD

**Issue by menggui1993** [uNetworking/uWebSockets#1498]
For ChunkedEncoding.h, some variables and functions are both declared and defined. This will lead to multiple definition error if you include the header from two source files.
It's quite simple to reproduce the error, just include the header from two source files, and then compile and link.

s1.cpp
`
#include <App.h>
...
`

s2.cpp
`
#include <App.h>
...
`
Thanks.

**Comment by SlavSlavov** [comment]
I got this error too.
Can be temporarily fixed by:
* Moving `consumeHexNumber` and `getNextChunk` in a private section of `ChunkIterator`
* Making STATE_HAS_SIZE, STATE_IS_CHUNKED and STATE_SIZE_MASK `constexpr`
* Making all other functions `inline constexpr`

**Comment by uNetworkingAB** [comment]
Should be fixed now

**Comment by menggui1993** [comment]
Fixed. Thanks.
