### ISSUE TITLE
Port Makefile to C

### ISSUE THREAD

**Issue by uNetworkingAB** [uNetworking/uWebSockets#1508]
Windows, Linux, macOS all have Clang, Clang++ they all take the same flags

C has system, getenv to easily replicate all logic is in Makefile right now.

A shim Makefile like the one used in uWebSockets.js will compile and run this "build system" written in C, being literally identical in behavior, yet **cross platform** even for Windows.

It is so incredibly stupid, to install some 100MB piece of garbage crap just to express some basic if-statements when **you have the freaking C compiler** right there - the most cross platform and standardized language ever made, period.

And, guess what - when you aim to compile a C/C++ project, you already have the dependency that is ....... a C compiler!

I can port this Makefile into C, and have it be LESS code

**Comment by uNetworkingAB** [comment]
```
ifeq ($(WITH_QUIC),1)
	override CXXFLAGS += -DLIBUS_USE_QUIC
	override LDFLAGS += -pthread -lz -lm uSockets/lsquic/src/liblsquic/liblsquic.a
endif
```

is literally the same as 

```
if (getenv("WITH_QUIC")) {
  strcat(CXXFLAGS, "-DLIBUS_USE_QUIC");
  strcat(LDFLAGS, "-pthread -lz -lm uSockets/lsquic/src/liblsquic/liblsquic.a");
}
```

**Comment by slavslavov** [comment]
While you are working on Mikefiles would it be possible to introduce a `DEBUG` configuration? This will make it easier to integrate to other projects. I was having issues with the -flto flag when linking the uSockets.a library to my executable when I was not specifying -flto but -g -Og. A workaround is to play with the `WITH_LTO` option but something like `WITH_DEBUG` will make it cleaner. Also there are still some hardcoded -flto flags in uWebsockets which make the use in debug mode difficult.

**Comment by uNetworkingAB** [comment]
$Env:CC='clang'; $Env:CXX='clang++'; nmake -f shim

That works on Windows without anything other than the Visaul Studio Build Tools. A few improvements and people will be able to build all of this incredibly easy on all platforms.

**Comment by uNetworkingAB** [comment]
Yep, will add all kinds of flags and remove hard-coded stuff. I am really liking not having to download Chokolatey + CygWin + CNU Make + whatever crap -> now I can just hit nmake from the official Microsoft tools and it will work (soon)
