### ISSUE TITLE
Windows is problematic

### ISSUE THREAD

**Issue by uNetworkingAB** [uNetworking/uWebSockets#1511]
I've spent quite some time trying to figure out Windows and I got it to compile like so:

`$ENV:VCPKG_INSTALLATION_ROOT='C:\vcpkg'; $ENV:WITH_LIBUV='1'; nmake`

This uses LTO and O3 optimizations from Clang and so I figured let's benchmark it using the same tools I benchmark on Linux and macOS.

I get completely CPU-time saturated at 67k msg/sec on this particular computer. On Linux it is more like 300k or 400k - these numbers are completely off and it makes me just want to delete Windows and forget it ever existed.

If I run Linux inside Windows, WSL, I get 300k so it's not exactly small differences. I bet there's some kind of mspaint.exe hogging the network on host or whatever

**Comment by ddevienne** [comment]
> makes me just want to delete Windows

FWIW, that it works on Windows is what matters. The fact it will be (much) slower than Linux is _OK_, and expected.
What's important is to be able to have a cross-platform source code, and ability to debug using Visual Studio. My $0.02.

BTW, what uSocket event-backend do you use in this test? Just curious. Maybe another one does better?

**Comment by uNetworkingAB** [comment]
I need to do some benchmarking here. Using other servers and compare. Is there some kind of setting I should make on windows? I have turned off Windows Defender and all toggles I can click on. No difference.

**Comment by uNetworkingAB** [comment]
I get the same piss poor results with Deno.serve. I guess this is why nobody uses Windows on the server side, because it sucks donkey balls. Same for disk performance, but that I already knew for sure. I guess the only thing Windows is good for is playing games. These numbers are ridiculously low, 5x as slow as Linux

**Comment by cirospaciari** [comment]
I have the same results on Windows, nobody should use windows to serve anything, almost any language/Lib I tried I have a huge performance decrease with windows. But it's useful to support it for development. I'm trying to compile using clang + boringssl without success on Windows but I will try using cl or clang-cl to see if I got better results than clang on Windows.
