### ISSUE TITLE
UBSan: load of misaligned address for type uint64_t

### ISSUE THREAD

**Issue by jwnimmer-tri** [uNetworking/uWebSockets#1512]
Running [UBSan](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html) against my code that's using uWebSockets==v20.29.0 reports an error:

```
uwebsockets/src/HttpParser.h:260:29: runtime error: load of misaligned address 0x7f80a8003db4 for
 type 'uint64_t' (aka 'unsigned long'), which requires 8 byte alignment`
0x7f80a8003db4: note: pointer points here
  47 45 54 20 2f 69 6e 64  65 78 2e 68 74 6d 6c 20  48 54 54 50 2f 31 2e 31  0d 0a 48 6f 73 74 3a 20
              ^ 
```

This is using Clang version 12.0.0-3ubuntu1~20.04.5 on Ubuntu 20.04.

The problem seems to be from 2b850f76d386f29b52baba7a6ab3c4efd5b9a31c.

**Comment by jwnimmer-tri** [comment]
After working around that diagnostic, I see another one:

```
uwebsockets/src/HttpParser.h:238:34: runtime error: load of misaligned address 0x7f4e68003dca for
 type 'uint64_t' (aka 'unsigned long'), which requires 8 byte alignment
0x7f4e68003dca: note: pointer points here
 2e 31  0d 0a 48 6f 73 74 3a 20  6c 6f 63 61 6c 68 6f 73  74 3a 37 30 30 30 0d 0a  55 73 65 72 2d 41
              ^ 
```

**Comment by uNetworkingAB** [comment]
It's the added invalid dereferences, they need to be memcpy

**Comment by ddevienne** [comment]
Saw a [good talk on type-punning on this kind, in CppCon 2022](https://www.youtube.com/watch?v=pbkQG09grFw), FWIW.

**Comment by uNetworkingAB** [comment]
Yeah it is a classic flaw, just need to update all those recently added issues.

**Comment by uNetworkingAB** [comment]
Can you try latest commit https://github.com/uNetworking/uWebSockets/commit/654b4558a4347cc9f437f82c6000639af5f20c2c

**Comment by jwnimmer-tri** [comment]
Thank you!  I can confirm that as of 654b455 all of my project's tests pass with UBSan (as well as our other memory checkers).

**Comment by uNetworkingAB** [comment]
Thanks for report and testing
