### ISSUE TITLE
20.30.0: No 'install' target exists any more

### ISSUE THREAD

**Issue by yurivict** [uNetworking/uWebSockets#1517]
The 'install' target was used by the FreeBSD port to install the project.

**Comment by uNetworkingAB** [comment]
https://github.com/uNetworking/uWebSockets/blob/7a363a8b10df4f77377d5905125007f374951760/GNUmakefile#L15

**Comment by yurivict** [comment]
Sorry, I misdiagnosed the problem. The Makefile was renamed which is ok.
