### ISSUE TITLE
Is there a way to set sub-millisecond timer without changing uWebSockets source?

### ISSUE THREAD

**Issue by galuha** [uNetworking/uWebSockets#1518]
Hello!
Is there a way to set sub-millisecond timer(like us_timer_set) without changing uWebSockets source?

**Comment by uNetworkingAB** [comment]
How do you mean? The OS on a regular PC cannot guarantee that precision and you kind of already answered your own question?

**Comment by galuha** [comment]
Want timer to shoot 10000 times per second. Don't need guaranteed precision.

**Comment by galuha** [comment]
Like changing this version of us_timer_set to accept microseconds instead of milliseconds:

void us_timer_set(struct us_timer_t *t, void (*cb)(struct us_timer_t *t), int ms, int repeat_ms) {
    struct us_internal_callback_t *internal_cb = (struct us_internal_callback_t *) t;

    internal_cb->cb = (void (*)(struct us_internal_callback_t *)) cb;

    struct itimerspec timer_spec = {
        {repeat_ms / 1000, (long) (repeat_ms % 1000) * (long) 1000000},
        {ms / 1000, (long) (ms % 1000) * (long) 1000000}
    };

    timerfd_settime(us_poll_fd((struct us_poll_t *) t), 0, &timer_spec, NULL);
    us_poll_start((struct us_poll_t *) t, internal_cb->loop, LIBUS_SOCKET_READABLE);
}:

**Comment by galuha** [comment]
I figured it out)), could just make my own version of it without changing uWebSocket source. Thank you for your answer. It helped))))) And it works

**Comment by uNetworkingAB** [comment]
Sounds like you want busywaiting

**Comment by galuha** [comment]
Yes. On select

**Comment by galuha** [comment]
Would it be more correct to attach my sockets to uWebSockets epoll instead of timer?

**Comment by galuha** [comment]
Will be using it in multithreaded mode. Busywaiting on the same core is not a good idea
