### ISSUE TITLE
Gracefully terminating the server on Ctrl+C (SIGINT and others)

### ISSUE THREAD

**Issue by sentisso** [uNetworking/uWebSockets#1536]
How would you go about handling the SIGINT signal?
Is it safe just to let the program "get killed" by the system when it receives this signal?
Or should I capture the signal and terminate the server in the handler?

Something like this:
```cpp
...
struct sigaction sigIntHandler;

sigIntHandler.sa_handler = [](int sig)
{
    us_listen_socket_close(0, listen_socket_);
};

sigemptyset(&sigIntHandler.sa_mask);
sigIntHandler.sa_flags = 0;

sigaction(SIGINT, &sigIntHandler, NULL);
```

Please mind that **this is not signal-safe**

**Comment by sentisso** [comment]
I've come to a solution using [boost's signal handling](https://www.boost.org/doc/libs/1_65_0/doc/html/boost_asio/overview/signals.html) which doesn't yield signal-unsafe errors with `-fsanitize=thread`

```cpp
#include <boost/asio/signal_set.hpp>
#include <boost/asio/io_service.hpp>

boost::asio::io_service io_service;
boost::asio::signal_set signals(io_service, SIGINT, SIGTERM);

signals.async_wait([](const boost::system::error_code &error, int signal_number)
{
    if (error)
        return;

    us_listen_socket_close(0, listen_socket_);
});

io_service.run();
```

**Comment by sentisso** [comment]
> So you compiled with ASIO as event loop?

Yes I did, but I also supplied "my own" boost headers, _if that's what you mean_, because I do not want to be dependant on the type of uWS build I end up using

**Comment by uNetworkingAB** [comment]
I mean you can compile uSockets to use ASIO as underlying event loop. Then everything runs on io_context
