### ISSUE TITLE
Tangentially related, for a future pull request, not this one, what do you think of something like this:

### ISSUE THREAD

**Issue by Evilantireversed** [uNetworking/uWebSockets#1540]
Tangentially related, for a future pull request, not this one, what do you think of something like this:

```
struct SocketContextOptions : us_socket_context_options_t {
    SocketContextOptions() : us_socket_context_options_t({}) {
    }
};
```

The idea is that the member variables would all be initialized to default values without the need to be kept in sync between two structs and there would be no need for a conversion operator since SocketContextOptions would inherit from us_socket_context_options_t.

_Originally posted by @alastairpatrick in https://github.com/uNetworking/uWebSockets/issues/1137#issuecomment-739718948_

**Comment by uNetworkingAB** [comment]
I don't care enough to figure out how to make it compile like that. If you want to fix it like that, do it. I can't get it working and I don't care enough to bother

**Comment by uNetworkingAB** [comment]
Yeah here is the problem:

When you derive A from B, brace initializers stop working like {} but need be {{}} so it ruins the whole interface of App({}). Initializing a derived POD with brace init is done with a list of lists like that, so it doesn't work.

You can probably define some kind of bizarre template-mess to kung-fu this problem but then you have a more complex solution than already is used.

Also - one benefit of doing it like this is that we can have camelCase in C++ land and snake_case in C (but that change hasn't happened yet)
