### ISSUE TITLE
CAPI uws_res_upgrade segfault

### ISSUE THREAD

**Issue by gigagrig** [uNetworking/uWebSockets#1542]
I'm trying to integrate capi web sockets. It looks like `uws_res_upgrade` leads to a segfault with ssl. The segfault is reproduced in provided example UpgradeSync.c
Compiler : gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

**Comment by cirospaciari** [comment]
I think the examples are not updated, I will take a look, fix and update them.

**Comment by cirospaciari** [comment]
uws_res_upgrade was broken, now it's fixed in PR #1571

**Comment by gigagrig** [comment]
> uws_res_upgrade was broken, now it's fixed in PR #1571
Contributor
[cirospaciari](https://github.com/cirospaciari), Thank you!
