### ISSUE TITLE
Consistency between uWebSockets and uSockets versioned releases

### ISSUE THREAD

**Issue by nbkolchin** [uNetworking/uWebSockets#1545]
Current uWebsockets (v20.34.0) requires unversioned snapshot of uSockets. This makes supporting uWebSockets in autopackaging systems like vcpkg almost impossible.

Can you please always use versioned uSockets in uWebsockets releases?

**Comment by uNetworkingAB** [comment]
https://vcpkg.link/ports/uwebsockets

Seems they are keeping things up to date, alright let's keep this in mind and release uSockets with proper versions

**Comment by nbkolchin** [comment]
Yes. The are keeping things "up to date" and currently uWebSockets is broken in vcpkg.

https://github.com/microsoft/vcpkg/issues/28611

**Comment by uNetworkingAB** [comment]
fixed
