### ISSUE TITLE
writeing to socket fails when fast forwarding large response

### ISSUE THREAD

**Issue by HagaiVinik** [uNetworking/uWebSockets#1564]
Hello everyone, would really appreciate your help.
I know I might be missing something so I'll hope to get an explanation here.

I have used uWebSocket and uSocket libraries to implement some kind of proxy server,

The problem occurs when huge amount of data is transmitted as a response. So lets say I'm a server (uWS) that got a request for a large file, and I don't have it, so I'm requesting it as a uSocket client from other server (http also), now I'm receiving it inside the body with chunks, I'm trying to write it back to the client, and the writing is failing. (probably because of back-pressure/fd is busy):

```
//This callback Is triggered on the client side receiving the file from the other server
struct us_socket_t* OnHttpSocketData(struct us_socket_t *s, char *data, int length)
{
    // I have used us_socket_ext() to extend the object to have mRe
    int written = us_socket_write(NO_SSL, (us_socket_t*)GetInstance(s)->mRes, data, length, 0);

    if (!written)
    {
        // error - what to do?
        //spdlog::error("Error writing data to socket, tried to write len: {}", length);
    }
    else
    {
        // success
    }

    return s;
}
```

Now, I looked at the examples and I saw the `onWriteable()` callback option, and I did manage to trigger it, but I don't know how to use it properly, and also, it was triggered only after all of the `OnHttpSocketData` events were finished. 
So even If I pass it somehow the missing data that wasn't written to socket, it'll write it not at the right place.

```
res->onWritable([&](int size)
    {
        // what to do? how to write the buffer at the right place?
        // Is it possible to block incoming requests from the server until I'll write the current chunk successfully?
    });

```

I would really appreciate if someone can guide me on how to solve this properly. 
Thanks a lot in advance!

Hagai

**Comment by uNetworkingAB** [comment]
read docs and see examples, this is not a bug. Text is already written for this

**Comment by HagaiVinik** [comment]
@uNetworkingAB 
Sorry, I was looking on the documentation but there wasn't any matching example for my case (getting data as a client using u_socket lib, and replying using res object from uWebSocket lib.  
I cannot perform pause() and resume() as in here: https://github.com/uNetworking/uWebSockets.js/blob/875f16e1fa8483f1cbe6e50fdb25efe4fc383731/examples/VideoStreamer.js#L56
since it's a raw u_socket

can you please provide me any guidance/tip regarding this? I'm having struggle solving this :(
