### ISSUE TITLE
use uWebSocket to send 5MB of data at a time 

### ISSUE THREAD

**Issue by 1565430482** [uNetworking/uWebSockets#1565]
[vcruntime140d.dll] <unknown> 0x00007ffe4ede161e
[WebSocketServer.exe] uWS::protocol::formatMessage<1>(char *, const char *, unsigned long long, OpCode, unsigned long long, bool, bool) WebSocketProtocol.h:241
[WebSocketServer.exe] uWS::WebSocket<0, 1, PerSocketData>::send(basic_string_view<char, std::char_traits<char> >, OpCode, bool, bool) WebSocket.h:134
[WebSocketServer.exe] ```main'::`2'::<lambda_2>::operator()<uWS::WebSocket<0,1,PerSocketData> >'::`2'::<lambda_1>::operator()'::`2'::<lambda_1>::operator()() WSServer.cpp:92
[WebSocketServer.exe] std::invoke<```main'::`2'::<lambda_2>::operator()<uWS::WebSocket<0,1,PerSocketData> >'::`2'::<lambda_1>::operator()'::`2'::<lambda_1> &>(<lambda_1> &) type_traits:1562
[WebSocketServer.exe] ofats::any_detail::handler_traits<void>::large_handler<```main'::`2'::<lambda_2>::operator()<uWS::WebSocket<0,1,PerSocketData> >'::`2'::<lambda_1>::operator()'::`2'::<lambda_1> >::call(ofats::any_detail::storage &) MoveOnlyFunction.h:152
[WebSocketServer.exe] ofats::any_detail::any_invocable_impl<void, 0>::call() MoveOnlyFunction.h:247
[WebSocketServer.exe] ofats::any_invocable<void __cdecl(void)>::operator()() MoveOnlyFunction.h:354
[WebSocketServer.exe] uWS::Loop::wakeupCb(us_loop_t *) Loop.h:41
[uSockets.dll] async_cb(uv_async_s *) libuv.c:63
[uv.dll] uv__process_async_wakeup_req(uv_loop_s *, uv_async_s *, uv_req_s *) async.c:96
[uv.dll] uv__process_reqs(uv_loop_s *) req-inl.h:189
[uv.dll] uv_run(uv_loop_s *, uv_run_mode) core.c:623
[uSockets.dll] us_loop_run(us_loop_t *) libuv.c:188
[WebSocketServer.exe] uWS::Loop::run() Loop.h:182
[WebSocketServer.exe] uWS::run() Loop.h:199
[WebSocketServer.exe] uWS::TemplatedApp<0>::run() App.h:545
[WebSocketServer.exe] main() WSServer.cpp:141
[WebSocketServer.exe] invoke_main() 0x00007ff700797509
[WebSocketServer.exe] __scrt_common_main_seh() 0x00007ff7007973ee
[WebSocketServer.exe] __scrt_common_main() 0x00007ff7007972ae
[WebSocketServer.exe] mainCRTStartup(void *) 0x00007ff70079759e
[kernel32.dll] <unknown> 0x00007ffed00a26bd
[ntdll.dll] <unknown> 0x00007ffed074dfb8

The above stack

**Comment by uNetworkingAB** [comment]
The below emoji

🖕

**Comment by 1565430482** [comment]
why？

**Comment by uNetworkingAB** [comment]
It's for you to figure out - what could have **possibly** triggered this outcome??? 🤔
