### ISSUE TITLE
CAPI bug: uws_res_override_write_offset

### ISSUE THREAD

**Issue by blackmius** [uNetworking/uWebSockets#1566]
must be in a separate branch
https://github.com/uNetworking/uWebSockets/blob/c5d687540ab6d12b5f33685892a08eb112df6ab1/capi/libuwebsockets.cpp#L1143

**Comment by uNetworkingAB** [comment]
elaborate

**Comment by cirospaciari** [comment]
No return and No else, branching is indeed needed, I added the fix to PR #1571
