### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by where2go947** [uNetworking/uWebSockets#1569]
Hello, I am trying to install uWebSockets on ubuntu 20.04.
I git uWebSockets and git uSockets, but when `make`, error has occured:
```
make -C uSockets
make[1]: Entering directory '/uWebSockets/uSockets'
rm -f *.o
cc -flto -DLIBUS_NO_SSL -std=c11 -Isrc -O3 -c src/*.c src/eventing/*.c src/crypto/*.c
lib.exe /out:uSockets.a *.o || ar rvs uSockets.a *.o
/bin/sh: 1: lib.exe: not found
r - bsd.o
r - context.o
r - epoll_kqueue.o
r - gcd.o
r - libuv.o
r - loop.o
r - openssl.o
r - quic.o
r - socket.o
r - udp.o
make[1]: Leaving directory '/uWebSockets/uSockets'
cc build.c -o build
./build examples
--> g++ -O3 -Wpedantic -Wall -Wextra -Wsign-conversion -Wconversion -std=c++2a -Isrc -IuSockets/src -flto examples/Client.cpp  uSockets/*.o -lz -o Client

g++: error: unrecognized command line option ‘-std=c++2a’; did you mean ‘-std=c++03’?
make: *** [GNUmakefile:7: examples] Error 255
```
Is the version of g++ not consistent with wanted and how can I change it ?
I can't even find the flag `-std=c++2a` in `Makefile`...
Could you please give me some help? thanks!

**Comment by uNetworkingAB** [comment]
Ubuntu 20.04 is too old, yes

**Comment by where2go947** [comment]
> Ubuntu 20.04 is too old, yes

Does uWebSocket not support ubuntu 20.04 now? Is there no way to run it on ubuntu 20.04?

**Comment by uNetworkingAB** [comment]
> The implementation is header-only C++17 (but examples use C++20 features for brevity and elegance!)
