### ISSUE TITLE
question about std::map in the library

### ISSUE THREAD

**Issue by Django-xinfa** [uNetworking/uWebSockets#1574]
I'm a newbie and I wonder why user manual say "Many times people tend to attach user data which should belong to the websocket by putting the pointer and the user data in a std::map. That's wrong!".
Thank you.

**Comment by Django-xinfa** [comment]
I use std::map in my case like this:
`std::map<int,uWS::WebSocket<true,true,PerSocketData> *> pos2WS;`
Not use std::map in PerSocketData. Is ok?

**Comment by Django-xinfa** [comment]
Sorry, I'm foolish.

**Comment by Django-xinfa** [comment]
I use std::map in my case like this:
`std::map<int,uWS::WebSocket<true,true,PerSocketData> *> pos2WS;`
Not use std::map in PerSocketData. Is ok?

**Comment by uNetworkingAB** [comment]
It's literally explained in the very next section.
