### ISSUE TITLE
Compiling under Windows as shared library.

### ISSUE THREAD

**Issue by yesilcimenahmet** [uNetworking/uWebSockets#1581]
Hi, I want to port this library to Delphi(Windows first, and after Linux), but I could not see CMake. I am not much familiar about Build systems. Could you help me?

Why you dont recommend for Windows also ? Because I saw some discussion about that.

Thanks.

**Comment by uNetworkingAB** [comment]
uws on Windows performs very poorly, and shared library compilation performs even poorer. This is not something we support or will support.
