### ISSUE TITLE
How can i get the query params in open event? uWebSockets-20.36.0

### ISSUE THREAD

**Issue by huge818** [uNetworking/uWebSockets#1582]
How can i get the query params i open event?

 This is the websocket client on web page.

`
var socket = new WebSocket('ws://192.168.1.2/webclient?id=12345678');
socket.onopen = function (e) {
	console.log(e);
}

socket.onmessage = function (e) {
	console.log(e.data);
}

socket.onclose = function (e) {
	console.log(e);
}
`

how can i get the query params and path in uwebsocket  server ?

//uWebSockets-20.36.0

#include "App.h"
#include "../capi/libuwebsockets.h"

#include<iostream>
#include<string>
using namespace std;

struct PerSocketData {
	//long ws;
};

int main() {

    auto App = uWS::App();
    App.ws<PerSocketData>("/*", {
        /* Settings */
        .compression = uWS::CompressOptions(uWS::DEDICATED_COMPRESSOR_4KB | uWS::DEDICATED_DECOMPRESSOR),
        .maxPayloadLength = 100 * 1024 * 1024,
        .idleTimeout = 16,
        .maxBackpressure = 100 * 1024 * 1024,
        .closeOnBackpressureLimit = false,
        .resetIdleTimeoutOnSend = false,
        .sendPingsAutomatically = true,
        /* Handlers */
        //.upgrade = nullptr,
        .upgrade = [](auto *res, auto *req, auto *context) {
        	
        },
        .open = [](auto *ws) { //,
            /* Open event here, you may access ws->getUserData() which points to a PerSocketData struct */
            //ws->getNativeHandle();
            How can I get query params and url path in this code?
         },

        .message = [](auto *ws, std::string_view message, uWS::OpCode opCode) {
            ws->send(message, opCode, true);
        },
        .drain = [](auto */*ws*/) {

            /* Check ws->getBufferedAmount() here */
        },
        .ping = [](auto */*ws*/, std::string_view) {
            /* Not implemented yet */
        },
        .pong = [](auto */*ws*/, std::string_view) {
            /* Not implemented yet */
        },
        .close = [](auto */*ws*/, int /*code*/, std::string_view /*message*/) {
            /* You may access ws->getUserData() here */
        }
    });
    
    App.listen(7012, [](auto *listen_socket) {
        if (listen_socket) {
            std::cout << "Listening on port " << 7012 << std::endl;
        }
    });

    App.run();
}

`

**Comment by uNetworkingAB** [comment]
https://github.com/uNetworking/uWebSockets/blob/master/examples/UpgradeSync.cpp#L37
