### ISSUE TITLE
Example Deprecated

### ISSUE THREAD

**Issue by poor1017** [uNetworking/uWebSockets#1588]
Hi all

I try to compile example/HttpServer.cpp, but I got the following error:

``` shell
examples/HttpServer.cpp:28:5: warning: missing initializer for member ‘optparse_long::argtype’ [-Wmissing-field-initializers]
examples/HttpServer.cpp:69:32: error: no matching function for call to ‘uWS::TemplatedApp<true>::TemplatedApp(us_socket_context_options_t&)’
   69 |         uWS::SSLApp(ssl_options).get("/*", [&asyncFileStreamer](auto *res, auto *req) {
      |                                ^
```

Is this example deprecated?

Thank you!

**Comment by uNetworkingAB** [comment]
That example has never worked. It's not included in the default build.

**Comment by poor1017** [comment]
So, the purpose it's in the repo is?

**Comment by uNetworkingAB** [comment]
IMO a broken example is better than no example, it should give a starting point and a direction for people to complete on their own. I have no time to maintain it, but it is there for anyone to look.
