### ISSUE TITLE
Avoiding copies of uWebSocket messages in message callback

### ISSUE THREAD

**Issue by kylepl** [uNetworking/uWebSockets#1590]
Hi,

Currently the `message` callback provides an `std::string_view`, which means it does not support transferring ownership.

For my application, I need to keep accumulating it (well, the last X messages), and was thinking it would be nice to avoid the copy and be able to take ownership?

Thoughts on supporting that? Or perhaps I'm just missing how it is supported.

Kyle

**Comment by uNetworkingAB** [comment]
This is a fundamental design and not something that's going to change
