### ISSUE TITLE
Client example doesn't seem to do anything

### ISSUE THREAD

**Issue by lava** [uNetworking/uWebSockets#1594]
Based on a glance at `src/ClientApp.hpp`, the `Client` example seems to do...nothing at all?

Does it mean this library currently doesn't support any client mode, or is the example just outdated?

**Comment by lanthora** [comment]
Please remove the client sample, or indicate at the beginning of the file that this project does not support the client.

**Comment by uNetworkingAB** [comment]
done

**Comment by ichao1214** [comment]
I am very confused about whether this library supports websocket clients. Can you please help explain?

**Comment by renzhenhua** [comment]
May I ask if this library currently supports WebSocket clients now?

**Comment by uNetworkingAB** [comment]
What is the point in writing text if you are not willing to, read, said text. I already wrote an answer in this very thread, some few centimeters away from the box you just typed your question in.

**Comment by renzhenhua** [comment]
> What is the point in writing text if you are not willing to, read, said text. I already wrote an answer in this very thread, some few centimeters away from the box you just typed your question in.

Sorry, it's my problem. The reason is because I read your code(https://github.com/uNetworking/uWebSockets/blob/master/examples/Client.cpp) and I didn't understand how that code works. It may be that my needs are more complicated, I will re-read the following code carefully.
