### ISSUE TITLE
Using the subscribe interface creates an infinite loop bug

### ISSUE THREAD

**Issue by 291920497** [uNetworking/uWebSockets#1598]
I used uWebSockets' subscribe, here is my code: 
```
uWS::App::WebSocketBehavior<WSPARAM> Behav;
	Behav.open = [](auto* WsPoint) {
		WsPoint->subscribe("Test");
	};
```

I created some multithreading and used callbacks in multithreading and used the publish function in callbacks, but he got into an infinite loop and he got stuck in the for loop of this function:

```
void drain() {
        if (drainableSubscribers) {
            /* Drain one socket a time */
            for (Subscriber *s = drainableSubscribers; s; s = s->next) {
                /* Instead of unlinking every single subscriber, we just leave the list undefined
                 * and reset drainableSubscribers ptr below. */
                

                //**The error is here, he loops here and cannot exit**
                drainImpl(s);
            }
            /* Drain always clears drainableSubscribers and outgoingMessages */
            drainableSubscribers = nullptr;
            outgoingMessages.clear();
        }
    }
```

Would I like to ask if this is a bug, as I have worked fine on multiple attempts and this problem comes up occasionally

**Comment by uNetworkingAB** [comment]
The library is not thread safe. You cannot mix threads any way you like. If you compile with ThreadSanitizer you can see why things break.

**Comment by 291920497** [comment]
Is this a network library for a single threaded reactor model? Can I change the settings to make it thread safe? If possible, I would like to use this method, but if not, I will use locks to maintain callback synchronization

**Comment by uNetworkingAB** [comment]
You should read the "read more" page.

**Comment by 291920497** [comment]
okay, thank you
