### ISSUE TITLE
req.getParameter("key")

### ISSUE THREAD

**Issue by uNetworkingAB** [uNetworking/uWebSockets#1607]
I can't believe I haven't thought about this before.

When you register the URL pattern with the app, you can just run over the URL and store parameter offsets in a hashmap that is constant, then just map from string to offset and call .getParameter(index) with whatever the index is.

So the overhead would be minimal, and only for those who get parameter by string key

**Comment by uNetworkingAB** [comment]
Even a hashmap is too overkill, the ideal thing would be just std::flat_map since the number of parameter is going to be veeeeeeery low

**Comment by uNetworkingAB** [comment]
So every node in the router tree would hold this map of parameter keys, and their respective offset in the URL

**Comment by hiqsociety** [comment]
@uNetworkingAB is this in any of the example folder?

**Comment by uNetworkingAB** [comment]
https://github.com/uNetworking/uWebSockets.js/blob/master/examples/Router.js

**Comment by uNetworkingAB** [comment]
I don't understand your question - getParameter is documented in the docs, is covered in the user manual and is used in Router example. There should be no confusion regarding how to use this single parameter function.
