### ISSUE TITLE
Proxy Protocol v2 not working

### ISSUE THREAD

**Issue by youzi** [uNetworking/uWebSockets#1610]
Request to [ProxyProtocol.js](https://github.com/uNetworking/uWebSockets.js/blob/master/examples/ProxyProtocol.js) example behind Cloudflare Spectrum with proxy protocol v2 enabled fails (just hangs).

Tested with:
- uNetworking/uWebSockets.js#v20.20.0 fails
- uNetworking/uWebSockets.js#v20.19.0 fails
- uNetworking/uWebSockets.js#v19.1.0 fails
- uNetworking/uWebSockets.js#v18.12.0 fails
- **uNetworking/uWebSockets.js#v18.11.0 works**

Is there an API change that I'm missing?

**Comment by uNetworkingAB** [comment]
Alright this is fixed now. Some refactoring broke it way back, working now and tested with haproxy
