### ISSUE TITLE
Feature request: Reverse proxy

### ISSUE THREAD

**Issue by porsager** [uNetworking/uWebSockets#1611]
This is slightly related to the http client request in that with the client support,  building a reverse proxy with uWebSockets only would be quite simple. 

Now perhaps having a simple reverse proxy feature built in to uws could be even better. Also, it would allow 0 overhead in the js lib by completely avoid passing into js land per request. 

I'm thinking there are 2 versions as low hanging fruit. 

A completely simple SNI proxy, that does no http parsing (currently using a slow one written with node tls), that just takes a SNI host  -> target map. 

An option that allows you to forward requests, eg by res.forward(...)

Having that could remove moving parts, eg nginx/caddy which feels superfluous and is annoying to config for best performance. In all my tests (except static files served from disk) uws comes out faster than nginx (even with uWebSockets.js, not raw uws).

**Comment by uNetworkingAB** [comment]
it's not planned
