### ISSUE TITLE
examples/broadcast* Wont build due to errors in clion

### ISSUE THREAD

**Issue by flipkickmedia** [uNetworking/uWebSockets#1616]
![Selection_002](https://github.com/uNetworking/uWebSockets/assets/15732784/78a1c353-6507-4d98-aa32-f962a5e5295b)

I'm not sure how to move past this one.  Im fairly new to C++ so any tips here would be helpful.

Thanks

**Comment by uNetworkingAB** [comment]
No idea. But you can't trust your IDE to tell you something is wrong. Many many many times the IDE is completely out of it and tells a lie. Only the compiler will tell you the truth.

**Comment by flipkickmedia** [comment]
Yes I understand it's out of scope really.  Ill see what they have to say over at the Jetbrains support forums and report back.
