### ISSUE TITLE
How to use from vcpkg with boost.asio?

### ISSUE THREAD

**Issue by vktr** [uNetworking/uWebSockets#1620]
Hi!

I'm trying to integrate this with an app I'm writing, which already has a dependency on boost.asio so I have an existing `io_context`. However, I can't seem to find any real examples on how to combine the two.

I'm using version 20.44.0 from vcpkg, together with boost.asio v1.82 something, also from vcpkg.

Happy for any help or pointers in the right direction!

**Comment by uNetworkingAB** [comment]
Loop::get(io_context *); must be called before anything else in uWS. The io_context is a "hint" that gets passed to us_create_loop(hint

**Comment by uNetworkingAB** [comment]
You can see we do the same for libuv in the Node.js addon: https://github.com/uNetworking/uWebSockets.js/blob/master/src/addon.cpp#L417

**Comment by vktr** [comment]
Thanks - what a magic trick 😃
