### ISSUE TITLE
Unable to shutdown one uWS::App while others are running

### ISSUE THREAD

**Issue by kylepl** [uNetworking/uWebSockets#1631]
Hi, perhaps I'm doing something wrong, but I've observed if I have multiple uWS::App's, I can not shut just one down, I needed to trigger `us_listen_socket_close` on each for either to exit their loop. 
[uwebsockets_many_apps.cc.txt](https://github.com/uNetworking/uWebSockets/files/12165558/uwebsockets_many_apps.cc.txt)

I've attached a small repro-case, where setting `TRIGGER_BOTH_APP_CLOSURES_BEFORE_BLOCKING_ON_EITHER` to false shows the case where it blocks forever, and true where it successfully exits by triggering both before blocking on one being done.

**Comment by kylepl** [comment]
Actually, I realized I had forgotten to check the case where I need to defer rather than call this from another thread. Will try that and report back.

**Comment by kylepl** [comment]
So the summary is using uWS::Loop::defer fixes the issue.

**Comment by uNetworkingAB** [comment]
Every thread has 1 loop, regardless of how many Apps that thread has. So you don't really shut down an App, you shut down a loop.
