### ISSUE TITLE
tried to write some web application using uwebsocket http but realised it's not easy

### ISSUE THREAD

**Issue by hiqsociety** [uNetworking/uWebSockets#1638]
@uNetworkingAB this is really a great piece of software but i was wondering if there are more examples whereby this can be used as a full fledged web application framework like accepting a form input and parameters processing.

i think you could have reached a speed limit with io_uring for now with uwebsocket so was wondering if maybe you can consider helping the community expand this into something more "enterprise" skewed for web application framework development?

maybe not now but do hope this can be one of the directions. thx.

**Comment by uNetworkingAB** [comment]
Pretty sure we already support both of those features. Queries and multipart.

**Comment by hiqsociety** [comment]
@uNetworkingAB it's not obvious in the examples given
https://github.com/uNetworking/uWebSockets/tree/master/examples

do u know where i can get better docs with other's examples to work with? a basic "cms" / todo example.

**Comment by uNetworkingAB** [comment]
That's not the average feedback I've received so far. That said, there is always going to be a certain cut-off base competence needed for any project.
