### ISSUE TITLE
Message inflation may overwrite the header of the next packet

### ISSUE THREAD

**Issue by OxleyS** [uNetworking/uWebSockets#1650]
`WebsocketContext::handleFragment()` often hands the `data` buffer it receives directly to the inflation stream for decompression. The inflation stream modifies this array in-place to append the tail/padding bytes before handing it off to `zlib`. However, said `data` buffer comes from `WebsocketProtocol`, which may be storing multiple frames back-to-back in it, if they were provided that way by the `uSockets` data callback. In this case, the inflation process will smash the header of the next frame, causing parse errors and likely `forceClose` down the line.

I'm not sure how to provide a reliable reproducer of this, as it seems dependent on the whims of the underlying TCP stream. I (somehow) have a reliable repro locally, but turning it into something sharable is probably not possible.

I see the `libdeflate` path saves and restores the bytes it overwrites this way. I imagine we just need to do the same for the `zlib` path. I can provide a PR for this if you prefer.

**Comment by uNetworkingAB** [comment]
> The inflation stream modifies this array in-place

It doesn't.

**Comment by OxleyS** [comment]
It (`InflationStream::inflate()`) does end up modifying the array it's passed, although it's not quite clear from looking at the [method's signature](https://github.com/uNetworking/uWebSockets/blob/3bb917da2e44f36a5fec32d735cb61839fe1cc6c/src/PerMessageDeflate.h#L228). The compressed data is given as an `std::string_view`, which normally is a `const` pointer, but on [this line](https://github.com/uNetworking/uWebSockets/blob/3bb917da2e44f36a5fec32d735cb61839fe1cc6c/src/PerMessageDeflate.h#L250), the constness is cast away to add the `0x0000FFFF` tail.

In the typical case of no fragmentation and all that, that pointer will usually be pointing directly into the buffer `WebsocketProtocol::consume()` is iterating through, thus the next packet, if one exists, gets corrupted.

The [libdeflate fast path](https://github.com/uNetworking/uWebSockets/blob/3bb917da2e44f36a5fec32d735cb61839fe1cc6c/src/PerMessageDeflate.h#L236-L240) just above does the same thing, except that after it calls `libdeflate_deflate_decompress()` it restores the bytes it overwrote with the padding. So all we would need to do is save and restore the 4 bytes we overwrite with `0x0000FFFF` in the same manner.

**Comment by uNetworkingAB** [comment]
Okay, I see. Can you make a PR to reset the 4 tail bytes? Never mind the libdeflate, it is not supported anymore.
