### ISSUE TITLE
how  to use ws?

### ISSUE THREAD

**Issue by chenyunshan** [uNetworking/uWebSockets#1654]
https://github.com/uNetworking/uWebSockets/edit/master/examples/Client.cpp
I want open param  ws.but got error .how to fix it ?
![Uploading @G_]K6TRSGQK0%[OY4KK95J.png…]()

**Comment by chenyunshan** [comment]
![@G_ K6TRSGQK0% OY4KK95J](https://github.com/uNetworking/uWebSockets/assets/6806308/1478d4a6-2b65-403f-b53d-7548a6bc3aaf)

**Comment by chenyunshan** [comment]
如果打开后会发生编译错误

**Comment by uNetworkingAB** [comment]
There is a base level of literacy needed to absorb the written text infront of your facial region. If text cannot be absorbed, there is no use to producing even more of said text.
