### ISSUE TITLE
Random `431 Headers Fields Too Large` errors

### ISSUE THREAD

**Issue by TomKlaverAH** [uNetworking/uWebSockets#1658]
I'm seeing some occasional '431 headers too large' HTTP errors for some HTTP requests.

```
< HTTP/1.1 431 Request Header Fields Too Large
< Date: Fri, 15 Sep 2023 10:54:47 GMT
< Strict-Transport-Security: max-age=31536000
< X-Frame-Options: SAMEORIGIN
< Vary: Origin,User-Agent,Access-Control-Request-Method,Access-Control-Request-Headers
< Access-Control-Allow-Origin: https://xxx.xx.xxx
< Access-Control-Allow-Credentials: true
< X-Correlation-Id: gateway-4bb5bc6e-1f92-4cac-a5db-21bad74f9e57
< X-IHS-Time: t=1694775287848962 D=23752
< Referrer-Policy: strict-origin-when-cross-origin
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< X-Srv: 10.232.178.134
< Transfer-Encoding: chunked
< 
* Connection #0 to host xxx.xx.xxx left intact
<h1>Request Header Fields Too Large</h1><hr><i>uWebSockets/20 Server</i>
```
Normal response for same request:
```
< HTTP/1.1 200 OK
< Date: Fri, 15 Sep 2023 10:54:47 GMT
< Strict-Transport-Security: max-age=31536000
< X-Frame-Options: SAMEORIGIN
< Vary: Origin,User-Agent,Access-Control-Request-Method,Access-Control-Request-Headers
< content-type: application/json; charset=utf-8
< uWebSockets: 20
< Content-Length: 55
< access-control-allow-origin: https://xxx.xx.xxx
< access-control-allow-credentials: true
< X-Correlation-Id: gateway-d0188869-5ee2-45c0-83bf-72433fbb198b
< X-IHS-Time: t=1694775288765646 D=22958
< Referrer-Policy: strict-origin-when-cross-origin
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< X-Srv: 10.232.178.134
< 
< (expected body)
```

This happens for some HTTP requests (nothing too crazy for headers, around 3kb total, largest is ~1-2kb cookie header).
It happens seemingly random for the same HTTP request.

From a `tcpdump` it appears it only happens if headers are sent over multiple TCP packets. But the error doesn't always happen every time there are multiple tcp packets..

I tried reproducing this locally, by setting a low MTU on `lo` network device.
Which results in some problems (random socket hangups), but not this exact error.
Not sure how to do more debugging.

**Comment by uNetworkingAB** [comment]
431 Headers Fields Too Large means your headers are too large 😉

**Comment by TomKlaverAH** [comment]
> 431 Headers Fields Too Large means your headers are too large 😉

It happens randomly for the same HTTP requests.
I've tried locally and was able to send much larger headers than what's in the deployed environment which trigger the error so I'm pretty sure it's actually a bug related to TCP/streaming somehow.

**Comment by uNetworkingAB** [comment]
There is no reason or guarantee for this error to be deterministic or strictly checked. This error will only be given if there is a reason for it, such as refusing to buffer any further.

**Comment by TomKlaverAH** [comment]
> There is no reason or guarantee for this error to be deterministic or strictly checked. This error will only be given if there is a reason for it, such as refusing to buffer any further.

So what would cause it to refuse to buffer any further?
Or, what are the limits that I need to maintain to make sure requests are processed? Can these be changed?

**Comment by uNetworkingAB** [comment]
Total header(s) size cannot be more than 4kb. You can't change it, it's a limit for a reason. There is nothing in HTTP that states sending data in header is a good idea or even supported. Headers hold small amounts of data, not several kb

**Comment by uNetworkingAB** [comment]
https://github.com/uNetworking/uWebSockets/blob/master/src/HttpParser.h#L175

**Comment by uNetworkingAB** [comment]
We decided to add environment variable UWS_HTTP_MAX_HEADERS_SIZE for setting it to any size you want

**Comment by bhargavkaranam** [comment]
@uNetworkingAB Do you have any insights on why the randomness exists here? Even though the header size is well under the limit? At what layer are these requests rejected randomly?

**Comment by uNetworkingAB** [comment]
You have a total of 4kb for all headers. It's not random if you keep under that
