### ISSUE TITLE
Compression support

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets#166]
formatMessage should optionally compress according to established permessage-deflate options.

**Comment by jgupta** [comment]
uWS does not compress data? I was thinking I am doing something wrong as response data says "permessage-deflate" but data is not being compressed. If this is true, you should add notes in readme file where it says "Permessage-deflate built-in.".

**Comment by alexhultman** [comment]
Compression is not a requirement of permessage-deflate. There should be an option to compress but if you plan on doing anything with good performance you shouldn't rely on compression but rather select a better protocol (JSON being the worst protocol you can select).

**Comment by SEAPUNK** [comment]
>JSON being the worst protocol you can select

You're confusing JSON with XML 😉 

msgpack is p nice though

you could also just exclusively send as binary and compress/decompress like that

**Comment by alexhultman** [comment]
JSON is the absolutely worst piece of garbage you can pick. XML is the exact same thing only a little more verbose. Comparing yourself with XML is not a good merit. Use something better and stop relying on this ultra slow compression to save you.

**Comment by jgupta** [comment]
Yes, we have selected JSON but selecting any other protocol won't make a noticeable difference as plan to send DOMString from HTMLCanvasElement.toDataURL(). This gives us a very long text string which could take advantage of compression.

Without compression, bandwidth would be too high for our application.

PS : We did try to compress strings using lz-string using javascript but latency is not acceptable.

**Comment by alexhultman** [comment]
So you are taking a canvas, rendering it to PNG (which already is one of the best compressed image formats), then encoding it as a string (making it extremely bloated) only to make it fit in your JSON world. Since you realize this is too big of a message you now want to compress it with the same compression used in the very source.

Do you realize how much you goofed up here? You have absolutely no right to make any kind of opinionated statement after exposing this piwce of garbage solution. Go fix your program and don't blame your problems on this library.

**Comment by alexhultman** [comment]
Making a PNG image a string inside a JSON document! Unbelievable!

**Comment by jgupta** [comment]
Yes, you are so right about how goofed we are (I can understand this statement), we are so much constrained with what API's and functionality browser expose to us. Browser either gives us uncompressed binary of raw 32-bit image using getImageData() or a string of compressed format using toDataURL(). We have to choose one between two and based upon our tests, we selected to go with toDataURL as we benefit with WebP compression of Chrome. I wished we could get compressed binary as we get from getImageData.

Now coming back to uWS, I never blamed your library for my problem, I only said that it does not support compression which I expected when I read "Permessage-deflate built-in".

You are saying that compression on WebSocket is useless which in my opinion is not a correct statement.

**Comment by alexhultman** [comment]
It's a problem of your front-end code. At least you could in the *worst case scenario* just loop over the base64 string you get from the browser and convert it to binary and send that -> *problem solved*. But I'm sure there are much more efficient ways to solve it. It's not my problem how you solve it, but sending an image as text is probably one of the worst solutions I have ever heard in my life, especially when this image itself already is highly compressed.

**Comment by chatziko** [comment]
Just wanted to point out that changing the format is not always a workaround to not having compression. Sometimes you simply have a lot of data to send, real data. Of course one can compress manually, but replacing the browser's native decompression with javascript is not optimal.

This is the only feature that prevents me from moving to uws (which I otherwise love), I'd say it's an important feature.

**Comment by jmealo** [comment]
This message is a bit heated/unkind.

People do crazy things in the browser due to constraints. It's not always someone being an idiot. Less than ideal is good enough for some cases. It's unfair to pass judgement without knowing the business requirements.

I may pass on using uws because I don't want my team to be flogged on GitHub for asking about a feature that the README implies is present.

I suggest changing the README and closing this ticket because it's a blemish on this library.

Let's keep it professional, no personal attacks.

**Comment by alexhultman** [comment]
@jgupta If you want to cuddle in a pillow fort folding paper planes while talking about feelings all night then µWS is not for you.

**Comment by jmealo** [comment]
@alexhultman: [![I'm sorry are you addressing me? Because your authority is not recognized in fort kickass.](http://s2.quickmeme.com/img/fd/fd6d6386734fe8f21884632b57f1dd358d4390447036f1b26f9605de24191ced.jpg)](http://yourauthorityisnotrecognized.com/)

**Comment by alexhultman** [comment]
@jmealo
![](http://i3.kym-cdn.com/entries/icons/facebook/000/009/993/tumblr_m0wb2xz9Yh1r08e3p.jpg)
Irony levels are off the charts here.
