### ISSUE TITLE
Add a way to overwrite the socket options

### ISSUE THREAD

**Issue by LumiereDeLOmbre** [uNetworking/uWebSockets#1665]
Hi,

I use this library inside a wrapping class.
Inside this class I have 

```
...
template <> struct HTTP_Server_setup <IS_SSL> {

private:
                uWS::SSLApp i;
...
}
```

I construct the uWS object with different options the user gives.

Now,  doing this, I can't add socket options later on.

I modified the source code, inside App.h to have:

```
void overwriteOptions ( SocketContextOptions &&options ){

        httpContext = HttpContext <SSL>::create( Loop::get(), options );

}
```

and my wrapper now works with:
```
uWS::SocketContextOptions sopts;
... construction here
i.overwriteOptions( std::move( sopts ) );
```

Is it possible to add this code ?

Thanks!

**Comment by uNetworkingAB** [comment]
That's highly broken

**Comment by LumiereDeLOmbre** [comment]
Even if it happens at the beginning of the object construction ?

**Comment by LumiereDeLOmbre** [comment]
Stepping back, it's ok with http but not ws.
Closing now.

**Comment by LumiereDeLOmbre** [comment]
I corrected my wrapper and everything works. But I sincerely would like to know what I am missing.

Not offensive tone; just honestly curious.

**Comment by uNetworkingAB** [comment]
> (from my tests, it works without issues)
Well, your "tests" are complete dog shit then. This kind of garbage does not belong here.

**Comment by LumiereDeLOmbre** [comment]
You judge too fast but that's fine.
