### ISSUE TITLE
uSockets/bsd.o: file not recognized: file format not recognized

### ISSUE THREAD

**Issue by NyaNekoplus** [uNetworking/uWebSockets#1666]
Hello

I have installed gcc 13.2 on my Ubuntu 20.04, and when I am trying to make uWebSocket via command below, 

`git clone --recurse-submodules git@github.com:uNetworking/uWebSockets.git`
`cd uWebSockets/`
`WITH_OPENSSL=1 make examples`

I encountered problem like title, here is my log:

> make -C uSockets
> make[1]: Entering directory '/home/cowa/Desktop/cpp/uWebSockets/uSockets'
> rm -f *.o
> cc -flto -DLIBUS_USE_OPENSSL -std=c11 -Isrc -O3 -c src/*.c src/eventing/*.c src/crypto/*.c src/io_uring/*.c
> g++  -std=c++17 -flto -O3 -c src/crypto/*.cpp
> lib.exe /out:uSockets.a *.o || ar rvs uSockets.a *.o
> /bin/sh: 1: lib.exe: not found
> ar: creating uSockets.a
> a - bsd.o
> a - context.o
> a - epoll_kqueue.o
> a - gcd.o
> a - io_context.o
> a - io_loop.o
> a - io_socket.o
> a - libuv.o
> a - loop.o
> a - openssl.o
> a - quic.o
> a - sni_tree.o
> a - socket.o
> a - udp.o
> ar: sni_tree.o: plugin needed to handle lto object
> make[1]: Leaving directory '/home/cowa/Desktop/cpp/uWebSockets/uSockets'
> cc build.c -o build
> ./build examples
> --> g++ -march=native -O3 -Wpedantic -Wall -Wextra -Wsign-conversion -Wconversion -std=c++20 -Isrc -IuSockets/src -flto examples/Http3Server.cpp  uSockets/*.o -lz -lssl -lcrypto -o Http3Server
> 
> **uSockets/bsd.o: file not recognized: file format not recognized**
> collect2: error: ld returned 1 exit status
> make: *** [GNUmakefile:7: examples] Error 255

Thanks for your reading.

**Comment by uNetworkingAB** [comment]
You have some issue with your installation
