### ISSUE TITLE
Publish not being received by client when unsubscribing [from all topics] in the same tick

### ISSUE THREAD

**Issue by myndzi** [uNetworking/uWebSockets#1673]
According to the [release notes](https://github.com/uNetworking/uWebSockets/releases/tag/v20.0.0):
> Pub/sub is now a lot more predictable and always guarantees strict ordering inside topics, across topics and between WebSocket::send and WebSocket::publish / App::publish. Subscription and unsubscription is always guaranteed to be strictly ordered with respect to publish. Support for MQTT wildcards has been removed.

I have a case where I'm working on the backend for an existing application; I'm using pub/sub to represent game lobbies. When the host leaves the room, a control message is sent to the topic, and then each subscribed client is unsubscribed. However, the control message is not being sent.

I managed to thin it down to a minimum reproducible version, though my initial attempts seemed to work as expected. I was unable to determine the significant difference between my initial attempts and the repro case below. I've been at it some hours, hopefully this is actually a repro case and not user error.

```js
const uWS = require('uWebSockets.js');
const { WebSocket } = require('ws');

const app = uWS
  .App()
  .ws('/', {
    open: (ws) => {
      ws.subscribe('test');
      app.publish('test', 'hi from pubsub');
      // swap comments on the next two lines - will change between success and failure
      ws.unsubscribe('test');
      // setImmediate(() => ws.unsubscribe('test'));
      ws.send('???');
    }
  })
  .listen(3300, () => {
    const wsClient = new WebSocket('ws://localhost:3300/');
    wsClient.addEventListener('message', (evt) => {
      const msg = Buffer.from(evt.data).toString();
      console.log('client received from server:', msg);
      if (msg === '???') app.close();
    });
  });
```

```bash
$ npm ls
uws-bug@1.0.0 /home/myndzi/uws-bug
├── uWebSockets.js@20.32.0 (git+ssh://git@github.com/uNetworking/uWebSockets.js.git#21c0e41a662c27bcc29b64f3e9d7f0bdaa6d7ee7)
└── ws@8.14.2

$ node --version
v20.8.1
```

**Comment by uNetworkingAB** [comment]
https://github.com/uNetworking/uWebSockets/commit/7da88ce71c31dbc799dfa9bdd8171d09a6b80b19

Will release this if it passes fuzzing

**Comment by myndzi** [comment]
Looking at the diff, is there anything that cleans these up? This feels leaky to me, though it will solve the problem. Is there no place to remove the subscriber once all messages have been flushed?

**Comment by uNetworkingAB** [comment]
freeSubscriber is not per topic, it's more like "downgrade this WebSocket to not using pub/sub". It happens in close either way.

**Comment by uNetworkingAB** [comment]
In a few hours, can you test **bun install uNetworking/uWebSockets.js#binaries** with these changes

**Comment by uNetworkingAB** [comment]
Did that work?

**Comment by myndzi** [comment]
> Did that work?

Yep, thank you!

**Comment by uNetworkingAB** [comment]
Yeah I ran your reproducer and saw it was fixed. Thanks for reporting, there is a new release both .js and c++
