### ISSUE TITLE
Segfault in SSLApp / SNI when key/cert files are not readable

### ISSUE THREAD

**Issue by myndzi** [uNetworking/uWebSockets#1675]
Hi there. The following code produces a segfault on the latest release:

```
const uWS = require('uWebSockets.js');

const app = uWS.SSLApp({});
app.addServerName('example.com', {
  key_file_name: '/tmp/nonexistent',
  cert_file_name: '/tmp/nonexistent',
});
```

Same thing happens if the files exist but aren't readable by the current user.

Ideally, the library would produce a human-meaningful error message (file doesn't exist, or no access, etc.). When creating the repro, I tried just creating an SSLApp with nonexistent files and the error message is just "App construction failed", which could also be improved to give some clue as to why.

**Comment by uNetworkingAB** [comment]
https://github.com/uNetworking/uSockets/blob/bb86c9c8eee67799af5d016282ee0920945a0fb3/src/crypto/openssl.c#L558

**Comment by uNetworkingAB** [comment]
fixed in https://github.com/uNetworking/uSockets/commit/a15d9bbdea68fd02dab40d2394200deb1b883aa6
