### ISSUE TITLE
Websocket Crashing  "Error: Cork buffer must not be acquired without checking canCork!"

### ISSUE THREAD

**Issue by gabrielOttopia** [uNetworking/uWebSockets#1690]
I have a Websocket Server that handles data received and exposes an public Send function so my app can send messages to the websocket client.
When i send messages to the websocket client, after a few reconnections and messages being sent - the program terminates with the following errors
"Error: Cork buffer must not be acquired without checking canCork!"
or
"Error: Cork buffer must not be held across event loop iterations!"

here is my code

```
WebSocketServer::WebSocketServer(uint16_t port, Common::Metadata::StatesRouter<Events::StationEventBase>& states_router) :
    m_port(port), m_websocket_message_handler(std::make_shared<WebsocketMessageHandler>(states_router)), m_socket(nullptr)
{
    // Intentionally left blank
}

void WebSocketServer::Start()
{
    m_server_thread = std::thread(&WebSocketServer::start_websocket_server, this);
}

WebSocketServer::~WebSocketServer()
{
    Stop();
    if (m_socket)
    {
        m_socket->close();
        delete m_socket;
    }
}

void WebSocketServer::Stop()
{
    if (m_app)
    {
        m_app->close();
        m_app.reset();
    }
    if (m_server_thread.joinable())
    {
        m_server_thread.join();
    }
}

void WebSocketServer::Send(const std::string& data)
{
    if (!m_socket)
    {
        return;
    }

    m_socket->send(data);
}

void WebSocketServer::start_websocket_server()
{
    m_app = std::make_unique<uWS::App>();
    m_app->ws<UserData>(WEB_SOCKET_PATH.data(),
                        uWS::TemplatedApp<false>::WebSocketBehavior<UserData> {
                                .open =
                                        [this](WebSocketType* ws) {
                                            on_open(ws);
                                        },
                                .message =
                                        [this](WebSocketType* /*ws*/, std::string_view message, uWS::OpCode /*opcode*/) {
                                            on_message(message);
                                        },
                                .close =
                                        [this](WebSocketType* /*ws*/, int code, std::string_view message) {
                                            on_close(code, message);
                                        }})
            .listen(m_port,
                    [this](auto* listenSocket) {
                        
                    })
            .run();
}

void WebSocketServer::on_open(WebSocketType* ws)
{
    m_socket = ws;
}

void WebSocketServer::on_message(std::string_view message)
{
// Handle Message
}

void WebSocketServer::on_close(int code, std::string_view message)
{
    m_socket = nullptr;
}```

**Comment by uNetworkingAB** [comment]
None of this is even remotely correct. You are mixing threads and taking ownership of memory you don't own. You need to go back to basics and get the fundamentals right.

**Comment by gabrielOttopia** [comment]
@uNetworkingAB Please post an example that is not just a simple EchoServer. That is the only example UWebSockets is able to provide unfortunately.

**Comment by ddevienne** [comment]
I'm no expert Gabriel, but you can't `send()` Willy Nilly from any thread like that.
See https://stackoverflow.com/questions/54967062/sending-data-to-uwebsockets-0-15-x-sockets-from-another-thread
and also https://github.com/uNetworking/uWebSockets.js/discussions/909. Notably the doc on Corking:
https://github.com/uNetworking/uWebSockets/blob/master/misc/READMORE.md#corking

**Comment by gabrielOttopia** [comment]
> I'm no expert Gabriel, but you can't `send()` Willy Nilly from any thread like that. See https://stackoverflow.com/questions/54967062/sending-data-to-uwebsockets-0-15-x-sockets-from-another-thread and also [uNetworking/uWebSockets.js#909](https://github.com/uNetworking/uWebSockets.js/discussions/909). Notably the doc on Corking: https://github.com/uNetworking/uWebSockets/blob/master/misc/READMORE.md#corking

I've tried the defer, but it does not work. I'm also not able to find any real documentation on how to use the WS other than as an echo server which is not very useful for me
