### ISSUE TITLE
incoming requests with content-length >= 1000000000 are aborted

### ISSUE THREAD

**Issue by porsager** [uNetworking/uWebSockets#1693]
Trying to receive a request that has a content-length >= 1000000000 (1gb) instantly closes the connection and calls onAborted.

I've been looking for some limit / max magic number in the source of uWebSockets and uWebSockets.js, but can't find anything anywhere. 

Is this configurable somehow, or can this limit be removed?

Here's a sample setup:

```js
import fs from 'fs'
import uws from 'uWebSockets.js'

const app = uws.App()

app.post('/*', (res, req) => {
  console.log('length', req.getHeader('content-length'))
  res.onAborted(() => console.log('aborts instantly'))
  res.onData((data, isLast) => {
    console.log('ondata never fires')
  })
})

app.listen(1234, x => x && console.log('listening'))
```

Then

```bash
mkfile -n 1953125b bigfile.mb // precisely 1000000000
curl -v --data-binary @bigfile.mb http://localhost:1234
```

**Comment by uNetworkingAB** [comment]
https://github.com/uNetworking/uWebSockets/commit/e0394289b6db96e3f0f5b5a2c4b660a71efea5f6

This commit bumps the limit to 62 bits. Feel free to test with the Crc32 example (POST it something, get the correct crc32)

**Comment by uNetworkingAB** [comment]
I tested with curl and Crc32 example, seems to work. Will give it a few days to fuzz before I do a release
