### ISSUE TITLE
How to send close frame?

### ISSUE THREAD

**Issue by poor1017** [uNetworking/uWebSockets#1696]
Hi

    I need to actively disconnect the WebSocket on the server side, and hope that the client receives a close frame that contains an error code that indicates the reason why the server closed the connection.

    I used `ws->end(code, reason_msg)`, but the client didn't seem to receive the close frame.

    Can you help locate the problem?

Thanks!

**Comment by uNetworkingAB** [comment]
> but the client didn't seem to receive the close frame

I'm not going to debug this claim. If you want to file a bug report, provide proof of this. Meanwhile I will be closing this
