### ISSUE TITLE
 uWS::HttpRequest setHeaders

### ISSUE THREAD

**Issue by devindasrinath** [uNetworking/uWebSockets#1721]
Hi, 
I am currently writing unit tests for some methods which use a object of HttpRequest. In these methods, various functions such as getHeaders, getUrl, and so on are utilized. To write the unit test for this methods, I need to add some headers and URLs for this objects at the beginning. However, there are no setter methods in the HttpRequest class. Can someone help me find a way to resolve this? 
Thank you.

**Comment by uNetworkingAB** [comment]
HttpRequest is read only and doesn't work like a generic key/value container. Its hard to write any unit test only for the getters, you would have to write a unit test for the parser instead. But those are already written (but could be expanded
