### ISSUE TITLE
C++ 20 Module support

### ISSUE THREAD

**Issue by Ariaszzzhc** [uNetworking/uWebSockets#1734]
Currently compilers such as gcc, clang, and msvs have already provided support for C++ standard modules. So is there are any plan to support C++ 20 Module?

**Comment by uNetworkingAB** [comment]
Yes but the library itself is still only requiring/using C++17, so a jump to C++23 with std::move_only_function (heavily used) could be a good time to update all of that.

**Comment by kelteseth** [comment]
I have linked this issue regarding modules support to https://arewemodulesyet.org/ to track the progress of modules adoption in the c++ ecosystem. @uNetworkingAB would uWebSockets need to upgrade the build system as well, because makefiles do not support modules.
