### ISSUE TITLE
Non-default constructor for UserData

### ISSUE THREAD

**Issue by mincequi** [uNetworking/uWebSockets#1736]
Hi there,

i have a question regarding how i could provide UserData, that has a non-default constructor?
Please check this example:

```
int main() {
    class AnotherUserData {};
    class SomeUserData {
    public:
        SomeUserData() {} // this works
        //SomeUserData(const AnotherUserData&) {} // this gives: "no matching member function for call to 'upgrade'"
    };
    uWS::App app;
    app.ws<SomeUserData>("/", {});
}
```

When using user data, that is default constructed, this works. Is there any possibility, to provide UserData, that has a non default constructor (to inject dependencies)?

**Comment by uNetworkingAB** [comment]
I don't understand, I took your code and put in EchoServer.cpp and it compiled fine.

The user data will be default constructed but you can init it as you like in the .open handler and free it as you like in .close handler.

**Comment by mincequi** [comment]
Yes, that version (with the commented non-default constructor) works, but check this one:

```
int main() {
    class AnotherUserData {};
    class SomeUserData {
    public:
        //SomeUserData() {} // this works
        SomeUserData(const AnotherUserData&) {} // this gives: "no matching member function for call to 'upgrade'"
    };
    uWS::App app;
    app.ws<SomeUserData>("/", {});
}
```

I will check the .open and .close handler, though.

**Comment by uNetworkingAB** [comment]
I can think of at least 5 different ways to solve whatever issue you think you have here. I think the issue is that you aren't looking to adopt the requirements of the library but rather want the library to adopt your requirements. But if you think about it, that's obviously not going to happen.

**Comment by mincequi** [comment]
Well, i was requesting your opinion in the most positive and constructive way. And that you know _at least 5 different ways_ is very impressive. So, are you willing to share your ideas?
I never intended your lib shall adapt to my needs, but to have a sane possibility to work around static objects and singletons, which are considered as a design flaw by many C++ developers.

**Comment by uNetworkingAB** [comment]
I don't understand what your actual problem here is. 

Obviously, you can use _void ptr_ as UserData and achieve anything you would normally with C. But there are about a million different ways to do it.

I have absolutely no idea why you're mentioning singleton or globals.

The most common way to pass user data in C is to pass void ptr but having a template T datatype allows eliminating an extra allocation if one wants to. 

This is not a "design flaw", you may use it or simply use void ptr

**Comment by mincequi** [comment]
Ok, thanks. I found a solution and injected my user data in the .open handler.
