### ISSUE TITLE
UB in sending long messages

### ISSUE THREAD

**Issue by alexolog** [uNetworking/uWebSockets#1743]
In WebSocket.h, line 118:
```
int header_length = (int) protocol::formatMessage<isServer>(header, nullptr, 0, opCode, message.length(), compress, fin);
```
In WebSocketProtocol.h, line 209:
```
static inline size_t formatMessage(char *dst, const char *src, size_t length, OpCode opCode, size_t reportedLength, bool compressed, bool fin) {
```
And in the same function, line 241:
```
memcpy(dst + headerLength, src, length);
```
From the [documentation of memcpy](https://en.cppreference.com/w/cpp/string/byte/memcpy):
> If either dest or src is an invalid or null pointer, the behavior is undefined, even if count is zero.

Consequence:
Program consistently crashes on this call to `memcopy` when UB sanitizer is enabled.
Program may behave incorrectly due to UB.

Fix suggestion:
```
if (length)
  memcpy(dst + headerLength, src, length);
```

**Comment by uNetworkingAB** [comment]
If you add curly brackets to that if, you can make it a PR

**Comment by alexolog** [comment]
> If you add curly brackets to that if, you can make it a PR

https://github.com/uNetworking/uWebSockets/pull/1744

**Comment by uNetworkingAB** [comment]
Now that I think of it, just replace nullptr with "" and remove the if.

**Comment by alexolog** [comment]
> Now that I think of it, just replace nullptr with "" and remove the if.

IMHO it will be worse for the following reasons:
(a) The intent will be less clear (why are we passing an empty null-terminated string here?), and
(b) It will not address the underlying problem (What if somebody calls FormatMessage with a nullptr three years from now?)

**Comment by uNetworkingAB** [comment]
Fixed by https://github.com/uNetworking/uWebSockets/commit/01058d90e9d092c2d6551956d7e0785e0e94ff21
