### ISSUE TITLE
Specify QoS for MQTT syntax

### ISSUE THREAD

**Issue by SebastienGllmt** [uNetworking/uWebSockets#1753]
In the [subscribe code](https://github.com/uNetworking/uWebSockets/blob/01058d90e9d092c2d6551956d7e0785e0e94ff21/src/WebSocket.h#L264), it mentions MQTT syntax being accepted for subscriptions. However, the docs mention nothing about how this MQTT support is implemented internally. This matters because MQTT defines [3 QoS levels](https://www.emqx.com/en/blog/introduction-to-mqtt-qos) which have different implications for how clients should be written

It's also possible that by `MQTT syntax` you mean you're just using the MQTT syntax and now actually following the protocol at all, but even in this case it would be nice if this was explicitly mentioned and possibly what QoS level the implementation maps to

**Comment by uNetworkingAB** [comment]
It's QoS 1, and MQTT syntax is no longer supported.
