### ISSUE TITLE
CLOSE_WAIT  question

### ISSUE THREAD

**Issue by 18328594608** [uNetworking/uWebSockets#1755]
A large number of CLOSE_WAIT occurs in my program, this problem causes the memory usage of the program to keep rising, do I need to actively call close to disconnect the connection? Or do you need to periodically check the socket connection status?

**Here's how things can go wrong:**

> netstat -n | awk '/^tcp/ {++S[$NF]} END {for(a in S) print a, S[a]}'    
> CLOSE_WAIT 127
> ESTABLISHED 41
> TIME_WAIT 49

**Comment by uNetworkingAB** [comment]
You have in particular idleTimeout for this:

https://github.com/uNetworking/uWebSockets/blob/01058d90e9d092c2d6551956d7e0785e0e94ff21/examples/EchoServer.cpp#L24-L28

**Comment by 18328594608** [comment]
I've actually activated this setting, But something went wrong.

> .maxPayloadLength = 16 * 1024,
> .idleTimeout = 10 ,
> .maxBackpressure = MAXBACKPRESSURE,
> .resetIdleTimeoutOnSend = true,
> .sendPingsAutomatically = true,

**Comment by 18328594608** [comment]
> I've actually activated this setting, But something went wrong.
> 
> > .maxPayloadLength = 16 * 1024,
> > .idleTimeout = 10 ,
> > .maxBackpressure = MAXBACKPRESSURE,
> > .resetIdleTimeoutOnSend = true,
> > .sendPingsAutomatically = true,

I found almost all close code = 1006, but no close message. What is code = 1006?

**Comment by uNetworkingAB** [comment]
> netstat -n | awk '/^tcp/ {++S[$NF]} END {for(a in S) print a, S[a]}'

This shows your entire system, not uWS. For uWS you can see exactly when it opens and closes sockets via strace. There is no growing memory use, the lib has been tested with million of connections and closures repeatedly. Esp. if you link with libtcmalloc the memroy usage is entirely predictable.

If you use idleTimeout together with sendPingsAutomatically and without resetIdleTimeoutOnSend it will close your connections properly without you having to care.

**Comment by 18328594608** [comment]
I currently have 25 connections in memory. But there are 100 CLOSE_WAIT connections, and the CLOSE_WAIT state is also on my socket using uWs. But the CLOSE_WAIT connection has actually been removed from my memory. Its socket state still exists. Do I need to disable resetIdleTimeoutOnSend?

**Comment by uNetworkingAB** [comment]
Post a reproducer and I can look at it. You haven't given any information other than your system CLOSE_WAIT. I dont even know the platform, the event loop or if you use threads or if you have run AddressSanitizer or anything.

**Comment by 18328594608** [comment]
Scenario:
1. Accidental appearance in the online user environment, no scene.
When something goes wrong, the only difference from the normal case is that the number of CLOSE_WAIT connections increases
3. The machine in question is using the system of ubutu18, and the Ngix domain name is used to forward the access to the machine. My application is multithreaded and pushes many transaction data packets to each connection. The memory increment is the packet pushed by this part. Using the release environment has nothing to do with running the task AddressSanitizer.
 Thanks!

**Comment by uNetworkingAB** [comment]
I can't make any sense of your writing. But even if I could, the fact that you reject my hints of using AddressSanitizer and strace - while hinting of using multithreading with a single threaded library, just means we've reached the end of this thread.

You're free to post actual bug reports with tangible evidence whenever you have such info
