### ISSUE TITLE
Segmentation fault when returning SSL_CTX of the app

### ISSUE THREAD

**Issue by ShakyaPr** [uNetworking/uWebSockets#1756]
**Description:** 

I am experiencing a segmentation fault when attempting to retrieve the SSL context of my SSL server using the following code: `SSL_CTX* sslContext = static_cast<SSL_CTX *>(_ssl_server->getNativeHandle());`

**Observations:**

1. **Stack Trace** : I used **gdb** to obtain the stack trace, which points to an issue in **openssl.c**:
![image](https://github.com/uNetworking/uWebSockets/assets/59193561/0ce89bea-9a2a-4c8d-a4bb-d9e8b3e04f34)

2. **Library Build** : The uWebSocket library was built without the `LIBUS_NO_SSL` flag.

3. **Comparative Test** : To isolate the issue, I created an identical HTTPS server in a separate project. In this test project, I was able to retrieve the `SSL_CTX` without any issues. Both projects use the same libraries and versions, but only my current development project encounters the segmentation fault.

**Details:**

 **Current Development Environment:**

- uWebSocket library built without `LIBUS_NO_SSL`.
- Identical code for setting up the HTTPS server.

**Test Project Environment:**

- Same uWebSocket library and version.
- No segmentation fault when retrieving `SSL_CTX`.

1. Why is there a difference in behavior between the two projects?
2. **The stack trace indicates a reference to openssl.c, which is not visited in the working test project.** What could be causing this discrepancy?
3. Are there any known issues or additional configurations needed when using uWebSockets with SSL in a specific project setup?

**Comment by uNetworkingAB** [comment]
Like always, AddressSanitizer is your friend

**Comment by uNetworkingAB** [comment]
Context is nullptr, why? I don't know

**Comment by ShakyaPr** [comment]
We are running three server instances in three different threads. Occasionally, when creating an ssl_server object using SSLApp, the httpContext is null. Is there any reason for this? Is this socket creation isn't thread safe?

**Comment by uNetworkingAB** [comment]
> Like always, AddressSanitizer is your friend

Use these tools. If you wonder about threading, use ThreadSanitizer. I don't accept bug reports of crashes without these tools being used.
