### ISSUE TITLE
µWebSockets.js => ~30.000 ; µWebSockets => ~1.015 ?

### ISSUE THREAD

**Issue by alexe100** [uNetworking/uWebSockets#1766]
Hi
I am trying to make some preliminary tests to both µWebSockets.js and µWebSockets in order to find out some aproximate limits in terms of supported concurrent websocket connections.
µWebSockets was compiled with: LIBUV=1 make examples

Env: Ubuntu 20, 16GB of RAM

Then, in localhost, I launched the EchoServer and used a nodejs client to create as much as possible websocket connections using WS. Only aproximate 1.015 are accepted

Then  I launched the the sample nodejs in https://github.com/uNetworking/uWebSockets.js page and using the same client. Now the client can reach ~30.000 successed websocket connections.

Why is this happen? Is the nodejs I/O system more capable than LibUV? Hopw can I reach at least the same results using the C++ version?

Thank you

**Comment by uNetworkingAB** [comment]
https://medium.com/@unetworkingab/millions-of-active-websockets-with-node-js-7dc575746a01
