### ISSUE TITLE
Underscore in http methods get trashed. 

### ISSUE THREAD

**Issue by geiseri** [uNetworking/uWebSockets#1769]
I have an instance that I need to handle a custom HTTP method `RDG_DATA_OUT` but it seems for some reason the when I call `getMethod()` or `getCaseSensitiveMethod()` on the request I see the ascii representation of the following `0x72 0x64 0x67 0x7F 0x6F 0x75 0x74 0x7F 0x64 0x61 0x74 0x61` that is approximately `rdg<delete>data<delete>out`.  Is this handled differently than the other header fields? It looks like it is still getting `|= 32` applied somehow.   My understanding is that [rfc9110](https://datatracker.ietf.org/doc/html/rfc9110#section-9.1) allows it to be a case sensitive [token](https://datatracker.ietf.org/doc/html/rfc9110#section-5.6.2). This also holds true for the other header fields, but in my not so humble opinion if a client is offering two different cases of  a field name with conflicting types they get what they deserve.  Or you are Microsoft's  MacOS Remote Desktop Client... where again they get what they deserve.

**Comment by uNetworkingAB** [comment]
Are you only calling getCaseSensitiveMethod?

**Comment by geiseri** [comment]
I actually tried both with the same results.  Or do only one only once?

**Comment by geiseri** [comment]
Ah, okay.  So if I ONLY call `getCaseSensitiveMethod()` i get the expected results.  But if at any point `getMethod()`  is called first it goes into the state above.  Is this expected?

**Comment by uNetworkingAB** [comment]
getMethod() is for backwards compatibility and will mutate the method
