### ISSUE TITLE
Encounter "Error: Cork buffer must not be acquired without checking canCork!"

### ISSUE THREAD

**Issue by twenty2811** [uNetworking/uWebSockets#1774]
**Description:**

When using uWebSockets as a server, I had occasionally encountered the following message:

 "Error: Cork buffer must not be acquired without checking canCork!"

 it would stop my whole program. 

Since the "bug" is not easily reproduced, I traced the source code and try to figure out what might be the reason for the error.

The error message comes from "AsyncSocket.h", and the "cork()" function might be called from the following code from "WebSocketContext.h" (the other place is "HttpContext.h", but that has less possibility in my use case):
```
/* Handle WebSocket data streams */
        us_socket_context_on_data(SSL, getSocketContext(), [](auto *s, char *data, int length) {

            /* We need the websocket data */
            WebSocketData *webSocketData = (WebSocketData *) (us_socket_ext(SSL, s));

            /* When in websocket shutdown mode, we do not care for ANY message, whether responding close frame or not.
             * We only care for the TCP FIN really, not emitting any message after closing is key */
            if (webSocketData->isShuttingDown) {
                return s;
            }

            auto *webSocketContextData = (WebSocketContextData<SSL, USERDATA> *) us_socket_context_ext(SSL, us_socket_context(SSL, (us_socket_t *) s));
            auto *asyncSocket = (AsyncSocket<SSL> *) s;

            /* Every time we get data and not in shutdown state we simply reset the timeout */
            asyncSocket->timeout(webSocketContextData->idleTimeoutComponents.first);
            webSocketData->hasTimedOut = false;

            /* We always cork on data */
            asyncSocket->cork();
...
```

**Questions:**

The error message states that "canCork()" should always be called before "cork()", but here "asyncSocket->cork();" without this check beforehand. So, my questions are the following:

- why there is no need to check "canCork()"? and what might be the assumption of the logic?
- in what situations would "invalid corking" happen?

**Environment:**
- Ubuntu 20.04
- No SSL used currently

**Comment by uNetworkingAB** [comment]
You can't leave a socket corked, if you cork it you need to uncork it before returning from whatever event you were called

**Comment by uNetworkingAB** [comment]
It can also be that you have some threading misuse. Nobody in JavaScript camp has reported this issue, but I have seen it reported by C++ users who play with corking / threading. You are doing C++, yes?

**Comment by twenty2811** [comment]
Thank you for you reply. Yes, I'm using in C++ environment. I'm still thinking your first reply and trying to figure out what could the the reasons.

**Environment:**
- C++ 17
- cmake version 3.30.1, project declare cmake_minimum_required 3.16

**Comment by twenty2811** [comment]
By the way, uWebSockets is not multithreaded in my use case, though for each new connection, I started a websocket connection with another websocket server. 

**Correction:**
- Using the uWebSockets as the server only

**Comment by twenty2811** [comment]
The problem seems to relate to the new threads that holds the "uWS::WebSocket<_> *ws" pointer for later use, which is against the rule of this library "isolated to only one thread".

**Comment by dgm3333** [comment]
@twenty2811 
Did you find a solution to this?
My websocket is server has to pass data to a subprocess which is best set up as a child thread - as it takes seconds to process the it just runs in the background, but having an intermittent random crash is pretty annoying...

and from what you are saying then would just adding a canCork check work like this?

us_socket_context_on_data(SSL, getSocketContext(), [](auto *s, char *data, int length) {

    /* We need the websocket data */
    WebSocketData *webSocketData = (WebSocketData *) (us_socket_ext(SSL, s));

    /* When in websocket shutdown mode, we do not care for ANY message, whether responding close frame or not.
     * We only care for the TCP FIN really, not emitting any message after closing is key */
    if (webSocketData->isShuttingDown) {
        return s;
    }

    auto *webSocketContextData = (WebSocketContextData<SSL, USERDATA> *) us_socket_context_ext(SSL, us_socket_context(SSL, (us_socket_t *) s));
    auto *asyncSocket = (AsyncSocket<SSL> *) s;

    /* Every time we get data and not in shutdown state we simply reset the timeout */
    asyncSocket->timeout(webSocketContextData->idleTimeoutComponents.first);
    webSocketData->hasTimedOut = false;

    bool corked = false;

    /* Check if corking is supported before attempting to cork */
    if (asyncSocket->canCork()) {
        asyncSocket->cork();  // Cork only if canCork() returns true
        corked = true;
    }

    /* This parser has virtually no overhead */
    WebSocketProtocol<isServer, WebSocketContext<SSL, isServer, USERDATA>>::consume(data, (unsigned int) length, (WebSocketState<isServer> *) webSocketData, s);

    /* Only uncork if corking was successful */
    if (corked) {
        asyncSocket->uncork();
    }

    /* If uncorking was successful and we are in shutdown state then send TCP FIN */
    if (asyncSocket->getBufferedAmount() == 0) {
        /* We can now be in shutdown state */
        if (webSocketData->isShuttingDown) {
            /* Shutting down a closed socket is handled by uSockets and just fine */
            asyncSocket->shutdown();
        }
    }

    return s;
});

**Comment by twenty2811** [comment]
Adding a canCork check does not solve my problem, I came up with other solutions in the end.

**Comment by twenty2811** [comment]
> @twenty2811 
> 
> Did you find a solution to this?
> 
> My websocket is server has to pass data to a subprocess which is best set up as a child thread - as it takes seconds to process the it just runs in the background, but having an intermittent random crash is pretty annoying...
> 
> 
> 
> and from what you are saying then would just adding a canCork check work like this?
> 
> Although I'm using the vcpkg across numerous developer machines so ideally I don't want to alter the source unless I really have to
> 
> 
> 
> 
> 
> WebSocketContext.h
> 
> ```
> 
> 
> 
> us_socket_context_on_data(SSL, getSocketContext(), [](auto *s, char *data, int length) {
> 
> 
> 
>     /* We need the websocket data */
> 
>     WebSocketData *webSocketData = (WebSocketData *) (us_socket_ext(SSL, s));
> 
> 
> 
>     /* When in websocket shutdown mode, we do not care for ANY message, whether responding close frame or not.
> 
>      * We only care for the TCP FIN really, not emitting any message after closing is key */
> 
>     if (webSocketData->isShuttingDown) {
> 
>         return s;
> 
>     }
> 
> 
> 
>     auto *webSocketContextData = (WebSocketContextData<SSL, USERDATA> *) us_socket_context_ext(SSL, us_socket_context(SSL, (us_socket_t *) s));
> 
>     auto *asyncSocket = (AsyncSocket<SSL> *) s;
> 
> 
> 
>     /* Every time we get data and not in shutdown state we simply reset the timeout */
> 
>     asyncSocket->timeout(webSocketContextData->idleTimeoutComponents.first);
> 
>     webSocketData->hasTimedOut = false;
> 
> 
> 
>     bool corked = false;
> 
> 
> 
>     /* Check if corking is supported before attempting to cork */
> 
>     if (asyncSocket->canCork()) {
> 
>         asyncSocket->cork();  // Cork only if canCork() returns true
> 
>         corked = true;
> 
>     }
> 
> 
> 
>     /* This parser has virtually no overhead */
> 
>     WebSocketProtocol<isServer, WebSocketContext<SSL, isServer, USERDATA>>::consume(data, (unsigned int) length, (WebSocketState<isServer> *) webSocketData, s);
> 
> 
> 
>     /* Only uncork if corking was successful */
> 
>     if (corked) {
> 
>         asyncSocket->uncork();
> 
>     }
> 
> 
> 
>     /* If uncorking was successful and we are in shutdown state then send TCP FIN */
> 
>     if (asyncSocket->getBufferedAmount() == 0) {
> 
>         /* We can now be in shutdown state */
> 
>         if (webSocketData->isShuttingDown) {
> 
>             /* Shutting down a closed socket is handled by uSockets and just fine */
> 
>             asyncSocket->shutdown();
> 
>         }
> 
>     }
> 
> 
> 
>     return s;
> 
> });
> 
> ```
> 
> 
> 
> 
> 
> 
> 
> in HttpContext.h it would seem a little more complex as uncork is called in multiple locations and I assume the calls should be paired?
> 
> ```
> 
>     /* Check if corking is supported before attempting to cork */
> 
>     bool corked = false;
> 
>     if (((AsyncSocket<SSL> *) s)->canCork()) {
> 
>         ((AsyncSocket<SSL> *) s)->cork();  // Cork only if canCork() returns true
> 
>         corked = true;
> 
>     }
> 
> ...
> 
> ```

**Comment by twenty2811** [comment]
@dgm3333 
Adding a canCork check does not solve my problem, I came up with other solutions in the end.

**Comment by dgm3333** [comment]
Thanks,
I've been running to check it and I think it was related to my having a ws->send call in a function called from HandleMessage which was originally non-threaded but I subsequently converted to threaded without removing the send from the child thread. Thus I think there was likely a datarace. Given it is clearly stated throughout the documentation that this is illegal it wasn't surprising.
I implemented a message queue something like this which solved it

struct PerSocketData {
	std::atomic<bool> isChildRunning = false;
	std::mutex messageQueueMutex;
	std::deque<std::string> messageQueue;
}
void FlushQueuedMessages(auto* ws)
{
	if (!ws || !ws->getUserData()) {
		std::cerr << "Invalid WebSocket or user data" << std::endl;
		return;
	}

	PerSocketData* socketData = GetSocketData(ws);
	if (!socketData)
		return;

	if (!socketData->isWebSocketConnected) {
		std::cerr << "WebSocket is not connected. Cannot flush messages." << std::endl;
		return;
	}

	//std::cerr << "Flushing queued messages..." << std::endl;

	{
		std::lock_guard<std::mutex> lock(socketData->messageQueueMutex);
		while (!socketData->messageQueue.empty() && ws->getBufferedAmount() == 0) {
			std::string message = socketData->messageQueue.front();
			try {
				ws->send(message, uWS::OpCode::TEXT);
				socketData->messageQueue.pop_front();
			}
			catch (const std::exception& e) {
				std::cerr << "Failed to send queued message: " << e.what() << std::endl;
				break;
			}
		}

		if (!socketData->messageQueue.empty()) {
			std::cerr << "Some messages remain queued due to persistent backpressure." << std::endl;
		}
	}
}

void SendMessage(auto* ws, const std::string& message)
{
	if (!ws || !ws->getUserData()) {
		std::cerr << "Invalid WebSocket or user data" << std::endl;
		return;
	}

	PerSocketData* socketData = GetSocketData(ws);
	if (socketData) {
		std::lock_guard<std::mutex> lock(socketData->messageQueueMutex);
		socketData->messageQueue.push_back(message); // Queue the message
	}

	FlushQueuedMessages(ws);
}

void ChildThread(PerSocketData& socketData)
{
	{
		std::lock_guard<std::mutex> lock(socketData.messageQueueMutex);
		socketData.messageQueue.push_back(response);
	}
}
inline void HandleWebSocketMessage(uWS::WebSocket<false, true, socketUsrData>* ws, const std::string_view& message, uWS::OpCode& opCode)
{

	if (!ws || !ws->getUserData()) {
		std::cerr << "Invalid WebSocket or user data" << std::endl;
		return;
	}

	// Access the user data associated with the WebSocket
	PerSocketData* socketData = GetSocketData(ws);
	if (!socketData) {
		std::cerr << "Invalid socketData data" << std::endl;
		return;
	}

	if (!socketData->isChildRunning) {
		std::thread(ChildThread, std::ref(*socketData));
	}

	FlushQueuedMessages(ws);
}
