### ISSUE TITLE
uwebsocket is not a header-only program

### ISSUE THREAD

**Issue by mcmy** [uNetworking/uWebSockets#1815]
#### Problem Description

While integrating `uWebSockets` using vcpkg, it was observed that:

1. The vcpkg documentation marks `uWebSockets` as a header-only library, but the actual configuration requires `uSockets` and `zlib` as additional dependencies.
2. On Windows, `libuv` is also required, which is not explicitly mentioned in the vcpkg documentation.

#### Required vcpkg Installation

Ensure the following dependencies are installed using vcpkg:

**Linux:**
```bash
vcpkg install uwebsockets usockets zlib
```
**windows**
```powershell
vcpkg install uwebsockets usockets zlib libuv
```

**cmake**
```cmake
# Find uSockets library
find_library(USOCKETS_LIBRARY NAMES uSockets)

if(USOCKETS_LIBRARY)
    message(STATUS "Detected uSockets library: ${USOCKETS_LIBRARY}")
else()
    message(FATAL_ERROR "uSockets library not found")
endif()

# Find uWebSockets header files
find_path(UWEBSOCKETS_INCLUDE_DIRS "uwebsockets/App.h")

# Find zlib
find_package(ZLIB REQUIRED)

# Add executable
add_executable(cws ${SOURCES})
target_link_libraries(cws PRIVATE ZLIB::ZLIB ${USOCKETS_LIBRARY})
target_include_directories(cws PRIVATE ${UWEBSOCKETS_INCLUDE_DIRS})

# Windows-specific configuration
if(WIN32)
    find_package(libuv CONFIG REQUIRED)
    target_link_libraries(cws PRIVATE $<IF:$<TARGET_EXISTS:libuv::uv_a>,libuv::uv_a,libuv::uv>)
endif()

# Precompiled headers (optional)
target_precompile_headers(cws PRIVATE src/inc/pch.h)
```

**Comment by uNetworkingAB** [comment]
I don't know what to do about this. I don't control what Microsoft does with the lib. I have tested vcpkg and it worked fine for me. Maybe not flawless but it's pretty simple. I'm closing this, as there is nothing here to do.
