### ISSUE TITLE
Segmentation fault on std::make_unique<uWS::App>();

### ISSUE THREAD

**Issue by maldag** [uNetworking/uWebSockets#1816]
If the `uWS::App` is default-constructed, an empty `options ` object is being generated.
If I just create this object and destroy it afterwards without issueing `run()`, I'll get an segmentation fault in `us_internal_loop_unlink`, because the given `context` object still uses `nullptr` which was the default initialization.
The construction part seems fine to me, I don't think the pointer dereference in `us_internal_loop_unlink` is well done. The error arises in line `context->prev->next = context->next;` where `prev` is nullptr.

Is there an easy way to use the `uWS::App` Object without segmentation fault?

```
  TemplatedApp(SocketContextOptions options = {}) {
        httpContext = HttpContext<SSL>::create(Loop::get(), options);

        /* Register default handler for 404 (can be overridden by user) */
        this->any("/*", [](auto *res, auto */*req*/) {
		    res->writeStatus("404 File Not Found");
	        res->end("<html><body><h1>File Not Found</h1><hr><i>uWebSockets/20 Server</i></body></html>");
        });
    }
```

```
/* Unlink is called before free */
void us_internal_loop_unlink(struct us_loop_t *loop, struct us_socket_context_t *context) {
    if (loop->data.head == context) {
        loop->data.head = context->next;
        if (loop->data.head) {
            loop->data.head->prev = 0;
        }
    } else {
        context->prev->next = context->next;
        if (context->next) {
            context->next->prev = context->prev;
        }
    }
}
```

**Comment by uNetworkingAB** [comment]
How do you mean? I can't trigger anything.

alexhultman@Windows11:~/uWebSockets$ valgrind ./HelloWorld
==5251== Memcheck, a memory error detector
==5251== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==5251== Using Valgrind-3.22.0 and LibVEX; rerun with -h for copyright info
==5251== Command: ./HelloWorld
==5251== 
==5251== 
==5251== HEAP SUMMARY:
==5251==     in use at exit: 0 bytes in 0 blocks
==5251==   total heap usage: 26 allocs, 26 frees, 636,216 bytes allocated
==5251== 
==5251== All heap blocks were freed -- no leaks are possible
==5251== 
==5251== For lists of detected and suppressed errors, rerun with: -s
==5251== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

**Comment by uNetworkingAB** [comment]
This code is incomplete. I need a minimal reproducer in full

**Comment by maldag** [comment]
Please try this one:

```
#include <functional>
#include <future> // needed for std::Async case
#include <memory>
#include <iostream>

class c_UWSServer final {
public:
  explicit c_UWSServer(std::unique_ptr<uWS::App> server);
  virtual ~c_UWSServer() = default;
  static std::unique_ptr<c_UWSServer> CreateApiServer(int port);
private:
  std::unique_ptr<uWS::App> uWebSocketApp_;
};
std::unique_ptr<c_UWSServer> c_UWSServer::CreateApiServer(int port) {

  std::cout << "compile time: " << __DATE__ << " : " << __TIME__ << '\n';
  std::cout << "Test createApiServer" << '\n';
  auto        uws  = std::make_unique<uWS::App>();
  const auto *root = "./";
  uws->get("/*", [](auto *res, auto *) {
    std::cout << "Root node reached" << '\n';
    res->end(R"({"name":"Hello World!"})");
  });
  uws->listen(port, [port, root](auto *token) {
    if(token) {
      std::cout << "Serving " << root << " over HTTP a " << port << '\n';
    }
  });
  return std::make_unique<c_UWSServer>(std::move(uws));
}

int main()
{
  int const port = 3000;
  //c_UWSServer::CreateApiServer(port);  

  auto      uut  = std::async(std::launch::async, c_UWSServer::CreateApiServer, port); // Will give segmentation fault
  uut.wait();
}
```
I imported it on godbolt but don't have your libraries there running. This is the stuff I tried.

**Comment by uNetworkingAB** [comment]
This code doesn't even compile. I'll give you one more try before I close this.

**Comment by uNetworkingAB** [comment]
> of course it didn't compile as I sad because it doesn't include your lib.

I know. I included it. It still doesn't even compile because you still haven't provided a complete reproducer:

/usr/bin/ld: /tmp/cclwO60X.ltrans0.ltrans.o: in function `c_UWSServer::CreateApiServer(int)':
<artificial>:(.text+0xaab2): undefined reference to `c_UWSServer::c_UWSServer(std::unique_ptr<uWS::TemplatedApp<false>, std::default_delete<uWS::TemplatedApp<false> > >)'
collect2: error: ld returned 1 exit status
make: *** [GNUmakefile:7: examples] Error 255

If you can give me a reproducer, I will look at it. So far, none of the code you sent me even compiles. I am not here to sit and try and figure out what you meant, you either give me a clean reproducer and I will fix the issue in the library or you don't, and I won't look at it.

**Comment by maldag** [comment]
I don't think the status is "completed" here. I tried to get a working example running which is easy to compile. So I checked out your git repo, followed the given manual and added a new cpp-file in your tests directory. But there is no chance in a limited amout of time to get it to compile because uWebsockets depends on other packages that are not easily integrated.
I thought there would be a CMakeLists.txt or Makefile (GNUmakefile) to get the project running, but apparently there are some Makefiles and I always got stucked somewhere.

So here is my code example:

```
// Content of tests/DefaultConstructible.cpp
#include "../src/App.h"

class c_UWSServer final {
public:
  explicit c_UWSServer(std::unique_ptr<uWS::App> server) : uWebSocketApp_(std::move(server)) {};
  ~c_UWSServer() = default;
  void Run() const { uWebSocketApp_->run(); };

  std::unique_ptr<uWS::App> uWebSocketApp_;
};
std::unique_ptr<c_UWSServer> CreateApiServer(int port) {

  std::cout << "compile time: " << __DATE__ << " : " << __TIME__ << '\n';
  std::cout << "Test createApiServer" << '\n';
  auto        uws  = std::make_unique<uWS::App>();
  const auto *root = "./";
  uws->get("/*", [](auto *res, auto *) {
    std::cout << "Root node reached" << '\n';
    res->end(R"({"name":"Hello World!"})");
  });
  uws->listen(port, [port, root](auto *token) {
    if(token) {
      std::cout << "Serving " << root << " over HTTP a " << port << '\n';
    }
  });
  return std::make_unique<c_UWSServer>(std::move(uws));
}
int main() {
  auto uut = CreateApiServer(3000); // NOLINT
  // Not calling Run will cause memory leak
  // uut->Run();
}
```

So I built another one without the unique_ptr thing:

```
// Content of: DefaultConstructibleNoUniquePtr.cpp
#include "../src/App.h"

int main() {
  const int port = 3000; // NOLINT
  std::cout << "compile time: " << __DATE__ << " : " << __TIME__ << '\n';
  std::cout << "Test createApiServer" << '\n';
  auto        uws  = std::make_unique<uWS::App>();
  const auto *root = "./";
  uws->get("/*", [](auto *res, auto *) {
    std::cout << "Root node reached" << '\n';
    res->end(R"({"name":"Hello World!"})");
  });
  uws->listen(port, [port, root](auto *token) {
    if(token) {
      std::cout << "Serving " << root << " over HTTP a " << port << '\n';
    }
  });
  // Not calling Run will cause memory leak
  // uws->run();
}
```

If I do run this example in my GTEST Project using conan and CMake and LLVM 19.1.4 with address sanitation activated, I get the following memory leak:

```
testDefaultConstructibleRMS6ApiAdaptor 
compile time: Dec  6 2024 : 14:07:35
Test createApiServer
Serving ./ over HTTP a 3000

=================================================================
==197432==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x55e86136aa8f in malloc /tmp/usr/lib/llvm-project-19.1.4.src/llvm-project-19.1.4.src/compiler-rt/lib/asan/asan_malloc_linux.cpp:68:3
    #1 0x55e8613f6c28 in us_socket_context_listen /root/.conan/data/usockets/0.8.8/_/_/build/8cc07c837d102b0094fe2078ee6886261aa5af08/src/src/context.c:266:27

SUMMARY: AddressSanitizer: 80 byte(s) leaked in 1 allocation(s).
```

Or without the UniquePtr:

```
testDefaultConstructibleNoUniquePtrRMS6ApiAdaptor 
compile time: Dec  6 2024 : 14:07:35
Test createApiServer
Serving ./ over HTTP a 3000

=================================================================
==197494==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x559383936a8f in malloc /tmp/usr/lib/llvm-project-19.1.4.src/llvm-project-19.1.4.src/compiler-rt/lib/asan/asan_malloc_linux.cpp:68:3
    #1 0x5593839c2328 in us_socket_context_listen /root/.conan/data/usockets/0.8.8/_/_/build/8cc07c837d102b0094fe2078ee6886261aa5af08/src/src/context.c:266:27

SUMMARY: AddressSanitizer: 80 byte(s) leaked in 1 allocation(s).
```

Compiling both with the commented out codepiece calling the `run()` Method, the app will wait for connections (which it should). When I send [CTRL+C] to the process in the console the application quits correctly.

So the mere question now would be: What happens when `run()` will be called an why is there a memory leak if``run()` is not being called (which I didn't in my GTEST cases)

**Comment by maldag** [comment]
Thanks for your comment to this. I did some more tracing and added a new ticket in uSockets where the segmentation fault is happenning. https://github.com/uNetworking/uSockets/issues/233
