### ISSUE TITLE
HttpResponse::tryEnd relies on evaluation order

### ISSUE THREAD

**Issue by rafalwijata** [uNetworking/uWebSockets#1827]
which is unspecified - https://en.cppreference.com/w/cpp/language/eval_order
thus hasResponded() may come from before or after calling internalEnd(...)

**Comment by uNetworkingAB** [comment]
Can you link where in code?

Den mån 30 dec. 2024 08:30Rafal W ***@***.***> skrev:

**Comment by rafalwijata** [comment]
https://github.com/uNetworking/uWebSockets/blob/d31eb40c98e1db71357702abf809329d4adbe76b/src/HttpResponse.h#L439

**Comment by uNetworkingAB** [comment]
Great, post more if you find
