### ISSUE TITLE
Is there Socks5 or Socks4 proxy support?

### ISSUE THREAD

**Issue by NuclearC** [uNetworking/uWebSockets#310]
Can I use this client to connect to server through SOCKS5 or SOCKS4 proxy?

**Comment by alexhultman** [comment]
No idea. You tell me 😜

**Comment by SEAPUNK** [comment]
Reading on SOCKS, it's a general purpose TCP proxy, so yeah, it should, if you know what you're doing.

**Comment by alexhultman** [comment]
I also read a little bit and since it seems to be below the application level I can't see how this wouldn't work as long as there's no magic setting missing.

**Comment by nuclearc** [comment]
so I made SOCKS5 client for WSA Sockets, but i have no idea in UWS where to put it. It must be after connecting to WebSocket server but before WebSocket handshake

**Comment by alexhultman** [comment]
This server is built directly ontop of the BSD socket interface so if anything needs to be done it should be as simple as any other regular TCP client. Networking lives in Node and Socket components.

**Comment by nuclearc** [comment]
btw is there any client examples for C++?

**Comment by alexhultman** [comment]
Okay I see. Any socks client has to implement some kind of handshake at application level? If so, then no this is not supported. I guess most users use nginx, which works perfectly fine.

**Comment by alexhultman** [comment]
You can take a look in the tests folder for examples

**Comment by nuclearc** [comment]
so no Socks5 proxy? :(

Thanks anyway.

**Comment by alexhultman** [comment]
You could give WebSocket++ a try, maybe they have support.

**Comment by nuclearc** [comment]
they have only HTTP, not SOCKS5 or SOCKS4

**Comment by alexhultman** [comment]
Maybe most ppl arent aware of socks then? From reading about it it seems far better than http proxying but then we know from the history that backend devs often take the simple solution rather than the better one

**Comment by nuclearc** [comment]
yeah... but for my project HTTP proxy sucks.....

**Comment by alexhultman** [comment]
Yes http proxying is mindblowingly retarded and incredibly inefficient. Http is probably one of the most inefficient protocols ever designed, and with http proxying you parse the http twice. Its just so incredibly bad.

**Comment by alexhultman** [comment]
My first encounter with any kind of (professional) backend development was in 2014 and I was in jaw dropping mode pretty much the entire time. The current backend scene is just so fuvked up that you cannot even wrap your head around how bad it is. It's as if someone really tried their hardest in designing the worst things they could imagine.

**Comment by henopied** [comment]
@alexhultman For the node.js interface could there be a way to use agents like in `ws`. I understand you do not aim for the same api as `ws` but it would be nice to have agent support. There are some node.js modules like `socks` that could work if there was agent support.

**Comment by socmag** [comment]
"Proactor Model" - tbh that's pretty funny.

The model is you do something, and you get called back on any waiting
thread when the operation completes.

That, to me, is a pretty simple and intuitive model.  Thread agnostic and
scalable.

**Comment by socmag** [comment]
There are samples for C++.  It's trivially easy and intuitive as compared
to most other C++ libraries from my personal experience, and compared with
other C++ ws libraries

**Comment by socmag** [comment]
Full disclosure - full-time development on Linux here... *nix platforms I
grew up on 25+ years ago, but still somewhat fucked up w.r.t the model.

epoll, kpoll, libuv... seriously how many attempts does it take to get to
IOCP?

otoh - perf is great and working fine :)

**Comment by socmag** [comment]
Well I don't know about that... at least on Windows, async programming
primitives have been the mainstay for at least 20 years and not at all
fucked up. As an observer it has been somewhat frustrating waiting for
cross-platform IO solutions that are lightweight and makes sense.  Sure, we
have Boost ASIO now, and I'm very glad they went with the proactor model,
it should never have been a question. The downside of Boost is the size of
the runtime and the perf overhead of the abstraction (IMHO).

I think you have been making  the right choices Alex with regard to
perf/complexity.  I'm pretty happy

**Comment by alexhultman** [comment]
@socmag You drunk?

**Comment by socmag** [comment]
Getting there...

Abandoning twenty years of indoctrinated wisdom regarding server topology
takes some readjustment.

I even built an award winning HTTP server with IOCP at some point. Fuck me,
how idiotic.

I feel like I've been brainwashed and duped by conventional wisdom,  but
I'm very happy to at last be doing it right finally.

I've seen the light, so thank you.  Server has been and continues to run
great.

Pfft

**Comment by alexhultman** [comment]
What's the deal with these random comments on closed issues lol wtf

**Comment by socmag** [comment]
Huh

I was was replying to *your* question

On Oct 28, 2016 7:02 PM, "Alex Hultman" <notifications@github.com> wrote:

What's the deal with these random comments on closed issues lol wtf

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/uWebSockets/uWebSockets/issues/310#issuecomment-256973908>,
or mute the thread

**Comment by alexhultman** [comment]
Lol IOCP still requires the copy from kernel buffer to user space buffer. The only difference with epoll is the copy is performed by the user space and the copy is performed from the kernel space with IOCP. They both require the same amound of CPU time in copying operations, while epoll enables you to far outscale the IOCP model since you can share memory. At least that is my opinion about this.

**Comment by alexhultman** [comment]
When I began this project I had one single goal and that was the memory scalability. Then I just happened to realize that "holy shit, this actually does outperform the other servers even when it comes to throughput". So the most important part of this project has always been memory scalability, not throughput. But yeah, that came as a bonus.

**Comment by alexhultman** [comment]
That's why it is called MicroWebSockets, not SpeedyWebSockets :wink:

**Comment by socmag** [comment]
Uhhuh I'm a geek as well. :-)

The reuse port thing is pure gold by the way.

Anyway, I won't comment further on this closed issue.

This library rocks is all I can say.

**Comment by alexhultman** [comment]
Lol it's just that Gitter is probably the better place for random discussions. That also includes my own random ramblings and rants :+1:

**Comment by NuclearC** [comment]
maybe someone will find a way to implement this someway idk
