### ISSUE TITLE
Listening on UNIX domain socket

### ISSUE THREAD

**Issue by samandj15** [uNetworking/uWebSockets#427]
It would be great to add support for UNIX domain Socket. libuv supports UDS (uv_pipe_init and uv_pipe_bind). it seems that Node.h needs some changes.

**Comment by shaharmor** [comment]
Any timeline for this?

**Comment by nikolaydimitrov** [comment]
Hi @alexhultman,

Thanks for the great library!
I would also like to use UNIX domain sockets, and it seems for next release you are moving to uSocket? Does that mean the support will be added that way?

Cheers

**Comment by alexhultman** [comment]
@nikolaydimitrov Hi,

I don't have any plan really, we'll have to see what happens. It should be easier to add things when the lib is split into two parts though.

**Comment by nikolaydimitrov** [comment]
I think it could be useful when used behind nginx or something like that.

**Comment by alexhultman** [comment]
So the idea and the reason why people want this is to improve performance? Have any of you benchmarked this? In my tests, NGINX is the bottleneck. Not TCP, not unix sockets, not µWS, but NGINX itself. Remove it and you can get 4x the throughput (even with TCP sockets).

**Comment by alexhultman** [comment]
You can outperform NGINX by multiple 100s of % with a simple TCP load balancer and a µWS server listening to localhost. If you find a good load balancer it will almost have 0 overhead. I recently benchmarked this and found that this balancer: https://github.com/codership/glb is seriously fast compared to NGINX. By having a simple TCP load balancer you can also distribute the cost of SSL over multiple processes instead of having the load balancer itself encrypt/decrypt everything. NGINX is a good brand but the product is highly overrated.

**Comment by alexhultman** [comment]
I mean sure, you can have NGINX as the load balancer with multiple µWS processes. Then you swap to Unix sockets to improve perf somewhat (according to theory, I'm pretty sure it won't improve anything).

But if you really want performance you should not even have any kind of IPC whatsoever on the local machine. You should just have 1 process of µWS listen to 1 port using REUSE_PORT and have multiple threads (1 per core) have 1 hub each. Then you get performance. This is how the lib is meant to be used. Look at the multithreading example, it has this design.

**Comment by nikolaydimitrov** [comment]
Yes, that would be the best scenario.
But in my case, an nginx module is what I'm actually building and obviously I can't get rid of nginx.. Also, they have to live on the same server and share a lot of code, so my idea is to start a uWebSockets thread within nginx process and make them communicate over unix domain sockets or TCP (use nginx as a websockets proxy).

The thing is that port 80/443 are taken by nginx and also I don't want to decouple things more. 
The best approach in my case would be to "proxy" data between nginx and uWebSockets but I couldn't find a way to plug that in. Basically, I want to use your library not based on sockets but on data packets. Any ideas?

**Comment by alexhultman** [comment]
Ah,

Okay but currently the code is a mess when it comes to networking (mixed all over, no clean separation between TCP and WebSockets). In 0.15 with µSockets and µWebSockets being 2 separate libraries you could easily emulate the µSockets layer. But yeah, currently that is not possible and I don't have any plan when 0.15 will be done, if ever.

**Comment by nikolaydimitrov** [comment]
Thanks for the replies and hope you get some free time to complete 0.15 :-)

**Comment by alexhultman** [comment]
Yep me to, thanks.
