### ISSUE TITLE
request headers usage in frameworks

### ISSUE THREAD

**Issue by pkoretic** [uNetworking/uWebSockets#590]
* What version of uws are you using?
  * master
* What features of µWS are involved in the issue?
  * Server support (HTTP)
* How does the issue reproduce?
  * All the time
* Can you show me some short code that triggers your issue or any other important information?

```
const http = require('uws').http
const Koa = require('koa')
const conditional = require('koa-conditional-get')

const app = new Koa()

app.use(conditional())

app.use(ctx => {
    ctx.body = 'Hello World!'
})

http.createServer(app.callback()).listen(8000)
```
this triggers
`Warning: req.headers usage past request handler is not supported!` because of koa-conditional-get module

koa (among others) is a framework that bundles middlewares with a downstream/upstream flow where you have code that does processing before response and after
so request headers do get used in responses as it doesn't make sense to allocate all variables for potential usage in response before downstream code is actually called
there is probably bunch of other modules with the same "issue"

https://github.com/koajs/conditional-get/issues/9

**Comment by alexhultman** [comment]
I don't know what you mean by upstream and downstream but that warning is not a bug. It simply warns about invalid usage of uws. Web libraries should run their chain of middleware inside the request handler of uws, and then either respond within that function (fast) or respond outside it (potentially slow). But you know it is almost pointless to run Koa or Express on uws as these libraries bottleneck any advantage. There are other libs like Aero.js which operate 50x faster but that project is stalled and has no contact available.

**Comment by pkoretic** [comment]
well koa seems fastest of the other frameworks when using uws.http judging from https://github.com/hbakhtiyor/node-frameworks-benchmark
at least three times faster than when using node's http so I would want to try it

**Comment by alexhultman** [comment]
Maybe you'll have a better try with this zeit/micro thing. I get 16k req/sec with it and 72k with uws as the http server. zeit/micro is however just a silly rebranding of Node.js's own vanilla http module since it doesn't really do anything.

**Comment by alexhultman** [comment]
I get 100k without any zeit/micro so it is not a zero-cost wrapper.

**Comment by pkoretic** [comment]
interesting, plain uws.http without abstractions interests me the most of course

for now I would like to migrate our current koa stack from node http to uws but I've hit this issue with few modules so decided to report and see where we get from there

**Comment by alexhultman** [comment]
Well the uws.http thing is not further developed at this point. It has more of a gimmick status right now. If anyone wants things done with it we are talking cash for code here. Otherwise I don't have any plan to finish it up.

**Comment by daliwali** [comment]
Care to elaborate on what makes it gimmicky and not ready for production use?

**Comment by alexhultman** [comment]
Streaming is broken, no SSL, "Connection: close" ignored, somewhat broken out of order response, and finally tons and tons of Node.js balancing between compatibility and perf
