### ISSUE TITLE
Test suite fails on ubuntu 17.04  clean install

### ISSUE THREAD

**Issue by ampyx** [uNetworking/uWebSockets#599]
* What operating system are you running?
  Ubuntu 17.04 fresh install
  -libboost-dev-all 1.62.0.1
  -libuv (from source or from apt repos results in same issue)
* Are you running any CPU architechute out of the normal?
  * I run 64-bit in the year 2017
  7700K intel i7
* What platform/language are you using?
  * C++
* What version of uws are you using?
  * master
* What features of µWS are involved in the issue?
  * Server support (WebSocket)
  * Client support (WebSocket)
  * Server support (HTTP)
* How does the issue reproduce?
  * All the time
* Can you show me some short code that triggers your issue or any other important information?
 Running the testsuite by
make
make install
make tests
./testsBin

Results in:
```bash
SSL: 1
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.0108696 echoes/ms (92 ms elapsed)
POSTing 0 bytes
POSTing 1000000 bytes
POSTing 2000000 bytes
POSTing 3000000 bytes
POSTing 4000000 bytes
POSTing 5000000 bytes
POSTing 6000000 bytes
POSTing 7000000 bytes
POSTing 8000000 bytes
POSTing 9000000 bytes
FAILURE: expectedRequests differ: 0

```

**Comment by alexhultman** [comment]
Maybe you are running other servers or multiple instances of the test? It looks very weird, those "POSTing"s should block until finished and it should print stuff in between. I just ran the test and everything finished as it should.

**Comment by irondune** [comment]
Same results as OP, same conditions except:

* Linux Mint 17.3 (Ubuntu 14.04.5)
* Intel(R) Core(TM) i7 CPU         870  @ 2.93GHz
* NO libboost-dev-all

**Comment by yaoyinbear** [comment]
Same results as @ampyx , same conditions except:

- Aliyun CentOS 6.7
- NO libboost-dev-all

**Comment by yaoyinbear** [comment]
Once I comment testHTTP() in the test suite, all the reset test can be passed.

```
int main(int argc, char *argv[])
{
    //serveEventSource();
    //serveHttp();
    //serveBenchmark();

#ifdef UWS_THREADSAFE
    testThreadSafety();
#endif

    // These will run on Travis OS X
    testReceivePerformance();
    testStress();
    //testHTTP();
    testSmallSends();
    testSendCallback();
    testRouting();
    testClosing();
    testListening();
    testBroadcast();
    testMessageBatch();
    testAutoPing();
    testConnections();
    testTransfers();

    // Linux-only feature
#ifdef __linux__
    testReusePort();
#endif

    //testAutobahn();
}
```

# ./testsBin 
Messages per microsecond: 35.456
Messages per microsecond: 35.4761
Messages per microsecond: 35.6722
Messages per microsecond: 35.7641
Messages per microsecond: 35.7462
Messages per microsecond: 35.6519
Messages per microsecond: 35.6608
Messages per microsecond: 35.7373
Messages per microsecond: 35.7245
Messages per microsecond: 35.7003
Messages per microsecond: 35.5834
Messages per microsecond: 35.7424
Messages per microsecond: 35.6952
Messages per microsecond: 35.671
Messages per microsecond: 35.6443
Messages per microsecond: 35.6812
Messages per microsecond: 35.6837
Messages per microsecond: 35.7003
Messages per microsecond: 35.5581
Messages per microsecond: 35.7411
Messages per microsecond: 35.6786
Messages per microsecond: 35.0165
Messages per microsecond: 35.5518
Messages per microsecond: 35.6773
Messages per microsecond: 35.6532
Messages per microsecond: 35.5821
Messages per microsecond: 35.7105
Messages per microsecond: 35.1815
Messages per microsecond: 35.1791
Messages per microsecond: 35.6786
Messages per microsecond: 35.6926
Messages per microsecond: 35.3794
Messages per microsecond: 34.4495
Messages per microsecond: 35.4158
Messages per microsecond: 35.6354
Messages per microsecond: 35.6633
Messages per microsecond: 35.6608
Messages per microsecond: 35.7015
Messages per microsecond: 35.6341
Messages per microsecond: 35.4635
Messages per microsecond: 35.7322
Messages per microsecond: 35.7079
Messages per microsecond: 35.6824
Messages per microsecond: 35.5417
Messages per microsecond: 35.6481
Messages per microsecond: 35.6595
Messages per microsecond: 35.6392
Messages per microsecond: 35.671
Messages per microsecond: 35.6646
Messages per microsecond: 35.6608
Messages per microsecond: 35.6659
Messages per microsecond: 35.5556
Messages per microsecond: 35.6595
Messages per microsecond: 35.6875
Messages per microsecond: 35.699
Messages per microsecond: 35.6977
Messages per microsecond: 35.7513
Messages per microsecond: 35.6265
Messages per microsecond: 35.6227
Messages per microsecond: 35.5051
Messages per microsecond: 35.6964
Messages per microsecond: 35.4635
Messages per microsecond: 35.6392
Messages per microsecond: 35.7309
Messages per microsecond: 35.6888
Messages per microsecond: 35.6481
Messages per microsecond: 35.6608
Messages per microsecond: 35.6824
Messages per microsecond: 35.3444
Messages per microsecond: 35.6722
Messages per microsecond: 34.5018
Messages per microsecond: 35.7539
Messages per microsecond: 35.7449
Messages per microsecond: 35.5973
Messages per microsecond: 35.699
Messages per microsecond: 35.759
Messages per microsecond: 35.7782
Messages per microsecond: 35.7833
Messages per microsecond: 35.7948
Messages per microsecond: 35.7743
Messages per microsecond: 35.8012
Messages per microsecond: 35.8038
Messages per microsecond: 35.7398
Messages per microsecond: 35.8038
Messages per microsecond: 35.7833
Messages per microsecond: 35.7871
Messages per microsecond: 35.7923
Messages per microsecond: 35.7923
Messages per microsecond: 35.7705
Messages per microsecond: 35.7807
Messages per microsecond: 35.7679
Messages per microsecond: 35.7679
Messages per microsecond: 35.8025
Messages per microsecond: 35.7897
Messages per microsecond: 35.7641
Messages per microsecond: 35.7859
Messages per microsecond: 35.7679
Messages per microsecond: 35.7807
Messages per microsecond: 35.7846
Messages per microsecond: 35.7846
[Size: 1, echoes: 1]
SSL: 0
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Too small load!
SSL: 1
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.0769231 echoes/ms (13 ms elapsed)
[Size: 2, echoes: 1]
SSL: 0
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Too small load!
SSL: 1
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.0769231 echoes/ms (13 ms elapsed)
[Size: 4, echoes: 1]
SSL: 0
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Too small load!
SSL: 1
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.0769231 echoes/ms (13 ms elapsed)
[Size: 8, echoes: 1]
SSL: 0
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Too small load!
SSL: 1
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.0769231 echoes/ms (13 ms elapsed)
[Size: 16, echoes: 1]
SSL: 0
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Too small load!
SSL: 1
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.0769231 echoes/ms (13 ms elapsed)
[Size: 32, echoes: 1]
SSL: 0
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Too small load!
SSL: 1
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.0769231 echoes/ms (13 ms elapsed)
[Size: 64, echoes: 1]
SSL: 0
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Too small load!
SSL: 1
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.0769231 echoes/ms (13 ms elapsed)
[Size: 128, echoes: 1]
SSL: 0
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Too small load!
SSL: 1
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.0769231 echoes/ms (13 ms elapsed)
[Size: 256, echoes: 1]
SSL: 0
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Too small load!
SSL: 1
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.0769231 echoes/ms (13 ms elapsed)
[Size: 512, echoes: 1]
SSL: 0
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Too small load!
SSL: 1
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.0769231 echoes/ms (13 ms elapsed)
[Size: 1024, echoes: 1]
SSL: 0
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Too small load!
SSL: 1
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.0769231 echoes/ms (13 ms elapsed)
[Size: 2048, echoes: 1]
SSL: 0
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Too small load!
SSL: 1
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.0714286 echoes/ms (14 ms elapsed)
[Size: 4096, echoes: 1]
SSL: 0
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Too small load!
SSL: 1
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.0769231 echoes/ms (13 ms elapsed)
[Size: 8192, echoes: 1]
SSL: 0
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Too small load!
SSL: 1
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.0769231 echoes/ms (13 ms elapsed)
[Size: 16384, echoes: 1]
SSL: 0
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Too small load!
SSL: 1
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.0666667 echoes/ms (15 ms elapsed)
[Size: 32768, echoes: 1]
SSL: 0
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Too small load!
SSL: 1
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.0666667 echoes/ms (15 ms elapsed)
[Size: 65536, echoes: 1]
SSL: 0
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Too small load!
SSL: 1
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.0714286 echoes/ms (14 ms elapsed)
[Size: 131072, echoes: 1]
SSL: 0
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Too small load!
SSL: 1
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.0625 echoes/ms (16 ms elapsed)
[Size: 262144, echoes: 1]
SSL: 0
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 1 echoes/ms (1 ms elapsed)
SSL: 1
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.0588235 echoes/ms (17 ms elapsed)
[Size: 524288, echoes: 1]
SSL: 0
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.333333 echoes/ms (3 ms elapsed)
SSL: 1
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.047619 echoes/ms (21 ms elapsed)
[Size: 1048576, echoes: 1]
SSL: 0
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.166667 echoes/ms (6 ms elapsed)
SSL: 1
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.0333333 echoes/ms (30 ms elapsed)
[Size: 2097152, echoes: 1]
SSL: 0
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.0714286 echoes/ms (14 ms elapsed)
SSL: 1
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.0208333 echoes/ms (48 ms elapsed)
[Size: 4194304, echoes: 1]
SSL: 0
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.0344828 echoes/ms (29 ms elapsed)
SSL: 1
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.0104167 echoes/ms (96 ms elapsed)
[Size: 8388608, echoes: 1]
SSL: 0
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.0123457 echoes/ms (81 ms elapsed)
SSL: 1
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.00578035 echoes/ms (173 ms elapsed)
[Size: 16777216, echoes: 1]
SSL: 0
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.00666667 echoes/ms (150 ms elapsed)
SSL: 1
CLIENT CLOSE: 1000
SERVER CLOSE: 1000
Throughput: 0.0030581 echoes/ms (327 ms elapsed)
Connected, will send small messages now
Falling through testSmallSends
Correct data was sent to send callback
testRouting passed, falling through
Server recives terminate close code after terminating
Client gets terminated on first connection
Server receives correct close code after closing
Client gets closed on second connection with correct close code
Falling through after testClosing!
Server emits error listening to port 80 (permission denied)
Server listens to port 3000
Server emits error listening to port 3000 twice
Server falls through after group closes
Broadcasting & closing now!
Falling through now!
Received message from batch: hello
Received message from batch: world
PING
PONG
PING
PONG
PING
PONG
Client emitted error on invalid URI
Client emitted error on invalid protocol
Client emitted error on resolve failure
Client emitted error on poll error
Client emitted error on connection timeout (non-SSL)
Client emitted error on connection timeout (SSL)
Client established a remote connection over non-SSL
Client got disconnected with data: 0x8, code: 1000, message: <>
Client established a remote connection over SSL
Client got disconnected with data: 0x9, code: 1000, message: <>
Client emitted error on HTTP response without upgrade (non-SSL)
Client emitted error on HTTP response without upgrade (SSL)
Falling through testConnections
Message 1: first message here
Message 2: second message
Message 3: some broadcast here
Message 4: binary
Message 1: first message here
Message 2: second message
Message 3: some broadcast here
Message 4: binary
Falling through testMultithreading
Can listen to same port twice!
