### ISSUE TITLE
Discarded constness of closing message

### ISSUE THREAD

**Issue by jmergiel** [uNetworking/uWebSockets#600]
Hi,

In the disconnection handler we get passed a non-const message and its length. **Why is it not const?**
 I have (_apparently wrongly_) assumed that since it is not, then I am free to modify it, which I (successfully) have. The modification was adding a null-terminator ('\0') at message[length] as the buffer (for some reasons) contained more text. That's not a problem - it's what the length field is for, so I don't (and shouldn't) care what you store in there after the message. Sure, I was surprised to see some headers in there, but still - I'm given the length field for a reason. So I used it and all was fine.

But later I started using my own close messages and suddenly the application started crashing. I obviously defined my own messages as **static const** which leads to the problem. For remotely initiated closing the message is stored in some internal uWebSocket buffer (which you **CAN** modify). But for locally initiated closing you just _cast away the const and pass those strings to the callback_. And in my case, as it's static const, it is located on a read-only page. Writing **does NOT work** on them read-only pages...

I'm wondering why you chose to make it non-const? Is it supposed to be modifiable? And anyway, the current behavior is not entirely coherent - it's non-const, but still you can only modify it **sometimes** (depending on the type of the close).

I'd suggest simply making the message const which is probably what most people think of it anyway. Sure, you can just in-place construct an std::string from it (which I currently do), but that's one copy that is not really needed, if (like me) the only thing you do with it is printing. Obviously, if you do add the const, there will be no more adding the null-terminator in-place to just print it, so that copy will become inevitable, but at least the behavior becomes **coherent**.
Plus, once we get std::string_view it's going to be a perfect use case to actually skip that copy :)

Oh, and BTW: **great job**! This is the **_ONLY_** WebSocket library worthy of improving :)

P.S.
I'm talking about [this](https://github.com/uWebSockets/uWebSockets/blob/master/src/WebSocket.cpp#L255) cast in WebSocket.cpp@255:
`Group<isServer>::from(this)->disconnectionHandler(this, code, (char *) message, length)`

**Comment by alexhultman** [comment]
Hi,

Yes the idea is to allow modification (if you want to do some kind of in-place zero-copy parsing you should be able to). And yes you are allowed to put zero-terminator if you want to. Taking const and casting away it is wrong like you say, the close function should not take a const. I don't know why that is.

**Comment by jmergiel** [comment]
I understand. The only "problem" with the idea of begin able to modify it in-place is you don't know the underlying buffer's size. So if I want to append the null-terminator I am *assuming* the buffer has at least one more byte, but that **does not have to be the case**... So to make that scenario work there would have to be some sort of guarantee about the buffer size OR you would have to add the null-terminator internally within uWebSocket and allow only modifications within length. I'd say the latter is easier/better (and won't change the interface), but what do you think?

It's obviously trivial to disallow using const strings as parameters to the function, but that will mean people can no longer use string literals and I don't think that's a good idea. And I don't think people will like it :) Let's first agree upon the first issue and then "synchronize" the interface with it.


I'll create a PR when I fix this, no problem. After giving this a thought I think:
1. Removing const from close() is a bad idea, will break stuff for people
2. Adding some buffer size parameters etc. to the callback will break stuff for people

To make this all work together I would actually dispose of the "in-place modifiable feature" in favor of a const, yet (internally) null-terminated message. And if someone needs to modify it then they need to copy it. And for all others who just need to examine/log it things get less complicated. This will also break stuff for people, but I think for **a lot less** people.

What say you?

**Comment by alexhultman** [comment]
It is not that complex. You either remove or add const, as long as they both match. I prefer to have non-const to allow in-place modifications so simply removing const from close function would do. But this is kind of a non-issue - there are far bigger issues in the code and if I ever get around to finishing 0.15 there will be a major refactor. I'm not actively working on this project right now though.
