### ISSUE TITLE
uws.chat down

### ISSUE THREAD

**Issue by mvayngrib** [uNetworking/uWebSockets#601]
just thought you should know. In case this is location-related, I'm in the NY area

![image](https://cloud.githubusercontent.com/assets/83948/26123728/ec8509d6-3a49-11e7-8b5e-12817eddde2c.png)

**Comment by sam3d** [comment]
Why?

**Comment by alexhultman** [comment]
Various reasons. I haven't bothered fixing it. It was mostly filled with profanity and spam anyways. If anyone wants to put something on that domain you can do it.

**Comment by sam3d** [comment]
How would we go about doing that @alexhultman?

**Comment by alexhultman** [comment]
I don't know. If you want the uws.chat domain it's yours
