### ISSUE TITLE
[NodeJS question] TypeError: This handle type can't be sent

### ISSUE THREAD

**Issue by endel** [uNetworking/uWebSockets#605]
I'm dealing with NodeJS multiple processes and would like to send the socket handle to a different process by [`process.send(message, sendHandle)`](https://nodejs.org/api/child_process.html#child_process_child_send_message_sendhandle_options_callback)

AFAIK, this would be possible by sending a `net.Socket` instance in the `sendHandle` parameter. Is it possible to get the `net.Socket` handle from uWebSocket's `WebSocket` instance?

Thanks

**Comment by alexhultman** [comment]
No this is not supported

**Comment by endel** [comment]
@alexhultman thanks for your reply. Do you have any idea if it would be possible to have in uWS? If you can give me some direction I'd like to contribute by implementing this.

**Comment by alexhultman** [comment]
Is it possible in websockets/ws? It certainly is possible but I haven't considered per process concurrency.
