### ISSUE TITLE
Segmentation fault in the testsBin All the time

### ISSUE THREAD

**Issue by ZDzhao** [uNetworking/uWebSockets#608]
#0  0x00007f9c6b720b0b in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007f9c6b720b0b in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007f9c6bdfca0c in uWS::Hub::connect(std::string, void*, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > >, int, uWS::Group<false>*)
    () from /usr/lib/libuWS.so
#2  0x0000000000410c1d in testReceivePerformance() ()
#3  0x0000000000404789 in main ()

**Comment by alexhultman** [comment]
What platform is this on?
