### ISSUE TITLE
LIBUV/EPOLL usage

### ISSUE THREAD

**Issue by Yatekii** [uNetworking/uWebSockets#609]
* What operating system are you running?
  * Linux
* Are you running any CPU architechute out of the normal?
  * I run 32-bit in the year 2017
* What platform/language are you using?
  * C++
* Are you using SSL, if so, how?
  * SSL is not part of the equation
* What version of uws are you using?
  * master
* What features of µWS are involved in the issue?
  * Server support (WebSocket)
* How does the issue reproduce?
  * All the time

Hi!

I am now successfully using uWS and it's great. But today I had an issue that if I have a blocking onMessage() call (from a message I got and I am still working on it) and I get a second request (which can terminate the ongoing calculation in the first call to onMessage()), the second call will never occur. Am I missunderstanding something or is it intended that I cannot have multiple onMessages at the same time? I tried EPOLL and LIBUV.
Thanks for any advice :)

Best wishes
Yatekii

**Comment by alexhultman** [comment]
Yes exactly. You cannot have blocking code in the handlers because naturally, they block.

**Comment by Yatekii** [comment]
Ok so I don't understand what libuv(asyncio) does then :S Isn't it used to provide concurrent function calls? Do I simply have to implement that myself? I am sorry but as I understood it was that can in fact be asynchronous, but I must have been mistaken :) I will issue an async call then myself :) Thanks for the quick answer!

**Comment by alexhultman** [comment]
If you can handle my ranting you could read this: https://github.com/alexhultman/The-real-history-of-async-networking
