### ISSUE TITLE
Installation issue on Ubuntu 14.04

### ISSUE THREAD

**Issue by AakashKumarNain** [uNetworking/uWebSockets#612]
I cloned the repo and followed the instructions as given in the README file, but I ran into the following errors:

> make[1]: Entering directory `/home/nain/Pictures/Personal/PID Controller/uWebSockets'
> if [ -d "/usr/lib64" ]; then cp libuWS.so /usr/lib64/; else cp libuWS.so /usr/lib/; fi
> cp: not writing through dangling symlink ‘/usr/lib/libuWS.so’
> make[1]: *** [installLinux] Error 1
> make[1]: Leaving directory `/home/nain/Pictures/Personal/PID Controller/uWebSockets'
> make: *** [install] Error 2

Please help!!

**Comment by dulguunbatmunkh** [comment]
@AakashKumarNain I think the error log is not complete. Could you post the full log, so we can help.

**Comment by alexhultman** [comment]
Google is your friend. "not writing through dangling symlink"
