### ISSUE TITLE
Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system

### ISSUE THREAD

**Issue by kozlown** [uNetworking/uWebSockets#613]
Hi and sorry to post this issue which is in the FAQ but I don't find out what to do now to fix this.
I tried several times to reinstall it.

About my configuration : 
- gcc version 5.4.1
- ubuntu~16.04 (64bits)

And I use : 
- uws: "^0.14.5"
- NodeJS v6.9.2

**Comment by dulguunbatmunkh** [comment]
@kozlown Can you give us what you have tried so far? Like which commands have you used? I have recently cross compiled uWS successfully and maybe I can help you.

**Comment by kozlown** [comment]
I've only tried to remove and reinstall the npm module (npm remove --save uws/npm install --save uws). I didn't try to recompile manually because I don't really know how to do it.
I'm using webpack, but I don't think that this error comes from that.
Thx if you can help me.

**Comment by alexhultman** [comment]
You need to check with webpack how native modules should be handled. Report issues in webpack instead, it's their problem.

**Comment by kozlown** [comment]
Okay, I'll do that.
I tried to use the webpack loaders "node-loader" and "node-native-loader" but both doesn't fix the problem...

**Comment by alexhultman** [comment]
Then report an issue for those projects. I cannot and should not fix up their mistakes.

**Comment by cedvdb** [comment]
@kozlown how did you resolve this ?

**Comment by kozlown** [comment]
@cedvdb I didn't resolve it, I finally used ws, it doesn't really matter for the development phase because both works the same way, so you can use ws while this issue is not resolved, I've already wasted too much time trying to make it work on my machines (local & server)..
By the way, If you resolve it, I would be happy to know how you did !
