### ISSUE TITLE
Unable to access HttpRequest from onHttpData()

### ISSUE THREAD

**Issue by ng5** [uNetworking/uWebSockets#617]
`template <bool isServer>
void Group<isServer>::onHttpData(std::function<void(HttpResponse *, char *, size_t, size_t)> handler) {
    httpDataHandler = handler;
}`

Is HttpRequest parameter missing intentionally for a design choice.  This is required to process large POST request because control will be transferred to onHttpData() and I need to process the request after all packets are assembled.  Can't think of a better way other than hacks like storing copy of HttpRequest inside extraUserData of HttpResponse. 

Happy to make the change and send a PR. Please let me know if there is another way to solve this problem?

**Comment by ng5** [comment]
Looks like it was done for performance reason to cut down parsing headers on every data packet.

**Comment by alexhultman** [comment]
The intended flow of data is:

onHttpRequest -> read headers, decide where to go from here. optionally store whatever state you want to store by attaching it to the socket via setUserData.

onHttpData -> headers are no longer available, you need to rely on your stored state which you have determined from the onHttpRequest handler.

You shouldn't rely on internal variables, those should be private but I guess I missed some.

**Comment by ng5** [comment]
Great! thanks! I looked at the echo example and thought setUserData() is being used to assemble full request and so thought of using some thing else. I will change it from string to some custom data structure to store headers etc.

**Comment by alexhultman** [comment]
Yes you basically "extend" sockets with setUserData. So whatever data *you* need to keep you simply put in a struct and attach to the socket, it is very C-like.

**Comment by ng5** [comment]
I'm very close to build so called REST interface, also integrated with mongodb cxx library for a full fledged application. it was a breeze to use this library.  wrk benchmark numbers are so unreal.
