### ISSUE TITLE
Heisenberg bug while sending ArrayBuffer

### ISSUE THREAD

**Issue by mwmaleks** [uNetworking/uWebSockets#618]
When I send `new Uint8Array(...).buffer` via WebSocket it's randomly broken on uws side.
For example look at gist https://gist.github.com/mwmaleks/71b2ca65e5288c4a39b454bfd1d4728f
There are two arrays made with `toString` the difference ends after  `|` - delimiter

**Comment by alexhultman** [comment]
> Binary data is passed zero-copy as an ArrayBuffer. This means you need to copy it to keep it past the callback. It also means you need to convert it with Buffer.from(message) if you expect a Node.js Buffer.

**Comment by mwmaleks** [comment]
Seems, I do all the recommendations

**Comment by mwmaleks** [comment]
By the way, turn back to the ws solved the problem

**Comment by alexhultman** [comment]
I'm closing this, you need to fix up your end according to docs.
