### ISSUE TITLE
Question : is it safe to set  webSocketHead  httpSocketHead Group members as public ?

### ISSUE THREAD

**Issue by meiry** [uNetworking/uWebSockets#619]
General Question 
i want to do simple iteration on all clients that are connected to my server 
and do manipulation on them for example not to send to all of them response 
i want to implement it as simple as link list iterator :   
```
WebSocket<isServer> *webSocket0 h.getDefaultGroup<uWS::SERVER>()->webSocketHead
                 while (webSocket0 != nullptr)
		{
                        //DO STUFF HERE WITH webSocket0 
			webSocket0 = (WebSocket<isServer> *) webSocket0->next;
		}
```
The problem is that the webSocketHead is protected , so is it safe to move it to public ? 

also i notice you have the general ForEach loop on all the connected clients 
can you please explain why it have to be so complex ? why not just as above loop ?
Thanks

**Comment by alexhultman** [comment]
Group::forEach already implement what you want. They are a little messy but at least they handle deletions mid iteration. I don't see the issue here

**Comment by meiry** [comment]
i Don't what deletions 
i what to control which WebSocket connection to send and which not 
The ForEach are to general and over complex for my simple needs

**Comment by alexhultman** [comment]
If you don't want to listen then don't ask. You are free to do whatever you want. I'm not your mum. Don't come yelling when you break things like you have done before.
