### ISSUE TITLE
[NodeJS] modify/inspect headers on "upgrade"

### ISSUE THREAD

**Issue by endel** [uNetworking/uWebSockets#621]
I've had a look through the source code and some issues and couldn't find if this feature is available or not.

In `websockets/ws` it's possible to inspect/modify the headers by listening to the `"headers"` event: (https://github.com/websockets/ws/blob/master/doc/ws.md#event-headers)

```javascript
wss.on("headers", (headers) => {
    headers.push("Set-Cookie: data=1");
})
```

Is this possible to achieve this with `uws`?

**Comment by alexhultman** [comment]
Nope. But you don't really need to pass data using headers when you have a websocket connection. Just send whatever data you want to send as the first message.

**Comment by lpinca** [comment]
> But you don't really need to pass data using headers when you have a websocket connection.

You can't set `HttpOnly` cookies in this way.

**Comment by alexhultman** [comment]
Well that sucks I guess. I will probably not add any new features to the Node.js addon though, so you will have to do with what is there.

**Comment by endel** [comment]
Thanks @alexhultman, no worries, I just wanted to confirm if this is currently possible or not. If it **is** possible using C++ directly, maybe I can collaborate to implement this in the Node binding.

**Comment by alexhultman** [comment]
No it's not possible right now but I'm assuming https://www.goodgamestudios.com/ is where you want this? I can fix it in approx 1-2 working day(s) with contracting fee.
