### ISSUE TITLE
[Node.js] prepareMessage() doesn't exist

### ISSUE THREAD

**Issue by tonyka** [uNetworking/uWebSockets#622]
**OS** `linux 64 bit`
**uws** `0.14.5`
**Node** `v7.10.0`

```
var uws = require('uws').Server,
    wss = new uws({ port: 8000 });

wss.on("connection", function(ws) {
    var prep = wss.prepareMessage("test");
    ws.sendPrepared(prep);
    wss.finalizeMessage(prep);
});
```

Then, connect to it.

**Output**

`TypeError: wss.prepareMessage is not a function`

**Comment by alexhultman** [comment]
Looks like those functions are gone yes

**Comment by alexhultman** [comment]
No they have been moved to uws.native.prepareMessage and the like
