### ISSUE TITLE
Client: another client TCP socket in the same libuv loop

### ISSUE THREAD

**Issue by aldanor** [uNetworking/uWebSockets#624]
Hi,

This is more of a question than an issue with the library (which is superb, kudos for that) - would appreciate any hints; apologies in advance if this is a duplicate or is irrelevant (I've found https://github.com/uNetworking/uWebSockets/issues/265 but couldn't figure how to apply it to my case).

If I have a uWS client that is normally spawned via the blocking `Hub::run()` and runs the libuv event loop, is it possible to integrate another (non-websockets) tcp client socket into the same event loop? I would hate to have to synchronize things manually. Ideally, I'd like to have something like `on_message_uws()` and `on_read_other()` being called from one event loop (and also be able to send websockets messages through uws and raw tcp through the other one).

**Comment by alexhultman** [comment]
Hub::getLoop gives you the (shared) uv_loop_t pointer. You can use this in any other libuv project on the same thread.

**Comment by aldanor** [comment]
I see, thanks! However (IIUC) a pointer to `WebSocket` is only available in hub's callbacks, in this case would it be possible to call `WebSocket::send` from a callback triggered by a different handle?

**Comment by alexhultman** [comment]
Yes you can use websockets any time between onConnection and onDisconnection

**Comment by aldanor** [comment]
@alexhultman Thanks a million for your help!

(Closing the issue now -- hopefully it will be helpful to others too might they come across the same question.)
