### ISSUE TITLE
Reducing size of uws node_modules dependency

### ISSUE THREAD

**Issue by Flux159** [uNetworking/uWebSockets#626]
Hi, I was doing a check of my node_modules folder in a medium sized project and I'm using uws as a dependency of another dependency. Uws was one of the largest dependencies in my package.

I used the following command on Mac OS X to check this:
```
du -sm node_modules/* | sort -rn | head -n 20
```

I did a quick check to see why uws was taking up so much space by making a brand new project w/ only uws as a dependency and seeing what it produced:

```
mkdir uwstest
cd uwstest
npm install uws
```

With npm 5.0 this produced a lockfile that showed this:
```
{
  "lockfileVersion": 1,
  "dependencies": {
    "uws": {
      "version": "0.14.5",
      "resolved": "https://registry.npmjs.org/uws/-/uws-0.14.5.tgz",
      "integrity": "sha1-Z6rzPEaypYel9mZtAPdpEyjxSdw="
    }
  }
}
```

Checking the node_modules directory showed that uws ends up bundling a bunch of .node binary packages - most of which are not needed for my system.

```
> ls node_modules/uws/*.node
node_modules/uws/uws_darwin_46.node	node_modules/uws/uws_linux_47.node
node_modules/uws/uws_darwin_47.node	node_modules/uws/uws_linux_48.node
node_modules/uws/uws_darwin_48.node	node_modules/uws/uws_linux_51.node
node_modules/uws/uws_darwin_51.node	node_modules/uws/uws_win32_48.node
node_modules/uws/uws_darwin_57.node	node_modules/uws/uws_win32_51.node
node_modules/uws/uws_linux_46.node
```

I notice that in uws.js there's a native() function that determines which one to use and doesn't need all of them:

```
...
return require(`./uws_${process.platform}_${process.versions.modules}`);
...
```

I'm assuming that this was done to simply the build process, but seeing as how uws is now downloaded hundreds of thousands of times per month (according to npm stats: https://www.npmjs.com/package/uws), I was wondering if uws could download the appropriate bundle rather than packaging all the bundles into the npm package. 

Some basic research showed that npm doesn't seem to support this at all, but other projects like node_sass which do similar things don't end up downloading unnecessary binaries (see here for their releases: https://github.com/sass/node-sass/releases). 

Of course this would end up adding some publishing overhead and a script to determine which bundle to download, but it seems like that's a one time cost that would benefit a number of users.

**Comment by alexhultman** [comment]
This is an issue for NPM to solve. They need to build a service that actually works according to need.

**Comment by Flux159** [comment]
This seems like an issue that NPM is not willing to solve - at least right now. This is probably the reason that people end up using things like travis and appveyor + github for releasing binaries instead. 

You've already talked about this in a few other issues #54, #285, #401 and your issues with node-gyp and prebuild - not going to recommend using any of those since you're free to choose whatever build process you want, but I still think that its a valid issue to not bundle unnecessary binaries even if that means getting around NPM's limitations.

**Comment by alexhultman** [comment]
Not my problem. NPM's problem.

**Comment by Flux159** [comment]
Saw that you closed this, but FYI, I did end up getting this working through Travis CI, Appveyor, and Github releases and modifying the package.json install script in bindings/nodejs/dist/package.json.

The results are here:
https://www.npmjs.com/package/uws-light
https://github.com/Flux159/uWebSockets/releases

A few things to note:
- I ended up making a monorepo out of bindings and uWebSockets because everywhere I tried to do a git clone --recursive of the bindings repo I ended up with the following error:
```
git clone --recursive https://github.com/Flux159/bindings.git
Cloning into 'bindings'...
remote: Counting objects: 128, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 128 (delta 5), reused 18 (delta 4), pack-reused 105
Receiving objects: 100% (128/128), 31.64 KiB | 0 bytes/s, done.
Resolving deltas: 100% (57/57), done.
Submodule 'uWebSockets' (https://github.com/uWebSockets/uWebSockets.git) registered for path 'uWebSockets'
Cloning into '/Users/suyogsonwalkar/Projects/test/bindings/uWebSockets'...
remote: Counting objects: 4372, done.        
remote: Compressing objects: 100% (13/13), done.        
remote: Total 4372 (delta 0), reused 5 (delta 0), pack-reused 4359        
Receiving objects: 100% (4372/4372), 2.37 MiB | 1.69 MiB/s, done.
Resolving deltas: 100% (2827/2827), done.
error: no such remote ref 2e671fde42a13a9cfe0e87dd026ef6a6a25814b5
Fetched in submodule path 'uWebSockets', but it did not contain 2e671fde42a13a9cfe0e87dd026ef6a6a25814b5. Direct fetching of that commit failed.
```

I ended up just making a monorepo in https://github.com/Flux159/uWebSockets that combined the two codebases into a single repo to deal with the git submodules issues for now.

In any case, I only made changes in 6 files and was able to setup Continuous Integration and Deployment on tagging through Travis and Appveyor. A few notes:
- All 6 of these files are in the bindings repo - .appveyor.yml, .travis.yml, changed the package.json to point to an install.js script, and made slight changes to README.md and made a .gitignore
- No changes to the Makefile build system were done
- No prebuild, no node-pre-gyp or other build tool was added
- install.js just runs node-gyp install and uses curl or a powershell script to download the appropriate binary from Github. install.js needs a bit of cleanup (and a change in the ordering of commands since it will try to build first, then download - so a build will be overwritten if a download exists at the moment). Technically this adds a dependency to curl on linux and osx systems (which I'm not handling the error for right now in install.js, but this as I said, install.js needs a bit of cleanup). For windows it uses a powershell command that can download files if PowerShell / .NET 2.0 are available on the system (which Windows 7 packages by default).

I was able to get travis to auto deploy to npm on new tags being pushed to master as well. The results can be seen at https://www.npmjs.com/package/uws-light and https://github.com/Flux159/uWebSockets/releases

Note that I haven't extensively tested everything and I can't get my fork of bindings to work because of the submodules error above. The appveyor, travis, and install.js scripts have a bunch of comments at the moment explaining what's going on. I have a branch of bindings at https://github.com/Flux159/bindings that can show that.

Another thing that I noticed while doing this is that each of the builds on Linux that are currently packaged with npm in uws are about 0.5MB larger than the automated builds that Travis CI is building (~1.5MB vs ~1MB). This may be because I used g++-4.8 instead of g++-4.7, however that I'm not sure what's causing that discrepancy since I'm simply using the Makefile as instructed. 

I know you've had multiple discussions on this before, but wanted to reopen this since I don't think its exactly a 'cannot be fixed' type of issue. In addition, at the very least, adding CI / CD makes it easier to notice things like the 0.5MB discrepancy between Linux builds (I'm assuming that you build manually right now on your own system according to some of your other comments?).

**Comment by Flux159** [comment]
One more thing, if you want to view the builds that generated uws-light version 0.22.0, they are located here:
https://travis-ci.org/Flux159/uWebSockets/builds
https://ci.appveyor.com/project/Flux159/uwebsockets/history
