### ISSUE TITLE
have you considered separating out your benchmark tools?

### ISSUE THREAD

**Issue by victusfate** [uNetworking/uWebSockets#629]
I was looking around for an ab or wrk equivalent for websockets and artillery.io was suggested, but I'd love something higher performance to really stress test our servers for loadtest support

**Comment by alexhultman** [comment]
It can certainly be done but currently these benchmarks rely on libuv which is of course not acceptable anymore. If I could get time to get µSockets working the benchmarks could be ported over to it.

**Comment by victusfate** [comment]
oh what happened with libuv ? I didn't realize µSockets wasn't functioning.
