### ISSUE TITLE
Node.js v8.1.2 Docker image... Compilation of µWebSockets has failed

### ISSUE THREAD

**Issue by jondubois** [uNetworking/uWebSockets#630]
When I try to use the latest Node.js Docker image `8.1.2-slim` - I get the `Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.` error. This also happens with pretty much every Docker image for Node.js v8.x.x I could find.

What is strange is that everything works fine with `7.10.0-slim` and 6.x.x images too...  Maybe when they bumped up the Node.js version to 8.x.x they also downgraded the base OS/compiler :(
It seems like a strange thing to do.

I just wanted to check if this is something that should be taken up with Node.js team or if there is an easy fix on the uws side?

**Comment by jondubois** [comment]
@heiba I pushed a new Docker image `v5.15.0` - But this is Node.js `v7.10.0`.

Unfortunately, the base image for Node.js `v8.x.x-xxx` fails to compile uWS so I raised an issue here: https://github.com/uNetworking/uWebSockets/issues/630

It seems more like an issue on the Node.js side than uWS though. The upgrade to Docker image for Node.js v8 will have to wait until this issue is resolved.

**Comment by alexhultman** [comment]
You need to install a C++11 compiler. There is no prebuilt binary for Node.js 8 yet.

**Comment by jondubois** [comment]
The problem is with the Node.js Docker image itself so I can't swap out the compiler. I'll mention this issue on the Node.js repo.

**Comment by alexhultman** [comment]
apt-get update && apt-get install -y build-essential python

**Comment by jondubois** [comment]
I will try adding this command to the Dockerfile.

**Comment by alexhultman** [comment]
I will introduce a new version scheme like this:

"max version of node.js | version of uws | whatever patch is needed"

So next version will have precompiled binaries for Node.js 8 and will be v8.14.0 on NPM while the µWS project itself will be separate as 0.14.5. Then when Node.js 9 comes it bumps up.

**Comment by alexhultman** [comment]
Alright, v8.14.0 works out of the box in node:8.1.2-slim. It is a bit of an experimentation but so far it works without any issues (I swapped from GCC 5.1 to GCC 7.1).

**Comment by alexhultman** [comment]
Correction: uws 0.14.5 (NPM) is identical package as uws 8.14.0 (NPM) except for the added uws_linux_57.node (which is built with GCC 7 instead of GCC 5 like the other binaries). So it won't wreck anything old.

**Comment by jondubois** [comment]
@alexhultman Thanks, it works.

**Comment by ORESoftware** [comment]
can anyone get uWS to run on MacOS, and _how_?
