### ISSUE TITLE
HTTP POST - Random switch between onHttpRequest() and onHttpData() - chrome dev console

### ISSUE THREAD

**Issue by ng5** [uNetworking/uWebSockets#631]
C++ server, Linux Fedora 24, GCC 6.3.1
Hi,
This is most likely not an issue with library. I'm running into a weird issue when Hub is switching between onHttpRequest() and onHttpData(). I'm sending fixed 100 bytes payload via Http POST.  Problem appears to happen only when chrome dev console is enabled (Ctrl+Shift+J). When it switches to onHttpData() it causes significant delay in response.  both methods still receive 100 bytes so can't explain why it switches.

onHttpRequest() - Responds with-in 1ms 
onHttpData() - upto 250ms to respond

If not using chrome dev console - then everything is fine and goes to normal onHttpRequest() and responds with-in 1 ms. 

I've extensively tested the code with wrk stress test, it never goes to onHttpData() block for 100 bytes payload. However chrome dev console is causing something that forces server to switch randomly between onHttpRequest() and onHttpData(). 

Question for the forum is - has anyone come across this situation while using chrome  dev console. What could have caused the server to switch randomly?

I've tested this on 2nd computer too, just to be sure chrome on fedora is stable. Otherwise you can close this issue, I will carry on doing more profiling. 

Thanks a lot.

**Comment by alexhultman** [comment]
You cannot assume 100 byte will land as one onHttpRequest without any onHttpData. It depends on how TCP segments come in.

**Comment by ng5** [comment]
thanks a lot. yes, you're right. 250ms measurement was done on chrome dev console. Server side still responds with-in same < 1ms from both onHttpRequest() or onHttpData(). 

OK, I will close the issue in 1 or 2 days, unless someone's else comes back on this. It could be something nasty on chrome debugger.
