### ISSUE TITLE
Failover

### ISSUE THREAD

**Issue by newtack** [uNetworking/uWebSockets#632]
Scenario: Server with open connection goes down or we have new container deployed. Connections would be lost. How can we fail over/move the connection over to another container/server?

I am using Node js and Redis and would like to store the connection in Redis and have the ability to move them over to another server. Per the readme a connection only requires 104 bytes, so is it possible to a) store these 104 bytes in Redis and b) reestablish the connection on another server/container?

**Comment by alexhultman** [comment]
No you cannot do that. I've never heard of such a feature before.
