### ISSUE TITLE
Using uWS server side but websocket on client side

### ISSUE THREAD

**Issue by jjdp** [uNetworking/uWebSockets#633]
Would there be still any actual performance difference? I am not sure if i understand the concepts right.
Im using socket.io (websocket as transport on client) on react-native but on my node.js server Im using uWS (socket io 2.0).

**Comment by alexhultman** [comment]
This project is most probably not for you.

**Comment by jjdp** [comment]
all im asking is that client libs doesnt matter? i can pick whatever, but use uws on my node js server to have actual performance, like in your benchmarks?

**Comment by alexhultman** [comment]
These results are for C++. Node.js addon has max 40% the perf and then you have Socket.io on that which leaves maybe 2%.

I shouldn't need to tell you this. If you did your own benhmarks uou would have known and that is why I don't think this project is for you

**Comment by jjdp** [comment]
what would you recommend then for the server with node.js, seeing as engine.io even with uws only leaves 2%?
