### ISSUE TITLE
reconnect issues by using in client side

### ISSUE THREAD

**Issue by zhoufusong** [uNetworking/uWebSockets#635]
When I use uWebsockets in client sides, I must write  “new uWS::Hub()”  so that I can reconnect server ,otherwise it cannot reconnect in after a period of time . Is there any solution with no need for new Hub object?

**Comment by dyu** [comment]
Have you tried:
```
    const char* ws_connect_url = "ws://localhost:3000";
    h.onDisconnection([&h, ws_connect_url](uWS::WebSocket<uWS::CLIENT> *ws, int code, char *message, size_t length) {
        h.connect(ws_connect_url, nullptr);
    });
```

**Comment by lineCode** [comment]
I have the same issues, Have you solved it?
