### ISSUE TITLE
HowTo: Return Http Status Code

### ISSUE THREAD

**Issue by jeffsyang** [uNetworking/uWebSockets#642]
Anybody able to return a 404 status code if there is no routing to an endpoint?

**Comment by alexhultman** [comment]
HttpSocket::write is a raw TCP write where you can have any response you wish. HttpSocket::end is a helper wrapper of HttpSocket::write that adds a default response.

**Comment by jeffsyang** [comment]
Thanks for the clarification!

For those who would like an example,
```c++
uWS::Hub h;

h.onHttpRequest([this](HttpResponse *res, HttpRequest req, 
                       char *data, size_t length, size_t remainingBytes) {
    const char* temp = "HTTP/1.1 404 Not Found\r\nContent-Length: 0\r\n\r\n";
    res->write(temp, strlen(temp));
}
```
