### ISSUE TITLE
How to connect to uws without web server

### ISSUE THREAD

**Issue by iloveyou99** [uNetworking/uWebSockets#644]
I try to use UWS as my websocket server , I can compiled and run the chat demo application by VS C++ 2015 without node.js ,but I don't really know how the ws client send binary data to UWS,and broadcast to all ws client ,would you give me some hint, thank you.
  
## Include the following information (where applicable):

* What operating system are you running?
  * Windows
* Are you running any CPU architechute out of the normal?
  * I run 32-bit in the year 2017
* What platform/language are you using?
  * C++
 
* Are you using SSL, if so, how?
  * SSL via µWS 

* What version of uws are you using?
  * master
 
* What features of µWS are involved in the issue?
  * Server support (WebSocket)
  * Client support (WebSocket)

* How does the issue reproduce?
  * All the time

**Comment by alexhultman** [comment]
It's impossible for me to understand what you mean here. Your text makes no sense at all.
