### ISSUE TITLE
uws v8.14.0 on npm

### ISSUE THREAD

**Issue by MarkHerhold** [uNetworking/uWebSockets#645]
It seems that uws `v8.14.0` was published to npm on June 18th, which is a huge version jump from `v0.14.5`. Could anyone explain why there's such a big jump and what the difference is? I can't find a changelog file.

**Comment by MarkHerhold** [comment]
@alexhultman Duplicate of which issue please?

**Comment by shaharmor** [comment]
https://github.com/uNetworking/uWebSockets/issues/630
