### ISSUE TITLE
*Not* working on OSX 

### ISSUE THREAD

**Issue by ORESoftware** [uNetworking/uWebSockets#646]
On MacOS, I am getting a client connection error:

```js
'use strict';

const WebSocket = require('uws');
const WebSocketServer = WebSocket.Server;

const host = 'localhost';
const port = '7802';

const wss = this.wss = new WebSocketServer({
    port,
    host
  },
  () => {
    console.log('wss callback fired.');
  });


setTimeout(function(){

  const ws = new WebSocket(['ws://', host, ':', port].join(''));

  ws.on('error', err => {
    console.error( ' => Websocket client error => ', err.stack || err);
  });

  ws.on('open', () => {
    ws.isOpen = true;
     console.log('ws client is connected.');
  });

}, 3000);
```

did the library API change? I am confused.
I am on uws version  "uws": "^8.14.0"
and I am on node.js version 6.10.2

I wil open another ticket on the node.js bindings page

**Comment by ORESoftware** [comment]
ah, so it's working on my Ubuntu machine, but not on my MacOS sierra machine.
Does this thing work on Macs? It should right? ;)

**Comment by alexhultman** [comment]
#653

**Comment by alexhultman** [comment]
People tell me it works on OS X. It's only you.

**Comment by ORESoftware** [comment]
@alexhultman well a simple smoke test (mentioned above) kept failing (and never succeeded) on my MacOS machine. With the spare error messages it was not easy to debug. I assume it's some deep lying problem. Do you have any ideas as to why it would fail on some MacOS machines and not others? I had to migrate my library away from uws and to Node.js core TCP because of it.

**Comment by alexhultman** [comment]
I know you have been stating that some 17 times by now. I cannot fix things that only you report (the last days multiple people have reported that they are successfully using the lib on OS X). If it doesn't work for you then it doesn't work for you, not really my problem.

**Comment by ORESoftware** [comment]
Thanks @alexhultman :)
