### ISSUE TITLE
uws benchmark

### ISSUE THREAD

**Issue by thomas-jeepe** [uNetworking/uWebSockets#647]
I would simply like to know if there is any real overhead to using a nodejs wrapper over uWebsockets. I tried making the benchmark myself and got the lovely `FD error, connections: 4853` and after trying to destroy my laptop gave up.

Anyways, I use a macbook pro and setting `kern.maxfilesperproc` and `kern.maxfiles` didn't work, among other things, so I was wondering if the benchmark could also be part of the library itself.

**Comment by alexhultman** [comment]
What wrapper are you talking about? It varies enormously. The most minimal Node.js wrapper (addon) that can be made will only leave 60% of original perf at best. The worst wrapper that can be made (Socket.IO) leaves almost nothing.

**Comment by thomas-jeepe** [comment]
I am specifically talking about `uws` binding.

**Comment by alexhultman** [comment]
"uws" the Node.js addon on NPM leaves *up to* 60% perf and requires 11x more memory. But even if that sounds like a lot, it is a fart in the wind compared to the performance loss you get by using Node.js alone (all the NPM modules stack up into one pile of performance loss). I think uws will be the least of your concerns - the addon employs a series of hacks and workarounds to try and minimize performance loss and memory bloat but it all comes down to the very fact that you still need a JavaScript object per WebSocket and then you basically lose the race anyways (one single empty JavaScript object is larger in memory than one entire WebSocket).

**Comment by thomas-jeepe** [comment]
Oh. Thank you, I'll be closing this now, you might want to add a uws benchmark inside this repo for future people to see it in a benchmark and not have to search for an issue with it.
