### ISSUE TITLE
send message with parameters

### ISSUE THREAD

**Issue by ad34** [uNetworking/uWebSockets#650]
is there a way to handle parameters  in .onMessage ? . I can build a parsing system on my own, but is there something working out of the box to send a message + parameters ?

**Comment by alexhultman** [comment]
No, how would that be received client side? If you look at the "HTML5" WebSocket feature in browsers they have no such feature and thus the server cannot have that feature either. You can infer that.

**Comment by ad34** [comment]
for the format. dont know. why not a char* with json inside. yep , I know the standard don't handle parameters but in most use cases you will need that kind of support, so having an exemple of how to handle this in a clean & robust way would be nice. talked to a friend this morning , he used libwebsockets  on a project and was handling parameters as json string.

**Comment by alexhultman** [comment]
libwebsockets has no such support. You can send whatever data you want be it json or whatever. It is not up to the messenger to care for what you send. If you want to send MP3 or json is not for me to bother with.

**Comment by ad34** [comment]
yes, I get your point.

Just saying most of the projects building something on top on your awesome library will require parmaters handling (as it's something pretty familiar to most webd developers/network programmers : it's handled in http requests , it's handled in socket.io, in photonengine, in unity best http.pro .... ) 

So if it's not handled in the core library, having an exemple whould be nice to help programmers ;)

**Comment by alexhultman** [comment]
You can take that up to the WebSocket standards committee then
