### ISSUE TITLE
onHttpResponse() data corruption

### ISSUE THREAD

**Issue by jeffsyang** [uNetworking/uWebSockets#654]
## Include the following information (where applicable):

* What operating system are you running?
   Ubuntu 64-bit in VMware on Windows 10 64-bit
* What platform/language are you using?
   C++
* Are you using SSL, if so, how?
   SSL via µWS
* What version of uws are you using?
   Release v0.14.3
* What features of µWS are involved in the issue?
   Server support (HTTP)
* How does the issue reproduce?
  All the time
* Can you show me some short code that triggers your issue or any other important information?

```c++
h.onHttpRequest([this](HttpResponse *res, HttpRequest req, char *data, size_t length, size_t remainingBytes) {
        std::string retval;
	auto req_method = req.getMethod();
	std::string req_url = req.getUrl().toString();
	
	std::cout<<data <<std::endl;

	try
	{
	    if(req_method == HttpMethod::METHOD_GET) {
	        if(req_url == "/getVersion") {
	            retval = this->getVersion(3);
                }
		else {
	            throw std::runtime_error("");
		}
	    }
	    else if (req_method == HttpMethod::METHOD_POST) {
                if(req_url == "/user/register") {
		    retval = this->userRegister(res, req, data, length);
		}
		else if(req_url == "/user/login") {
		    retval = this->userLogin(res, req, data, length);
		}
		else {
	            throw std::runtime_error("");
		}
	    }
	} catch(const std::runtime_error& e) {
	    const char* temp = "HTTP/1.1 404 Not Found\r\nContent-Length: 0\r\n\r\n";
	    res->write(temp, strlen(temp));
	    return;
	}

        const char* c_retval = retval.c_str();
        res->end(c_retval, strlen(c_retval));
	return;
    });
}
```

using the above snippet, when i do a 3rd or 4th unique variation of 
`curl -k https://localhost:8080/user/register -d '{"username":"user@domain.com1", "password":"securepassword1", "passphrase":"securepassphrase1"}' -v` 
(I would change username to something else), 
`std::cout<<data`  shows that data was malformed consisting of the previous request's end and a partial of the current request data. 

An example output would be
`rase2"}name":"user@domain.com3", "password":"securepassword3", "passphrase":"securepassphrase3"}`

1) Looking at the snippet, does anything come to mind as to why `data` could end up this way?
2) Should I be using onHttpData() instead due to the JSON string in data? I had tried setting up onHttpData(), but was not successful in getting it to even print out anything. How could i successfully trigger onHttpData()?
3) Any article that can shed more light on the conceptual difference between onHttpResponse() and onHttpData()?

**Comment by jeffsyang** [comment]
Sorry, it seems like it was a problem with `curl`; '@' symbol has special significance when used with `curl -d`, used `curl --data-raw` instead and it seems to have solved the problem.

**Comment by alexhultman** [comment]
The problem isn't curl or this lib. The problem is that you don't take length into account. data is a pointer, not a string.

**Comment by ng5** [comment]
just to add 2 cents - alex had previously advised me not to assume everything will be available in onHttpRequest(), there are no guarantees. so you should continue to append bytes in a user defined structure inside onhttprequest() and onhttpdata() both until remaining bytes are zero. Although your current payload is very small it is unlikely to go to httppost() but it's better not to assume that.

**Comment by jeffsyang** [comment]
@ng5 Hey thanks for your input! I don't really understand what you mean by 'append bytes in a _user defined structure_ inside onHttpRequest() and onHttpData()'. How do the two functions work together? And what do you mean by 'user define structure'? 

Truth be told, I don't understand why in `tests/main.cpp`, controlData() is called from within both onHttpRequest() and onHttpData(). Could you or @alexhultman shed some light on this matter?

**Comment by ng5** [comment]
Repeating words from Alex:

TCP packets will come in segment, initial segment will come onHttpRequest(), if remainingbytes are zero then you can construct full request body object right there. If remaining bytes are non-zero, library will continue to call onHttpData() for subsequent segments, in each function call continue to read data until remaining bytes are zero.

Your payload will be malformed if you don't full read data obviously. You can use a heap allocated string to read json object you're sending. But incase you were sending data in another format like Google's flat buffer, obviously you can't deserialize until all the binary data is received. In that case you will need byte array or something similar. 

In order to see everything in action, try sending large JSON (something like 2000 bytes) payload and add printf on onHttpRequest() and onHttpData() you will see what i mean.

**Comment by jeffsyang** [comment]
After putting extra `std::cout` statements in `tests/main.cpp`'s `testHttp()` and removing `>/dev/null` from the POST tests, I was able to understand the relationship between `onHttpRequest()` and `onHttpData()` with @ng5's explanation as well.

To answer my own question about a _user defined structure_ for others, in the case of the test files, `res->getHttpSocket()->getUserData()` returns a void* pointing to where the payload is stored. In the tests, they simply store the payload as a std::string but you can store yours in a struct/std::vector/Json-object or some other data structure. Just remember to recast what you get back from `getUserData()` to use it.
