### ISSUE TITLE
Close connection after write

### ISSUE THREAD

**Issue by WebProdPP** [uNetworking/uWebSockets#655]
* What operating system are you running?
  * Linux
* What platform/language are you using?
  * C++
* Are you using SSL, if so, how?
  * SSL is not part of the equation
* What version of uws are you using?
  * master
* What features of µWS are involved in the issue?
  * Server support (HTTP)
* How does the issue reproduce?
  * All the time
* Can you show me some short code that triggers your issue or any other important information?

```
    uWS::Hub h;

    h.onHttpRequest([](uWS::HttpResponse *res, uWS::HttpRequest req, char *data, size_t length, size_t remainingBytes) {
        if (length == 0) {
            string s = "HTTP/1.1 200 OK\r\nContent-Type: text/html; charset=utf-8\r\n\r\n"
                    "<form method='POST'><input type='hidden' name='hidden' value='test'>"
                    "<input type='text' name='message' value=''><input type='submit'></form>";
            res->write(s.c_str(), s.length(),[](void* socket, void*, bool, void*) -> void {
                ((uWS::HttpSocket<true>*)socket)->terminate();
            });
            return;
        }

        res->end(data, length);
    });
```
This code throw ERR_CONNECTION_RESET in browser, how I can terminate request after write?

**Comment by alexhultman** [comment]
The HTTP connection is managed by the library itself. You simply respond to requests using end or write and then the library will terminate the connection if no more requests come in for some seconds. Mind you the HTTP part is currently a little bit incomplete and might have bugs in that callback you use (I can't remember if I have tested that cb or not, might be broken).
