### ISSUE TITLE
Add VS2013 Support

### ISSUE THREAD

**Issue by zhouwanchun1993** [uNetworking/uWebSockets#657]
Actually,I'm using VS2013 to write and run c++,so how can I build uWebSockets with vs2013? or I have to upgrade vs to version 2015 or later?( I have to do lots of things else to upgrade vs version)

**Comment by muizabdul29** [comment]
You have to upgrade your VS. I just did it 3 days ago. It's not just this library, you may get into troubles with other libraries as well. VS2017 Community being free gives just another reason to upgrade.

**Comment by alexhultman** [comment]
If it doesn't compile in VS2013 then it doesn't. I don't know if it does or not. Primary platform is Linux (which has had C++11 support since 2009).
