### ISSUE TITLE
Linux Mint 18.1 Fails benchmark

### ISSUE THREAD

**Issue by happilymarrieddad** [uNetworking/uWebSockets#660]
## Include the following information (where applicable):

* What operating system are you running?
  * Linux
* Are you running any CPU architechute out of the normal?
  * 64bit
* What platform/language are you using?
  * C++
* Are you using SSL, if so, how?
  * SSL via µWS or Node.js
* What version of uws are you using?
  * master
* What features of µWS are involved in the issue?
  * Benchmarks
* How does the issue reproduce?
  * All the time
* Can you show me some short code that triggers your issue or any other important information?
![selection_290](https://user-images.githubusercontent.com/6416323/28230401-1003e6c4-68a4-11e7-9509-0079a04fb543.png)

Hey man, I'm sure I'm just doing something wrong. I installed libuv and boost and ran make and got this error. I had to add the -w flag to get past the warnings. Can you please give me some advice on what I need to get the benchmarks running. Thanks!

![selection_291](https://user-images.githubusercontent.com/6416323/28230424-3b2c8c5c-68a4-11e7-91b7-5b59521d2098.png)

**Comment by alexhultman** [comment]
Looks like you have an old libuv version

**Comment by happilymarrieddad** [comment]
@alexhultman thanks man
For future use, here is a link for upgrading
http://docs.libuv.org/en/v1.x/migration_010_100.html
