### ISSUE TITLE
No pre-compiled binary error on Node 8.2.0

### ISSUE THREAD

**Issue by dylansmurray** [uNetworking/uWebSockets#663]
`throw new Error('Compilation of µWebSockets has failed and there is no pre-compiled binary ' +
Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system`

I started receiving this error after upgrading to node 8.2.0; reverting to node 7.10.1 resolved the issue. Does this node_module not have node 8 support?

OS X
Node
Release v0.14.0 (issue replicated on master)

**Comment by Avaray** [comment]
I confirm. Works for 7.10.1 and below. Doesn't work for 8.0.0+

Win10 x64 here.

**Comment by alexhultman** [comment]
What C++11 compiler do you guys have installed?
