### ISSUE TITLE
`yarn add uws` fails on FreeBSD

### ISSUE THREAD

**Issue by Jehops** [uNetworking/uWebSockets#668]
If `npm` is installed, `node-gyp` will get installed in the project directory and `uws` builds fine.  However, without `npm` installed, running `yarn add/install` gives the error below unless the user globally installs `node-gyp`.  I first [reported this to the yarn project](https://github.com/yarnpkg/yarn/issues/4097#issuecomment-320421369).  Should `uws` have a dependency on `node-gpy`, so that non-root users can install `uws` with yarn?

```
% yarn add uws
yarn add v0.27.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
info This package requires node-gyp, which is not currently installed. Yarn will attempt to automatically install it. If this fails, you can run "yarn global add node-gyp" to manually install it.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "node-gyp@3.6.2" with binaries:
      - node-gyp
error /usr/home/jrm/uws_test/node_modules/uws: Failed to auto-install node-gyp. Please run "yarn global add node-gyp" manually. Error: "We don't have permissions to touch the file \"/usr/local/bin/mkdirp\"."
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by alexhultman** [comment]
Yarn is not supported. If it works in NPM but not in Yarn they need to fix that. I won't add dependency to some now-deprecated build system with 30+ dependencies of its own. Besides, even if node-gyp fails the install should succeed and fall back to the pre-compiled binaries (this works on NPM).

**Comment by Jehops** [comment]
Ok, thanks for the quick response.  Do you mean pre-compiled FreeBSD binaries for `uws`?

**Comment by alexhultman** [comment]
No there are only pre-compiled binaries for Linux, OS X and Windows.

**Comment by Daniel15** [comment]
> I won't add dependency to some now-deprecated build system with 30+ dependencies of its own.

If your package needs to build native packages, it should ideally have a dependency on `node-gyp`, as node-gyp is the build system used for native packages.

> Besides, even if node-gyp fails the install should succeed and fall back to the pre-compiled binaries (this works on NPM).

It's not working in this particular case due to a lack of precompiled FreeBSD binaries.

**Comment by alexhultman** [comment]
FreeBSD is not supported. Neither is AmigaOS.

**Comment by alexhultman** [comment]
> If your package needs to build native packages

It doesn't *need* to, it *can* if dev tools are present.

> It's not working in this particular case due to a lack of precompiled FreeBSD binaries.

No, it's not working in this case because of Yarn failing to install node-gyp and aborting. Had it "failed" due to missing FreeBSD-binaries it would have printed this when loading:

"Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'."

The issue here is that Yarn *thinks* that uws *depends on* node-gyp and fails. It shouldn't *think* this, it should just skip the node-gyp step, which is what happens in NPM installs. Clearly it is a Yarn compatibility issue with the behavior of NPM. Besides, I never published any package to Yarn, I published to NPM and it works on NPM.

**Comment by Jehops** [comment]
Alex Hultman <notifications@github.com> writes:

> FreeBSD is not supported. Neither is AmigaOS.

Understood.  uWebSockets, so far, does seem to run well under FreeBSD.

**Comment by alexhultman** [comment]
This is not an issue with the lib, please open non-duplicates in the bindings repo. I do not guarantee support for Yarn or FreeBSD, you are using both.

**Comment by saper** [comment]
I think this problem belongs to https://github.com/uNetworking/bindings (I was confused, too, due to https://github.com/uNetworking/bindings/pull/33). Preliminary FreeBSD port can be found in #701, #702, #703, #704 and #705

**Comment by saper** [comment]
This particular problem with yarn could be fixed with https://github.com/uNetworking/bindings/pull/32

**Comment by jharris4** [comment]
`npm i -g node-gyp` can fix this issue. Also see https://github.com/yarnpkg/yarn/issues/3728
