### ISSUE TITLE
How to: Prevent server from switching from HTTPS to HTTP on incorrect key password entry

### ISSUE THREAD

**Issue by jeffsyang** [uNetworking/uWebSockets#674]
When setting up the TLS::Context, I do
```
uS::TLS::Context c = uS::TLS::createContext( cert, key);
h.listen(port, c, uS::ListenOptions::REUSE_PORT);
```

Doing so this way, the server would prompt for the PEM password if the key is encrypted. If entered correctly, it will listen with HTTPS. If the key is entered incorrectly, it would default to listen with HTTP. How could I shut down the server automatically if it switches over to HTTP on incorrect key password entry?

**Comment by alexhultman** [comment]
if (c) {
//ssl
} else {
//tcp
}

**Comment by jeffsyang** [comment]
oh wow, thanks
