### ISSUE TITLE
Example not blocking

### ISSUE THREAD

**Issue by Voultapher** [uNetworking/uWebSockets#678]
I guess I'm doing something wrong here.

Building and running this program:
```cpp
#include <uWS/uWS.h>

#include <iostream>

int main()
{
  std::cout << "hello uWS\n";
  uWS::Hub h;

  h.onMessage([](
    uWS::WebSocket<uWS::SERVER>* ws,
    char* message,
    size_t length,
    uWS::OpCode opCode
  ) {
    ws->send(message, length, opCode);
  });

  h.listen(3000);
  h.run();
  std::cout << "I don't get it\n";
}
```
Results in:
```sh
hello uWS
I don't get it
```
As far as I can tell `h.run()` is supposed to block.
I'm building on Arch linux with clang 4.0.1. Although I've tried g++ and got the same result.

**Comment by alexhultman** [comment]
Listen returns true if it could listen. Your fails and thrn run will just exit since there is nothing to do. Check your permissions or change port.

**Comment by Voultapher** [comment]
Thanks. Indeed it was a port issue. In order to avoid this issue in the future, could we have some kind of output telling the user, that the port isn't available. Afaik node does it that way. Or tweak the examples to react based on the `listen()` return value?

**Comment by alexhultman** [comment]
You can add that to the example if you want to

**Comment by Voultapher** [comment]
Any preference of system io. Iostreams of cstdio?

**Comment by alexhultman** [comment]
You can also just if(!listen(...)) then return -1; It's just about highlighting the fact listen can fail.

**Comment by Voultapher** [comment]
Fixed with: https://github.com/uNetworking/uWebSockets/pull/679
