### ISSUE TITLE
How to: Process multiple requests simultaneously

### ISSUE THREAD

**Issue by jeffsyang** [uNetworking/uWebSockets#680]
I think there is only 1 thread running for my server application causing requests to be blocked. To be able to process requests asynchronously and/or simultaneously, would I create more threads each running a Hub like in https://github.com/uNetworking/uWebSockets/issues/530, or should i set up more Group\<Server\>, `group->addAsync()`, and use `REUSE_PORT` (similar to testReusePort() in https://github.com/uNetworking/uWebSockets/blob/master/tests/main.cpp)?

Could somebody also please give a high level description of what a Hub, Group, and Node are?

**Comment by alexhultman** [comment]
examples/multithreaded_echo is the way to go. A group is a palette of callbacks and a set of sockets using these callbacks. A Hub is a per:-thread resource / event-loop. 8 cpu cores = 8 threads and 8 Hubs in total.

**Comment by jeffsyang** [comment]
Got it, I really appreciate the answers. Will give this a shot

**Comment by jeffsyang** [comment]
@alexhultman I was able to get my server application running with multiple threads using your example. When testing, I noticed that although requests do not block every time like in the scenario with only 1 thread, there are times when multiple requests are passed to the same thread causing them to block. Do you know of anything else I can do to make all requests not block? Will doing `group->addAsync()` somehow help?

**Comment by alexhultman** [comment]
Either you follow the rules of the *event loop* (see Node.js) or you go with Apache doing 1 thread per request. There is no cheating this. I cannot help more than this. addAsync does not change anything for you.

**Comment by jeffsyang** [comment]
Ok, I was thinking in terms of how Nginx does things asynchronously. Quick question, what do you mean by rules of the event loop? Are there a few articles/links I could read to understand what you mean?
