### ISSUE TITLE
Server drops connection by sending [FIN, ACK]

### ISSUE THREAD

**Issue by FlyClover** [uNetworking/uWebSockets#681]
* What operating system are you running?
  * Ubuntu 12.04
* Are you running any CPU architechute out of the normal?
  * No
* What platform/language are you using?
  * C++
* Are you using SSL, if so, how?
  * SSL via µWS
* What version of uws are you using?
  * Release v0.14.3
* What features of µWS are involved in the issue?
  * Server support (WebSocket)
* How does the issue reproduce?
  * 1/10
* Can you show me some short code that triggers your issue or any other important information?

My uWS websocket server sometimes would close a client's long lived connection, after the connection is idle for a while and client sends data again (always happen in situation like this). The close is sent from the server on tcp level. My application code does not close the connection (otherwise there would be a websocket close message). I captured a tcpdump to show what actually happened.

Frame 517041: client and server finished a session.
Frame 517549: client initiated a new session.
Frame 517551: server sent [FIN, ACK], indicating a termination of tcp connection.

![screenshot from 2017-08-15 17 25 51](https://user-images.githubusercontent.com/186422/29310170-513423c6-81df-11e7-8a01-f1ef30a11d95.png)

Has anyone seen similar problems?

**Comment by FlyClover** [comment]
After adding some traces, I find the trigger here: https://github.com/uNetworking/uWebSockets/blob/master/src/Socket.h#L201

Apparently there's something wrong with the underlying TCP connection so server drops the connection. But from the tcpdump from in first post, all the data seems to be fine. Have you seen something like this before? @alexhultman

**Comment by alexhultman** [comment]
use ping/pong

**Comment by FlyClover** [comment]
Yes, ping/pong is already enabled on both client and server side. Before server sends [FIN, ACK], the TCP is fine because server can still receive data from client.

**Comment by alexhultman** [comment]
> after the connection is idle for a while and client sends data again (always happen in situation like this).

this contradicts ping pong. also there is no way to enable or disable ping pong client side only server can ping

**Comment by FlyClover** [comment]
Sorry, let me be more specific. On client side, I use OkHttp and set ping period to 45s. On server side, auto ping is enabled with period 600s.

For the case in the first post, server receives a packet form client at 22:05:21 (517041), then another  packet at 22:05:44 (517549). Because there's only 23 seconds in between, there's no ping/pong message. But apparently, the TCP link is good otherwise the server cannot receive the message. The question here is that why server sends [FIN, ACK] (517551) in response to client's message?

**Comment by FlyClover** [comment]
Finally fixed it: it's caused by OpenSSL. I was using 1.0.2. After upgrading it to 1.1.0 the issue resolved.
