### ISSUE TITLE
Mobile Support? (iOS/Android)

### ISSUE THREAD

**Issue by MattFoley** [uNetworking/uWebSockets#682]
I was doing some research, and I was curious if this library is capable of being compiled for Android or iOS, and/or if that has been done.

Thanks!

**Comment by alexhultman** [comment]
It probably can but client side shouldn't matter anyways. Just go with any client really.

**Comment by Hersir88** [comment]
You can use [https://github.com/acmacalister/jetfire](jetfire)  or [https://github.com/daltoniam/starscream](starscream) for iOS and [https://github.com/TooTallNate/Java-WebSocket](Java-WebSocket) for Android
