### ISSUE TITLE
Build error on Ubuntu

### ISSUE THREAD

**Issue by SaxonDruce** [uNetworking/uWebSockets#685]
I'm getting this error (and lots of others like it) when building master on Ubuntu 16.04:

```
make[1]: Entering directory '/home/username/dev/uWebSockets'
g++   -std=c++11 -O3 -I src -shared -fPIC src/Extensions.cpp src/Group.cpp src/Networking.cpp src/Hub.cpp src/Node.cpp src/WebSocket.cpp src/HTTPSocket.cpp src/Socket.cpp src/Epoll.cpp -s -o libuWS.so
In file included from src/WebSocketProtocol.h:5:0,
                 from src/WebSocket.h:4,
                 from src/Group.h:4,
                 from src/Group.cpp:1:
src/Networking.h:14:22: error: expected identifier before numeric constant
 #define MSG_NOSIGNAL 0
                      ^
```

I think the error is caused by this recent change to the #ifndef test for MSG_NOSIGNAL:

https://github.com/uNetworking/uWebSockets/commit/836b5993ee0dc92637f3c029a029d3e2176d2c75

I think this needs to be moved to somewhere after the #include <sys/socket.h> for it to pick up the pre-existing MSG_NOSIGNAL.

**Comment by alexhultman** [comment]
Oh for fucks sale can people stop sending boken PRs? Thanks for reporting.

**Comment by alexhultman** [comment]
Incompetent morons shouldn't send PRs. It was completely broken on Linux. Fixed now thanks.
