### ISSUE TITLE
WSS, SSL setup documentation?

### ISSUE THREAD

**Issue by ddibiase** [uNetworking/uWebSockets#686]
I do apologize if this is not the correct place to post, but I'm looking for documentation on how to properly configure WSS with UWS. Currently I'm simply doing:

    this.server = new WebSocket.Server({
      port: this.config.port,
      verifyClient: this.authenticate.bind(this)
    });

Which obviously just binds a basic socket. Do I need to initialize a separate https with the settings and plug it into the UWS options? If so does that still leverage the UWS internals with SSL? I have no idea how the internalized structure looks so just curious.

I have a full extended question on Stackoverflow: https://stackoverflow.com/questions/45863747/setup-node-with-uws-and-ssl

**Comment by alexhultman** [comment]
I behaves like ws. Pass an https server as option and it will be SSL:ed.

**Comment by ddibiase** [comment]
Thanks @alexhultman. Would you mind giving me a few sentences on what's happening here? Is `https` only used for the encryption side before its sent over the wire with uws? I'm very curious how it works.

**Comment by alexhultman** [comment]
OpenSSL has *reference counted* resources which makes it possible to *transfer* a TLS connection from Node.js over to uws. When the 'upgrade' event is handled uws will *dup* the SSL connection and the file descriptor only to then close down the Node.js tls.Socket. This removes all the Node.js bloat and from here on it's smooth sailing.

Now uws has the SSL pointer and the file descriptor of this TLS connection while Node.js is completely empty handed except for still holding the SSL *context* (certificate, settings, etc). Sending and receiving to/from this TLS connection is now made all from native land. This is essential to the idea of uws - anything else would ruin any performance / memory endeavors.
