### ISSUE TITLE
Integreate event loop in one thread

### ISSUE THREAD

**Issue by iONinja** [uNetworking/uWebSockets#688]
I'm writing a C++ project which has my own custom event loop. It's a while loop, with a variable delay between each execution. It looks something like this:

```C++
while (true) {
    std::this_thread::sleep_for (variableTime);
    // Execute logic
}
```

I've previously been using another thread to execute logic, but I want to integrate the uWebSockets loop with my loop. Something like this:

```C++
#include <iostream>
#include <uWS/uWS.h>

using namespace std;

int main () {
    uWS::Hub h;

    h.onMessage([](uWS::WebSocket<uWS::SERVER> *ws, char *message, size_t length, uWS::OpCode opCode) {
        ws->send(message, length, opCode);
    });

    if (h.listen(3000)) {
        h.run();
    }

    while (true) {
        std::this_thread::sleep_for (variableTime);
        h.getMessages(); // <-- doesn't call `onMessage` until this is executed
        // Execute logic
    }
}
```

How would I go about doing this?

Thanks! :smile:

**Comment by alexhultman** [comment]
Why would you want to deliberately limit your CPU usage? Is it some kind of embedded, power constrained device?

**Comment by iONinja** [comment]
@alexhultman 

The machine that I will be using only has 1 core, so there's no advantage in multi-threading.

The specific reason that I want to integrate the event loop, is to avoid the issues of threads accessing the same data. I can use mutexes, but it seems like unnecessary work, and the extra complexity creates room for bugs and undefined behaviour.

Any ideas on how to do this?
Thanks for your help :slightly_smiling_face:.

**Comment by alexhultman** [comment]
This is not how you write async servers. If you want a timer, then use a timer. You cannot have a blocking sleep in the middle of your only thread.
