### ISSUE TITLE
How does javascript use WSS to connection uws?

### ISSUE THREAD

**Issue by zhanMan** [uNetworking/uWebSockets#690]
problem:
          **1.uws has API instructions or use to the guide ?
           2.How does javascript use WSS to connection uws?_I have been not connected, how should I do?    
follow my code**：
            _javascript:_
             `  this.ws = new WebSocket("wss://IP:Port/");
		this.ws.onerror = function(event) 
		{
		};
		this.ws.onopen = function(event)
		{
		};
		this.ws.onmessage = function(event) 
		{
		};	
		this.ws.onclose = function(event)
		{
		};` `
            **__C++ uws__**

            `uWS::Hub h;

	h.onMessage([](uWS::WebSocket<uWS::SERVER> *ws, char *message, size_t length, uWS::OpCode opCode) {
		ws->send(message, length, opCode);
	});

	h.onError([](void *user) {	
		std::cout << "onError:" << std::endl;
	});

	h.onConnection([](uWS::WebSocket<uWS::CLIENT> *ws, uWS::HttpRequest req) {
		std::cout << "onConnection:"<<(long)ws->getUserData() << std::endl;
	});

	h.onDisconnection([](uWS::WebSocket<uWS::CLIENT> *ws, int code, char *message, size_t length) {
		std::cout << "Client got disconnected with data: " << ws->getUserData() << ", code: " << code << ", message: <" << std::string(message, length) << ">" << std::endl;
	});

	h.onHttpRequest([](uWS::HttpResponse *res, uWS::HttpRequest req, char *data, size_t length, size_t remainingBytes) {
		res->end(data, length);
	});

	uS::TLS::Context sslContext = uS::TLS::createContext("misc/ssl/cert.pem", "misc/ssl/key.pem", "1234");
	int options = uS::ListenOptions::ONLY_IPV4;
	if (h.listen(8081, sslContext, options)) {
		h.run();
	}`

**Comment by zhanMan** [comment]
@alexhultman

**Comment by alexhultman** [comment]
This is not english.
