### ISSUE TITLE
Feature request - improve handling of unmasked client packets

### ISSUE THREAD

**Issue by d3x0r** [uNetworking/uWebSockets#691]
I managed to identify the failure of using ws with uws.  (as exposed by Thor).
Yes, it's missing 4 bytes, the masking bytes.  ws is not properly masking client to server data. 
The RFC does not specify a behavior to follow if a message from a client is sent unmasked, merely states that it  (in https://tools.ietf.org/html/rfc6455#section-5.2 ) 

Masking-key:  0 or 4 bytes

      All frames sent from the client to the server are masked by a
      32-bit value that is contained within the frame.  This field is
      present if the mask bit is set to 1 and is absent if the mask bit
      is set to 0.  See Section 5.3 for further information on client-
      to-server masking.

option 1) be forgiving and don't read 4 bytes extra if the masking bit is not set.
option 2) generate a close with a status indicating protocol failure  

or of course option 3) do nothing, leave the connection hanging, and be uninformative about the situation.

https://tools.ietf.org/html/rfc6455#section-7.4.1  (defined close codes) 

these close codes may be applicable.

   1003
      1003 indicates that an endpoint is terminating the connection
      because it has received a type of data it cannot accept (e.g., an
      endpoint that understands only text data MAY send this if it
      receives a binary message).

   1007
      1007 indicates that an endpoint is terminating the connection
      because it has received data within a message that was not
      consistent with the type of the message (e.g., non-UTF-8 [RFC3629]
      data within a text message).

   1008
      1008 indicates that an endpoint is terminating the connection
      because it has received a message that violates its policy.  This
      is a generic status code that can be returned when there is no
      other more suitable status code (e.g., 1003 or 1009) or if there
      is a need to hide specific details about the policy.

1011
      1011 indicates that a server is terminating the connection because
      it encountered an unexpected condition that prevented it from
      fulfilling the request.

**Comment by alexhultman** [comment]
You own citation clearly states:

```
   Mask:  1 bit

      Defines whether the "Payload data" is masked.  If set to 1, a
      masking key is present in masking-key, and this is used to unmask
      the "Payload data" as per Section 5.3.  All frames sent from
      client to server have this bit set to 1.
```

> All frames sent from client to server have this bit set to 1.

Report this issue in thor (ws) repo. uws is doing the right thing according to spec.

**Comment by alexhultman** [comment]
Further on a more strict citation:

```
5.3.  Client-to-Server Masking

   A masked frame MUST have the field frame-masked set to 1, as defined
   in Section 5.2.
```

ws is breaking a "MUST" requirement of the spec. Basically ws is ignoring the cache poisoning fix that is required by the spec, which has security implications in case of proxies with cache.

**Comment by d3x0r** [comment]
I did report it there also https://github.com/websockets/ws/issues/1194
And as I said it's undefined in the RFC so your behavior is within spec... just would be nice to know why the connection is just haning.  (leaving this closed).

**Comment by alexhultman** [comment]
> websockets/ws#1194

Go fuck off
