### ISSUE TITLE
(Node.js) Accessing request object on connection

### ISSUE THREAD

**Issue by timetocode** [uNetworking/uWebSockets#692]
Is there a way to get the http request object? For example:

```
var wsServer = new WebSocketServer({ port: port })
wsServer.on('connection', (ws, req) => {
   // req is undefined in uws, but defined in ws
})
```
Perhaps I am using the wrong syntax. I also tried starting the server by passing it an http server to no avail.  I make websocket games and use the above syntax to pass in some initial state... like a session. Am open to alternate methods as well.

Edit: here's the syntax I tried from ws https://github.com/websockets/ws#expressjs-example

**Comment by alexhultman** [comment]
That's the brand new ws 3+ interface. uws still mocks the 2+ interface. You can PR the change in bindings repo - it's a 1 line change (ws 2+ has this req attached to the socket itself as upgradeReq property).

**Comment by alexhultman** [comment]
https://github.com/websockets/ws/pull/1099
