### ISSUE TITLE
Concurrency.

### ISSUE THREAD

**Issue by hifall** [uNetworking/uWebSockets#694]
First of all, uWebSockets looks awesome.
I found this description in Readme:

> One million WebSockets require ~111mb of user space memory

I am wondering what's the max concurrent sockets an 'average' single-core server CPU running uWebSockets can handle, before apparent delays/socket disconnects happen on the clients. Care to share some info if such stress tests been done?

Thanks!

**Comment by alexhultman** [comment]
Nobody can answer this question without any kind of context. You need to benchmark it.

**Comment by hifall** [comment]
I think there is DEFINITELY some kind of context in the original question. But anyways...

**Comment by alexhultman** [comment]
It depends on what you are doing. You can keep 10 million if you only send rarely and maybe you can flood the server at only 20 connections what do I know it depends. Idle connectiona consume 0 CPU time.

**Comment by alexhultman** [comment]
Also it is not easy to interpret "apparent" and "average" those words are highly inaccurate you cannot go to the store and buy "a handful of apples" or "an arms length of sausages" or "a foot of watermelon".

**Comment by alexhultman** [comment]
An eyelid of sugar 😉

**Comment by alexhultman** [comment]
ja hallå jag vill ha två mockasiner banan

**Comment by hifall** [comment]
Yeah, I do know these words are highly subjective. I did that on purpose to leave some room for possible feedback.

I can throw out some question with 'hard' context info like 'How does uWebSockets perform on one of the cores of Intel Xeon Processor X5650 (12M Cache, 2.66 GHz, 6.40 GT/s), and on 96GB of Kingston DDR3-1600 ...', if that's what's being intended here.

**Comment by alexhultman** [comment]
don't know
