### ISSUE TITLE
Can't build on Arch Linux. Website Demo doesn't work...

### ISSUE THREAD

**Issue by stephendliang** [uNetworking/uWebSockets#698]
I'm new to linux (Arch Linux specifically). I installed everything needed, and used git clone to clone the master to my home directory, ~. Then, I cd into the folder, and used the command make. Then, I git cloned the website chat demo. When I try to build the website chat demo with make, it says: "fatal error: uWS/uWS.h: No such file or directory".

How come this isn't in my library folder? I have built it, and I am trying to run the demo site to test.

**Comment by alexhultman** [comment]
don't post issues like these, read a book.
