### ISSUE TITLE
question on endianness hub.onMessage()

### ISSUE THREAD

**Issue by ng5** [uNetworking/uWebSockets#699]
Hi, Is it safe to assume that uWebSocket is using default platform endianness after message are received. so far there are no surprises (both text and binary data are received in expected order), because I'm only using x86_64 servers and client. data on network is big endian by default. 

I'm asking because I saw below line in benchmark code, where data is being converted to bigendian in one of the condition.

*((uint64_t *) &framePackBufferOffset[2]) = htobe64(byteSize);

thanks a lot for any feedback.

**Comment by alexhultman** [comment]
a message is never changed, you send an apple, you get an apple

**Comment by ng5** [comment]
thanks

**Comment by alexhultman** [comment]
sounds efficient, i like that :)

**Comment by ng5** [comment]
thanks, just wanted to make sure google's flat buffer doesn't mess around with endianness. flatbuffer library disables compiler alignment and forces little endianness. raw binary data (sent from node) works without any problem.
