### ISSUE TITLE
Poor HTTP performance vs Node.js

### ISSUE THREAD

**Issue by njlr** [uNetworking/uWebSockets#708]
## Include the following information (where applicable):

* What operating system are you running?
  * OS X
* Are you running any CPU architechute out of the normal?
  * No
* What platform/language are you using?
  * C++
  * Node.js
* Are you using SSL, if so, how?
  * SSL is not part of the equation
* What version of uws are you using?
  * Release v0.14.4
* What features of µWS are involved in the issue?
  * Server support (HTTP)
* How does the issue reproduce?
  * All the time
* Can you show me some short code that triggers your issue or any other important information?
  * Yes

-------------------

I am trying to build a "Hello world" server in uWS and Node.js for comparison purposes. 

Here is my uWS server: 

```c++=
#include <uWS/uWS.h>

int main() {

  uWS::Hub h;

  std::string const document = "<h1>Hello, world. </h1>";

  h.onHttpRequest([&document](uWS::HttpResponse *res, uWS::HttpRequest req, char *data, size_t length, size_t remainingBytes) {
    res->end(document.data(), document.length());
  });

  h.listen(3000);
  h.run();

  return 0;
}
```

I am compiling in LibUV mode with `-O3`. 

Here is my Node.js server: 

```javascript=
'use strict';

const express = require('express');

const app = express();

const doc = '<h1>Hello, world. </h1>';

app.get('/', (req, res) => {
  return res.send(doc);
});

app.listen(8080);
```

Here are the results for uWS: 

```
$ ab -n 10000 -c 100 http://127.0.0.1:3000/
This is ApacheBench, Version 2.3 <$Revision: 1757674 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


Server Software:
Server Hostname:        127.0.0.1
Server Port:            3000

Document Path:          /
Document Length:        23 bytes

Concurrency Level:      100
Time taken for tests:   200.560 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      620000 bytes
HTML transferred:       230000 bytes
Requests per second:    49.86 [#/sec] (mean)
Time per request:       2005.601 [ms] (mean)
Time per request:       20.056 [ms] (mean, across all concurrent requests)
Transfer rate:          3.02 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        2    5   1.7      5      11
Processing:  1989 2000   4.2   2000    2015
Waiting:        1    3   0.7      3       7
Total:       1992 2006   5.6   2005    2020

Percentage of the requests served within a certain time (ms)
  50%   2005
  66%   2008
  75%   2010
  80%   2011
  90%   2013
  95%   2015
  98%   2016
  99%   2017
 100%   2020 (longest request)
```

Here are the results for Node.js: 

```
$ ab -n 10000 -c 100 http://127.0.0.1:8080/
This is ApacheBench, Version 2.3 <$Revision: 1757674 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


Server Software:
Server Hostname:        127.0.0.1
Server Port:            8080

Document Path:          /
Document Length:        21 bytes

Concurrency Level:      100
Time taken for tests:   4.046 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      2210000 bytes
HTML transferred:       210000 bytes
Requests per second:    2471.72 [#/sec] (mean)
Time per request:       40.458 [ms] (mean)
Time per request:       0.405 [ms] (mean, across all concurrent requests)
Transfer rate:          533.45 [Kbytes/sec] received

Connection Times (ms)
             min  mean[+/-sd] median   max
Connect:        0    0   1.0      0      13
Processing:    14   40  16.1     31     113
Waiting:       12   40  16.1     31     112
Total:         25   40  16.2     32     114

Percentage of the requests served within a certain time (ms)
 50%     32
 66%     39
 75%     46
 80%     50
 90%     64
 95%     76
 98%     87
 99%    102
100%    114 (longest request)
```

As you can see, Node.js is considerably faster with **2471.72 requests/sec** vs **49.86 requests/sec** for uWS! This is very surprising given that they use the same underlying library (libuv). 

Is this expected? Perhaps there is something wrong with my server implementation?

**Comment by alexhultman** [comment]
Don't benchmark http 1.0, benchmark http 1.1 (wrk is a good bench)

**Comment by dyu** [comment]
Try [wrk2](https://github.com/giltene/wrk2)

**Comment by njlr** [comment]
@alexhultman So should I avoid uWS as a solution for HTTP 1.0?

**Comment by alexhultman** [comment]
@njlr I can't answer that for you, but Internet Explorer 4 compatibility is maybe a little too anal? Http 1.1 is already 10 years old now.

**Comment by alexhultman** [comment]
Correction: 20 years

**Comment by njlr** [comment]
OK, fair enough. So Node.js is faster for HTTP 1.0, but uWS is only interested in HTTP 1.1. 

I will take a look at some HTTP 1.1 benchmarks 👍

**Comment by nikhedonia** [comment]
@alexhultman 
Since HTTP 1.1 is generally speaking a subset of HTTP 1.0 it is a valid performance test.
As far as i can see, a server that only sends 'Hello World' cannot take any advantages of HTTP 1.1 to improve it's performance. 

Note that unlike wrk, ApacheBench is not testing throughput but performance of connection processing.
It tests how quickly can an http server write a message, accept and close a connection.
The provided test shows this library is not able to process many connections per second.

After a quick look in the sourcecode it appeared to me that there is no logic for handling the 
'Connection: keep-alive' header.
My guess would be that the current implementation assumes 'keep-alive' and timeouts when no further request are performed by the client. This behavior might be acceptable if 99% of clients are upgrading to a Websocket connection but detrimental for a static file server.

**Comment by alexhultman** [comment]
> The provided test shows this library is not able to process many connections per second.

No, the apache bench (ab) test shows that this lib doesn't care about anal Connection: close behavior since Http 1.1 has keep-alive by default. In actuality it already sent the data and is simply timing out before it closes the connection. Anyways, all of this info is a repeat of another issue report.

**Comment by alexhultman** [comment]
#511
