### ISSUE TITLE
sending multiple messages one websocket frame at a time

### ISSUE THREAD

**Issue by alexpmorris** [uNetworking/uWebSockets#723]
I'm using the latest version of uWebSockets in VS2017 via vcpkg, and I'm trying to send several JSON packets in the onConnection() event for a client.  If I place a small delay between each json packet, it works perfectly, and I receive 1 json response per request:

```
ws->send(data1.data(), data1.length(), uWS::TEXT);  
std::this_thread::sleep_for(std::chrono::milliseconds(10));

ws->send(data2.data(), data2.length(), uWS::TEXT);  
std::this_thread::sleep_for(std::chrono::milliseconds(10));

```
However, if I send them all at once, I only receive ONE response for the first json packet, and no others.  I believe this is because the server expects only ONE json packet per websocket frame, and they're likely being bunched up into a single frame.  The small delay seems just enough to achieve that result.  However, this seems rather "hacky" *(not to mention adding unnecessary delays)*, and I figure that I must be missing the correct way to do this.  

I also tried using `PreparedMessage`:
```
		uWS::WebSocket<uWS::CLIENT>::PreparedMessage *preparedMessageBatch = uWS::WebSocket<uWS::CLIENT>::prepareMessageBatch(msgs, excludedMessages, uWS::TEXT, false);
		ws->sendPrepared(preparedMessageBatch);
		ws->finalizeMessage(preparedMessageBatch);
```
And it gave me the same result as if I didn't use the delay.  Appreciate any guidance you can offer regarding this.

**Comment by alexhultman** [comment]
The server doesn't expect, or care about JSON at all. It doesn't care about the content of your messages. If you send two messages you get two messages. I'm 200% sure the issue is on your end because what you describe makes no sense and Autobahn tests would not pass if the server was this broken.

**Comment by alexhultman** [comment]
> and they're likely being bunched up into a single frame

this is not how it works. one send is strictly one message and will never be bunched into one message

**Comment by alexpmorris** [comment]
Perhaps I wasn't clear enough.  In this case I am using uWebSockets to connect to a **non uWebSockets** server *(and **not** controlled by me)*.

I have a similar implementation in Delphi that talks to the same server.  If I send each json packet in its own websocket frame, for example:
```
addWebSocketMessage(jsonPacket1);
addWebSocketMessage(jsonPacket2);
addWebSocketMessage(jsonPacket3);
```
The **non uWebsocket** server responds perfectly to all three requests.  However, if I do the following:
```
addWebSocketMessage(jsonPacket1+jsonPacket2+jsonPacket2);
```
that same server then **only responds to the first packet**.  

This is the **same behavior** I am observing when uWebSockets sends the data, which tells me that send()/sendPrepared() is most likely also bunching the packets together into a single websocket message frame.  That may be fine in many cases, but in this case I need to assure 1 json packet per frame.

By adding even a 10ms delay after each uWebsocket send(), I'm basically tricking uWebSockets to flush the message buffer (and thus keeping each message in its own frame), so that it performs in a similar manner achieved by me in Delphi by explicitly controlling the content of each message.

I hope this better clarifies what I am trying to do.

**Comment by ng5** [comment]
i'm using uwebsockets to send multiple json or binary flatbuffer messages, it is working correctly and as expected. there is no such issue that you described.

**Comment by alexpmorris** [comment]
I just did some more testing with the website chat example.  When sending messages to chrome, each message does appear to come up individually in onMessage().  So, as a next step I redirected my uWebSocket client to the uwebsocket chat server.

Oddly, this seems it may be more about losing messages.  I say this because even with the delay, if I step through `   h.onMessage([&h](uWS::WebSocket<uWS::SERVER> *ws, char *data, size_t length, uWS::OpCode opCode) { ... }` line by line, onMessage() is only triggered once!  However, if I don't step through, all four messages are received!

Just to be thorough, here's the exact client code:
```
	h.onConnection([&h](uWS::WebSocket<uWS::CLIENT> *ws, uWS::HttpRequest req) {
		std::string data = "";
		jsonRpcId++;  data = "{\"id\":" + std::to_string(jsonRpcId) + ",\"method\":\"call\",\"params\":[1,\"login\",[\"\",\"\"]]}";  
		ws->send(data.data(), data.length(), uWS::TEXT);  std::this_thread::sleep_for(std::chrono::milliseconds(10));
		jsonRpcId++;  data = "{\"id\":" + std::to_string(jsonRpcId) + ",\"method\":\"get_dynamic_global_properties\",\"params\":[]}";
		ws->send(data.data(), data.length(), uWS::TEXT);  std::this_thread::sleep_for(std::chrono::milliseconds(10));
		jsonRpcId++;  data = "{\"id\":" + std::to_string(jsonRpcId) + ",\"method\":\"call\",\"params\":[1,\"get_api_by_name\",[\"database_api\"]]}";
		ws->send(data.data(), data.length(), uWS::TEXT);  std::this_thread::sleep_for(std::chrono::milliseconds(10));
		jsonRpcId++;  data = "{\"id\":" + std::to_string(jsonRpcId) + ",\"method\":\"call\",\"params\":[1,\"get_api_by_name\",[\"market_history_api\"]]}";
		ws->send(data.data(), data.length(), uWS::TEXT);  std::this_thread::sleep_for(std::chrono::milliseconds(10));
	});
```

as shown above, without stepping through the chat demo code, I receive this:
```
Message posted: {"id":1,"method":"call","params":[1,"login",["",""]]}
Message posted: {"id":2,"method":"get_dynamic_global_properties","params":[]}
Message posted: {"id":3,"method":"call","params":[1,"get_api_by_name",["database_api"]]}
Message posted: {"id":4,"method":"call","params":[1,"get_api_by_name",["market_history_api"]]}
```
If I remove the delays or step through the code, at best I receive only 1 or 2 messages.  Even stranger, if I restart the chat server, I can step through onMessage() and I receive all four messages for the *first* connection.  Upon subsequent connections by the chat client, onMessage() is triggered only once.

I also tried ASIO mode (#define USE_ASIO) with the same results.  Perhaps it's still just some sort of issue with the Windows/Visual C++ implementation that I'm using?

**Comment by alexhultman** [comment]
You are doing something wrong here. This is not an issue in the lib. Mind you the lib is used by others.

**Comment by alexpmorris** [comment]
That very well may be.  As such, I'll just leave this simple example that seems to reproduce the problem I'm having quite consistently (on my machine, at least).  Apparently, what seems to be actually be happening is that the connection is lost if I don't have the small delay in there... 
```
#include "stdafx.h"
#include <iostream>
#include <uWS/uWS.h>

uint64_t jsonRpcId = 0;
uint64_t msgsRcvd = 0;

const bool useDelay = false;

int main()
{
	uWS::Hub h;

	h.onConnection([](uWS::WebSocket<uWS::CLIENT> *ws, uWS::HttpRequest req) {
		std::string data = "";
		jsonRpcId++;  data = "{\"id\":" + std::to_string(jsonRpcId) + ",\"method\":\"call\",\"params\":[1,\"login\",[\"\",\"\"]]}";
		ws->send(data.data(), data.length(), uWS::TEXT);  
		if (useDelay) std::this_thread::sleep_for(std::chrono::milliseconds(10));
		jsonRpcId++;  data = "{\"id\":" + std::to_string(jsonRpcId) + ",\"method\":\"get_dynamic_global_properties\",\"params\":[]}";
		ws->send(data.data(), data.length(), uWS::TEXT);  
		if (useDelay) std::this_thread::sleep_for(std::chrono::milliseconds(10));
		jsonRpcId++;  data = "{\"id\":" + std::to_string(jsonRpcId) + ",\"method\":\"call\",\"params\":[1,\"get_api_by_name\",[\"database_api\"]]}";
		ws->send(data.data(), data.length(), uWS::TEXT);  
		if (useDelay) std::this_thread::sleep_for(std::chrono::milliseconds(10));
		jsonRpcId++;  data = "{\"id\":" + std::to_string(jsonRpcId) + ",\"method\":\"call\",\"params\":[1,\"get_api_by_name\",[\"market_history_api\"]]}";
		ws->send(data.data(), data.length(), uWS::TEXT);  
		if (useDelay) std::this_thread::sleep_for(std::chrono::milliseconds(10));
	});

	h.onMessage([](uWS::WebSocket<uWS::CLIENT> *ws, char *data, size_t length, uWS::OpCode opCode) {
		msgsRcvd++;
		data[length] = 0;
		std::cout << msgsRcvd << " clnt_in " << data << std::endl;
	});

	h.onDisconnection([](uWS::WebSocket<uWS::CLIENT> *ws, int code, char *message, size_t length) {
		std::cout << "disconnect" << std::endl;
	});


	h.connect("wss://steemd.steemit.com", nullptr);
	h.run();

}
```

output (delay = false):
```
C:\WorkSpace>wsclnt
1 clnt_in {"id":1,"result":true}
disconnect
```

Perhaps it's also just an issue with the way this particular server handles incoming messages *(they're currently using the https://github.com/zaphoyd/websocketpp library)*.

**Comment by ng5** [comment]
https://www.websocket.org/echo.html - this is a simple echo server. 
h.connect("wss://echo.websocket.org", nullptr);

You can use another public server - just to confirm uwebsockets client implementation. I ran your code and got all the messages with or without delay.

alternatively here is javascript client implementation, hitting the same server getting similar errors. so definately something is wrong with that server.  Whichever method you choose outcome is same: your server is not working correctly.

You need npm and ws. 
npm install ws

//nodeclient.js
===========
const WebSocket = require('ws');
//const ws = new WebSocket('wss://steemd.steemit.com');
const ws = new WebSocket('wss://echo.websocket.org');
var jsonRpcId = 0;
var msgsRcvd = 0;
ws.on('open', function open() {
    var data = "";
    jsonRpcId++;
    data = {
        id: jsonRpcId,
        method: "call",
        params: "[1,\"login\"]"
    };
    console.log(data);
    ws.send(JSON.stringify(data));
});

ws.on('message', function incoming(data) {
    console.log(data);
});

**Comment by alexpmorris** [comment]
I tried the same requests in nodejs 8.6 using `require('uws')` and it worked perfectly, *without* any additional delays!  At first I thought it could be x86 versus x64 (nodejs), so I recompiled the C++ code for x64, and still had the same results.  Here's the code I used:

```
const WebSocket = require('uws');

const ws = new WebSocket('wss://steemd.steemit.com');
//const ws = new WebSocket('wss://echo.websocket.org');

var jsonRpcId = 0;
var msgsRcvd = 0;

ws.on('open', function open() {
  var data = "";

  data = "{\"id\":1,\"method\":\"call\",\"params\":[1,\"login\",[\"\",\"\"]]}";
  console.log(data);
  ws.send(data);

  data = "{\"id\":2,\"method\":\"get_dynamic_global_properties\",\"params\":[]}";
  console.log(data);
  ws.send(data);

  data = "{\"id\":3,\"method\":\"call\",\"params\":[1,\"get_api_by_name\",[\"database_api\"]]}";
  console.log(data);
  ws.send(data);

  data = "{\"id\":4,\"method\":\"call\",\"params\":[1,\"get_api_by_name\",[\"market_history_api\"]]}";
  console.log(data);
  ws.send(data);

});

ws.on('message', function incoming(data) {
  console.log("RECV " + data);
});

ws.on('close', function close() {
  console.log('disconnected');
});
```

**Comment by alexpmorris** [comment]
I solved the problem, it was staring me in the face the whole time...
```
	h.onMessage([](uWS::WebSocket<uWS::CLIENT> *ws, char *data, size_t length, uWS::OpCode opCode) {
		msgsRcvd++;
		data[length] = 0;
		std::cout << msgsRcvd << " clnt_in " << data << std::endl;
	});
```
I had set `data[length] = 0` so that I could debug the output to console.  What I didn't realize is that the uWebSockets event was also sending me the complete input message stream, which meant I was effectively tossing any bytes (and their respective message events) after that.  Each time I had looked at it earlier, the data after `length` appeared to be junk, but that was likely before I added additional events.  

Foolish oversight on my part, but hopefully it'll help others realize that the (char* data) stream should be immutable from the event context, at least for anything beyond `length`.

```
0 clnt_in {"id":1,"result":true}ü~{"id":2,"result":{"id":0,"head_block_number":16251085, ...
```

**Comment by jimmyt857** [comment]
I'm pretty sure uws will call onMessage once per message received, even when they are received together. When you assign `data[length] = 0;` you are overwriting the WebSocket protocol header for the following message, which probably ruins its ability to parse that message. You should just say `std::string msg = std::string(data, length);` instead.

**Comment by alexpmorris** [comment]
Yeah, that's exactly what was happening, and that's what I *should* have done.  Serves me right for messing with the character buffer in the first place, even as a "quick shortcut". Now it works perfectly every time, just like the `uws` sample I put together in nodejs.

**Comment by alexhultman** [comment]
The buffer is mutable to your liking but data[length] is not even within bounds of the buffer you got. It is like saying malloc is broken because it bugs out when you write outside of the given buffer. Of course any native program will bug out of you write outside of any given buffer.

**Comment by alexpmorris** [comment]
I realize that, but in many implementations I've seen over the years these buffers are often pre-allocated to a fixed length *(so you don't waste cycles repeatedly reallocating your buffer space)*, and when I had first looked at it I saw other data there that would indicate that's how it had been implemented.  

Not denying it was a bit of a "brain fart" on my part, and of course, I also didn't realize that the message was being parsed right back to the same buffer.
