### ISSUE TITLE
Can not get code and reason on close event on the server 

### ISSUE THREAD

**Issue by goriunov** [uNetworking/uWebSockets#724]
I have checked couple of times on linux and windows. I am using node js module 'UWS' and listening on the server on close event. When i pass code and reason from the client i am not able to retrieve it on the server. How ever if i do the same with 'WS' module everything works fine.

'WS'
![image](https://user-images.githubusercontent.com/18750503/31315016-06444466-ac6b-11e7-8d8e-24d006cb4b8d.png)

'UWS'
![image](https://user-images.githubusercontent.com/18750503/31315021-1d07b124-ac6b-11e7-8635-1b2935425260.png)

Can you please fix it _)

Thank you very much.

**Comment by alexhultman** [comment]
It works like it should
