### ISSUE TITLE
Node client connections refused?

### ISSUE THREAD

**Issue by flatfatfishfart** [uNetworking/uWebSockets#725]
I've tried a few different websocket client libraries and all of them successfully connect to Beast and my own websocket server but I am presented with the 1006 error code which is unfortunately not very informative. :[

Has anyone been able to successfully connect to uWebSockets server using a node client?

I'm sorry if this is not the place to post this. I just don't know where else to ask for help.

```
var WebSocket = require('ws');
var ws = new WebSocket("ws://localhost:3000");

ws.on('message', function(message) {
  console.log('Received: ' + message);
});

ws.on('close', function(code) {
  console.log('Disconnected: ' + code);
});

ws.on('error', function(error) {
  console.log('Error: ' + error.code);
});
```

```
Error: ECONNREFUSED
Disconnected: 1006
```

**Comment by NuclearC** [comment]
I was getting the same error with my own websocket client implementation connecting to UWS server, in C++. Problem solved by just changing the client-sided encryption key. I don't know how its possible on node tho :/

**Comment by alexhultman** [comment]
ws can of course connect to and send / receive messages to uws, just like any other client
