### ISSUE TITLE
this.emit is not getting called, in Node JS

### ISSUE THREAD

**Issue by ankibalyan** [uNetworking/uWebSockets#727]
## Frequently posted issues
**Feature X is not 100% identical to feature X of `ws`**  
```this.emit(event, data)``` is not getting executed from connection object.
  
## Include the following information (where applicable):

* What operating system are you running?
  * Linux
* Are you running any CPU architechute out of the normal?
  * I run 64-bit in the year 2017
* What platform/language are you using?
  * Node.js
* Are you using SSL, if so, how?
   No
* What version of uws are you using?
  * master
  * Release v8.14.1
* What features of µWS are involved in the issue?
  * Server support (WebSocket)
* How does the issue reproduce?
  * All the time
* Can you show me some short code that triggers your issue or any other important information?

here is what I'm trying to get json string from the client and then separating with execution flow.

    const { Server } = require('uws');
    const wss = new Server({ port: 5151 })
    const CLIENTS = {}

    function toEvent (message) {
      try {
        const event = JSON.parse(message);
        if (event.type && event.method) {
          this.emit(event.type, event);
        } else {
          console.error('=============== START ERROR LOG BAD_REQUEST ===============');
          console.error(message);
          console.error('=============== END ERROR LOG BAD_REQUEST ===============');
        }
      } catch(err) {
        console.log('not an event' , err);
      }
    }

    wss.on('connection', function(ws) {
      const connectionId = Date.now().toString(36) + Math.random().toString(36).substr(2);
      ws = Object.assign(ws, {id: connectionId})
      CLIENTS[connectionId] = ws;

      ws.send(JSON.stringify({type: 'connection', method: 'connect', id: ws.id}));

      // send message to client
      ws.on('message', toEvent);
      
      ws.on('method', function (data) {
        console.log('=============== START DEBUG LOG on method ===============');
        console.log(data);
        console.log('=============== END DEBUG LOG on method ===============');

        if (typeof this[data.method] === 'function') {
          this[data.method](data)
        }
      });
      ws.on('close', onClose);
      ws.on('error', onError);
    });

    function sendMsg(message) {
      console.log('=============== START DEBUG LOG sendMsg ===============');
      console.log(message);
      console.log('=============== END DEBUG LOG sendMsg ===============');
      Object.keys(CLIENTS).forEach((CLIENT) => {
        if (CLIENT.readyState == CLIENT.OPEN) {
          CLIENT.send(message)
        }
      })
    }
    function sendMsg(message) {
      console.log('=============== START DEBUG LOG sendMsg ===============');
      console.log(message);
      console.log('=============== END DEBUG LOG sendMsg ===============');
      Object.keys(CLIENTS).forEach((CLIENT) => {
        if (CLIENT.readyState == CLIENT.OPEN) {
          CLIENT.send(message)
        }
      })
    }

    function onClose(client) {
      delete CLIENTS[client]
      console.log('client disconnected')
    }

    function onError(err) {
      console.log('=============== START DEBUG LOG on ws connection ===============');
      console.log(err);
      console.log('=============== END DEBUG LOG on ws connection ===============');
      delete CLIENTS[client]
    }

**Comment by alexhultman** [comment]
These issues are listed under frequently posted issues because......... they are frequently posted. Do not post them. Also "I run 64-bit in the year 2017" is clearly a joke, it is not meant to be taken seriously. I don't care if you run 64-bit or not, I care if you run ARM or not (or Sega or whatever strangeness).

**Comment by ankibalyan** [comment]
I'm not able to find out, where have discussed for this.emit,  FAQ page is empty,  Neither Readme has it. Yes I can extend `eventEmitter`, but does it handles by itself like `ws`. Can you please link me the similar issue if know?

**Comment by alexhultman** [comment]
If you search for eventemitter there are 21 duplicated and or similar issues reported. I have said this 20 times prior to this. Next will be 22nd :tada:
