### ISSUE TITLE
How to associate identity from verifyClient to ws

### ISSUE THREAD

**Issue by ericdolson** [uNetworking/uWebSockets#728]
I am using the verifyClient option to validate headers before allowing the connection to be upgraded to a websocket. This is great that I can be selectively permissive about the connections at this point. 

However, once I get the onConnection callback with my websocket that was just established, there is no way to associate what "user" this ws was authorized for.

I would prefer a way to append some identity to the ws at the time of verifyClient instead of the client having to send their identity all over again as the first message.

Is this possible? Would a PR for such a feature be considered?

UPDATE:

I found that the 'ws' project has handled this: https://github.com/websockets/ws/issues/1212

It does not seem to be in 'uws' though. But it seems the need existed there and should be covered here as well.

**Comment by ng5** [comment]
i don't think websocket protocol has any built-in authentication mechanism. I've implemented authentication by sending a security token(XSRF) using **sec-websocket-protocol** header and maintaining a server side session.  Please note that authenticated cookie (if any generated by normal HTTP authentication e.g. SESSIONID) will be automatically sent when you upgrade the protocol. XSRF is only required to prevent cross site forging. You can access SESSIONID and XSRF both and check if a valid session exists before allowing upgrade in onConnection() callback. this blog might help. 

http://blog.stratumsecurity.com/2016/06/13/websockets-auth/

**Comment by alexhultman** [comment]
@ericdolson You can already achieve this, info.req <-> ws.upgradeReq

**Comment by ericdolson** [comment]
What??? Ok how in the world did I miss that @alexhultman. Thank you so much! Sorry for what turned out to be a needless question.
