### ISSUE TITLE
compilation error on Windows Visual Studio 2017 using Boost 1.65.1 

### ISSUE THREAD

**Issue by mrudangit** [uNetworking/uWebSockets#729]
I am trying to compile the uWebSockets on Windows 7 Visual Studio 2017  with Boost 1.65.1 
using USE_ASIO  define 

however getting compilation error:

asio.h(103): error C2039: 'posix': is not a member of 'boost::asio'

**Comment by alexhultman** [comment]
Asio support is unix only

**Comment by mrudangit** [comment]
i see 
with libuv it compiles however the echo server example doesn’t seem to respond to sample node websocket client 
with require(‘ws’) as well as require(‘uws’)

**Comment by alexhultman** [comment]
It is known to work on Windows.

**Comment by mrudangit** [comment]
from browser's websocket client  it is connecting and is working file however node websocket client is not working
