### ISSUE TITLE
Compile with Header: SYSV

### ISSUE THREAD

**Issue by ramonberrutti** [uNetworking/uWebSockets#730]
## Frequently posted issues
**I cannot compile or link the project \<insert compiler or linker error\>**  
Try a released version, master branch is where development happens. If you still have issues then you need to check your end very thoroughly before posting this issue. You are not the only one using µWS and it is probably not this broken.

**Fundamental feature X is broken**  
Again, check your end very thoroughly before posting such an issue. µWS is successfully used by many others.

**You are not using NAN, prebuild or \<insert overrated project X\>**  
I know, this is by design. Things like NAN would render this project a million times more bloated.

**Feature X is not 100% identical to feature X of `ws`**  
Things like EventEmitters differ in behavior between the two projects. Other differences are listed on the main README. This is by design.

**Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system**  
This error message is more accurate than you might think. Install a C++11 compiler or update your distribution. You can also dig in uws.js yourself for more information before posting this issue.
  
## Include the following information (where applicable):

* What operating system are you running?
  * Linux
* Are you running any CPU architechute out of the normal?
  * I run 32-bit in the year 2017
* What platform/language are you using?
  * C++
* Are you using SSL, if so, how?
  * SSL is not part of the equation
* What version of uws are you using?
  * master
* What features of µWS are involved in the issue?
  * Client support (WebSocket)
* How does the issue reproduce?
  * All the time

* Can you show me some short code that triggers your issue or any other important information?

I try adding  -Wl,--hash-style=sysv  and also with -lstdc++  but I always get the GNU/Linux version.
I test with others librarys and adding that work, but with uWebSockets I can't. Is the library?

**Comment by alexhultman** [comment]
This is obviously not a bug. If you toss in a handful of custom flags you have to figure things out yourself.

**Comment by ramonberrutti** [comment]
@alexhultman sorry for this issue. I was wrong compiling the library. Now i compile static and work perfect. Thanks!!
