### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by AlexGladin** [uNetworking/uWebSockets#735]
* Linux Mint
  * C++
  * version: master
  * Server support (HTTP)
  * Randomly (specify approximate percentage)
  * reproduce: All the time

I have some error when try to build example:
`#include <uWS/uWS.h>

int main() {
    uWS::Hub h;

    h.onHttpRequest([](uWS::HttpResponse *res, uWS::HttpRequest req, char *data, size_t length, size_t remainingBytes) {
        res->end("Hello world", 13);
    });

    if (h.listen(3000)) {
        h.run();
    }

    return 0;
}`

Stack of exceptions:
`CMakeFiles/uwsserver.dir/main.cpp.o: In function `main':
/home/alex/CLionProjects/uwsserver/main.cpp:8: undefined reference to `uWS::Group<true>::onHttpRequest(std::function<void (uWS::HttpResponse*, uWS::HttpRequest, char*, unsigned long, unsigned long)>)'
/home/alex/CLionProjects/uwsserver/main.cpp:10: undefined reference to `uWS::Hub::listen(int, uS::TLS::Context, int, uWS::Group<true>*)'
/home/alex/CLionProjects/uwsserver/main.cpp:10: undefined reference to `uS::TLS::Context::~Context()'
/home/alex/CLionProjects/uwsserver/main.cpp:11: undefined reference to `uS::Node::run()'
/home/alex/CLionProjects/uwsserver/main.cpp:10: undefined reference to `uS::TLS::Context::~Context()'
CMakeFiles/uwsserver.dir/main.cpp.o: In function `uS::Socket::write(uS::Socket::Queue::Message*, bool&)':
/usr/include/uWS/Socket.h:309: undefined reference to `SSL_write'
/usr/include/uWS/Socket.h:314: undefined reference to `SSL_get_error'
CMakeFiles/uwsserver.dir/main.cpp.o: In function `uWS::Hub::Hub(int, bool, unsigned int)':
/usr/include/uWS/Hub.h:47: undefined reference to `uS::Node::Node(int, int, int, bool)'
/usr/include/uWS/Hub.h:47: undefined reference to `uWS::Group<true>::Group(int, unsigned int, uWS::Hub*, uS::NodeData*)'
/usr/include/uWS/Hub.h:47: undefined reference to `uWS::Group<false>::Group(int, unsigned int, uWS::Hub*, uS::NodeData*)'
/usr/include/uWS/Hub.h:48: undefined reference to `inflateInit2_'
/usr/include/uWS/Hub.h:47: undefined reference to `uS::Node::~Node()'
CMakeFiles/uwsserver.dir/main.cpp.o: In function `uWS::Hub::~Hub()':
/usr/include/uWS/Hub.h:65: undefined reference to `inflateEnd'
/usr/include/uWS/Hub.h:64: undefined reference to `uS::Node::~Node()'
collect2: error: ld returned 1 exit status
CMakeFiles/uwsserver.dir/build.make:94: recipe for target 'uwsserver' failed
make[3]: *** [uwsserver] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/uwsserver.dir/all' failed
make[2]: *** [CMakeFiles/uwsserver.dir/all] Error 2
CMakeFiles/Makefile2:79: recipe for target 'CMakeFiles/uwsserver.dir/rule' failed
make[1]: *** [CMakeFiles/uwsserver.dir/rule] Error 2
Makefile:118: recipe for target 'uwsserver' failed
make: *** [uwsserver] Error 2`

**Comment by alexhultman** [comment]
Do *not* report you own incompetence as bugs!!
