### ISSUE TITLE
Missing Symbol on build

### ISSUE THREAD

**Issue by mmclau14** [uNetworking/uWebSockets#736]
* What operating system are you running?
  * OS X
* What platform/language are you using?
  * Node.js
* Are you using SSL, if so, how?
  * SSL via µWS or Node.js
* What version of uws are you using?
  * Release v0.14.5
* How does the issue reproduce?
  * All the time
* Can you show me some short code that triggers your issue or any other important information?
  * not currently, will work on recreating in basic electron app.

found this build log

```
  CXX(target) Release/obj.target/uws/src/Extensions.o
  CXX(target) Release/obj.target/uws/src/Group.o
In file included from ../src/Group.cpp:1:
In file included from ../src/Group.h:4:
In file included from ../src/WebSocket.h:4:
In file included from ../src/WebSocketProtocol.h:5:
../src/Networking.h:7:10: fatal error: 'openssl/opensslv.h' file not found
#include <openssl/opensslv.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/uws/src/Group.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/8.4.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/uws
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
```

also, this shows up in stdout

```
dyld: lazy symbol binding failed: Symbol not found: _SSL_library_init
  Referenced from: /Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/uws/uws_darwin_57.node
  Expected in: flat namespace

dyld: Symbol not found: _SSL_library_init
  Referenced from: /Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/uws/uws_darwin_57.node
  Expected in: flat namespace```

**Comment by mmclau14** [comment]
possible culprit? https://stackoverflow.com/questions/45212080/socket-io-native-dependency-issues-with-electron-forge-and-mac-os-x

**Comment by alexhultman** [comment]
#735

**Comment by alexhultman** [comment]
You need to hire someone who knows how to compile a C++ project. This issue tracker is not for posting C++ 101 questions.

../src/Networking.h:7:10: fatal error: 'openssl/opensslv.h' file not found
#include <openssl/opensslv.h>
         ^~~~~~~~~~~~~~~~~~~~

This is as clear of a error message as a compiler can possibly give you.

**Comment by mmclau14** [comment]
yup, so i get that the dependency is missing but where is it missing from? is this because of the dependency that is building it uws?

**Comment by alexhultman** [comment]
> You need to hire someone who knows how to compile a C++ project. This issue tracker is not for posting C++ 101 questions.

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
