### ISSUE TITLE
Improved cluster / load balancing / threading support

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets#788]
Should be added in µSockets and hooked up here.

**Comment by alexhultman** [comment]
You already have some kind of clustering support, FYI. It can be improved, yes.

**Comment by tonyrewin** [comment]
so how to clusterize it?

**Comment by GeorgeShagov** [comment]
From the examples I see only cases when multiple threads are listening to the same port. this is not what I am after.
If I need multiple threads writing the same ws, what would be the scenario here?
Can somebody help with this?
May be there is a timer support for Connection? that could help

**Comment by GeorgeShagov** [comment]
any help???

**Comment by alexhultman** [comment]
@GeorgeShagov You shouldn't have multiple threads writing to the same websocket. One websocket belong to one thread, only that thread should write to it.

If you have multiple threads producing something to be written, use Loop::defer to have the correct thread write to the websocket.
