### ISSUE TITLE
WebSocket client support

### ISSUE THREAD

**Issue by ghost** [uNetworking/uWebSockets#791]
v0.15 will not feature client support but will be added later on together with proper Http client. It would make sense to add client support in a separate release just for that.

**Comment by AdrianEddy** [comment]
It would be nice for Http client to support simple HTTP(s) proxy and chunked responses. If not in the initial release, please consider designing it in a way that those features could be easily implemented by users.
I use those two features in my app (implemented them on top of v0.14) and except the http client itself are the only missing features preventing me from migrating to v0.15

**Comment by aadityataparia** [comment]
Will it support `http/2` ?

**Comment by Suhail** [comment]
+1 to a client

**Comment by maurodelazeri** [comment]
would be nice a ws client

**Comment by maurodelazeri** [comment]
for those who need a sample client websocket , it wraps https://libwebsockets.org/ (pure C)

https://github.com/maurodelazeri/bitmexcpp

**Comment by ibsusu** [comment]
It seems like you're going to handle this in the next version.  I was wondering if there would be any issues if I use libcurl multi stuff with the Loop's `defer` in order to be a simple http client for now.

**Comment by hoytech** [comment]
Hey guys, the v0.14 branch of uWebSockets has websocket client support, so using the older version might be your best bet if you need a client. It's way better than the libwebsockets approach suggested above, and v0.14 is the best C++ library with both server and client support IMO.

I'm got a fork of the v0.14 branch with some minor improvements in it:

https://github.com/hoytech/uWebSockets

* Compression works for client connections (without sliding window for now)
* Server now supports `server_no_context_takeover` if sent by a client (and doesn't allocate a sliding window for that client)
* Allow apps to find out the size of compressed messages (both sent and received) so you can log your compression ratios and such (I kept the API backwards compatible)
* Added some docs on compression: https://github.com/hoytech/uWebSockets/blob/master/docs/User-manual-v0.14.x.md#compression
* Tweaked Makefile a bit so you can build a .a file in addition to an .so

Of course I'm looking forward to client support in v0.18 or whenever and will port over my apps once that is released.

Cheers!

**Comment by alexhultman** [comment]
How should a client API look like?

I think App and SSLApp should be renamed to Server and SSLServer and then introduce Client and SSLClient?

Or something similar

**Comment by AdrianEddy** [comment]
As far as I'm concerned, the client API can be pretty much the same as for server API, except that you call connect instead of listen. You then have the same .get, .post, .ws etc APIs but you deal with responses from the target server instead of requests to your server.

**Comment by alexhultman** [comment]
Please write a few examples of how it could look like in code

**Comment by AdrianEddy** [comment]
Just a few ideas, what do you think? It would work for me, but others please comment too to see what are everyone's needs

```c++
// GET https://example.com/hello
uWS::SSLApp({})
// this can be called immediately to build the 
// HTTP request (add headers etc), and then again when we get the response
// what do you think?
.get("/hello", [](auto *res, auto *req) {
    if (res) {
        // handle the response
    } else {
        // build the request
        req->writeHeader("Authorization", "xyz")
           ->end();
    }
}).connect("example.com", 443, [](auto *token) {
    // Alternatively, .get() can receive full url .get("https://example.com/hello") 
    // and then connect() will take no arguments (as the host and port would
    // be deduced already from the url) - example below in POST
}).run();
```
```c++
// POST https://example.com/upload
uWS::SSLApp({})
.post("https://example.com/upload", [](auto *res, auto *req) {
    if (res) {
        // handle the response
    } else {
        // build the request
        req->writeHeader("Content-Type", "text/plain; charset=utf-8")
           ->end("some POST data");
    }
}).connect([](auto *token) {

}).run();
```
```c++
// WebSockets to https://example.com/ws
uWS::SSLApp({})
.ws<UserData>("/ws", {
    .open = [](auto *ws, auto *req) {
        // May be similar to previous examples, ie. we need a way to add custom headers to the HTTP request before it's sent
        // ...
    },
    .message = [](auto *ws, std::string_view message, uWS::OpCode opCode) {
        // ...
    }
}).connect("example.com", 443, [](auto *token) {

}).run();
```
Also would be nice to have:
- Some way to set the proxy (CONNECT method)
- Allow for a single App or SSLApp to make different requests at any time (so if want to do 100 http requests you don't have to create multiple Apps or event loops)

**Comment by hoytech** [comment]
The 0.14 API works well for me. I haven't really considered how the HTTP client features will interact with websockets, but purely thinking about websockets, here's a quick sketch of an idea:

    struct ConnData { /* ... */ };

    uWS::ClientApp myClient({
        .insecureDontValidateCertYesIknowTheRisks = true,
        // stuff like SSL client cert options?
    }).run();
    
    myClient.connect<ConnData>("wss://server.com:8443/path", {
        .compress = true,
        .slidingWindow = false,

        .open = [](auto *ws) {
            // ws->getUserData() points to a ConnData
        },

        .error = [](int code) {
            std::cout << "Error connecting, reason: " << uWS::code2str(code) << std::endl;
        },

        .close = [](auto *ws, int code, std::string_view message) {
            if (code != uWS::Codes::NORMAL_SHUTDOWN) {
                std::cout << "Disconnection, reason: " << uWS::code2str(code) << std::endl;
            }
        },

        .message = [](auto *ws, std::string_view message, uWS::OpCode opCode, size_t compressedSizeIn) {
            std::cout << "Incoming msg was " << compressedSizeIn << " bytes on wire" << std::endl;

            size_t compressedSizeOut;
            ws->send(message, opCode, &compressedSizeOut);

            std::cout << "Outgoing msg is " << compressedSizeOut << " bytes on wire" << std::endl;
        },
    });

Notice that you pass in a URL which can be either `ws://` or `wss://` just like in 0.14. I think this is convenient since you can just take a URL from the command-line or a config file, and don't have to worry about whether to make a `Client` or `SSLClient`. Of course this would require URL parsing which is a bit annoying. Not a big deal either way, since users could make a wrapper that does it if it's out of scope for the library.

Thanks!

**Comment by 2-5** [comment]
uWebSockets is the fastest ws client library out there. Adding ws client support to 0.18 would allow people using 0.14 to upgrade to the new version.

One possible API, based on @AdrianEddy third suggestion:
```c++
// WebSockets to https://example.com/ws
uWS::SSLApp({})
.ws<UserData>("*", {
    .open = [](auto *ws, auto *req) {
        // ...
    },
    .message = [](auto *ws, std::string_view message, uWS::OpCode opCode) {
        // ...
    }
}).connect("example.com/ws", 443, [](auto *token) {
}).run();
```

**Comment by wbrickner** [comment]
Status on this? Thanks.

**Comment by alexhultman** [comment]
Nobody is paying for a client and I haven't come up with any good interface for clients yet.

**Comment by pps83** [comment]
> Please write a few examples of how it could look like in code

I think your (server) APIs are really nice and close to what nodejs has. Perhaps, client should also follow what works well in nodejs?

**Comment by alexhultman** [comment]
Problem with these proposed client interfaces is that they break the entire idea with uSockets: to hold a **socket context** and then instantiate a **socket** referring to that context.

In other words; you have to first define a shared behavior (the context) then from that context create a socket.

You cannot do both in one function call because then the entire point of all memory hierarchy is wasted.

So the app.ws call needs to be separate from the app.connect call but the app has to be able to hold many different contexts and app.connect has to refer to what context it should use.

The only proposal that remotely follow this rule is this one:

```
uWS::SSLApp({})
.ws<UserData>("*", {
    .open = [](auto *ws, auto *req) {
        // ...
    },
    .message = [](auto *ws, std::string_view message, uWS::OpCode opCode) {
        // ...
    }
}).connect("example.com/ws", 443, [](auto *token) {
}).run();
```

Is it suppoed to map outgoing URL "example.com/ws" to the pattern "*"? Like an inverted Http router?

**Comment by alexhultman** [comment]
> Perhaps, client should also follow what works well in nodejs?

Absolutely not. Node.js is the anti-inspiration in every sense.

**Comment by ibsusu** [comment]
I'm trying to wrap my head around what you're saying.  When I referred to uWebSockets14 client the way the connections happened were with Hubs like so:

```C++
uWS14::Hub* hub = nullptr;
uWS14::Group<uWS14::CLIENT> *hubGroup = nullptr;

hub = new uWS14::Hub(0, false, 16777216);
hubGroup = hub->createGroup<uWS14::CLIENT>();

hubGroup->onConnection([](uWS14::WebSocket<uWS14::CLIENT> *ws, uWS14::HttpRequest req){
  std::cout << "Connected" << std::endl;
  std::string workerInfo = fmt::format("workerinfo-mastersignature:{}/workername:{}/");
  ws->send("hello", 6, uWS14::OpCode::TEXT);
});

hubGroup->onMessage([](uWS14::WebSocket<uWS14::CLIENT> *ws, char *message, size_t length, uWS14::OpCode opCode) {
    std::cout << "Got reply: " << std::string(message, length) << std::endl;
    ws->send(message, strlen(message), uWS14::OpCode::TEXT);
    //ws->terminate();
});

hubGroup->onDisconnection([](uWS14::WebSocket<uWS14::CLIENT> *ws, int code, char *message, size_t length) {
    std::cout << "Disconnect." << std::endl;
});

hubGroup->onError([](uWS14::CLIENT::type errorType){
  ERROR("HubGroup Error, couldn't connect: {}", errorType);
});

hub->connect("ws://someservice.local:3333", nullptr, { }, 5000, hubGroup);
hub->connect("ws://someOtherService.local:3334", nullptr, { }, 5000, hubGroup);  // note the reuse of hubGroup
```

It seems to me that the `HubGroup` from the past is similar to the **socket context** that you're talking about.  The slick thing about the current version of uWebSockets is that the websocket context is built into the server application initialization.  At first glance I don't think that's easily possible to do on the client side.  Each connection needs its own handlers unless you want to heavily generalize it.

I think a modified version of https://github.com/uNetworking/uWebSockets/issues/791#issuecomment-585656572 would work best.  No `.connect()`, just `.run()`.
```
uWS::SSLApp({})
.wsClient<UserData>("wss://example.com:443", {
    .connection = [](auto *ws, auto *req) {
        // ...
    },
    .message = [](auto *ws, std::string_view message, uWS::OpCode opCode) {
        // ...
    },
    .disconnection = [](auto *ws, std::string_view message, uWS::OpCode opCode) {
        // ...
    },
    .error = [](errorType error) {
        // ...
    },
}).run();
```

That rvalue reference settings object is essentially the aforementioned `HubGroup` from what I can tell.  Can you just either have an array of them or allow multiple callings of wsClient to set the handlers and context for different connections?  If it's possible to refer to the SSLApp later then we can connect to a bunch of stuff from within the handlers or with some kind of functionality inside the `UserData`.  I think HubGroup isn't really a good name for it btw.  I have no suggestions for names.

**Comment by ibsusu** [comment]
I would like to add that I have not dropped down into the uSockets internals much so I don't know how reusable the `us_socket_context_t` is or what can be derived from them but from the hammer test https://github.com/uNetworking/uSockets/blob/577c822ac2e27d297eb6ea8712c84db5bbfe3b44/examples/hammer_test.c it seems like they share something.

**Comment by ibsusu** [comment]
Last post for the night, but I think that settings object would work for choosing if we're sending a get, post, or put as well if it's just an http request instead of a websocket initialization request. That would be a `Client` instead of `wsClient`.  I think doing it that way would make it easier to fold both the client and the server together into one run loop.  Whether you want to do that or not is still up in the air though.

**Comment by ibsusu** [comment]
OK so I looked into doing some rough socket work with uSockets and I think I understand what you're getting at by saying that the app.connect needs to understand what context it should refer to.

```C++

struct user_data {
    char *backpressure;
    int length;
    int testvalue;
};

struct us_socket_t* s = us_socket_context_connect(SSL, client_context, other_host, other_port, NULL, 0, sizeof(struct user_data));

struct user_data *usr = (struct user_data *)us_socket_ext(SSL, s);
```

That `usr` right there is separate from any other connection you create even with the same client_context so that equates to the UserData from my previous suggestion.  Is the socket_context for connections only used to connect the loop, handlers and ssl options to the socket?

**Comment by alexhultman-2fa** [comment]
It's a hierarchy from most general to most specific. Only the most specific memory is kept per socket. The most general is kept per loop, which is kept per thread. Every part can have user data, even loop and socket context.

So all settings and callbacks are stored per socket context, not per socket. That's why sockets are down to 90 byte or so. This is very different from how most other implementations do it

**Comment by alexhultman-2fa** [comment]
The socket context is the "behavior". Sockets are created using a specific "behavior". Therefore the API needs to work like this; first you define the behavior then you instantiate from that behavior a socket

**Comment by ibsusu** [comment]
If it's meant to work like that then the previous suggestion is definitely clunky.  Maybe this makes more sense? C++20 allows string literals as a template parameter.  I *think* that feature makes this possible.

Here's how it should be initialized
```C++
uWS::SSLApp({})
.context<"ContextName", UserData>({
    .open = [](auto *ws) {
        // ...
    },
    .message = [](auto *ws, std::string_view message, uWS::OpCode opCode) {
        // ...
    },
    .ping = [](auto *ws) {
        // ...
    },
    .pong = [](auto *ws) {
        // ...
    },
    .close = [](auto *ws, int code, std::string_view closeVal) {
        // ...
    }
})
.context<"ContextName2", UserData>({
    .open = [](auto *ws) {
        // ...
    },
    .message = [](auto *ws, std::string_view message, uWS::OpCode opCode) {
        // ...
    },
    .ping = [](auto *ws) {
        // ...
    },
    .pong = [](auto *ws) {
        // ...
    },
    .close = [](auto *ws, int code, std::string_view closeVal) {
        // ...
    },
})
.run();
```

Here's how it could be used while looping.

This should work for the websocket client

```C++
struct SocketUserData{
    void* something = nullptr;
};

uWS::connect<SocketUserData>(std::string_view contextName, std::string_view host, uint16_t port);  // if the template literals don't work
uWS::connect<"ContextName2", SocketUserData>(std::string_view host, uint16_t port);  // if the template literals work

```


These should work for http requests since the signatures are different.  The API is clean but I don't know about its clarity.  Maybe you can do something with contexts here as well for default handlers.

```C++
uWS::get(std::string_view host, uint16_t port, fu2::unique_function<void(uint8_t*)> &&handler);

uWS::post(std::string_view host, uint16_t port, uint8_t* data, fu2::unique_function<void(uint8_t*)> &&handler);

uWS::put(std::string_view host, uint16_t port,  uint8_t* data, fu2::unique_function<void(uint8_t*)> &&handler);

uWS::patch(std::string_view host, uint16_t port,  uint8_t* data, fu2::unique_function<void(uint8_t*)> &&handler);

uWS::del(std::string_view host, uint16_t port, fu2::unique_function<void(uint8_t*)> &&handler);
```

Input would be appreciated.

**Comment by ibsusu** [comment]
I can't help but feel you've already thought of this solution before but it's the best I can seem to come up with.

**Comment by alexhultman** [comment]
The idea currently is that you attach **behavior** (context) to **routes** (URLs), then **listen** to incoming connections.

Doing the opposite for clients, attaching behavior to whole URLs and then referring to that behavior when connecting could be a natural extension.

This is close to, or identical to what @AdrianEddy proposed.

This makes sense because your behavior is very likely to be grouped by URLs, not by any individual connection. So for instance, all websockets connecting to wss;//api.bitfinex.com are very likely to have the same behavior.

SSLApp().wsClient("api.bitfinex.com", {the behavior here, defined once}).connect("wss://api.bitfinex.com", [](auto *error) {}).

I think this solution has the same benefits and drawbacks as the current incoming router has, for instance, defining the same behavior for many different routes or URLs requires duplicated contexts - but by using wildcards this could be mitigated in similar ways as we already do.

I think this is the best and cleanest API to build on, for now. It makes a lot of sense in my mind, and allows to efficiently re-use contexts when establishing many connections to the same URL/service.

**Comment by alexhultman** [comment]
You could have "*" wildcards for all outgoing URLs, "*.bitfinex.com/*" for semi-wildcards, or entirely static "api.bitfinex.com" ones. "wss://" or "ws://" should be excluded, or ignored if present.

This does make a lot of sense to me. Clearly the best API!

**Comment by alexhultman** [comment]
To those wondering about status - as you can see we have a rough idea about the APIs, but this remains a low priority issue that is not being worked on.

I don't have any customers who want or need client support, they are all on the server side and only care about server side performance. If you want client support, you can order it by paying for contracting hours required to make this happen. I would say 2 weeks or less.

It's not going to happen by waiting for it to happen, so if you need this it's up to you. I have no intention to work on things I have no use for. And frankly, if something is not paid for that means it has no commercial value, hence shouldn't exist. It's basic capitalism at play.

**Comment by dzobbe** [comment]
As you prefer. But the client support would make the library more complete and allow people like me to use it instead of discard it. Cheers ;)

**Comment by ibsusu** [comment]
> As you prefer. But the client support would make the library more complete and allow people like me to use it instead of discard it. Cheers ;)

Go ahead, use an inferior, poorly conceived websocket library since you don't care about quality.  If you cared about your work you'd use this one.

**Comment by dzobbe** [comment]
But I only need to build a secure version of a client websocket. So why should I use this one that does not provide it to me?!

**Comment by ibsusu** [comment]
Then it isn't for you and you have discarded nothing.  Have fun with your project.

**Comment by alexhultman** [comment]
@dzobbe Whatever floats your boat. Doesn't change anything.

**Comment by hst-m** [comment]
the server is where all the performance needs to be, you could use any old client for the websocket client, if you use javascript Deno 1.4 was just released with websocket client https://deno.land/posts/v1.4#websocket-api

**Comment by JSalazar88** [comment]
The above clarifications about the use-case and intention of providing server, but not client, support was very helpful and potentially worth summarized inclusion in the `README`, though not necessary given the callout in the heading as being a "web server".

**Comment by melton1968** [comment]
Any status updates? 

I'd be willing to provide some funding for the development of a client if that is an option.

**Comment by pps83** [comment]
> Any status updates?
> 
> I'd be willing to provide some funding for the development of a client if that is an option.

@alexhultman ^^^

**Comment by alexhultman** [comment]
Holy crap boost::beast is ABSURDLY complex like are they brain dead in designing that interface?

"You want a lever for your gearbox? Pfft, here's the cog you can slide it with your bare hands".

And for SSL, the code is different! Wow!

**Comment by soulmachine** [comment]
@alexhultman Hi Alex, can you create a grant on Gitcoin? So that people who need client APIs can support you

**Comment by tommitytom** [comment]
@alexhultman any update on this?  We've reached the point where we're running other websocket and http clients in a separate thread and we're piping them in via `Loop::defer` and to be honest, it's pretty nasty.  Seems there are a few people willing to sponsor this feature - is this something you're still interested in doing for cash?

**Comment by alexhultman** [comment]
Status is as it was last time someone asked for a status.

**Comment by tommitytom** [comment]
The last status update you gave contained this:

> I don't have any customers who want or need client support, they are all on the server side and only care about server side performance. If you want client support, you can order it by paying for contracting hours required to make this happen. I would say 2 weeks or less.

So does that mean you are, or are not interested in doing paid contract work to implement this feature?

**Comment by alexhultman** [comment]
I have to check, can you contact me over email

**Comment by ddevienne** [comment]
FWIW, my codebase is pure C++17, for both the client and the server. With the former used to test and drive the latter.
(custom industry-specific _protocol_ using WebSocket as the _transport_). I understand most people use clients
directly in the browser, or in Node.JS, so I get why you do just the server. Still, there's definitely (non-paying...)
interest for a C++ client with the quality and speed of your server. Not having two 3rd parties for WebSocket is
in part what's holding up adoption here (not that you care either :)).

**Comment by cjxx2016** [comment]
I finally know why my question was rejected. It turns out that the developers don't intend to make the framework better, but just want to provide only a few interfaces, that's fine. I understand. But there is really no need to speak ill.

**Comment by needmoreram** [comment]
+1 for client support.

@alexhultman would you be open to accepting PRs that gradually implement a client? I'd be willing to chip in time towards this effort!

**Comment by deforation** [comment]
> To those wondering about status - as you can see we have a rough idea about the APIs, but this remains a low priority issue that is not being worked on.
> 
> I don't have any customers who want or need client support, they are all on the server side and only care about server side performance. If you want client support, you can order it by paying for contracting hours required to make this happen. I would say 2 weeks or less.
> 
> It's not going to happen by waiting for it to happen, so if you need this it's up to you. I have no intention to work on things I have no use for. And frankly, if something is not paid for that means it has no commercial value, hence shouldn't exist. It's basic capitalism at play.

Let's say, we would be interested in this.
About how much are we talking here?

**Comment by uNetworkingAB** [comment]
What is your company?

**Comment by Triasmus** [comment]
Does it have to be a single company that pays for this? If we can get an estimate for how much it'll cost, one of us could start a gofundme or something.

I know I'd be willing to contribute some. I don't have a use-case for both a server and client *right now*, but this seems to be the best cpp websocket library and I'd rather integrate it into my current project from [close to] the beginning, since I do have future plans that involve both a server and client. (Right now it's just a client, so I can't use this)

**Comment by uNetworkingAB** [comment]
If you do some kind of crowd funding there's 25% VAT added, and again it highlights the underlying problem; no commercial interest

**Comment by gillsoftab** [comment]
> Triasmus
> Does it have to be a single company that pays for this? If we can get an estimate for how much it'll cost, one of us could start a gofundme or something.
> 
> I know I'd be willing to contribute some. I don't have a use-case for both a server and client _right now_, but this seems to be the best cpp websocket library and I'd rather integrate it into my current project from [close to] the beginning, since I do have future plans that involve both a server and client. (Right now it's just a client, so I can't use this)

Given that the rates are between SEK 800 - SEK 900 you can assume it will take "at least" 1 month (maybe 2) to complete (approx. 167 h per month). That translates to SEK 167000 - SEK 187875 VAT included, just to give you a hint what kind of money it will cost. My company charge the same amount per hour so that's what you usually have to pay for a professional to develop.

**Comment by Triasmus** [comment]
I'm in the US, so there wouldn't be VAT added based on the source of the money (unless you have some weird laws...). If I were to organize the GoFundMe it'd just be a "Help me pay for uWebsockets to implement client capability." There shouldn't be any extra taxes on my end (according to my cursory look) and then between us it'd just be a normal client/contractor relationship.

I assume your problem with "lack of commercial interest" is more along the lines of "no one will be paying you to maintain it after implementation?" There are obviously people willing to put some money towards it, and we won't know how much until we could get some sort of pledge going, but a lack of funds for ongoing maintenance would put a damper on things.

**Comment by gillsoftab** [comment]
@Triasmus I think the discussion went a bit off topic, things that might or might not be true.

**Comment by cirospaciari** [comment]
@uNetworkingAB I will add H3App experimental suporte to C API and after this can I send an PR for a client?

**Comment by uNetworkingAB** [comment]
> wouldn't be VAT added based on the source of the money (unless you have some weird laws

We have weird laws. There is 25% added VAT to anything that touches individuals, regardless where in the world they are. Swedish companies must pay this fee straight to the Swedish state. A gofundme is nothing more than a bunch of individuals paying for servies, and that is 25% added VAT.

**Comment by pha377** [comment]
You have developed the Ferrari of websockets
Not having a client is like owning a Ferrari and using it on a gravel bumpy road
Your benchmarks could include not only the best serving but also the best performant and stable links

**Comment by cirospaciari** [comment]
@pha377 calm down bro, @uNetworkingAB i'm working in an WS Client based on uWS, can i open an PR for this when i have something more stable? I will try to collab with uWS on my free time. In this case this client is for my personal usage, but can evolve with time.
