### ISSUE TITLE
ZeroSSL certificates

### ISSUE THREAD

**Issue by Merethiel** [uNetworking/uWebSockets#795]
Hello, I have certificates generated by letsencrypt to point to my domain which I'm using for secure websocket connections. 
I'm using the tls context as such

uS::TLS::Context tls = uS::TLS::createContext("cert.pem", "key.pem");
if (h.listen(7070,tls)) {
        h.run();
    }
But when I run my websocket client code:

 ws = new WebSocket("wss://domain.pw:8080");

Chrome gives me this error:
 failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR

Unfortunately uWebSockets does not give any indication of whether the certificate and key were available or read properly. 

The certificate could be a problem because it seems there's two certificates in cert file.

-----BEGIN CERTIFICATE-----
.....
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
 

And I'm not sure which one to remove or keep or use both. But when I try visiting the ip address of the domain directly over https while the server is running, I can view the certificate in the browser and the certificate is valid. Which leads me to believe that uWebSockets is loading the certificate but for some reason wss connections can't be made.

**Comment by alexhultman** [comment]
You can try latest code, I know I have had letsencrypt working with it

**Comment by Merethiel** [comment]
Hello Alex,

I've also had letsencrypt working with this in the past; however, this time I generated my certificates with ZeroSSL and I'm not sure what consequences that might have had. But yes I can try the latest version of your code. Do you have any SSL examples on it?

**Comment by alexhultman** [comment]
The front page shows how to do SSL

**Comment by Merethiel** [comment]
Alex,

When I generate a self signed certificate using openssl with the following command:
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes -subj '/CN=mydomain.tld'

The code reads the cert.pem and key.pem just fine because then I can visit the website in the browser and receive an error telling me that the certificate is not trusted. Which means the code is in fact loading the certificate. But when I generate a certificate with ZeroSSL, it does not want to load those certificates. Do you have any solutions?

**Comment by alexhultman** [comment]
You have to look into this on your own. You seem to know why things fail so you know where to start

**Comment by Merethiel** [comment]
Hi Alex, I did manage to solve the issue. It was definitely a certificate problem and not an issue with your code! Thank you.
