### ISSUE TITLE
Idle timeout / automatic ping/pong

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets#801]
as option to context

**Comment by Merethiel** [comment]
I wondered about this. When the websockets are idle for too long they are automatically disconnected? Is there some option to prevent that from happening?

**Comment by alexhultman** [comment]
Yeah that's a good solution, the server doesn't even have to respond to it. That saves a lot of resources.

I had automatic ping in v0.14 but that's more demanding on the server as it has the responsibility of sending to everyone, all the time. Idle timeout is a good solution and it's simpler too.

**Comment by jimmyt857** [comment]
As far as I can tell, there is no way to currently send pings from a browser client to the server. I agree it would consume fewer server resources, but for now could the auto-ping feature be kept? The only alternative is to send the ping from a higher level protocol, which is pretty unsatisfying.

**Comment by kenjichanhkg** [comment]
how are we supposed to do ping/pong now? My chrome ws connection got disconnected every 10-20 seconds.

**Comment by alexhultman** [comment]
It will disconnect as per idleTimeout if you don't send or receive anything, so you either have to make the client send an empty message or the like, or make the server send something.

This issue discussed the autoPing feature to have the server automatically ping clients in time for idleTimeout - if you want me to work on that you can have the people at aax.com pay for the hours, you can reach me on email.
