### ISSUE TITLE
Apache Software Foundation

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets#802]
I'm wondering if it would make sense to transfer ownership to ASF:

* Apache 2.0 is permissive enough, even for a fork.
* I cannot sign it away via bad contracts - nobody can say "hey, we own this because this and that".
* ASF have legal powers to sue people who act like assholes.
* I'm getting bored with web dev..?

**Comment by idoop** [comment]
Maybe you should do what you like and don't be disturbed by the outside world.

**Comment by alexhultman** [comment]
Problem solved, I'm not the legal owner so I cannot sign anything away.
