### ISSUE TITLE
The uSockets folder in the 0.15 series is empty

### ISSUE THREAD

**Issue by idoop** [uNetworking/uWebSockets#804]
I download 0.15.x release and decompression it, but the `uSockets` folder in the 0.15.x is empty. Would you download it `or use git clone --recursive ` first and pack it later?

**Comment by alexhultman** [comment]
This seems like if anything a GitHub bug. They produce the tarballs and it makes sense to also put submodules in there. Check with GitHub what they think about it.

**Comment by idoop** [comment]
Ok,thanks for your reply.

**Comment by ddevienne** [comment]
FWIW, still an empty uSockets directory in 0.15beta2 ZIP file.

Are we supposed to get uSockets sources independently, or uWebSocket's source ZIP is supposed to be "standalone" and contain everything? Thanks, --DD

PS: Is there a way (forum? ML?) to discuss uWebSocket issues or ask for community help (w/o bothering Alex the author)? Or is StackOverflow this only way? Creating actual Issues on GitHub doesn't seem like a good way for this.

**Comment by alexhultman** [comment]
I can't fix that, it's a GitHub issue.

Do you have any idea what would be a good community platform? Now that both C++ and JS projects are the exact same interfaces, it could make sense to let Node.js people collaborate with C++ people in the same "room".

**Comment by dvergeylen** [comment]
https://www.discourse.org/ might be of interest :thinking:.

**Comment by alexhultman** [comment]
Is it possible for mere mortals to create subreddits? Reddit is pretty well established.
