### ISSUE TITLE
WebSocket - Safari - Invalid UTF-8 sequence in header value

### ISSUE THREAD

**Issue by PooyaEimandar** [uNetworking/uWebSockets#811]
Hi
How can I prevent this error in https connection in Safari.

> WebSocket - Safari - Invalid UTF-8 sequence in header value

**Comment by alexhultman** [comment]
You'll have to provide far more info than this.

**Comment by PooyaEimandar** [comment]
I changed my server in order to support https, after that, after that, safari couldn't open my websocket and thrown following error.
Invalid UTF8 sequence in header value.

Safari/WebKit does not like empty headers. In this particular case, the problem is the empty Set-Cookie: header. It is a bug in Webkit. Chrome had that problem too but they fixed it in Blink.
Remove that header in the server response and it should work.

**Comment by alexhultman** [comment]
I don't know what you mean, there are no empty headers and I just tried SSL WebSockets on macOS and it works just fine.

**Comment by PooyaEimandar** [comment]
Did you test it with Safari?

**Comment by alexhultman** [comment]
Yes

**Comment by PooyaEimandar** [comment]
Thank you for reply.
I'm going to close this issue.

**Comment by alexhultman** [comment]
You can find Node.js builds for macOS later on, use those to check if it works. If those work, then you know it is possible to get this to work also.
