### ISSUE TITLE
res.begin()

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets#816]
Optionally it should be possible to call res.begin() before writing headers and res.end or res.tryEnd.

What happens is you guarantee corking of headers and response, even when responding "async".

res.begin(); must have an immediate end or tryEnd call

res.writeHeader(lalalaal)
res.writeHeader(lalalaalala)

res.end(lalalaal); or res.tryEnd(lalalaalal)

**Comment by alexhultman** [comment]
It can also be res.cork(() => {
// write your response here
})

That way it is impossible to NOT do it properly.

**Comment by alexhultman** [comment]
There's experimental support for this now. It boosts performance a lot in some cases. res.cork(lambda)

**Comment by dalisoft** [comment]
@alexhultman I can't [use](https://github.com/uNetworking/uWebSockets.js/issues/147) `res.cork(() => {...})`, says `TypeError: res.cork is not a function`

**Comment by mattiasewers** [comment]
@dalisoft the method is called `res.experimental_cork`

**Comment by dalisoft** [comment]
@mattiasewers Both `res.experimental_cork` and `res.cork` isn't available

**Comment by mattiasewers** [comment]
@dalisoft Did you install `uNetworking/uWebSockets.js#binaries`?

**Comment by dalisoft** [comment]
@mattiasewers Yea. Passing host make it work :)
