### ISSUE TITLE
Pong functionality is disabled

### ISSUE THREAD

**Issue by adamkaplan** [uNetworking/uWebSockets#819]
I understand via #801 that you aren't too keen on using server-side ping/pong as a keep-alive and prefer client-side keep alive. That approach makes sense, and I buy the argument completely.

The problem is that pong appears to be completely disabled after v0.14 for some reason. This prevents systems that do rely on the spec's ping-pong control packets from working properly with uWebSockets.

https://github.com/uNetworking/uWebSockets/blob/7d990a3bc177271eb64af2f58c30a5253507fa7f/src/WebSocketContext.h#L180

In my particular case, I want to test swapping in uWebSockets instead of one of the competing libraries that is in your benchmark graph. I am using ping/pong, and I have a million+ shipped clients that cannot be quickly ported to client-side keep-alive.

Any good reason why pong is disabled? It would be better to be compliant to the RFC. I'm happy to enabled it, but I won't send a PR if you have a reason.

**Comment by alexhultman** [comment]
We can bring those back, I disabled them to make a release. It's all about time - need to release something stable very soon.

Yahoo Finance? I've used that site to watch some stocks - but I can't see that they use any websockets? For me it's http polling?

**Comment by adamkaplan** [comment]
There's no recurring polling on the website AFAIK. There is a home rolled streaming solution in place which predates ubiquitous stable websockets in browsers. You might mistake it for polling by the way it works. About 50% of web users are seeing websockets. You're probably not in the test bucket.. try a private browser window or two.

100% of the iOS and Android users have been using it for over a year. But you'll have to use the web to play with it because most of the apps are SSL Pinned.

**Comment by alexhultman** [comment]
Ah, cool. Chrome with private window did have WS.

**Comment by adamkaplan** [comment]
Awesome!

If you can get it fixed, I will try this project out and see how it does under our load which is concurrent connections in the six figures and very high message rate.

I'm currently using [ws](https://github.com/websockets/ws) on Node, with some optimizations. The idea is to use approachable tools (hence Node) for the non-performance sensitive stuff, and go crazy optimizing only the critical path. It's not clear that ws will be slower than uWebSockets, despite that I believe your benchmark chart. I have tuned ws to work with the Yahoo Finance use case: mostly identical messages with tons of subscribers.

For example, instead of using the naive `sockets.forEach { ws => ws.send(data) }`, I precompute the full RFC-6455 frame once, and send it directly to all clients. That trick massively improved the throughput of ws.

So the critical path is basically just executing `ws.sender.sendFrame(frame)` with a binary frame thousands of times a second. i.e. this is the line of ws that is in the most critical path: https://github.com/websockets/ws/blob/master/lib/sender.js#L394

With uWebSockets, the server will be much faster and lower overhead overall. However I suspect that the frame repeated construction will still weigh down the throughput. I'm happy to try adding something like `broadcast(listOfWs, payload, opcode)` if you can get ping/pong working :D

**Comment by alexhultman** [comment]
For a price tag you can send me a mail.

**Comment by alexhultman** [comment]
You have no contact information whatsoever. Do you want things fixed or not? I can prioritize things and help out with getting things working if you contact me. I don't want to chase you via Tumblr or whatever that is.

**Comment by adamkaplan** [comment]
I just had not yet come back to this issue yet and since you did not add any new comments, did not think it a priority. Anyway Github wasn't showing my email anymore for some reason, and I have fixed that. Thanks for pointing it out!

**Comment by marchaos** [comment]
Hey. Any reason for this to still be commented out? We were making use of this on uWS which seem to work without issue.

**Comment by alexhultman** [comment]
It's not going to fix itself

**Comment by alexhultman** [comment]
Ping/pong handlers are working, but most importantly the pub/sub has come a long way. There are similar users who run it in prod.
