### ISSUE TITLE
Uncorked WebSocket sends should be temporarily corked if allowed

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets#827]

**Comment by alexhultman** [comment]
This could be solved in similar ways as for HttpResponse::cork(lambda), in fact that support could really be moved down to AsyncSocket as a foundation feature and then just add a note about it in the docs/user manual.

After that, a smarter more implicit solution can be made, but we still need AsyncSocket::cork anyways.

**Comment by not-implemented** [comment]
I do not understand exactly, what's the goal here - but maybe this will solve my current problem:

We need to put multiple WebSocket-Messages into a single TCP/TLS-packet. I patched WebSocket.h to expose `cork()`/`uncork()` now ... and it works when I call:

```c++
socket->cork();
socket->send(message1, opCode, true);
socket->send(message2, opCode, true);
// ...
socket->uncork();
```

I know, the cork-buffer is shared, so cork/uncork has to be used with care. And I understand when you do not want to expose it. But it would be interesting, if there are other ideas for that - and this issue sounds promising.

**Comment by alexhultman** [comment]
I think the idea was to have AsyncSocket::cork take a lambda so that it is impossible to mess up the cork/uncorking.

**Comment by not-implemented** [comment]
Ah ... now I understand, thanks (sorry, didn't have a look at `HttpResponse::cork()` before).

Yes, sounds good!

**Comment by not-implemented** [comment]
@alexhultman: Perfect ... and nice interface, thanks!
