### ISSUE TITLE
Better way to do redirects?

### ISSUE THREAD

**Issue by andymans** [uNetworking/uWebSockets#830]
In the scenario where we need to:
1. Receive a request
2. Do some work
3. Redirect that request somewhere else

I'm seeing very sluggish performance (some seconds in fact)

I suspect it's my own fault. On a NodeJS Http (or Polka) server I normally do:

`res.writeHead(302, {'Location', 'http://some-other-url'})`

and the performance is acceptable. On UWebSockets.js I'm trying as follows:

```
res.writeStatus('302')
res.writeHeader('location', ''http://some-other-url')
res.end()
```
but the delay is palpable. Is there a better approach?

**Comment by alexhultman** [comment]
#828

**Comment by andymans** [comment]
Closing as #828 will fix.
