### ISSUE TITLE
ExtensionsParser

### ISSUE THREAD

**Issue by yangxingpping** [uNetworking/uWebSockets#831]
When I want to create more than one instance of app. So I need include App.h in more than one xxx.cpp,
But that cause ExtensionsParser::ExtensionsParser(...) redefined, and I find class ExtensionsParser's member function declare and definition are both in WebSocketExtensions.h file. Does that because of new branch was designed for head only library, so do like this ?

**Comment by alexhultman** [comment]
This should be fixed now
