### ISSUE TITLE
uS::Async segmentationfault with libuv

### ISSUE THREAD

**Issue by yangxingpping** [uNetworking/uWebSockets#836]
When I try to use uWS14.xx with one uS::Async object by define MACRO USE_LIBUV, program crashed in uS::Async::start(...) function, with stack info is:
Program received signal SIGSEGV, Segmentation fault.
0x00005555556bf49f in uv_async_init (loop=0x5555559872e0, handle=0x7fffffffdd30,
    async_cb=0x555555582b1d <<lambda(uS::Async*)>::_FUN(uS::Async *)>)
    at /root/source/vcpkg/buildtrees/libuv/src/v1.25.0-b119df65cf/src/unix/async.c:48
48        uv__handle_init(loop, (uv_handle_t*)handle, UV_ASYNC);
(gdb) bt
#0  0x00005555556bf49f in uv_async_init (loop=0x5555559872e0, handle=0x7fffffffdd30,
    async_cb=0x555555582b1d <<lambda(uS::Async*)>::_FUN(uS::Async *)>)
    at /root/source/vcpkg/buildtrees/libuv/src/v1.25.0-b119df65cf/src/unix/async.c:48
#1  0x00005555555834fd in uS::Async::start (this=0x7fffffffdd30,
    cb=0x555555582b1d <<lambda(uS::Async*)>::_FUN(uS::Async *)>)
    at /root/source/vcpkg/installed/x64-linux/include/uWS/Libuv.h:41

libuv version is 1.25.0

**Comment by alexhultman** [comment]
v0.14 is not developed anymore
