### ISSUE TITLE
can we have a golang library?

### ISSUE THREAD

**Issue by jjhesk** [uNetworking/uWebSockets#841]
I hope that there is a golang library exported. Any plan to make a go wrapper for this library that is ready to deploy and no need to do CGO.

**Comment by alexhultman** [comment]
Hello - I think that's not the way to go(lang). There are high performance alternatives for Go already, see graph. For Node.js and Python and Lua and whatnot, where you have a lacking language, it makes sense to offload things to C++ but for Golang you already have a decent language as can be shown with gobwas/ws and valyala/fasthttp.

**Comment by jjhesk** [comment]
thank you!, I was comparing to the chart alone and think if that can be also wrap this uwebsock into go because there are still distinguish differences from both language implementations.

**Comment by alexhultman** [comment]
It's not going to fit. Golang is very peculiar and does not have a standardized C base you can link to.
