### ISSUE TITLE
0.14 - 0.15 feature parity - non-blocking way to poll events

### ISSUE THREAD

**Issue by Izowiuz** [uNetworking/uWebSockets#842]
I'm currently migrating my application from 0.14.x to 0.15.x version of uWS.
This project already uses its own event loop - the one provided by the Qt framework.
In the 0.14 release I used non-blocking poll() function of the uWS::Hub to, well, poll events using my own timer.

As I understand, at the level of uWS, we currently only have blocking run() method.
Going one level lower - to the uSockets sources - I see interfaces for the 'us_poll' structs that get internally used in loop.c in, for example, us_internal_dispatch_ready_poll.
Are they the way to implement non-blocking event polling?

**Comment by alexhultman** [comment]
Why aren't you using the Qt WebSocket support? There's no need to use a high performing server software if you're just going to trash it up by putting it inside a timer of another GUI event loop. I don't get it-what kind of GUI app needs a web server and cannot use qwebsocket?

**Comment by Izowiuz** [comment]
I'm using GUI-less QCoreApplication derived classes to implement a very, very simple game server software. Qt loop is there mainly for their nice abstraction around SQL related stuff and signal-slot mechanism used in less performance critical situations.

In my humble tests uWS easliy outperformed QWebSockets at pretty much everything, even when using poll() function - especially when I added SSL to it.

It would be nice if I could strip Qt from this project completly. Maybe I will look at replacing QSql* classes with something else.

**Comment by alexhultman** [comment]
Okay hmm yeah maybe we can add the same poll function but really, it kind of opens up for lazy integrations that should really be done as proper plugins instead. Qsocketnotifier kind of integration. Anyways, let's see about this

**Comment by alexhultman** [comment]
Why don't you do the opposite? Put Qt polling in a timer of uWS? Qt definitely have that support and we have timers

**Comment by Izowiuz** [comment]
Yea, I will definitely try this. Thank you.

Other idea I have is to split "server" part of the app into two threads. One for the uWS - high perf communication - and other for the QCoreApplication - for the 'nice-but-slower' features.

**Comment by Izowiuz** [comment]
This actually works pretty great :] I also see slight performance improvement against similar solution that uses 0.14 release.

One problem I'm having is a suspicious crash somewhere at the level of contex.c file, seemingly at random times. From what I see method us_socket_context_loop() tries to dereference an invalid context.
I will try to check if problem is at my end. I will post another issue if I'll found something.

If you don't want to track anything with this issue I believe it can be closed. This is probably much more optimal solution than calling poll() from Qt loop - aside from proper Qt based loop plugin.

**Comment by alexhultman** [comment]
> works pretty great

and

> suspicious crash somewhere

are kind of mutually exclusive but sure 😉

**Comment by Izowiuz** [comment]
Yes, I suppose they kind of are :]

By suspicious I mean that I reduced my code to the EchoServer.cpp example plus additional timer which only spins Qt's event loop. No data goes between uWS and Qt and I just spam ws messages at uWS server from external source.

I currently blame my setup but I need some more time to properly isolate this. I have to try this on my VPS based on Linux. Who knows, maybe compiling stuff with prerelease versions of Visual Studio causes it.
