### ISSUE TITLE
Http an ws callbacks. Why pointers?

### ISSUE THREAD

**Issue by guffy1234** [uNetworking/uWebSockets#843]
Hi Alex
Why you use pointers 
(auto* req, auto* resp)
Instead of references
(const auto& req, auto& resp)
?
And in methods of responce you use
auto* foo() { return this; }
Instead of
auto& foo() { return *this; }

Is there some significant reason to use pointers?

Sorry that it a bit violate your rule about questions

**Comment by alexhultman** [comment]
That's just how it is, both V8 and C deal with pointers. Malloc returns a pointer.
