### ISSUE TITLE
multithread safe uWS::Loop::defaultLoop()

### ISSUE THREAD

**Issue by yangxingpping** [uNetworking/uWebSockets#844]
When I try to create two app object in two thread, the Loops in each thread is confused, then program crashed. code snippet is:

**void threadhttp1()
{
uWS::App app.get("/*",[](auto* resp, auto* req){resp->end("hello.world");})
.listen(10086,[](auto* token){}).run();
}
void threadhttp2()
{
uWS::App app.get("/*",[](auto* resp, auto* req){resp->end("hello.world");})
.listen(10087,[](auto* token){}).run();
}
thread th1(threadhttp1);
thread th2(threadhttp2);
th1.join();
th2.join();**

It's crash on uv's timer mini-heap with access null pointer at most of time. Finally I found the function uWS::Loop::defaultLoop() is not thread safe.

**Comment by alexhultman** [comment]
I don't know, you can check for yourself

**Comment by yangxingpping** [comment]
Add an mutex lock guard in defaultLoop() has performance impact, so I try make sure multithread safe at first call uWS::Loop::defaultLoop() in each thread function, we call the defaultLoop() with a mutex lock guard as the first  call. After that, it's work! 

std::mutex g_lock;
void threadhttp1()
{
{std::lock_guard<std::mutex> lock(g_lock); uWS::Loop::defaultLoop();}
uWS::App app.get("/_",[](auto_ resp, auto* req){resp->end("hello.world");})
.listen(10086,[](auto* token){}).run();
}
void threadhttp2()
{
{std::lock_guard<std::mutex> lock(g_lock); uWS::Loop::defaultLoop();}
WS::App app.get("/_",[](auto_ resp, auto* req){resp->end("hello.world");})
.listen(10087,[](auto* token){}).run();
}
thread th1(threadhttp1);
thread th2(threadhttp2);
th1.join();
th2.join();

**Comment by alexhultman** [comment]
Good find, it's now fixed inside defaultLoop
