### ISSUE TITLE
Some "uws client" Examples?

### ISSUE THREAD

**Issue by LeMoussel** [uNetworking/uWebSockets#854]
I want to do an "C++ uws client" with  subscription message.
I'm not sure how to do so...
I didn't find any examples of that. 

Any Info?

Regards.

**Comment by alexhultman** [comment]
There is no client support. Client is your browser

**Comment by cnaccio** [comment]
Client isn't necessarily your browser; in many cases we need to communicate with websocket APIs from backend services; would be great to have client support with similar amazing performance.

**Comment by kadko** [comment]
open websocket connection in your html :
let socket = new WebSocket("ws://127.0.0.1:9001/hello");`

**Comment by JSalazar88** [comment]
Definitely okay with the mission of this repo to provide a server implementation. However, has anyone identified any industry trends regarding which c++ web socket client libraries are being paired with uWebSockets server deployments, that is architecture recommendations which include uWebSockets server components and xxyy client library components?
