### ISSUE TITLE
Using with existing loops requires new or modified constructor on TemplatedApp

### ISSUE THREAD

**Issue by abrownsword** [uNetworking/uWebSockets#855]
Updating to the latest version I found that the us_integrate_loop call is no longer the right way to use my existing libuv loop.  Instead the designed path is through TemplatedApp's constructor where it calls uWS::Loop::get().  Unfortunately it doesn't allow for an existingNativeLoop pointer to be passed in and through get, so I needed to add another constructor overload:

`	TemplatedApp(void *existingNativeLoop, us_new_socket_context_options_t options = {}) {
		httpContext = uWS::HttpContext<SSL>::create(uWS::Loop::get(existingNativeLoop), options);
	}
`

After adding this, everything seems to be working fine, including shutdown where the previously reported problem was occurring.

**Comment by alexhultman** [comment]
The idea is you call

Loop::get(uv_default_loop()) first.

"get" is maybe a misleading name, "init" could be a better one, but it works

**Comment by abrownsword** [comment]
Ah, that'll work.  Thanks.  Might want to put a note somewhere obvious about that.
