### ISSUE TITLE
Is there a release plan for the websocket client?

### ISSUE THREAD

**Issue by lano2088** [uNetworking/uWebSockets#865]

**Comment by tommitytom** [comment]
https://github.com/uNetworking/uWebSockets/issues/791

**Comment by alexhultman** [comment]
I have no idea, that may never happen. Nobody has expressed commercial interest in that.

**Comment by lano2088** [comment]
There are many people with this need.

**Comment by lano2088** [comment]
How much do you charge for your commercial edition?

**Comment by alexhultman** [comment]
I don't have any commercial version, but I accept contracts adding features

**Comment by mrlika** [comment]
You can give a try to https://opencollective.com/ or something similar. Setup goals and implement features once a goal is reached.

**Comment by alexhultman** [comment]
Maybe, I don't know. It's not a priority.
