### ISSUE TITLE
Cannot remove fallback buffer of HttpParser before emitting websocket open event

### ISSUE THREAD

**Issue by mrlika** [uNetworking/uWebSockets#867]
I got 2 similar segmentation faults that are most likely caused by malformed requests. Here is the log output:
```
2019-03-23T03:08:14.936Z wt-tracker:uws-tracker-requests 0.0.0.0 443 ws-open url: / query:  origin: https://www.streamlive.to total: 286
2019-03-23T03:08:29.554Z wt-tracker:uws-tracker-requests 0.0.0.0 443 ws-open url: ^@ query:  origin: https://www.streamlive.to total: 283
Segmentation fault (core dumped)
```
First line is how looks normal request. Second line is how looks fault request. Symbol ^@ from the log refers to 0x00.

uWebSockets.js v15.8.0

This is how I gather the logs:
https://github.com/Novage/wt-tracker/blob/master/lib/uws-tracker.ts#L91

**Comment by alexhultman** [comment]
It should be fixed now. I wound up adding salvageFallbackBuffer to the parser, basically the same solution but we only move the fallback buffer not the whole HttpResponseData

**Comment by alexhultman** [comment]
fallback is always padded with at least sizeof std::string before parsing, so SSO cannot happen (it is kind of a hack but works). The hack is at least contained in the HttpParser module and exposed as a public function
