### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [uNetworking/uWebSockets#870]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") in [the destructor for the class “WebSocketData”](https://github.com/uNetworking/uWebSockets/blob/a0eeb769c97aa2666d4254f8acb03db1d9a48b6c/src/WebSocketData.h#L54 "Destructor for WebSocketData").

**Comment by alexhultman** [comment]
It literally makes no difference either way. It's nice to see the intended behavior even if it's technically redundant (before optimization).

**Comment by elfring** [comment]
How do you think about corresponding software design options?
* Adjusted class hierarchy (and fine-tuning of involved member variables)
* Application of a smart pointer

**Comment by alexhultman** [comment]
If anything std::unique_ptr, but I'm not sure how deep that change would be. It's a pretty pointless thing to care for given the many bugs, issues and features with priority.
