### ISSUE TITLE
Memory allocation error - incorrect checksum for freed object

### ISSUE THREAD

**Issue by wehriam** [uNetworking/uWebSockets#871]
**Description**

Memory allocation errors occur when launching 100 servers that do not appear when launching 10 servers in the same configuration.

 - OS: Mac OS 10.14
 - Node: Homebrew v10.15.2

**Code to reproduce**

https://github.com/bunchtogether/braid-server/blob/master/tests/peers-ring.test.js

(Apologies, I have been unable to reproduce in a simpler example.)

**Output**

```
node(65675,0x1091595c0) malloc: Incorrect checksum for freed object 0x104819200: probably modified after being freed.
Corrupt value: 0x1baffed00baffedf
node(65675,0x1091595c0) malloc: *** set a breakpoint in malloc_error_break to debug
```

**Extended Description**

The Braid application syncs key-value pairs between a small network of peers and a larger network of read-only subscribers. All communication between the peer and subscriber processes occurs over WebSockets.

In this test 100 uWebSocket servers are created and linked in a ring using [ws](https://www.npmjs.com/package/ws), i.e. peer A opens a connection to peer B, peer B opens a connection to peer C, peer C opens a connection to peer A.

When the test is reduced to 10 uWebSocket servers the error does not occur.

**Thanks**

Thanks for the great work and let me know if there is any additional information I can provide.

**Comment by alexhultman** [comment]
Could you try out 15.9.0?

**Comment by wehriam** [comment]
Still present in 15.9.0:

```
node(92178,0x10af8e5c0) malloc: Incorrect checksum for freed object 0x10517ac00: probably modified after being freed.
Corrupt value: 0x1baffed00baffedf
node(92178,0x10af8e5c0) malloc: *** set a breakpoint in malloc_error_break to debug
```

**Comment by alexhultman** [comment]
You have to strip down your code and provide instructions. I don't know what to do with it.

**Comment by wehriam** [comment]
To run the tests and trigger the error you can “yarn install” then “yarn test” from the linked repo - but I wasn’t able to create an example that reproduces the error building from the bottom up. (See the previous code.)

I’ll work on

**Comment by alexhultman** [comment]
I figured npm install npm test but I got error when npm installing. So yarn install yarn test should work better?

**Comment by wehriam** [comment]
I've updated the repo to work with npm, ```npm install``` followed by ```npm run test:js``` should work.

```bash
git clone https://github.com/bunchtogether/braid-server.git
cd braid-server/
npm install
npm run test:js
```

**Comment by wehriam** [comment]
Also, while I can still reproduce the error with the test suite, it does seem to be less frequent with 15.9.0, happening ~30% of the time instead of 90% with 15.8.0.

**Comment by alexhultman** [comment]
How can I run that test without any other process or mid-step? Only vanilla nodejs, no test runner or anything. These files don't contain JavaScript, it's some kind of typed thing.

I need to run only nodejs and only that one script that triggers the issue.

**Comment by wehriam** [comment]
These files use Flow, which is like Typescript. I’ll work on a version that triggers the error without the test framework or type checking.

**Comment by alexhultman** [comment]
Did you make any progress? I would like to run AddressSanitizer on the nodejs process that runs this test. But I don't know how to do that with all of these test runner parent processes spawning things to the left and right.

**Comment by alexhultman** [comment]
Even if you don't see any error, how can I run without spawning any new process?

**Comment by wehriam** [comment]
To run the example without spawning:

```js
node tests/malloc-example.js
```

**Comment by alexhultman** [comment]
Perfect, will try this out

**Comment by jeremy-j-ackso** [comment]
Chiming in with something sort of relevant: I started watching this issue because it's similar to an error I'm coming across. I have a C addon that I wrote for Node, but I'm only using Mocha for my test framework. I also only get the error when running my tests. Practice samples seem to work fine.

I'm starting to think that it may be a problem related to mocha with native addons. Mocha is a dependency of Jest, so could be relevant?

**Comment by alexhultman** [comment]
I cannot reproduce this on Linux and I own no Apple products. It may be something about forking the process on non-Linux systems, as it really only has been tested on Linux.

Really, spawning multiple processes on non-Linux is completely untested.

You say it only happens when spawning processes? Can you try it on Linux instead?
