### ISSUE TITLE
How to broadcast?

### ISSUE THREAD

**Issue by dvergeylen** [uNetworking/uWebSockets#875]
Hi Alex,

In v0.14, there was [uS::Async](https://github.com/uNetworking/uWebSockets/wiki/User-manual-v0.14.x#usasync) allowing to ask the thread responsible for websocket communication to send ws messages (respecting ownership and avoiding thread unsafe problems).

I've seen in TopicTree constructor you are assigning a `postHandler` to thread's Loop and feeding `pubNodes` vector that will be cleared by Loop's postHandler. Is this the way to go to implement broadcast?

Unfortunately TopicTree is still work in progress → how can I help on this? I can ask you for  a quotation but I am an indie dev  :grimacing:.

Would you mind sharing a canonical way of broadcasting with v0.15?

**Comment by dvergeylen** [comment]
Except `write` is `protected`, `send` seems the way to go for now.

In that case broadcast might not be efficient as the same message will be processed again and again, would it be possible to send a preparedMessage like before? That way we could prepare the message once (if no or shared deflationStream) and send raw data multiple times... :thinking: 

Thoughts?

**Comment by yangxingpping** [comment]
Is uS::Loop::defer(...) is what you search for?

**Comment by dvergeylen** [comment]
Yes, thanks :+1:

**Comment by alexhultman** [comment]
Broadcasting is done via pub/sub functions -> they are missing

**Comment by alexhultman** [comment]
#790
