### ISSUE TITLE
Receive chunked encoding (new http parser)

### ISSUE THREAD

**Issue by ghost** [uNetworking/uWebSockets#881]
Parse and emit data

**Comment by alexhultman** [comment]
This will be implemented as part of a rewrite/cleanup of the current http parser.

A goal is to simplify the code, modernize it and remove lambdas in favor of a much simpler iterator-based parser.

**Comment by ma-rom** [comment]
Does this mean that chunked transfer encoding is currently not supported in 19.2.0?
