### ISSUE TITLE
vcpkg not updating to most recent revision.

### ISSUE THREAD

**Issue by JadeVand** [uNetworking/uWebSockets#882]
When installing uWebSockets through vcpkg, version 0.14 is installed rather than the most recent (master branch). Are you able to update the ports in vcpkg to install the most recent revisions? Or does it have to be done manually?

**Comment by alexhultman** [comment]
Tell them about the issue and let them fix it. They are paid to keep their project up to date.

**Comment by JadeVand** [comment]
I have posted the issue to them though I'm not sure how long they'll take to fix it. I did it through vcpkg for consistency but I'll install libuv and uWebSockets from the repos instead.
