### ISSUE TITLE
Echo server example cannot start on windows10

### ISSUE THREAD

**Issue by seamusmore** [uNetworking/uWebSockets#885]
![image](https://user-images.githubusercontent.com/35286167/56557190-c12a0100-65cc-11e9-9466-6edc30d38a38.png)
Runtime error occur when start EchoServer on win10 at line 785 in function2.hpp.
My IDE is VS2017.

**Comment by seamusmore** [comment]
I didn't use makefile to generate VS project. I just create a blank project and add the EchoServer.cpp into the project. I compile the project successful but failed when start program. The HelloWorld example can run  normally.

**Comment by alexhultman** [comment]
Try with latest version
