### ISSUE TITLE
UDP support?

### ISSUE THREAD

**Issue by BotoX** [uNetworking/uWebSockets#887]
Was available in v14, removed in v15, will it come back?
(Using v14 right now for a torrent tracker, was about to refactor to v15)

**Comment by alexhultman** [comment]
You mean Unix sockets?

**Comment by BotoX** [comment]
Nope, I mean adding UDP / Datagram sockets to the event loop so I get events from both TCP (HTTP) and UDP sockets from the same uWebSockets event loop.
Then I can read the actual data from the UDP socket myself using recvmsg.

Was possible like so in v14:
```
bool ret = h.listen<HandleUDP>(
			host,
			port,
			nullptr,
			uS::ListenOptions::REUSE_PORT | uS::ListenOptions::LISTEN_UDP,
			(uS::NodeData *)(uWS::Group<uWS::SERVER> *)hub,
			nullptr);


HandleUDP(uS::Socket *s;) {
    uv_os_sock_t fd = s->getFd();
    int recvd = recvmsg(fd, msg, flags);
}
```

**Comment by alexhultman** [comment]
I'm pretty sure this never was a thing, anyways..

You want to use us_poll from uSockets to just add your FD, or if that is not possible, just straight up use libuv they have UDP sockets.

**Comment by BotoX** [comment]
Could be that I hacked support into uWebSockets at the time and forgot, thanks for the tip with us_poll will look into it.
I guess the issue is probably in the wrong repo anyways, if anything then uSockets should have support for opening (possibly reading/writing) UDP sockets.
