### ISSUE TITLE
Error while building target uWs on Ubuntu 16.04

### ISSUE THREAD

**Issue by HoangHa91** [uNetworking/uWebSockets#889]
I got the error while try to run CMake with uWebsocket.
the error description as below 

```
[ 73%] Built target uWS
Scanning dependencies of target multithreaded_echo
[ 80%] Building CXX object examples/CMakeFiles/multithreaded_echo.dir/multithreaded_echo.cpp.o
[ 86%] Linking CXX executable multithreaded_echo
../libuWS.so: undefined reference to `SSL_CTX_up_ref'
../libuWS.so: undefined reference to `OPENSSL_init_ssl'
../libuWS.so: undefined reference to `TLS_client_method'
../libuWS.so: undefined reference to `SSL_CTX_set_options'
../libuWS.so: undefined reference to `TLS_server_method'
collect2: error: ld returned 1 exit status
examples/CMakeFiles/multithreaded_echo.dir/build.make:99: recipe for target 'examples/multithreaded_echo' failed
make[2]: *** [examples/multithreaded_echo] Error 1
CMakeFiles/Makefile2:124: recipe for target 'examples/CMakeFiles/multithreaded_echo.dir/all' failed
make[1]: *** [examples/CMakeFiles/multithreaded_echo.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
[ 73%] Built target uWS
[ 80%] Linking CXX executable multithreaded_echo
../libuWS.so: undefined reference to `SSL_CTX_up_ref'
../libuWS.so: undefined reference to `OPENSSL_init_ssl'
../libuWS.so: undefined reference to `TLS_client_method'
../libuWS.so: undefined reference to `SSL_CTX_set_options'
../libuWS.so: undefined reference to `TLS_server_method'
collect2: error: ld returned 1 exit status
examples/CMakeFiles/multithreaded_echo.dir/build.make:99: recipe for target 'examples/multithreaded_echo' failed
make[2]: *** [examples/multithreaded_echo] Error 1
CMakeFiles/Makefile2:124: recipe for target 'examples/CMakeFiles/multithreaded_echo.dir/all' failed
make[1]: *** [examples/CMakeFiles/multithreaded_echo.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
ln: failed to create symbolic link '/usr/lib/libuWS.so': File exists

```

anyone can help me with this ??? many thanks

**Comment by alexhultman** [comment]
You need openssl 1.1+ or disable openssl

**Comment by HoangHa91** [comment]
> You need openssl 1.1+ or disable openssl
Thanks, but I tried and it's still the same issue.

**Comment by alexhultman** [comment]
No you didn't.

**Comment by chop0** [comment]
Wow, you're a wanker

**Comment by alexhultman-2fa** [comment]
Yes I'm a **horrible** person for not personally tutoring everyone on the internet, for free, who cannot figure out how to link a C++ project. I'm **that** horrible of a person. How **dare** I set up personal rules for how I dispose my professional time. I'm a horrible, **dreadful** person.

**Comment by chop0** [comment]
Someone reported an issue on a project of yours, and you just rudely told them it didn't exist rather than trying to work out what is wrong. Looking at google, you have a bit of history of being unconstructive

**Comment by chop0** [comment]
You just shut down a bug report with no attempt to work out what is going wrong. You by no means need to support this project, but at least say that. You don't know what the issue was; you didn't ask for any clarification or details

**Comment by alexhultman-2fa** [comment]
The very first post **screams** of the culprit, which I even explained:


```
[ 86%] Linking CXX executable multithreaded_echo
../libuWS.so: undefined reference to `SSL_CTX_up_ref'
../libuWS.so: undefined reference to `OPENSSL_init_ssl'
../libuWS.so: undefined reference to `TLS_client_method'
../libuWS.so: undefined reference to `SSL_CTX_set_options'
../libuWS.so: undefined reference to `TLS_server_method'
collect2: error: ld returned 1 exit status
```

Quote

> You need openssl 1.1+ or disable openssl

This project **doesn't even use CMake**, so expecting me to support people who use their own building tools (unsuccessfully) is an **incredible** stupid argument.

You talk like you know what it's like, yet you have no fucking idea what it takes to not lose your mind running an open source project.

I once took a shit, 10 minutes long, and received two building error bug reports during that very break.

Once you've taken a shit like that you can call me and we can talk.

**Comment by HoangHa91** [comment]
Hello, I've found this issue in my last year project. 
I posted it here because you are the owner of the project I used, but your reply is the same as million people out there. 
You once took a shit and treat other like you took a ton of shit thousand time. Thanks but may be you no need to reply because it helps nothing.
Once more thing that I do the same step in another computer with same environment and magically it work. I knew why after that, but for sure it's not because your reply.  Very appreciate your work but if you feel to hard to help other, you can say nothing, it's better than spending time to agrue with other that you're doing nothing wrong.

**Comment by alexhultman-2fa** [comment]
This is like a symphony of contradiction.

Nanana NA NA, nanana NA NA; na di dah :notes: 

:trumpet:

**Comment by alexhultman-2fa** [comment]
> but your reply is the same as million people out there

Yes. Maybe, just maybe consider that those millions of people **are right**.

> You just shut down a bug report with no attempt to work out what is going wrong. You by no means need to support this project, but at least say that. You don't know what the issue was; you didn't ask for any clarification or details

https://stackoverflow.com/questions/12573816/what-is-an-undefined-reference-unresolved-external-symbol-error-and-how-do-i-fix

This question has thousands of upvotes and is entirely why I don't care to spend more than five seconds on users who cannot figure it out. Of course I knew what the issue was, it's fucking blatantly obvious.
