### ISSUE TITLE
HTTP Reason Phrase

### ISSUE THREAD

**Issue by nikes** [uNetworking/uWebSockets#890]
Now http server send this HTTP/1.1 200\r\n
But with some libs he can't parse http state line without reason phrase.

https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html

**Comment by alexhultman** [comment]
I don't understand

**Comment by nikes** [comment]
At protocol need
HTTP/1.1 200 OK,
But now u not send reason phrase 'OK'

**Comment by nikes** [comment]
This is not necessary, but some applications can not parse the answer, so there is no reason.

**Comment by alexhultman** [comment]
https://github.com/uNetworking/uWebSockets/blob/master/src/HttpResponse.h#L35

**Comment by nikes** [comment]
Hm.... Ao mb i not use the last version... But check this tomorrow, but thx.

**Comment by nikes** [comment]
@alexhultman using v.15.10.0 (node.js lib)
Info from curl

```
HTTP/1.1 200
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
Content-Type: application/json
uWebSockets: v0.15
Content-Length: 16
```
