### ISSUE TITLE
Can this work with CentOS 5?

### ISSUE THREAD

**Issue by kayechica** [uNetworking/uWebSockets#894]
I currently have CentOS5/Rhel5 machine with the following old environment specs:
cmake version 2.8.11
gcc (GCC) 4.1.2
OpenSSL 0.9.8h
Will there be restrictions if I use this library in my current environment?
I had problems with libwebsockets library so I am looking for alternatives.
Please let me know.
Thanks.

**Comment by alexhultman** [comment]
This is not a big report and I have no interest doing your errands for you.
