### ISSUE TITLE
Does it accept tcp data sending ?

### ISSUE THREAD

**Issue by Taymindis** [uNetworking/uWebSockets#899]
I saw there is a regular tcp-only app supported, does it accept tcp data sending from client side?

**Comment by ctubio** [comment]
nope, see https://github.com/uNetworking/uWebSockets/issues/791 or https://github.com/uNetworking/uWebSockets/search?q=client&type=Issues

**Comment by alexhultman** [comment]
You can do stuff with uSockets, Loop::get() returns an us_loop ptr
