### ISSUE TITLE
Read the "Read this before posting". No chats but can create chat on slack/telegram?

### ISSUE THREAD

**Issue by hiqsociety** [uNetworking/uWebSockets#908]
1. No chats but can create an official chat on slack/telegram?
2. Need more "complete" / real life useful scenario demo examples with redis backend etc 
3. async or futures (coroutine)... what do u suggest to work with uwebsocket?

it's a great software. Thanks.

**Comment by alexhultman** [comment]
Hello, for my sanity I try and not provide any personal help as that would eat up all my time and more.

This issue tool is therefore used only as a bug reporting tool. You have the "Read more" user manual and there are some examples.

**Comment by hiqsociety** [comment]
yes i understand. can you pls create an official channel / group so others can contribute to help answer questions? that'll be great for ideas exchanges and sharing. telegram will be best. u dont have to answer anything. we will help each other out amongst ourselves.

**Comment by alexhultman** [comment]
You can start any chat channel anywhere as you wish but I don't have time to moderate it so it won't be "official". You already have StackOverflow and such peer-built places to look at
