### ISSUE TITLE
add length check before substr (the question maybe only on my pc).

### ISSUE THREAD

**Issue by yathon** [uNetworking/uWebSockets#909]
when i used the websockets, i always catch a exception about "xmemory0", and i can not find why.
It looks like std::basic_string is wrong, and i have no idea. At the last i think is my physical memory not enough? OK!!! I get it !!!
modify AsyncSocket.h line 126:
`asyncSocketData->buffer = asyncSocketData->buffer.substr(written);`
to:
```
if (written)
{
	asyncSocketData->buffer = asyncSocketData->buffer.substr(written);
}
```
Why do this? I found that the function "us_socket_write" return only two result : 0 and send length. Even I know it is not bug, but if someone else catch the same exception. 

In any case, it works !!! It works !!! It works !!!

**Comment by alexhultman** [comment]
You skip all the buffering of unsent data if you add this. I don't know what or why you get problems but could you do some more digging and see what you find?

Try running with AddressSanitizer or Valgrind or similar?
