### ISSUE TITLE
How does this library's performance compare to UDP? 

### ISSUE THREAD

**Issue by elieobeid7** [uNetworking/uWebSockets#910]
Didn't see it in the benchmark, unless I missed it. I'm using this library for a game, so I'd like to know. And I guess [these guys](https://github.com/lance-gg/lance/issues/98) would like to know too. Too many people would love to know.

**Comment by alexhultman** [comment]
What is better? Hammer or wrench?

**Comment by elieobeid7** [comment]
I get that, I'm not even trying to compare, I was curious to have an idea about the performance, that's all.

**Comment by alexhultman** [comment]
I can't help you sorry
