### ISSUE TITLE
High load, 100% cpu usage

### ISSUE THREAD

**Issue by gmatej** [uNetworking/uWebSockets#912]
I am having problems handling 300 req/s. In a testing environment with around 30 req/s the CPU usage is around 0.3 -0.7.

But when going to production it spikes to 100% and stays there. The messages are not small can sometimes be 10-40KB. Still, I don't understand why the high CPU.

The logic is that from the received message we send it directly sent to Redis using hiredis. We had this directly coupled but now we do it in another thread and a memory queue. Still CPU usage goes to 100%.

We are sending binary messages. Is this a buffer size problem?

**Comment by gmatej** [comment]
In prod we have around 5000 connections and it's linux, meaning 100% CPU is one core fully loaded.

**Comment by gmatej** [comment]
It was ulimit issue. Sorry for that... But it's hard to find because no errors are thrown...

**Comment by rodrigoreis22** [comment]
> It was ulimit issue. Sorry for that... But it's hard to find because no errors are thrown...

Hi @gmatej , what ulimit configuration do you have now to fix this problem?
