### ISSUE TITLE
help, uWebSocket, crash when enable websocket compress on CentOS7.0

### ISSUE THREAD

**Issue by balloonwj** [uNetworking/uWebSockets#915]
Crash in uWS::Hub::deflate， my version is uWebSockets-0.15.7.
my crash stack is as follows:
(gdb) bt
#0  0x00007f173823e14c in build_tree () from /opt/marketserver/libs/libz.so.1
#1  0x00007f173823e7b0 in _tr_flush_block () from /opt/marketserver/libs/libz.so.1
#2  0x00007f17382328a3 in deflate_fast () from /opt/marketserver/libs/libz.so.1
#3  0x00007f173823453d in deflate () from /opt/marketserver/libs/libz.so.1
#4  0x00000000005babe8 in uWS::Hub::deflate (this=0x279ed28, 
    data=0x7f16f8019268 "{\"table\":\"order\",\"action\":\"partial\",\"keys\":[\"orderID\"],\"types\":{\"orderID\":\"guid\",\"clOrdID\":\"symbol\",\"clOrdLinkID\":\"symbol\",\"account\":\"long\",\"symbol\":\"symbol\",\"side\":\"symbol\",\"simpleOrderQty\":\"float\",\"orderQty\":\"long\",\"price\":\"float\",\"displayQty\":\"long\",\"stopPx\":\"float\",\"pegOffsetValue\":\"float\",\"pegPriceType\":\"symbol\",\"currency\":\"symbol\",\"settlCurrency\":\"symbol\",\"ordType\":\"symbol\",\"timeInForce\":\"symbol\",\"execInst\":\"symbol\",\"contingencyType\":\"symbol\",\"exDestination\":\"symbol\",\"ordStatus\":\"symbol\",\"triggered\":\"symbol\",\"workingIndicator\":\"boolean\",\"ordRejReason\":\"symbol\",\"simpleLeavesQty\":\"float\",\"leavesQty\":\"long\",\"simpleCumQty\":\"float\",\"cumQty\":\"long\",\"avgPx\":\"float\",\"multiLegReportingType\":\"symbol\",\"text\":\"symbol\",\"transactTime\":\"timestamp\",\"timestamp\":\"timestamp\"},\"foreignKeys\":{\"symbol\":\"instrument\",\"side\":\"side\",\"ordStatus\":\"ordStatus\"},\"attributes\":{\"orderID\":\"grouped\",\"account\":\"grouped\",\"ordStatus\":\"grouped\",\"workingIndicator\":\"grouped\"},\"filter\":{\"account\":172114},\"data\":[]}", length=@0x7f17157e7928: 994, slidingDeflateWindow=0x0)
    at /opt/build/market/market/websocket/Hub.cpp:29
#5  0x00000000005b169e in uWS::WebSocket<true>::send(char const*, unsigned long, uWS::OpCode, void (*)(uWS::WebSocket<true>*, void*, bool, void*), void*, bool)::WebSocketTransformer::transform(char const*, char*, unsigned long, uWS::WebSocket<true>::send(char const*, unsigned long, uWS::OpCode, void (*)(uWS::WebSocket<true>*, void*, bool, void*), void*, bool)::TransformData) (
    src=0x7f16f8019268 "{\"table\":\"order\",\"action\":\"partial\",\"keys\":[\"orderID\"],\"types\":{\"orderID\":\"guid\",\"clOrdID\":\"symbol\",\"clOrdLinkID\":\"symbol\",\"account\":\"long\",\"symbol\":\"symbol\",\"side\":\"symbol\",\"simpleOrderQty\":\"float\",\"orderQty\":\"long\",\"price\":\"float\",\"displayQty\":\"long\",\"stopPx\":\"float\",\"pegOffsetValue\":\"float\",\"pegPriceType\":\"symbol\",\"currency\":\"symbol\",\"settlCurrency\":\"symbol\",\"ordType\":\"symbol\",\"timeInForce\":\"symbol\",\"execInst\":\"symbol\",\"contingencyType\":\"symbol\",\"exDestination\":\"symbol\",\"ordStatus\":\"symbol\",\"triggered\":\"symbol\",\"workingIndicator\":\"boolean\",\"ordRejReason\":\"symbol\",\"simpleLeavesQty\":\"float\",\"leavesQty\":\"long\",\"simpleCumQty\":\"float\",\"cumQty\":\"long\",\"avgPx\":\"float\",\"multiLegReportingType\":\"symbol\",\"text\":\"symbol\",\"transactTime\":\"timestamp\",\"timestamp\":\"timestamp\"},\"foreignKeys\":{\"symbol\":\"instrument\",\"side\":\"side\",\"ordStatus\":\"ordStatus\"},\"attributes\":{\"orderID\":\"grouped\",\"account\":\"grouped\",\"ordStatus\":\"grouped\",\"workingIndicator\":\"grouped\"},\"filter\":{\"account\":172114},\"data\":[]}", 
    dst=0x7f16f8017860 "t89b, expiredTime: 1564147332, signature: 36d936f9dca5c096b1c129771eacf6f4b009af57e0e81ce11025c02eaeb33174, clientID: 7470865580, accountID: 1355087893, url: http://192.168.1.24/api/v1/accountx, response: [{\"currMargin\":8499782,\"frozenMargin\":0,\"capitalFee\":0,\"capitalFeeTimestamp\":1564147195165,\"transfer\":0,\"settlementId\":0,\"buyCost\":0,\"sellCost\":0,\"buyVolSum\":0,\"sellVolSum\":0,\"noFilledCnt\":0,\"fee\":-2371,\"withdrawFee\":0,\"transferAccount\":0,\"transferClient\":0,\"largess\":0,\"compensation\":0,\"sinked\":true,\"reduceRealisedPnl\":0,\"clientId\":\"7470865580\",\"account\":\"1355087893\",\"currency\":\"XBT\",\"riskLimit\":1", '0' <repeats 12 times>, ",\"prevState\":\"\",\"state\":\"\",\"action\":\"\",\"amount\":0,\"pendingCredit\":80000000000,\"pendingDebit\":0,\"confirmedDebit\":0,\"prevRealisedPnl\":null,\"prevUnrealisedPnl\":null,\"grossComm\":-2371.00,\"grossOpenCost\":0,\"grossOpenPremium\":0,\"grossExecCost\":null,\"grossMarkValue\":18374400,\"riskValue\":18374400,\"taxableMargin\":0,\"initMargin\":0,\"maintMargin\":8499782,\"sessionMargin\":0,\"targetExcessMargin\"4", length=994, transformData=...) at /opt/build/market/market/websocket/WebSocket.cpp:54
#6  0x00000000005b496c in uS::Socket::sendTransformed<uWS::WebSocket<true>::send(char const*, unsigned long, uWS::OpCode, void (*)(uWS::WebSocket<true>*, void*, bool, void*), void*, bool)::WebSocketTransformer, uWS::WebSocket<true>::send(char const*, unsigned long, uWS::OpCode, void (*)(uWS::WebSocket<true>*, void*, bool, void*), void*, bool)::TransformData>(char const*, unsigned long, void (*)(void*, void*, bool, void*), void*, uWS::WebSocket<true>::send(char const*, unsigned long, uWS::OpCode, void (*)(uWS::WebSocket<true>*, void*, bool, void*), void*, bool)::TransformData) (this=0x7f16f800b160, 
    message=0x7f16f8019268 "{\"table\":\"order\",\"action\":\"partial\",\"keys\":[\"orderID\"],\"types\":{\"orderID\":\"guid\",\"clOrdID\":\"symbol\",\"clOrdLinkID\":\"symbol\",\"account\":\"long\",\"symbol\":\"symbol\",\"side\":\"symbol\",\"simpleOrderQty\":\"float\",\"orderQty\":\"long\",\"price\":\"float\",\"displayQty\":\"long\",\"stopPx\":\"float\",\"pegOffsetValue\":\"float\",\"pegPriceType\":\"symbol\",\"currency\":\"symbol\",\"settlCurrency\":\"symbol\",\"ordType\":\"symbol\",\"timeInForce\":\"symbol\",\"execInst\":\"symbol\",\"contingencyType\":\"symbol\",\"exDestination\":\"symbol\",\"ordStatus\":\"symbol\",\"triggered\":\"symbol\",\"workingIndicator\":\"boolean\",\"ordRejReason\":\"symbol\",\"simpleLeavesQty\":\"float\",\"leavesQty\":\"long\",\"simpleCumQty\":\"float\",\"cumQty\":\"long\",\"avgPx\":\"float\",\"multiLegReportingType\":\"symbol\",\"text\":\"symbol\",\"transactTime\":\"timestamp\",\"timestamp\":\"timestamp\"},\"foreignKeys\":{\"symbol\":\"instrument\",\"side\":\"side\",\"ordStatus\":\"ordStatus\"},\"attributes\":{\"orderID\":\"grouped\",\"account\":\"grouped\",\"ordStatus\":\"grouped\",\"workingIndicator\":\"grouped\"},\"filter\":{\"account\":172114},\"data\":[]}", length=994, callback=0x0, callbackData=0x0, 
    transformData=...) at /opt/build/market/market/websocket/Socket.h:384
#7  0x00000000005c178d in uS::NodeData::NodeData (this=0x7f16f800b160) at /opt/build/market/market/websocket/Networking.h:199
#8  0x0000000000602e1e in WebSocketSession::send (this=0x7f16f800b3a0, 
    pData=0x7f16f8019268 "{\"table\":\"order\",\"action\":\"partial\",\"keys\":[\"orderID\"],\"types\":{\"orderID\":\"guid\",\"clOrdID\":\"symbol\",\"clOrdLinkID\":\"symbol\",\"account\":\"long\",\"symbol\":\"symbol\",\"side\":\"symbol\",\"simpleOrderQty\":\"float\",\"orderQty\":\"long\",\"price\":\"float\",\"displayQty\":\"long\",\"stopPx\":\"float\",\"pegOffsetValue\":\"float\",\"pegPriceType\":\"symbol\",\"currency\":\"symbol\",\"settlCurrency\":\"symbol\",\"ordType\":\"symbol\",\"timeInForce\":\"symbol\",\"execInst\":\"symbol\",\"contingencyType\":\"symbol\",\"exDestination\":\"symbol\",\"ordStatus\":\"symbol\",\"triggered\":\"symbol\",\"workingIndicator\":\"boolean\",\"ordRejReason\":\"symbol\",\"simpleLeavesQty\":\"float\",\"leavesQty\":\"long\",\"simpleCumQty\":\"float\",\"cumQty\":\"long\",\"avgPx\":\"float\",\"multiLegReportingType\":\"symbol\",\"text\":\"symbol\",\"transactTime\":\"timestamp\",\"timestamp\":\"timestamp\"},\"foreignKeys\":{\"symbol\":\"instrument\",\"side\":\"side\",\"ordStatus\":\"ordStatus\"},\"attributes\":{\"orderID\":\"grouped\",\"account\":\"grouped\",\"ordStatus\":\"grouped\",\"workingIndicator\":\"grouped\"},\"filter\":{\"account\":172114},\"data\":[]}", dataLength=994)
    at /opt/build/market/market/appsrc/WebSocketSession.cpp:53
#9  0x0000000000602e93 in WebSocketSession::send (this=0x7f16f800b3a0, 
    strResponse="{\"table\":\"order\",\"action\":\"partial\",\"keys\":[\"orderID\"],\"types\":{\"orderID\":\"guid\",\"clOrdID\":\"symbol\",\"clOrdLinkID\":\"symbol\",\"account\":\"long\",\"symbol\":\"symbol\",\"side\":\"symbol\",\"simpleOrderQty\":\"float\",\"orderQty\":\"long\",\"price\":\"float\",\"displayQty\":\"long\",\"stopPx\":\"float\",\"pegOffsetValue\":\"float\",\"pegPriceType\":\"symbol\",\"currency\":\"symbol\",\"settlCurrency\":\"symbol\",\"ordType\":\"symbol\",\"timeInForce\":\"symbol\",\"execInst\":\"symbol\",\"contingencyType\":\"symbol\",\"exDestination\":\"symbol\",\"ordStatus\":\"symbol\",\"triggered\":\"symbol\",\"workingIndicator\":\"boolean\",\"ordRejReason\":\"symbol\",\"simpleLeavesQty\":\"float\",\"leavesQty\":\"long\",\"simpleCumQty\":\"float\",\"cumQty\":\"long\",\"avgPx\":\"float\",\"multiLegReportingType\":\"symbol\",\"text\":\"symbol\",\"transactTime\":\"timestamp\",\"timestamp\":\"timestamp\"},\"foreignKeys\":{\"symbol\":\"instrument\",\"side\":\"side\",\"ordStatus\":\"ordStatus\"},\"attributes\":{\"orderID\":\"grouped\",\"account\":\"grouped\",\"ordStatus\":\"grouped\",\"workingIndicator\":\"grouped\"},\"filter\":{\"account\":172114},\"data\":[]}") at /opt/build/market/market/appsrc/WebSocketSession.cpp:61
#10 0x000000000060c79c in BusinessSession::send (this=0x7f16f800b3a0, 
    strResponse="{\"table\":\"order\",\"action\":\"partial\",\"keys\":[\"orderID\"],\"types\":{\"orderID\":\"guid\",\"clOrdID\":\"symbol\",\"clOrdLinkID\":\"symbol\",\"account\":\"long\",\"symbol\":\"symbol\",\"side\":\"symbol\",\"simpleOrderQty\":\"float\",\"orderQty\":\"long\",\"price\":\"float\",\"displayQty\":\"long\",\"stopPx\":\"float\",\"pegOffsetValue\":\"float\",\"pegPriceType\":\"symbol\",\"currency\":\"symbol\",\"settlCurrency\":\"symbol\",\"ordType\":\"symbol\",\"timeInForce\":\"symbol\",\"execInst\":\"symbol\",\"contingencyType\":\"symbol\",\"exDestination\":\"symbol\",\"ordStatus\":\"symbol\",\"triggered\":\"symbol\",\"workingIndicator\":\"boolean\",\"ordRejReason\":\"symbol\",\"simpleLeavesQty\":\"float\",\"leavesQty\":\"long\",\"simpleCumQty\":\"float\",\"cumQty\":\"long\",\"avgPx\":\"float\",\"multiLegReportingType\":\"symbol\",\"text\":\"symbol\",\"transactTime\":\"timestamp\",\"timestamp\":\"timestamp\"},\"foreignKeys\":{\"symbol\":\"instrument\",\"side\":\"side\",\"ordStatus\":\"ordStatus\"},\"attributes\":{\"orderID\":\"grouped\",\"account\":\"grouped\",\"ordStatus\":\"grouped\",\"workingIndicator\":\"grouped\"},\"filter\":{\"account\":172114},\"data\":[]}") at /opt/build/market/market/appsrc/BusinessSession.cpp:1112
#11 0x00000000006048a0 in WebSocketSessionManager::handPackge (this=0x27f4440, pMsg=0x7f1739712010 "\354\364\313\n\200a\030\200\021ދ\265\205*\357\322l\242\034\261qxS\362\347\224\364\335;\242\247;8\033<3c\314A\004", msgLength=90, pws=0x7f16f800b160)
    at /opt/build/market/market/appsrc/WebSocketSessionManager.cpp:358
#12 0x00000000005fb0cf in WebSocketServer::__lambda8::operator() (__closure=0x7f16f8000920, pws=0x7f16f800b160, pMsg=0x7f1739712010 "\354\364\313\n\200a\030\200\021ދ\265\205*\357\322l\242\034\261qxS\362\347\224\364\335;\242\247;8\033<3c\314A\004", 
    msgLength=90, opCode=uWS::TEXT) at /opt/build/market/market/appsrc/WebSocketServer.cpp:120
#13 0x00000000005fccce in std::_Function_handler<void(uWS::WebSocket<true>*, char*, long unsigned int, uWS::OpCode), WebSocketServer::run()::__lambda8>::_M_invoke(const std::_Any_data &, uWS::WebSocket<true> *, char *, unsigned long, uWS::OpCode) (
    __functor=..., __args#0=0x7f16f800b160, __args#1=0x7f1739712010 "\354\364\313\n\200a\030\200\021ދ\265\205*\357\322l\242\034\261qxS\362\347\224\364\335;\242\247;8\033<3c\314A\004", __args#2=90, __args#3=uWS::TEXT)
    at /usr/include/c++/4.8.2/functional:2071
---Type <return> to continue, or q <return> to quit---
#14 0x00000000005b4334 in std::function<void (uWS::WebSocket<true>*, char*, unsigned long, uWS::OpCode)>::operator()(uWS::WebSocket<true>*, char*, unsigned long, uWS::OpCode) const (this=0x279ee28, __args#0=0x7f16f800b160, 
    __args#1=0x7f1739712010 "\354\364\313\n\200a\030\200\021ދ\265\205*\357\322l\242\034\261qxS\362\347\224\364\335;\242\247;8\033<3c\314A\004", __args#2=90, __args#3=uWS::TEXT) at /usr/include/c++/4.8.2/functional:2471
#15 0x00000000005b0a53 in uWS::WebSocket<true>::handleFragment (data=0x7f1739712010 "\354\364\313\n\200a\030\200\021ދ\265\205*\357\322l\242\034\261qxS\362\347\224\364\335;\242\247;8\033<3c\314A\004", length=90, remainingBytes=0, opCode=1, fin=true, 
    webSocketState=0x7f16f800b1a0) at /opt/build/market/market/websocket/WebSocket.cpp:341
#16 0x00000000005b67ab in uWS::WebSocketProtocol<true, uWS::WebSocket<true> >::consumeMessage<6u, unsigned char> (payLength=73 'I', 
    src=@0x7f17157e7e98: 0x7f173975e01d "\301ɪV\312/P\262R*.M*N.\312LJU\322QJ,J/V\262\212V\312/JI-\262\212p\n\t\rv\001\n\247V\244&\227\226d\346\347\001\331\005\371řPf.Py&\262X@bQb\256Rl-", length=@0x7f17157e7e94: 79, wState=0x7f16f800b1a0)
    at /opt/build/market/market/websocket/WebSocketProtocol.h:131
#17 0x00000000005b3d46 in uWS::WebSocketProtocol<true, uWS::WebSocket<true> >::consume (
    src=0x7f173975e01d "\301ɪV\312/P\262R*.M*N.\312LJU\322QJ,J/V\262\212V\312/JI-\262\212p\n\t\rv\001\n\247V\244&\227\226d\346\347\001\331\005\371řPf.Py&\262X@bQb\256Rl-", length=79, wState=0x7f16f800b1a0)
    at /opt/build/market/market/websocket/WebSocketProtocol.h:347
#18 0x00000000005b06bc in uWS::WebSocket<true>::onData (s=0x7f16f800b160, data=0x7f173975e01d "\301ɪV\312/P\262R*.M*N.\312LJU\322QJ,J/V\262\212V\312/JI-\262\212p\n\t\rv\001\n\247V\244&\227\226d\346\347\001\331\005\371řPf.Py&\262X@bQb\256Rl-", 
    length=79) at /opt/build/market/market/websocket/WebSocket.cpp:197
#19 0x00000000005be290 in uS::Socket::ioHandler<uWS::WebSocket<true> > (p=0x7f16f800b160, status=0, events=1) at /opt/build/market/market/websocket/Socket.h:262
#20 0x00000000005cccf6 in uS::Loop::doEpoll (this=0x27a0690, epollTimeout=-1) at /opt/build/market/market/websocket/Epoll.cpp:35
#21 0x00000000005ccef2 in uS::Loop::run (this=0x27a0690) at /opt/build/market/market/websocket/Epoll.cpp:64
#22 0x00000000005b9989 in uS::Node::run (this=0x279ed28) at /opt/build/market/market/websocket/Node.cpp:64
#23 0x00000000005fb266 in WebSocketServer::run (this=0x279ed20) at /opt/build/market/market/appsrc/WebSocketServer.cpp:128
#24 0x0000000000602be5 in std::_Mem_fn<bool (WebSocketServer::*)()>::operator()<, void>(WebSocketServer*) const (this=0x2801e70, __object=0x279ed20) at /usr/include/c++/4.8.2/functional:601
#25 0x0000000000602ae6 in std::_Bind<std::_Mem_fn<bool (WebSocketServer::*)()> (WebSocketServer*)>::__call<bool, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (this=0x2801e70, 
    __args=<unknown type in /opt/marketserver/marketserver, CU 0x36f1e7, DIE 0x3b3851>) at /usr/include/c++/4.8.2/functional:1296
#26 0x0000000000602a18 in std::_Bind<std::_Mem_fn<bool (WebSocketServer::*)()> (WebSocketServer*)>::operator()<, bool>() (this=0x2801e70) at /usr/include/c++/4.8.2/functional:1355
#27 0x0000000000602936 in std::_Bind_simple<std::_Bind<std::_Mem_fn<bool (WebSocketServer::*)()> (WebSocketServer*)> ()>::_M_invoke<>(std::_Index_tuple<>) (this=0x2801e70) at /usr/include/c++/4.8.2/functional:1732
#28 0x00000000006027e5 in std::_Bind_simple<std::_Bind<std::_Mem_fn<bool (WebSocketServer::*)()> (WebSocketServer*)> ()>::operator()() (this=0x2801e70) at /usr/include/c++/4.8.2/functional:1720
#29 0x0000000000602716 in std::thread::_Impl<std::_Bind_simple<std::_Bind<std::_Mem_fn<bool (WebSocketServer::*)()> (WebSocketServer*)> ()> >::_M_run() (this=0x2801e58) at /usr/include/c++/4.8.2/thread:115
#30 0x00007f1737dd7070 in ?? () from /lib64/libstdc++.so.6
#31 0x00007f17375f5dd5 in start_thread () from /lib64/libpthread.so.0
#32 0x00007f173731eead in clone () from /lib64/libc.so.6

**Comment by alexhultman** [comment]
Hello

> my version is uWebSockets-0.15.7

This stack trace is from something very old in the 0.14.x branch. I do not work on that branch anymore so I cannot say if there is an issue or not.

Keep up to date with the 0.16.x branch for secure / performant software.
