### ISSUE TITLE
Support for non-latest compiler versions.

### ISSUE THREAD

**Issue by myrrc** [uNetworking/uWebSockets#916]
Hello, Alex!

In `App.h::ws(...)` you invoke methods:
- `webSocket->cork()` (line 206)
- `webSocket->init(...)` (line 210)

Methods are marked private in `WebSocket.h` and `AsyncSocket.h`, respectively. Although these classes have `TemplatedApp` as a friend,  invocation leads to compilation errors (` ... is private in ...`).

In general, to a question "Can a lambda invoke `object`'s private/protected methods if lambda's parent class is friended in `object`?" `gcc 8` and `clang 8` answer "Yes", older versions  (e.g. `gcc 7.`) answer "no".

I have read the pinned ticket and do understand this is not a bug, but could you please add support for the older compilers?

Possible hotfix would consist only of two lines:
- Make `Websocket::init(...)` `public` (`Websocket.h:38`).
- Make `AsyncSocket::cork()` `public` (`AsyncSocket.h:63`).

Regards, Mikhail.

**Comment by alexhultman** [comment]
Hello Mikhail,

I like your thorough analysis.

I'm not sure what is the correct behavior, I have wondered the same.

Maybe it's better to move away from using lambdas? Making things public maybe messes with the public interface? No?

**Comment by myrrc** [comment]
I suggested the solution only as a hotfix, not as a production-ready variant (namely because of the public interface breakage).

IMHO, removing the lambda in `ws(...)` would do the trick (and also make the code a bit simpler).

I can't speak for all the lambdas in your library -- never came across debugging them, the system works like a charm.

**Comment by ddevienne** [comment]
Just my $0.02 from the sidelines...

Requiring super recent of compilers is too much of a burden IMHO.
Already requiring C++17 (I'm limited to C++14 at this point...) limits potential users.
I fear that by the time I can use C++17 (in a few months), C++20 will be required ! :(

I fully understand you that you don't want to be beholden to old compilers,
but not always being on bleeding edge C++XY and compiler releases would
grow the user community IMHO.

On C++14, I'm _stuck_ to WebSocketPP and Boost.Beast right now (or an old branch of uWebSocket no longer supported). I also need cross-platform Windows/Linux web-sockets (even for servers, yes).
Just FYI from a lurker.

**Comment by alexhultman** [comment]
I've been doing this for so long now I know you cannot please everyone no matter which direction you go. 17 is the current spec, time to update your compiler ;)

**Comment by myrrc** [comment]
> I've been doing this for so long now I know you cannot please everyone no matter which direction you go. 17 is the current spec, time to update your compiler ;)

As a matter of fact, this library is nearly C++14 -ready (just needs some minor changes like replacing the `string_view` or so). I have ported it (in one of my projects I am also limited to C++14), benchmarks stayed on the same level (except for the consumed memory, but that's not the point).

Feel free to mention me for the pull request.

**Comment by alexhultman** [comment]
If anything, it should be written in C. But then you lose a lot of what people like about it. Also, 99% of users are not actually C++ users but rather Node.js users.

**Comment by ddevienne** [comment]
If it was written in C, I could use it from any C++ version :) (OK, not if it was in C11...)

@myrrc, you don't have a fork on GitHub with your backport to C++14? --DD

**Comment by myrrc** [comment]
> @myrrc, you don't have a fork on GitHub with your backport to C++14? --DD

Nope, but I can send it to you via an email, contact me at `me [at] myrrec.space`
