### ISSUE TITLE
Issues Compiling on MacOS using Xcode 10.3 with Apple Clang

### ISSUE THREAD

**Issue by JadeVand** [uNetworking/uWebSockets#918]
I'm not certain if this is compiler specific related issues or I'm doing something wrong. I'm trying to compile boilerplate with just the includes and I receive these compiler errors.

Line 135 in WebSocketContext.h
```Assigning to 'char *' from incompatible type 'const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::value_type *' (aka 'const char *')```

Line 95 in AsyncSocket.h
```Use of undeclared identifier 'us_new_socket_remote_address'```

Line 264 in HttpParser.h
```No matching member function for call to 'fenceAndConsumePostPadded'```

Line 62 in HttpContext.h
```No matching member function for call to 'us_new_socket_context_on_open'```

I'm using the default Apple Clang compiler.

**Comment by alexhultman** [comment]
git pull is your friend

**Comment by JadeVand** [comment]
I did pull the most recent changes and end up with more errors than before. Are you sure it's nothing to do with lacking of C++17 support? Also to be clear I did use the most recent port of uWebSockets from vcpkg and the uSocket library itself does compiler. It's just the headers.
