### ISSUE TITLE
idleTimeout isn't reset after some data is sent

### ISSUE THREAD

**Issue by RussCoder** [uNetworking/uWebSockets#925]
I want to point out that currently (I'm using v15.11.0) a connection is closed even if a message was sent by the server to the client, while the [documentation](https://unetworking.github.io/uWebSockets.js/generated/interfaces/websocketbehavior.html#idletimeout) says that the `idleTimeout` is:

> Maximum amount of seconds that may pass without **sending** or getting a message.

I suppose either the behavior should be changed or the documentation must be corrected.

**Comment by alexhultman** [comment]
Fixed
