### ISSUE TITLE
Expose zlib options for DEDICATED_COMPRESSOR

### ISSUE THREAD

**Issue by not-implemented** [uNetworking/uWebSockets#926]
To optimize memory usage when using DEDICATED_COMPRESSOR it would be nice to make the hardcoded values for `deflateInit2()` in https://github.com/uNetworking/uWebSockets/blob/master/src/PerMessageDeflate.h#L69 configurable.

Is it worthwhile to write a pull-request for that? I can try to add the options to WebSocketBehavior struct?

Example: Currently we use `windowBits = -11, memLevel = 3` with almost the same compression ratio for simple JSON messages ... but reduced zlib RAM usage to ~12-16 KB / client, instead of 300 KB (important when having ~25.000 connections ;-))

**Comment by alexhultman** [comment]
Yes that could make sense but I guess you need to also update the negotiation of permessage-deflate options

**Comment by alexhultman** [comment]
I would like to have simplified options:

From no memory overhead to lots of memory overhead and then many steps in between. I rather have simplified options people can easily grasp than strange knobs few understand.

Maybe simply have an integer going from 0 (off), 1 (shared), 2 (low memory usage), 3 (lots of memory usage), and so on

**Comment by alexhultman-2fa** [comment]
There are formulas for calculating those settings to reach a certain memory usage:

2kb
4kb
8kb
16kb

And so on. It could be made as simple as a set of flags you can specify like COMPRESSOR_16KB,

Anding with DEDICATED_COMPRESSOR.

That way it can be backwards compatible and impossible to specify wrong settings and it becomes easy to tinker with settings in regards to memory usage

**Comment by alexhultman** [comment]
Like I wrote in the PR, I have added DEDICATED_COMPRESSOR_2KB and all the way up to DEDICATED_COMPRESSOR_256KB so that it is super easy to pick one based on ones memory budget. Thanks

**Comment by not-implemented** [comment]
@alexhultman: Very cool, thanks! I hope I will have some time in the near future to test/integrate this (and your changes from december - the new cork() and the improved router) :+1:

**Comment by not-implemented** [comment]
@alexhultman: Works well, thanks!
