### ISSUE TITLE
Missing way to read HttpRequest raw data or body data for POST

### ISSUE THREAD

**Issue by xingyun86** [uNetworking/uWebSockets#927]
Missing way to read HttpRequest raw data or body data for POST
I use :
	res->onData([&](std::string_view data, bool last) {
						if (last) {
							if (requestData.size() == 0) {
								//requestData.reserve(data.size());
								//requestData.append(data.data(), data.size());
								res->end(data);
								std::cout << "<: " << data.length() << std::endl;
							}
							else {
								requestData.append(data.data(), data.size());
								res->end(requestData);
								std::cout << "[" << data.size() << "] <: " << requestData.length() << std::endl;
							}
							return;
						}
						else {
							if (requestData.length() == 0) {
								requestData.reserve(contentLength);
							}
							requestData.append(data.data(), data.size());
							std::cout << "[" << data.size() << "] ";
						}
						});

but it cannot be used.

**Comment by alexhultman** [comment]
I don't know about that one, there are examples of how to read POST data

**Comment by 0xffff00** [comment]
> I don't know about that one, there are examples of how to read POST data

where are read POST data examples? I cannot find them in v0.16

**Comment by Habush** [comment]
> I don't know about that one, there are examples of how to read POST data

And I can't find them in v0.18

**Comment by hst-m** [comment]
@Habush 
https://github.com/uNetworking/uWebSockets/blob/master/misc/main.cpp#L96
https://github.com/uNetworking/uWebSockets/blob/master/examples/helpers/AsyncFileStreamer.h
