### ISSUE TITLE
Query (not an issue) : We were using  libwebsocket for our project, but now we want to upgrade with uWebsocket.

### ISSUE THREAD

**Issue by KabeerSadiq123** [uNetworking/uWebSockets#932]
Hi,
We are facing some issue with LWS, therefore we are planning to upgrade with uWebsocket. 
We want the following to support our project. 

1. Load balancing. 
2. SSL and without SSL support.
3. Http request support.
4. WS support.
5. Chunk upload support. 
Will uWebsocket provide the above support? 
Thanks .

**Comment by alexhultman** [comment]
5. I don't know if that one is done

**Comment by alexhultman** [comment]
Otherwise yes it should work
