### ISSUE TITLE
I am not able to install uWebsocket, and getting followings errors. 

### ISSUE THREAD

**Issue by KabeerSadiq123** [uNetworking/uWebSockets#933]
Hi,
I am installing uWebsocket for my project and I am getting following errors:
Steps which I followed :
1. git clone --recurse-submodules https://github.com/uNetworking/uWebSockets
2. cd uWebSocket and then ran make command there.
**_logs after make commands are below:_**

cd uSockets && WITH_SSL=0 make
make[1]: Entering directory '/nas/data3/msadiq/rama_latest/spkinfo/3rd_party/uWebSockets/uSockets'
rm -f *.o
cc -DLIBUS_NO_SSL -std=c11 -Isrc -flto -O3 -c src/*.c src/eventing/*.c
ar rvs uSockets.a *.o
ar: creating uSockets.a
a - context.o
a - epoll_kqueue.o
a - gcd.o
a - libuv.o
a - loop.o
a - socket.o
a - ssl.o
make[1]: Leaving directory '/nas/data3/msadiq/rama_latest/spkinfo/3rd_party/uWebSockets/uSockets'
g++ -flto -O3 -std=c++17 -Isrc -IuSockets/src examples/HelloWorld.cpp -o HelloWorld uSockets/*.o -lz; g++ -flto -O3 -std=c++17 -Isrc -IuSockets/src examples/EchoServer.cpp -o EchoServer uSockets/*.o -lz; g++ -flto -O3 -std=c++17 -Isrc -IuSockets/src examples/BroadcastingEchoServer.cpp -o BroadcastingEchoServer uSockets/*.o -lz;
g++ -pthread -flto -O3 -std=c++17 -Isrc -IuSockets/src examples/HelloWorldThreaded.cpp -o HelloWorldThreaded uSockets/*.o -lz; g++ -pthread -flto -O3 -std=c++17 -Isrc -IuSockets/src examples/EchoServerThreaded.cpp -o EchoServerThreaded uSockets/*.o -lz;

=========================================================
Step: 3 , ran make install command and getting follow error message: 
make: *** No rule to make target 'install'.  Stop.

What are the dependencies, which I supposed to install here?
g++ --version
============
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by alexhultman** [comment]
Hello, there is no install. We could add such a thing but you could also just modify your include path

**Comment by KabeerSadiq123** [comment]
Hi @alexhultman,
Thanks for the quick response. 
I want to upgrade uWebsocket for my project.
I am following the below steps to install it.  
1. git clone --recurse-submodules https://github.com/uNetworking/uWebSockets
2. cd uWebSockets
3. make 
4. make install 
seems like "make" command  is working properly and I am getting below logs:
==================================================
rm -f *.o
cc -DLIBUS_NO_SSL -std=c11 -Isrc -flto -O3 -c src/*.c src/eventing/*.c
ar rvs uSockets.a *.o
ar: creating uSockets.a
a - context.o
a - epoll_kqueue.o
a - gcd.o
a - libuv.o
a - loop.o
a - socket.o
a - ssl.o
make[1]: Leaving directory '/nas/data3/msadiq/rama_latest/spkinfo/3rd_party/uWebSockets/uSockets'
g++ -flto -O3 -std=c++17 -Isrc -IuSockets/src examples/HelloWorld.cpp -o HelloWorld uSockets/*.o -lz; g++ -flto -O3 -std=c++17 -Isrc -IuSockets/src examples/EchoServer.cpp -o EchoServer uSockets/*.o -lz; g++ -flto -O3 -std=c++17 -Isrc -IuSockets/src examples/BroadcastingEchoServer.cpp -o BroadcastingEchoServer uSockets/*.o -lz;
g++ -pthread -flto -O3 -std=c++17 -Isrc -IuSockets/src examples/HelloWorldThreaded.cpp -o HelloWorldThreaded uSockets/*.o -lz; g++ -pthread -flto -O3 -std=c++17 -Isrc -IuSockets/src examples/EchoServerThreaded.cpp -o EchoServerThreaded uSockets/*.o -lz;
================================================================
when I am running the "make install" command, I am getting the following string.
"make: *** No rule to make target 'install'.  Stop."
==================================================
what do you mean by include path?
Am I following steps properly? 
Please correct me, If I am doing some mistakes.
Thanks again.

**Comment by alexhultman** [comment]
I cannot help; it should be obvious what you need to do
