### ISSUE TITLE
Misplaced includes causing build errors

### ISSUE THREAD

**Issue by tommitytom** [uNetworking/uWebSockets#950]
In the following file, `string` is included within the uWS namespace which is causing me many issues in VS.  Works fine if moved above the namespace declaration: https://github.com/uNetworking/uWebSockets/blob/master/src/AsyncSocketData.h#L25

The zlib include is included outside of the `UWS_NO_ZLIB` ifdef, so build fails even if UWS_NO_ZLIB since it still looks for the header:
https://github.com/uNetworking/uWebSockets/blob/master/src/PerMessageDeflate.h#L23

**Comment by alexhultman** [comment]
Do you mind creating a PR?
