### ISSUE TITLE
Scale horizontally using Redis

### ISSUE THREAD

**Issue by danieleratti** [uNetworking/uWebSockets#954]
Is there any possibility of scaling uWebSockets on multiple instances (for eg. using Redis) as it had been possible in past with Socket.io + the old uws using the io.adapter method?

`io.adapter(redis({ ... }));`

**Comment by alexhultman** [comment]
It's not more complicated than publishing to Redis every time one of your instances end up publishing to their clients. Then the other instances connected to Redis will also publish to their clients.

You don't even need Redis for this, you just need some client and some server to act as "master". I'm pretty sure Kubernetes and the like already has support for master/slave set-ups like this.

**Comment by danieleratti** [comment]
That's perfect, but there is only one more problem: when the pub/sub (eg. Redis) alerts a different machine that a given message should be sent to a topic, there's not a static method to publish without having a WebSocket instance.

```
/* Redis subscribe */
subscriber.on('message', function (channel, message) {
	/* In this context I don't have a WebSocket object, so what should I use to publish? */
	/* ws.publish('mytopic', message); */
});
subscriber.subscribe('ws');
```

The 2 possibilities I've found are:
a) I need to establish a client connection within the server, and use that WebSocket
b) I need to save a random WebSocket (eg. the last that connected or sent a message) -> this is risky as it could be disconnected meanwhile

Am I missing something?

**Comment by vahansoft** [comment]
> It's not more complicated than publishing to Redis every time one of your instances end up publishing to their clients. Then the other instances connected to Redis will also publish to their clients.
> 
> You don't even need Redis for this, you just need some client and some server to act as "master". I'm pretty sure Kubernetes and the like already has support for master/slave set-ups like this.

Can you explain more in details? I can't imagine how it gonna work.

**Comment by danieleratti** [comment]
It's actually pretty simple:

In your server code you just have to setup a redis PubSub connection or whatever you prefer for message broking...

Then, when you want to send a message to a channel, instead of directly sending it, publish on redis pubsub the channel and the message.

I'll explain better with the following pseudocode:
```
redis = new RedisPubSub()
redis.onMessageReceived(data) {
   ws.publish(data.channel, data.message)
}

// sending a message to a channel
redis.publish({channel: 'foo', message: 'bar'})
```
Instead of the directly publishing on ws.
