### ISSUE TITLE
Any wss websockets examples?

### ISSUE THREAD

**Issue by uniqss** [uNetworking/uWebSockets#958]
Any wss websockets examples provided? EchoServer and HelloWorld and threaded examples are excellent,but I just need a very simple wss example as simple as possible.tks very much!

**Comment by alexhultman** [comment]
The front page shows an SSLApp

**Comment by uniqss** [comment]
Thanks very much for your apply.
There are tons of bugs in your library code.
./bye

**Comment by xiaoshanlin000** [comment]
@uniqss Please use other versions of uSocket libraries like v0.3.2

**Comment by alexhultman** [comment]
> Thanks very much for your apply.
> There are tons of bugs in your library code.
> ./bye

You care to elaborate?

**Comment by uniqss** [comment]
In actual fact, I don't know whether it is the openssl's problem.
`/usr/bin/ld: uSockets/ssl.o: undefined reference to symbol 'BIO_up_ref@@OPENSSL_1_1_0'
/usr/local/openssl_1.1.1d/lib/libcrypto.so.1.1: error adding symbols: DSO missing from command line`
My openssl version is 1.1.1d, the latest stable.

**Comment by uniqss** [comment]
I meam could you please add an ssl echo server to your examples folder kindly? The first thing someone get to your library is compile the examples and test them. If no ssl examples offered and ssl example have many many errors, I think they will turn to other libraries.

**Comment by uniqss** [comment]
> @uniqss Please use other versions of uSocket libraries like v0.3.2

Yes, you are right! Thank you!

**Comment by uniqss** [comment]
> > Thanks very much for your apply.
> > There are tons of bugs in your library code.
> > ./bye
> 
> You care to elaborate?

Can I join this project and add an ssl example and a CMakeLists.txt file for linux g++ cmake?

**Comment by alexhultman** [comment]
> In actual fact, I don't know whether it is the openssl's problem.
/usr/bin/ld: uSockets/ssl.o: undefined reference to symbol 'BIO_up_ref@@OPENSSL_1_1_0' /usr/local/openssl_1.1.1d/lib/libcrypto.so.1.1: error adding symbols: DSO missing from command line
My openssl version is 1.1.1d, the latest stable.

*facepalm*
