### ISSUE TITLE
UserData isn't being initialized properly

### ISSUE THREAD

**Issue by SGSSGene** [uNetworking/uWebSockets#959]
The structures that can be receivid via `ws->getUserData()` are not being initialized. There are missing calls for C'tor and D'tor.

**Comment by alexhultman** [comment]
That's right. It doesn't construct or destruct the data type, so you have to placement new/delete your type, or use void pointer

**Comment by alexhultman** [comment]
It's not a bug it's a feature :wink:

**Comment by SGSSGene** [comment]
Thanks for the quick reply! Yeah I currently placement new and custom call to the constructor.
But I am not so happy about it.

**Comment by alexhultman** [comment]
Technically it is possible to fix by wrapping the callbacks, but that will break every usage which currently use placement.

I think this has to be a major version change

**Comment by alexhultman** [comment]
Fixed
