### ISSUE TITLE
Websockets Authorization

### ISSUE THREAD

**Issue by manast** [uNetworking/uWebSockets#966]
Is there any best practice for implementing websockets authorization with uWS? 
In previous versions of the library it was possible to check a bearer token in the req.headers of the initial HTTP request before upgrading to websockets, then respond with status 401 oer whatever. Is this still possible somehow? currently I am doing the authorization in the ws callback like this:
```ts
app
  .ws("/*", {
    /* Options */
    compression: CompressOptions.SHARED_COMPRESSOR,
    maxPayloadLength: 16 * 1024 * 1024,
    idleTimeout: 10,
    open: (ws, req) => {
      console.log("A WebSocket connected via URL: " + req.getUrl() + "!");

      console.log(ws, req.getHeader("authorization"));

      const authorization = req.getHeader("authorization");

      if (authorization) {
        const token = authorization.split(" ")[1];
        if (token) {
          ws.userId = getUserIdFromToken;
          if(ws.userId) {
             return;
        }
      }
      // 404 is not a valid websocket error code
      ws.end(404, "Unauthorized");
    },
```
Problem is that there are not suitable standard websocket error codes that express missing authorization or similar. Also it is not as clean as just doing the authorization before even starting the ws connection.

**Comment by kinsi55** [comment]
> And any "fix" to this would be limited to "non-async" actions.

I think having it to where you can have an upgrade handler as part of the WS handlers would be amazing.

If unpassed it could be short cuircuited / skipped, continue on with the upgrade as usual and thus would be a non-breaking change, but if set it would give you access to the original res / req and a `continue` callback, if the user desires to continue with the upgrade. I'm unsure about the technical side but surely this wouldnt introduce a performance overhead, would it?

**Comment by alexhultman-2fa** [comment]
The reason this hasn't been prioritized is because it's really a cosmetic thing. You already have the option to implement auth using WebSocket messages, there's even a standard way to close using code and message (such as invalid auth).

This issue is about moving auth to the http layer, and that introduces a lot of unnecessary complexity

**Comment by kinsi55** [comment]
I'm not in need for this as is currently and this isnt a complaint, but I think having this as an option for those that want to / can use it would be great regardless.

As an example, assuming you have a ws endpoint which should exclusively be called by logged in users, the only thing you need at that point to confirm that their login is valid is the cookies / other headers (Assuming you use that as your auth method at least ofc). For those with valid headers this wouldnt change anything, their auth is validated as usual and the upgrade is then completed, but those with an invalid login would fail early (And thus even cause less load overall)? Overall its pretty much the same authflow, just moved to pre-upgrade.

**Comment by alexhultman-2fa** [comment]
> Overall its pretty much the same authflow, just moved to pre-upgrade.

Yep.

> but those with an invalid login would fail early (And thus even cause less load overall?)

Theoretically yes, but in practise you can do 200k upgrades a second per cpu so that's not going to be an issue compared to say the cost of SSL or the auth itself.

**Comment by kinsi55** [comment]
Yeah definitely agree its not something that one necessarily needs to worry about from a load standpoint (Eventho I like to cut corners wherever possible just because), but even for usuability (At least with something like node where the auth process most likely is async), delaying and possibly outright denying the upgrade alltogether would prevent the client from sending any messages before having passed auth and thus make for less attack vectors / imo better usage. This definitely is something that would be most useful for usage in Node, I'm unsure about the usefulness in native / python.

**Comment by alexhultman** [comment]
I'm looking at this now. This is a huge change and will not be fully backwards compatible. It will support async upgrades and add a new .upgrade handler. This change alone will make v18

**Comment by alexhultman** [comment]
* Open handler will no longer take HttpRequest, only WebSocket (API-breaking)
* Upgrade handler will take HttpResponse and HttpRequest
* HttpResponse.upgrade will take UserData, protocol, extensions, sec-key) and immediately call open handler with a WebSocket having UserData set, and immediately invalidate HttpResponse
* If doing async work in upgrade handler, you have to read and pass protocol, extensions and sec-key along manually, and pass them into HttpResponse.upgrade when done with async work (HttpRequest is stack allocated and cannot be grabbed)

**Comment by kinsi55** [comment]
> * If doing async work in upgrade handler, you have to read and pass protocol, extensions and sec-key along manually, and pass them into HttpResponse.upgrade when done with async work (HttpRequest is stack allocated and cannot be grabbed)

Wouldnt it be possible to have an alternate upgrade prototype that accepts a HttpRequest as the only parameter, which will then pull the required values from it? Might be cleaner since I one rarely should need to modify those values

**Comment by alexhultman** [comment]
You pass data from upgrade to open handler by calling res.upgrade with UserData, so if you're in JavaScript something like this:

in upgrade handler:

res.upgrade({whatever: "yes"}, ...)

then in open handler:

ws.whatever starts as "yes"

**Comment by alexhultman** [comment]
This is the interface I'm leaning towards: https://github.com/uNetworking/uWebSockets/blob/v18/examples/UpgradeSync.cpp

**Comment by alexhultman** [comment]
And here is the async counterpart (more complex): https://github.com/uNetworking/uWebSockets/blob/v18/examples/UpgradeAsync.cpp

**Comment by kinsi55** [comment]
Looks good to me. Is there any technical reason its behind a function instead of being a variable (Say `->userData` / .userData in the JS wrapper)?

**Comment by alexhultman-2fa** [comment]
> BTW my use case above is not about auth. It's about routing the WS connection to a dynamically obtained destination.

Yep I get that. But you have been able to solve this using any other HTTP server as "balancer". You could really just use nodejs http for this, you're basically asking for a http server with upgrade event. You already have that built-in to nodejs. None of this has been impossible ever.

**Comment by alexhultman-2fa** [comment]
getUserData is not part of JS wrapper, they differ in that regard.

This is implemented in v18 branch now

**Comment by alexhultman** [comment]
Merged to master now
