### ISSUE TITLE
Planning for v0.17

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets#967]
Routing:
* #860 
* #822 

Http:
* #966 
* #838 
* experimental_cork -> cork

WebSockets:
* #926 
* #959 
* #960

**Comment by dalisoft** [comment]
Can i add idea (not required to be added to project)

- KeepAlive timeout
- HTTP2
- Proxy to other domain feature
- `req.on('upgrade')` even
- built-in for separate project to impressive graphql
- Load balancer
- SO_REUSEPORT on Win / Mac

Thanks for amazing and fastest project

**Comment by alexhultman** [comment]
req.on('upgrade') is #966

**Comment by alexhultman** [comment]
Primarily this will focus on better routing. Making it behave more like people expect it to (ws and get on the same route, order of matches easier to understand, etc)

**Comment by rimmartin** [comment]
Been experimenting with middleware; one specifically is for virtual hosting:
https://github.com/DataDriven-CAM/cxx-vhost similar to [vhost](https://github.com/expressjs/vhost).  

I forked and am experimenting with adding a use method to the uWS::TemplatedApp struct but unsure of design for this. Do you have any plans for special middleware such as virtual hosting and cors?

**Comment by dalisoft** [comment]
@rimmartin I think there no plan for `.use` method and/or CORS middleware. But you can do it yourself, at first glance looks like hard do it, but it's not hard (not easy too).
You can use libraries made on top of uWebSockets.js (if you about Node.js binding) which provides similar to Express interface

**Comment by rimmartin** [comment]
@dalisoft I have some c++ based on uWebSockets for cors but didn't test enough to push it to the web. I worded that wrong above; not asking for it to be implemented but rather if it can be accommodated

**Comment by dalisoft** [comment]
@rimmartin If CORS and ‘.use’ will be available at C++ level could be great

**Comment by rimmartin** [comment]
@dalisoft With the power uWebSockets already has we aren't far from pure c++/c enterprise serving:-)  I'm experimenting with serving large hdf5 images thru uWebSockets and should get the fastest displays yet. Learning a lot from the modern coding in and compiler use by uWebSockets.

With uWebSockets virtual hosting, working on an [ldp](https://www.w3.org/TR/ldp/) compliant server for [solid pods](https://solid.inrupt.com/)

**Comment by alexhultman-2fa** [comment]
Problem with these .use and similar Express-like features is that they are hard or impossible to make fast. Their use is often counter to performance and requires memory allocations in the fast path of execution.

**Comment by rimmartin** [comment]
Hi @alexhultman 

Koa-like no better?

If the .use doesn't cause a slowdown for users/developers who don't put anything to it then their applications wouldn't be harmed?  I'm not claiming to know how to design for this; just learning what can be done.

I'll set up testings for speed with my working copy with an image the size of https://www.nasa.gov/images/content/734344main_g306_wide_large.jpg.  Bet uWebSockets will load it much faster than it loads from https://www.nasa.gov :-)

**Comment by alexhultman-2fa** [comment]
Image sending it's not faster with a faster server. You'll get no speedup compared to any other server. Speedup is significant for REST and small event messages like chat or SMS or similar. Image IO is not such a case

**Comment by rimmartin** [comment]
will use your .ws 

similar to the way I previously used ws
https://github.com/HDF-NI/hdf5.ws
made image arrive in tiles from hdf5 file on the server; can pan from there with the viewfinder without the user knowing
