### ISSUE TITLE
Is there any way to get IP address from a HttpRequest?

### ISSUE THREAD

**Issue by summerinsects** [uNetworking/uWebSockets#969]

**Comment by ggerganov** [comment]
Not sure about the HttpRequest, buy you could get the remote IP address from the WebSocket. For example:

```c++
.open = [&](auto *ws, auto *req) {
    ...
    auto remoteAddress = ws->getRemoteAddress();
    ...
}
```

**Comment by summerinsects** [comment]
I tested on macOS, `getRemoteAddress` returns empty string from either `uWS::WebSocket<>` or `HttpResponse<>`

**Comment by alexhultman** [comment]
It doesn't

**Comment by OneCodeCZ** [comment]
I am on Win10 and `getRemoteAddress` also returns an empty string. If only I could get the native SOCKET handle to be able to query the socket manually.

**Comment by alexhultman-2fa** [comment]
getRemoteAddress **is** querying the SOCKET. If you really do get length 0 then it fails and you cannot get it anyways. It is not a string, btw.

**Comment by OneCodeCZ** [comment]
I am using this function so I kind of expected it will be a string.
```    
    /* Returns the remote IP address or empty string on failure */
    std::string_view getRemoteAddress() {
        static thread_local char buf[16];
        int ipLength = 16;
        us_socket_remote_address(SSL, (us_socket_t *) this, buf, &ipLength);
        return std::string_view(buf, ipLength);
    }
```
When I look closer at the result, I get 16 bytes. There are zeors at the beginning, then some bytes and the last 4 bytes are actually the correct IP address.
How should I interpret the result correctly? Thanks.

**Comment by alexhultman** [comment]
> When I look closer at the result, I get 16 bytes.

Right, so we are back at square one. That's why this issue is closed already.

Those 16 bytes **are** the IP address. It's obviously an IPv6 address.

**Comment by ddevienne** [comment]
On a completely unrelated note, what's the point of using a thread_local just so you can return a std::string_view, when std::string, which is mandated to implement the small-buffer-optimization since C++11 (and you require C++17), can return that string by value without any heap-allocation? Why not simply:

int ipLength = 16;
std::string addr(ipLength, '\0');
us_socket_remote_address(SSL, (us_socket_t *) this, addr.data(), &ipLength); // non-const data() since C++17
addr.resize(ipLength); // I assume this is an in/out param
return addr;

No thread_local, only local state and by-value return, and just as efficient, no?

**Comment by alexhultman** [comment]
That's relying on very particular assumptions which Microsoft and others may ignore (they are not very standards oriented).

I did put both in compiler explorer and the std::string way is much heavier, completely different beast. Besides it shouldn't matter that much.

**Comment by ddevienne** [comment]
I don't think so, SBO in `std::string` is part of the standard since C++11 AFAIK.
I would think `thread_local `should be reserved to where it matters for performance,
and that pure local and by-value programming should be preferred everywhere else.
But hey, it's your library, thanks for considering it and looking into it. --DD

**Comment by alexhultman** [comment]
It's not a matter of belief - like I said I ran it through gcc with O3 and std c++17 and it outputted garbage assembly, compared to the thread local which was essentially entirely optimized away it had "call" and other shitty instructions. I do science, not religion. Test for yourself. However, this is too irrelevant

**Comment by RDP1974** [comment]
Can you test with CLANG?

Da: Alex Hultman <notifications@github.com>
Inviato: venerdì 6 marzo 2020 20:34
A: uNetworking/uWebSockets <uWebSockets@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Oggetto: Re: [uNetworking/uWebSockets] Is there any way to get IP address from a HttpRequest? (#969)


It's not a matter of belief - like I said I ran it through gcc with O3 and std c++17 and it outputted garbage assembly, compared to the thread local which was essentially entirely optimized away it had "call" and other shitty instructions. I do science, not religion. Test for yourself. However, this is too irrelevant

**Comment by alexhultman-2fa** [comment]
This is highly irrelevant and you should test for yourself. I did however try both clang and gcc and both create absolute horrible code when using std::string like that. Compare with std::string_view which is entirely constant folded and has no operator delete or constructor calls

**Comment by alexey-v-paramonov** [comment]
Those who get an empty string with `getRemoteAddress()` - you should use `getRemoteAddressAsText()`

**Comment by 96chh** [comment]
> I am using this function so I kind of expected it will be a string.
> 
> ```
>     /* Returns the remote IP address or empty string on failure */
>     std::string_view getRemoteAddress() {
>         static thread_local char buf[16];
>         int ipLength = 16;
>         us_socket_remote_address(SSL, (us_socket_t *) this, buf, &ipLength);
>         return std::string_view(buf, ipLength);
>     }
> ```
> 
> When I look closer at the result, I get 16 bytes. There are zeors at the beginning, then some bytes and the last 4 bytes are actually the correct IP address.
> How should I interpret the result correctly? Thanks.

I change source code: functon addressAsText：
```
if (binary.length() == 16) {
            ipLength = sprintf(buf, "%u.%u.%u.%u", b[12], b[13], b[14], b[15]);
 }
```
