### ISSUE TITLE
Controlling serverMaxWindowBits in uWebSocket

### ISSUE THREAD

**Issue by emaadgh** [uNetworking/uWebSockets#972]
Hi, I'm using Websocket-sharp in my Unity game as client that is connecting to a uWebsocket backend server.
We want to enable Per-message Compression for this connection but the problem is that when I enable compression in client the server refuses the request from the client. 

We also reproduced this issue with [ws library in node js](https://github.com/websockets/ws) as backend with its provided example configuration, but the problem persists. When we set serverMaxWindowBits in ws library to default negotiated value, the client can connect to the server properly.

Now my question is, Is there any way that we can control this serverMaxWindowBits in uWebsockets? 

uWebSocket 16.4
CentOS 7
Node js 10.17

Thanks.

**Comment by alexhultman** [comment]
This should ultimately be paired with the new compressors; specifying DEDICATED_COMPRESSOR_2KB should negotiate a smaller sliding window than 15 (in this case it should be 8).

**Comment by alexhultman** [comment]
There's no negotiation needed; the server decides and needs no request to add server_max_window_bits to the response. So a fix is really just to add server_max_window_bits to the response with whatever compressor you're using. Unless of course you're using DEDICATED_COMPRESSOR_256KB which is the unlimited default

**Comment by alexhultman** [comment]
Okay this is kind of fixed now, for most cases. But the server still decides with highest authority
