### ISSUE TITLE
catchall for `get` does not respect order for `any`

### ISSUE THREAD

**Issue by mattkrick** [uNetworking/uWebSockets#975]
I can't seem to hit the `any` handler with a `get` request method in the demo.

Repro:
- Use router example: https://github.com/uNetworking/uWebSockets.js/blob/master/examples/Router.js
- `await fetch('/anything', {method: 'get'}).then(res => res.text()) // Nothing to see here!` <-- bad
- `await fetch('/anything', {method: 'post'}).then(res => res.text()) // Any route with method: post` <-- good
- remove the catchall `/*` & it works

Expectation:
- the matcher follows the order of the method chain

Version: 16.4

**Comment by alexhultman** [comment]
#860 #822

**Comment by alexhultman-2fa** [comment]
I think the way to go is to completely drop the idea that adding routes in a particular order changes matching. It makes no sense, you really only need the rule to be:

Static routes match first
Paremeter routes match second
Wildcard routes match last

And of course, any should not be treated different to get/post

What do you think?

**Comment by alexhultman-2fa** [comment]
This is yet another example of how this project has to differ from Express.js because of differing implementations

**Comment by alexhultman-2fa** [comment]
https://github.com/dimfeld/httptreemux/blob/master/README.md#routing-priority

This makes sense

**Comment by mattkrick** [comment]
matching based on specificity rules confuse me a bit. Essentially it's turning an O(log(n)) into O(n). Performance wise, who cares, it's all stupid fast. But for developer experience, that means I have to read every single rule to understand which one is at fault.

say the requested route is `/a/b/c/d`

`/*` <- matches, but maybe something more specific?
`/a/b/*cat` <- matches, but something more specific?
`/a/b/c/:dog` <- matches, but something more specific? 

...100 rules later. nothing better, so go with the handler behind `/a/b/c/:dog`. 

super contrived example & i hope  no one's logic is that ugly, but IMO order seems simpler.

**Comment by alexhultman-2fa** [comment]
> Essentially it's turning an O(log(n)) into O(n).

No it's the opposite, matching in order of registration like Express is O n while matching in order of (static, paremeter, wildcard) is the only order you can do with O log n

I've seen cases where the O n matching has large differences between first and last in speed, something you rarely will have with a proper tree.

Besides - it makes sense that wildcards are lowest prio while static have highest (the more specific the higher priority)

**Comment by mattkrick** [comment]
Whoa! Never thought the difference would be noticeable. You're right then, specificity matching sounds like the way to go. If I understand correctly, a fixed `any` matcher comes before a wildcard `get`, if there's a tie, the `any` matcher loses?

**Comment by alexhultman-2fa** [comment]
Yes I guess that's how it goes. Simply put, the more specific route the higher priority. I guess any should come behind get if their route is equally specific.

**Comment by alexhultman** [comment]
Please have a test with npm install uNetworking/uWebSockets.js#binaries
