### ISSUE TITLE
can make uWebSockets REALLY header-only？

### ISSUE THREAD

**Issue by 0xffff00** [uNetworking/uWebSockets#976]
uWebSockets is an excellant library. 
However, uWebSockets relies on uSockets which is not header-only library.
can make them both header-only?

**Comment by alexhultman** [comment]
No the idea is to have a minimal C library that is completely opaque and doesn't leak anything over its very minimal interface. Then you have this header-only library of higher level server logic without any dependencies other than the C library. So it's a good balance right now, and you still need OpenSSL and zlib and they aren't header-only so you still can't get perfectly header-only.
