### ISSUE TITLE
Ability to publish to all except

### ISSUE THREAD

**Issue by jgrajewsky** [uNetworking/uWebSockets#978]
When using `TemplatedApp.publish()` it does publish to all as it should but when using `WebSocket.publish()` there should be an ability to make it so it ignores this specific WebSocket when publishing. It would be very useful for me in many cases like when a client sends data about his position there is no need to send it back to him just the other clients.

**Comment by alexhultman-2fa** [comment]
Yes I agree. This should be fixed. It is a bit complicated though

**Comment by alexhultman** [comment]
I have a good solution for this now

**Comment by alexhultman** [comment]
Nay, I have a splendid solution. It kicks ass.

**Comment by ajilk** [comment]
What is the solution for this?
