### ISSUE TITLE
how to register the on_open callback on tcp accept of the websocket, before any ssl code execution?

### ISSUE THREAD

**Issue by uniqss** [uNetworking/uWebSockets#981]
Sometimes our server will ban some IP address, it should be disconnected on first tcp accept, before any ssl or other code execution. So we need to register the uSockets on_open callback of the websocket.

**Comment by uniqss** [comment]
Just find the context then call us_socket_context_on_open. So how to get the context of the websocket's first tcp accept?

**Comment by alexhultman-2fa** [comment]
You should ban IP addresses using the kernel

**Comment by yasser-sobhy** [comment]
this is how it can be done using iptables
https://making.pusher.com/per-ip-rate-limiting-with-iptables/

**Comment by uniqss** [comment]
@yasser-sobhy @alexhultman-2fa thanks very much for your kindly answer. It seemed not a good idea to block the ip at program-level on security level, because when the program get accept, many things already happened, from syn queue to accept queue and a callback.
but we just need some program-level settings, not so efficient, just for usage. such as when our program is online, we just want our company's users to use, just config a xml or a json file. so can we get the client peer's ip address on websocket on_open callback? there are two parameters:
`void wss_on_open(uWS::WebSocket<true, true>* ws, uWS::HttpRequest* req)`

**Comment by alexhultman-2fa** [comment]
You have to start reading the docs and using your IDE. You can't misuse the issue tracker as your personal free consultant. There's plenty of info available on this topic.
