### ISSUE TITLE
I keep getting ERROR C2664

### ISSUE THREAD

**Issue by Slowair6** [uNetworking/uWebSockets#982]
`C2664	'void us_new_socket_context_on_open(const int,us_new_socket_context_t *,us_new_socket_t *(__cdecl *)(us_new_socket_t *,int))': cannot convert argument 3 from 'uWS::HttpContext<false>::init::<lambda_1a1e4fd2aa024a7b371578dc5ee59d10>' to 'us_new_socket_t *(__cdecl *)(us_new_socket_t *,int)'`

I installed uWEbSockets via vcpkg and I keep getting this error 

Here some of my code

header
`#include "uwebsockets/App.h"`

body

```
uWS::App* h = new uWS::App;

	int port =443;//test
	h->get("/*", [=](auto* res, auto* req) {
		auto url = req->getUrl();
		transform(url.begin(), url.end(), url.begin(), ::tolower);

		if ((url == "/test")/* && req->getMethod() == uWS::HttpMethod::METHOD_GET*/)
		{
			...
		}
	});

	h->listen(port, [=](auto* token) {
		LOGI << "Web Socket listening to port " << port;
		if (token) {
			LOGI << "Serving over HTTPS a " << port;
		}
		else
		{
			LOGE << "Failed to listen to port:" << port;
			return;
		}
	});
```

can someone help me fix the error?

**Comment by alexhultman** [comment]
Something seems mismatching in vcpkg package. It looks very old, tell them about it
