### ISSUE TITLE
same code works in Centos 7, but not in raspberry Pi4

### ISSUE THREAD

**Issue by kenjichanhkg** [uNetworking/uWebSockets#983]
The following code  works in Centos 7, but not in raspberry Pi4.
The my_timer never fired in raspberry pi4.
I have no idea why it behaves differently, bug or something?

I'm using tags/v0.17.0a3

```
#include <uws/App.h>

int main(int argc, char** argv){
    auto app = uWS::App()
    .get("hi", [](auto *res, auto *req) {;
        res->end("hi");
	})
    .listen(3001, [](auto *token) {
	});

    int ms = 1, repeat_ms = 3000;
    auto my_timer = us_create_timer((us_loop_t*)uWS::Loop::get(), 0, 0);
    if (my_timer == nullptr){
        printf("failed to create my_timer\n");
        return 0;
    }
    us_timer_set(my_timer, [](auto t){
        printf("my_timer fired!\n");
    }, ms, repeat_ms);

    app.run();
    return 0;
}
```

Kenji

**Comment by alexhultman** [comment]
You could try WITH_LIBUV=1 to build with libuv and see if that works

**Comment by alexhultman** [comment]
I'm closing this. If you have more info and more specific descriptions you can reopen

**Comment by kenjichanhkg** [comment]
using WITH_LIBUV=1 is working, but us_timer_ext() is now not working as expected.
I've noticed that the uv version of us_create_timer() is different, it allocates more for sizeof(uv_timer_t).
So the address returned by us_timer_ext() will be wrong?
