### ISSUE TITLE
Enumerate through all UserData

### ISSUE THREAD

**Issue by boogerlad** [uNetworking/uWebSockets#987]
For a websockets user authentication system, I store the user ID in the socket's UserData after their credentials have been verified through a "login" websocket message. However, if another socket is created and another "login" message with the same credentials is supplied, the same user would now be logged in twice(one user, two sockets). If I was able to enumerate through all UserData, I could make sure no sockets exist with that User ID in UserData before authenticating them. In the event that a socket does exist with that User ID in UserData, I could close the connection or "logout" by setting the User ID to null, for example.

Please close if this feature already exists, it's stupid, or if there's an alternative way. The only pitfall I see for this feature is it's a potential security risk for one session to access all sessions, even though it's server side. I did a pass through the documentation and both issue trackers (uws and uws.js) and couldn't find anything.

**Comment by alexhultman** [comment]
Use a set
