### ISSUE TITLE
Generate some nice documentation

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets#989]
Some PDF or something nice based on the comments in the code.

**Comment by dalisoft** [comment]
What about jsDoc? Or community-powered documentation? Maybe this works https://docusaurus.io/en/? This library very great and i sure community will help  improve docs

**Comment by alexhultman** [comment]
There is already nice JS docs in the JS project. What I want here is nice C++ docs. I never get Doxygen to look nice though..

**Comment by alexhultman** [comment]
Doxygen is ugly and all, but I guess it is the most suitable here. Esp. since you can have the "user manual" Markdown page as the Main page of Doxygen docs, putting all docs in one place where you also can navigate important classes.

I had to disable a lot of classes that Doxygen was including, but now it looks decent. PDF generation with Doxygen looks ugly and hard to use. This needs a web page, I guess GitHub pages can host that.

Putting all docs in one place, using comments to aid should be an improvement even though I would argue people can just include the header files and use a good IDE to get an idea.

**Comment by alexhultman** [comment]
[mozilla.pdf](https://github.com/uNetworking/uWebSockets/files/4517815/mozilla.pdf)

This looks pretty nice

**Comment by alexhultman** [comment]
Instead of introducing a new Doxygen docs browser, it makes sense to put efforts into improving the docs we already have done with TypeDoc. They are in most cases 1-to-1 and simple to navigate. Doxygen can make sense at some point in time, but I rather spend time writing better docs for TypeDoc first, and in the user manual than to introduce some auto-generated thing your IDE can easily display anyways. As such this issue has very low prio.

**Comment by yesudeep** [comment]
Have you considered using Sphinx instead?
