### ISSUE TITLE
Routing doesn't work as expected

### ISSUE THREAD

**Issue by mrlika** [uNetworking/uWebSockets#990]
Looks like 17.0.0 release broke routing.

This code doesn't work as expected any more: https://github.com/Novage/wt-tracker/blob/b6c34fb3d16f63dd12bed6be74050b447aceb3c0/lib/run-uws-tracker.ts#L89

I want to serve index "/", "/stats.json" and 404 for all other requests "/*".

But when I add "/*" route all other routes stop working.

**Comment by alexhultman** [comment]
There's a priority flaw for ws routes in some cases, I know how to fix it (simple) but then there's an opportunity to optimize the tree a bit which will require more work and a new function "build" that builds this optimized tree.

**Comment by alexhultman** [comment]
Essentially you need to hold two trees, one for get/any and one for ws. When you added all routes you call "build" and it merges the two trees as far as possible, reducing number of duplicated nodes without changing priority.

**Comment by alexhultman** [comment]
Alright this is fixed now, will release in a few days thanks for pointing it out
