### ISSUE TITLE
Rustls or LibreSSL instead of OpenSSL

### ISSUE THREAD

**Issue by leeoniya** [uNetworking/uWebSockets#994]
> - LIBUS_NO_SSL - disable OpenSSL dependency/functionality for uSockets and uWebSockets builds

LibreSSL or Rustls support might be a good alternative to a binary choice between an OpenSSL dependency or nothing at all.

oh, and of course the performance doesn't suck either: https://jbp.io/2019/07/01/rustls-vs-openssl-performance.html

EDIT: but LibreSSL seems to be slower than OpenSSL by a good margin

food for thought.

**Comment by alexhultman** [comment]
I don't have any problem with OpenSSL, it is used by both Python and Node.js and nowadays they fuzz it via Google oss-fuzz.

LibreSSL seems to be just like most forks are; a joke.

We already have WolfSSL support btw, but I have no interest in Rust
