### ISSUE TITLE
Prevent to expose HTTP header "uWebSockets".

### ISSUE THREAD

**Issue by dmitigr** [uNetworking/uWebSockets#997]
Hello,

Can we please optionally prevent sending of "uWebSockets" header (initiated by HttpResponse::writeMark())? Not all users of the library, including me, are happy to expose the server implementation and it's version for security reasons.

It would be nice to make it possible to prevent it by setting a corresponding macro definition, for example. I can provide a patch for this.

Thanks.

**Comment by alexhultman** [comment]
Sure, as macro would make sense.

**Comment by dmitigr** [comment]
Opened pull request #998
